force-app/main/default/objects/Case/fields/Current_Step__c.field-meta.xml
<CustomField>
    <fullName>Current_Step__c</fullName>
    <description>Used by the Time and Attendance department to mark the stage of the onboarding process</description>
    <label>Current Step</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>(1 0f 7)Paperwork with Contractual</fullName>
            </value>
            <value>
                <fullName>(10 of 12) First Payroll Run</fullName>
            </value>
            <value>
                <fullName>(11 of 12) Post Run Debrief</fullName>
            </value>
            <value>
                <fullName>(12 of 12) Transfer to Ongoing Support</fullName>
            </value>
            <value>
                <fullName>(1 of 1) Waiting for 1st Tax Year</fullName>
            </value>
            <value>
                <fullName>(1 of 12) Sales Rep Conducting Needs Analysis</fullName>
            </value>
            <value>
                <fullName>(1 of 2) Introductory Call</fullName>
            </value>
            <value>
                <fullName>(1 of 2) Waiting for Appointment</fullName>
            </value>
            <value>
                <fullName>(1 of 3) Client in onboarding</fullName>
            </value>
            <value>
                <fullName>(1 of 3) Send Welcome Email</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Approval Copy Sent</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Client Load Received</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Introductory Call</fullName>
            </value>
            <value>
                <fullName>(1 of 4) PLE Welcome Call</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Waiting on IC</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Waiting on Turnover Call</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Client Load Received</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Kickoff Call</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Load Received - Welcome Call In Progress</fullName>
            </value>
            <value>
                <fullName>(1 of 5) New Case Received</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Schedule Training</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Welcome Call</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Welcome Email</fullName>
            </value>
            <value>
                <fullName>(1 of 6) Documentation Received/ Welcome Letter Sent</fullName>
            </value>
            <value>
                <fullName>(1 of 6) Internal Notification Email</fullName>
            </value>
            <value>
                <fullName>(1 of 6) Introductory Call</fullName>
            </value>
            <value>
                <fullName>(1 of 6) Welcome Call</fullName>
            </value>
            <value>
                <fullName>(1 of 7) Load received – IS verifying load docs</fullName>
            </value>
            <value>
                <fullName>(1 of 7) Meet &amp; Greet</fullName>
            </value>
            <value>
                <fullName>(1 of 8) Plan received - Waiting on IC</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Overview_Configuration__c/Client_Overview_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The criteria that determines what and how cases and reference objects are displayed in the Onboarding Overview section of the Client Overview.</description>
    <label>Client Overview Configuration</label>
</CustomObject>

force-app/main/default/objects/Client_Overview_Configuration__c/fields/Case_Only__c.field-meta.xml
<CustomField>
    <fullName>Case_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Case the only object used for Onboarding this product type (No Reference Object).</description>
    <inlineHelpText>Is Case the only object used for Onboarding this product type (No Reference Object).</inlineHelpText>
    <label>Case Only?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Overview_Configuration__c/fields/Case_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Record_Type_Name__c</fullName>
    <description>Select the Onboarding Case record type name for this product.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Select the Onboarding Case record type name for this product.</inlineHelpText>
    <label>Case Record Type Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Overview_Configuration__c/fields/Completed_Onboarding_Status__c.field-meta.xml
<CustomField>
    <fullName>Completed_Onboarding_Status__c</fullName>
    <description>The Case or Reference Object Current Step that indicates that the client has been successfully Onboarded.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Case or Reference Object Current Step that indicates that the client has been successfully Onboarded.</inlineHelpText>
    <label>Completed Onboarding Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Overview_Configuration__c/fields/Current_Step_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Current_Step_API_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Current Step API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Overview_Configuration__c/fields/OnboardingPOC_api__c.field-meta.xml
<CustomField>
    <fullName>OnboardingPOC_api__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Onboarding Point of Contact</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Overview_Configuration__c/fields/Owner_Custom_Label__c.field-meta.xml
<CustomField>
    <fullName>Owner_Custom_Label__c</fullName>
    <description>The custom label (Title) for the Owner of the Onboarding Case or Reference Object.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The custom label (Title) for the Owner of the Onboarding Case or Reference Object.</inlineHelpText>
    <label>Owner Custom Label</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Overview_Configuration__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>The name of the product as it should be displayed int he Onboarding Overview.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the product as it should be displayed int he Onboarding Overview.</inlineHelpText>
    <label>Product Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Overview_Configuration__c/fields/Reference_Object_Exp_Run_Date_api__c.field-meta.xml
<CustomField>
    <fullName>Reference_Object_Exp_Run_Date_api__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reference Object Expected Run Date Api</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Overview_Configuration__c/fields/Reference_Object_Relationship_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Reference_Object_Relationship_API_Name__c</fullName>
    <description>The API name of the relationship name between the Case and the Reference Object. Leave this blank if no reference object is used for Onboarding.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The API name of the relationship name between the Case and the Reference Object. Leave this blank if no reference object is used for Onboarding.</inlineHelpText>
    <label>Reference Object Relationship API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Overview_Status_Info__c/Client_Overview_Status_Info__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of potential statuses for a product</description>
    <label>Client Overview Status Info</label>
</CustomObject>

force-app/main/default/objects/Client_Overview_Status_Info__c/fields/DisplayText__c.field-meta.xml
<CustomField>
    <fullName>DisplayText__c</fullName>
    <description>The text to be displayed in the overview. If left blank, the status will be shown</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Display Text</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Overview_Status_Info__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Key</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Overview_Status_Info__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Overview_Status_Info__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_HRO__c/Reference_HRO__c.object-meta.xml
<CustomObject>
    <description>Object used to store additional information for on-boarding HRO products. 
Fields removed from Case object and moved to this object.</description>
    <label>Reference Online Services</label>
    <nameField>
        <displayFormat>OS-{00000}</displayFormat>
        <label>Reference OS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Online Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_HRO__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Reference_HROs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_HRO__c/fields/Current_Step__c.field-meta.xml
<CustomField>
    <fullName>Current_Step__c</fullName>
    <label>Current Step</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>(1 of 4) PLE Welcome Call</fullName>
            </value>
            <value>
                <fullName>(2 of 4) PLE Author Training</fullName>
            </value>
            <value>
                <fullName>(3 of 4) PLE Admin Training</fullName>
            </value>
            <value>
                <fullName>(4 of 4) PLE Final Review Call - Transition Pending</fullName>
            </value>
            <value>
                <fullName>(1 of 1) Waiting for 1st Tax Year</fullName>
            </value>
            <value>
                <fullName>(1 of 2) Introductory Call</fullName>
            </value>
            <value>
                <fullName>(1 of 3) Send Welcome Email</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Introductory Call</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Kickoff Call</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Schedule Training</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Welcome Call</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Welcome Email</fullName>
            </value>
            <value>
                <fullName>(1 of 6) Internal Notification Email</fullName>
            </value>
            <value>
                <fullName>(1 of 6) Introductory Call</fullName>
            </value>
            <value>
                <fullName>(1 of 6) Welcome Call</fullName>
            </value>
            <value>
                <fullName>(2 of 6) Checklist Training Call</fullName>
            </value>
            <value>
                <fullName>(3 of 6) Client - Site Configuration</fullName>
            </value>
            <value>
                <fullName>(4 of 6) Checklist Followup-Order Form Review Call</fullName>
            </value>
            <value>
                <fullName>(4 of 6) HMQR</fullName>
            </value>
            <value>
                <fullName>(5 of 6) MSP - Site Configuration</fullName>
            </value>
            <value>
                <fullName>(5 of 6) Onboarding Review and Followup</fullName>
            </value>
            <value>
                <fullName>(6 of 6) New User Training</fullName>
            </value>
            <value>
                <fullName>(6 of 6) Training Complete-Pending Transition</fullName>
            </value>
            <value>
                <fullName>Client Site Configuration</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Configuration/Development</fullName>
            </value>
            <value>
                <fullName>Order Form/Requirements</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_HRO__c/fields/HRO_1st_Payroll_New_Setup_Date__c.field-meta.xml
<CustomField>
    <fullName>HRO_1st_Payroll_New_Setup_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>1st Payroll Rundate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_HRO__c/fields/Implementation_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Coordinator</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>ExpenseWire Representatives</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Reference_Online_Services1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_HRO__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <formula>text(Case_Number__r.Status)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Integration Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OnboardingOverViewControllerTest.cls
/*Test methods for the OnboardingOverViewController class.
 
  History
  -------
  05/30/2012 Carrie Marciano and Justin Stouffer   Created.
  06/25/2013 Justin Stouffer 						Complete Redesign to Use Custom Setting
  11/08/2013 Cindy Freeman							fix timezone issue when creating user
  08/19/2019 Jacob Hinds							Changes to correspond to controller change
 */
@isTest
public with sharing class OnboardingOverViewControllerTest {

  static testMethod void testRefObject() {
          
      Client_Overview_Configuration__c coc = new Client_Overview_Configuration__c(Name='HRO' 
      																			  ,Product_Name__c='HRO'
                                                                                  ,Reference_Object_Relationship_API_Name__c='Reference_HROs__r'
                                                                                  ,Completed_Onboarding_Status__c='Completed'
                                                                                  ,Case_Record_Type_Name__c='Service Onboarding HRO Case Record Type'
                                                                                  ,Owner_Custom_Label__c='HRO Specialist'
                                                                                  ,Case_Only__c=FALSE);
      
      Client_Overview_Configuration__c coc1 = new Client_Overview_Configuration__c(Name='HRO1' 
      																			  ,Product_Name__c='HRO'
                                                                                  ,Reference_Object_Relationship_API_Name__c='Reference_HROs__r'
                                                                                  ,Completed_Onboarding_Status__c='Completed'
                                                                                  ,Case_Record_Type_Name__c='Service Onboarding MSP Ref Object'
                                                                                  ,Owner_Custom_Label__c='HRO Specialist'
                                                                                  ,OnboardingPOC_api__c='Implementation_Coordinator__r'
                                                                                  ,Reference_Object_Exp_Run_Date_api__c='HRO_1st_Payroll_New_Setup_Date__c'
                                                                                  ,Current_Step_API_Name__c='Integration_Status__c'
                                                                                  ,Case_Only__c=FALSE);
      
      Client_Overview_Status_Info__c cosi= new Client_Overview_Status_Info__c(Name='HRO 1'
                                                                         ,Key__c='HRO'
                                                                         ,Number__c=1
                                                                         ,DisplayText__c='Step 1'
                                                                         ,Status__c='(1 of 6) Introductory Call');
      Client_Overview_Status_Info__c cosi2= new Client_Overview_Status_Info__c(Name='HRO 2'
                                                                         ,Key__c='HRO'
                                                                         ,Number__c=5
                                                                         ,DisplayText__c=''
                                                                         ,Status__c='Step2');
      
      insert coc;
      insert coc1;
      insert cosi;
      insert cosi2;
      
      Account a1 = new Account(Name='Test Account');
      insert a1;
            
      User u1 = createUser();
      insert u1;
      
      Case HRO = createCase(RecordTypeHelper.getRecordType('Service Onboarding HRO Case Record Type','Case').getRecordTypeId(), a1.Id,u1.Id);
      insert HRO;
         
      //Set the current page to the account we are testing
      ApexPages.currentPage().getParameters().put('Id',a1.Id);   

      //Create the controller
      OnboardingOverViewController oov = new OnboardingOverViewController(new ApexPages.StandardController(a1));
      
      Reference_HRO__c rfHRO =  [Select Id, Current_Step__c, Name, Owner.Name, Owner.Phone from Reference_HRO__c where Case_Number__c=:HRO.Id];
      System.assertEquals(rfHRO.Current_Step__c, oov.singleRefCollection[0].status);
      System.assertEquals(rfHRO.Id, oov.singleRefCollection[0].id);
      System.assertEquals(rfHRO.Name, oov.singleRefCollection[0].refName);
      System.assertEquals(rfHRO.Owner.Name, oov.singleRefCollection[0].ownerName);
      System.assertEquals(rfHRO.Owner.Phone, oov.singleRefCollection[0].ownerPhone);
     
      oov.singleRefCollection[0].openTimeline();
      system.assert(oov.singleRefCollection[0].showTimeLine);
      
      //Change the current step or status of the reference object or case
      rfHRO.Current_Step__c = 'Completed'; 
      update rfHRO;

      //Create a second controller
      OnboardingOverViewController oov2 = new OnboardingOverViewController(a1.Id);

      //Assert the boolean values for the render attributes are correct for the new controller
      System.assertEquals(rfHRO.Current_Step__c, oov2.singleRefGradCollection[0].status);
      System.assertEquals(rfHRO.Id, oov2.singleRefGradCollection[0].id);
      System.assertEquals(rfHRO.Name, oov2.singleRefGradCollection[0].refName);
      System.assertEquals(rfHRO.Owner.Name, oov2.singleRefGradCollection[0].ownerName);
      System.assertEquals(rfHRO.Owner.Phone, oov2.singleRefGradCollection[0].ownerPhone);

  }

 static testMethod void testCaseOnly() {
      Client_Overview_Configuration__c coc = new Client_Overview_Configuration__c(Name='Preview' 
      																			  ,Product_Name__c='Preview'
                                                                                  ,Reference_Object_Relationship_API_Name__c=''
                                                                                  ,Completed_Onboarding_Status__c='Completed'
                                                                                  ,Case_Record_Type_Name__c='Service Onboarding MMS Payroll Case'
                                                                                  ,Owner_Custom_Label__c='Preview Specialist'
                                                                                  ,OnboardingPOC_api__c='Owner'
                                                                                  ,Case_Only__c=TRUE);
      insert coc;
           
      Account a1 = new Account(Name='Test Account');
      insert a1;
           
      User u1 = createUser();
      insert u1;
     Case Preview = createCase(RecordTypeHelper.getRecordType('Service Onboarding MMS Payroll Case','Case').getRecordTypeId(), a1.Id, u1.Id);
     insert Preview;     

      
      //Set the current page to the account we are testing
      ApexPages.currentPage().getParameters().put('Id',a1.Id);   
      //Create the controller
      OnboardingOverViewController oov = new OnboardingOverViewController(new ApexPages.StandardController(a1));

      Case rfPreview =  [Select Id, Status, CaseNumber, Owner.Name, Owner.Phone from Case where ID=:Preview.Id];
      System.assertEquals(rfPreview.Status, oov.singleRefCollection[0].status);
      System.assertEquals(rfPreview.Id, oov.singleRefCollection[0].id);
      System.assertEquals(rfPreview.CaseNumber, oov.singleRefCollection[0].refName);
      System.assertEquals(rfPreview.Owner.Name, oov.singleRefCollection[0].ownerName);
      System.assertEquals(rfPreview.Owner.Phone, oov.singleRefCollection[0].ownerPhone);

      //Change the current step or status of the reference object or case
      rfPreview.Status = 'Completed';     
      update rfPreview;
 
      //Create a second controller
      OnboardingOverViewController oov2 = new OnboardingOverViewController(a1.Id);

      //Assert the boolean values for the render attributes are correct for the new controller
      System.assertEquals(rfPreview.Status, oov2.singleRefGradCollection[0].status);
      System.assertEquals(rfPreview.Id, oov2.singleRefGradCollection[0].id);
      System.assertEquals(rfPreview.CaseNumber, oov2.singleRefGradCollection[0].refName);
      System.assertEquals(rfPreview.Owner.Name, oov2.singleRefGradCollection[0].ownerName);
      System.assertEquals(rfPreview.Owner.Phone, oov2.singleRefGradCollection[0].ownerPhone);    
  }
  private static Case createCase(Id recordTypeId, Id accountId, Id owner_Id) {
       Case c = new Case(RecordTypeId=recordTypeId, AccountId=accountId,OwnerId=owner_Id);
       return c;
    } // createCase
    
  private static User createUser(){
       Profile stdUsrProfile = [select id from profile where name='Standard User'];  
       User u1 = new User (lastName='Test1', firstName='Test', Phone='(555)555-5555',Sales_Org__c='Core',
         alias = 'stdUser9', email='stdUser999229@stdUser992299.com',   
         emailencodingkey='UTF-8', languagelocalekey='en_US',   
         localesidkey='en_US', profileid = stdUsrProfile.Id,   
         timezonesidkey='America/Indiana/Indianapolis', username='stdUser999922@stdUser999922.com');
       return u1;
    } //createUser
   
}