force-app/main/default/objects/Case/fields/Current_Step__c.field-meta.xml
<CustomField>
    <fullName>Current_Step__c</fullName>
    <description>Used by the Time and Attendance department to mark the stage of the onboarding process</description>
    <label>Current Step</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>(1 0f 7)Paperwork with Contractual</fullName>
            </value>
            <value>
                <fullName>(10 of 12) First Payroll Run</fullName>
            </value>
            <value>
                <fullName>(11 of 12) Post Run Debrief</fullName>
            </value>
            <value>
                <fullName>(12 of 12) Transfer to Ongoing Support</fullName>
            </value>
            <value>
                <fullName>(1 of 1) Waiting for 1st Tax Year</fullName>
            </value>
            <value>
                <fullName>(1 of 12) Sales Rep Conducting Needs Analysis</fullName>
            </value>
            <value>
                <fullName>(1 of 2) Introductory Call</fullName>
            </value>
            <value>
                <fullName>(1 of 2) Waiting for Appointment</fullName>
            </value>
            <value>
                <fullName>(1 of 3) Client in onboarding</fullName>
            </value>
            <value>
                <fullName>(1 of 3) Send Welcome Email</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Approval Copy Sent</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Client Load Received</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Introductory Call</fullName>
            </value>
            <value>
                <fullName>(1 of 4) PLE Welcome Call</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Waiting on IC</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Waiting on Turnover Call</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Client Load Received</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Kickoff Call</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Load Received - Welcome Call In Progress</fullName>
            </value>
            <value>
                <fullName>(1 of 5) New Case Received</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Schedule Training</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Welcome Call</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Welcome Email</fullName>
            </value>
            <value>
                <fullName>(1 of 6) Documentation Received/ Welcome Letter Sent</fullName>
            </value>
            <value>
                <fullName>(1 of 6) Internal Notification Email</fullName>
            </value>
            <value>
                <fullName>(1 of 6) Introductory Call</fullName>
            </value>
            <value>
                <fullName>(1 of 6) Welcome Call</fullName>
            </value>
            <value>
                <fullName>(1 of 7) Load received – IS verifying load docs</fullName>
            </value>
            <value>
                <fullName>(1 of 7) Meet &amp; Greet</fullName>
            </value>
            <value>
                <fullName>(1 of 8) Plan received - Waiting on IC</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_Terms_Transfers__c/Reference_Terms_Transfers__c.object-meta.xml
<CustomObject>
    <description>Used to track cancellations/NSF&apos;s/Transfers</description>
    <label>Reference Operations Support</label>
    <nameField>
        <displayFormat>Ref Ops Support-{000000}</displayFormat>
        <label>Reference Operations Support Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Operations Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_Terms_Transfers__c/fields/Case_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Case_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Lookup</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Reference Operations Support</relationshipLabel>
    <relationshipName>Reference_Terms_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_Terms_Transfers__c/fields/Current_Step__c.field-meta.xml
<CustomField>
    <fullName>Current_Step__c</fullName>
    <label>Current Step</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 of 4 - Void and Reissue Requested</fullName>
            </value>
            <value>
                <fullName>2 of 4 - Sent to Risk to Void Check</fullName>
            </value>
            <value>
                <fullName>3 of 4 - New Check Out for Approval</fullName>
            </value>
            <value>
                <fullName>401(k) Termination Complete</fullName>
            </value>
            <value>
                <fullName>401k Transfer Complete</fullName>
            </value>
            <value>
                <fullName>Closed - Cannot be Processed</fullName>
            </value>
            <value>
                <fullName>Closed - Check Already Cashed.</fullName>
            </value>
            <value>
                <fullName>Closed - Discrepancy Not Resolved</fullName>
            </value>
            <value>
                <fullName>Closed - NSF Unresolved</fullName>
            </value>
            <value>
                <fullName>Closed – Paperwork Discrepancy Never Resolved</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Complete - Check Approved</fullName>
            </value>
            <value>
                <fullName>Complete - New Check Approved</fullName>
            </value>
            <value>
                <fullName>Discrepancy - Need Additional Information</fullName>
            </value>
            <value>
                <fullName>Distribution Entered for Approval</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>NSF Closed</fullName>
            </value>
            <value>
                <fullName>Oustanding NSF</fullName>
            </value>
            <value>
                <fullName>Paperwork Discrepancy</fullName>
            </value>
            <value>
                <fullName>Returned - Not Processed</fullName>
            </value>
            <value>
                <fullName>S125 FSA Termination Complete</fullName>
            </value>
            <value>
                <fullName>S125 POP Termination Complete</fullName>
            </value>
            <value>
                <fullName>Term/Transfer Stopped</fullName>
            </value>
            <value>
                <fullName>New Request</fullName>
            </value>
            <value>
                <fullName>Void in Process</fullName>
            </value>
            <value>
                <fullName>New Check Out for Approval</fullName>
            </value>
            <value>
                <fullName>Check must be 10 BD Old to Process</fullName>
            </value>
            <value>
                <fullName>Waiting on CAM</fullName>
            </value>
            <value>
                <fullName>Waiting on LDPS</fullName>
            </value>
            <value>
                <fullName>Waiting on Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_Terms_Transfers__c/fields/Ready_for_Approval_2__c.field-meta.xml
<CustomField>
    <fullName>Ready_for_Approval_2__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Starts step 2 of the approval process</description>
    <label>Ready for Approval 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reference_Terms_Transfers__c/fields/Ready_for_Approval_3__c.field-meta.xml
<CustomField>
    <fullName>Ready_for_Approval_3__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Starts step 3 of the approval process</description>
    <label>Ready for Approval 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reference_Terms_Transfers__c/fields/Ready_for_Approval__c.field-meta.xml
<CustomField>
    <fullName>Ready_for_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Starts the approval process</description>
    <label>Ready for Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reference_Terms_Transfers__c/fields/Stable_Value_Funds__c.field-meta.xml
<CustomField>
    <fullName>Stable_Value_Funds__c</fullName>
    <label>Stable Value Funds</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FED CAP</fullName>
            </value>
            <value>
                <fullName>INVESCO (Manual)</fullName>
            </value>
            <value>
                <fullName>METLIFE GAC</fullName>
            </value>
            <value>
                <fullName>METLIFE SERIES</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>SVF (No Waiver Needed)</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_Terms_Transfers__c/fields/Stable_Value_Funds_Rep_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Stable_Value_Funds_Rep_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Stable Value Funds Rep</description>
    <label>Stable Value Funds Rep Lookup</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Reference_Operations_Support9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_Terms_Transfers__c/fields/Wire_Amount__c.field-meta.xml
<CustomField>
    <fullName>Wire_Amount__c</fullName>
    <label>Wire Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ReferenceOperationsSupportTest.cls
/*
*  Contains test methods pertinent to the Reference Operations Support Object
*
*  History
*  ---------
*  08/05/2016  Jacob Hinds    Created
*  08/10/2016  Jacob Hinds    Using Cancellations Queue now.
*
*/
@isTest
private class   ReferenceOperationsSupportTest {

    static testMethod void testOwnerUpdate() {
        String[] queueNames = new String[]{'HRS 4S Cancellations','HRS 4S Level 1 Approvers','HRS 4S Level 2 Approvers'};
	    Group[] queues = [select Id,Name from Group where Name in: queueNames and Type = 'Queue'];
	    Id cancellation;
	    Id level1;
	    Id level2;
	    if(!queues.isEmpty()){
	        for(Group g:queues){
	            if(g.Name == 'HRS 4S Cancellations'){
	                cancellation = g.Id;
	            }
	            else if(g.Name == 'HRS 4S Level 1 Approvers'){
	                level1 = g.Id;
	            }
	            else if(g.Name == 'HRS 4S Level 2 Approvers'){
	                level2 = g.Id;
	            }
	        }
	    }
        Schema.RecordTypeInfo cRT = RecordTypeHelper.getRecordType('401k/S125 Operations Support','Case');
        Schema.RecordTypeInfo refRT = RecordTypeHelper.getRecordType('401k Transfer','Reference_Terms_Transfers__c');
        
        Case c = new Case(RecordTypeId = cRT.getRecordTypeId());
        insert c;
        Reference_Terms_Transfers__c ref1 = new Reference_Terms_Transfers__c(RecordTypeId = refRT.getRecordTypeId(),Case_Lookup__c = c.Id);
        Reference_Terms_Transfers__c ref2 = new Reference_Terms_Transfers__c(RecordTypeId = refRT.getRecordTypeId(),Case_Lookup__c = c.Id);
        Reference_Terms_Transfers__c ref3 = new Reference_Terms_Transfers__c(RecordTypeId = refRT.getRecordTypeId(),Case_Lookup__c = c.Id);
        Reference_Terms_Transfers__c[] refs = new Reference_Terms_Transfers__c[]{ref1,ref2,ref3};
        insert refs;
        
        Test.startTest();
        
        ref1.OwnerId = cancellation;
        update ref1;
        
        Case newCase = [SELECT Id,OwnerId FROM Case WHERE Id = :c.Id];
        system.assertEquals(cancellation,newCase.OwnerId);
        
        //ref.OwnerId = level1;
        ref1.Wire_Amount__c = 1000000;
        ref1.Ready_for_Approval__c = true;
        update ref1;
        
        newCase = [SELECT Id,OwnerId FROM Case WHERE Id = :c.Id];
        system.assertEquals(level1,newCase.OwnerId);
        
        ref1.OwnerId = UserInfo.getUserId();
        update ref1;
        ProcessInstance pi1 = [SELECT TargetObjectId, CreatedDate FROM ProcessInstance WHERE TargetObjectId = :ref1.Id];
    	System.assert(pi1!=null);
        
        ref2.Wire_Amount__c = 1000000;
        ref2.Ready_for_Approval__c = true;
        ref2.Ready_for_Approval_2__c = true;
        update ref2;
        
        newCase = [SELECT Id,OwnerId FROM Case WHERE Id = :c.Id];
        system.assertEquals(level1,newCase.OwnerId);
        
        ref2.OwnerId = UserInfo.getUserId();
        update ref2;
        ProcessInstance pi2 = [SELECT TargetObjectId, CreatedDate FROM ProcessInstance WHERE TargetObjectId = :ref2.Id];
    	System.assert(pi2!=null);
        
        ref3.Wire_Amount__c = 1000000;
        ref3.Ready_for_Approval__c = true;
        ref3.Ready_for_Approval_2__c = true;
        ref3.Ready_for_Approval_3__c = true;
        update ref3;
        
        newCase = [SELECT Id,OwnerId FROM Case WHERE Id = :c.Id];
        system.assertEquals(level2,newCase.OwnerId);
        
        ref3.OwnerId = UserInfo.getUserId();
        update ref3;
        ProcessInstance pi3 = [SELECT TargetObjectId, CreatedDate FROM ProcessInstance WHERE TargetObjectId = :ref3.Id];
    	System.assert(pi3!=null);
        
        Test.stopTest();
    }
    
    static testMethod void testCaseCreation()
    {
        Schema.RecordTypeInfo cRT = RecordTypeHelper.getRecordType('401k/S125 Operations Support','Case');
        Schema.RecordTypeInfo refRT = RecordTypeHelper.getRecordType('401k Transfer','Reference_Terms_Transfers__c');
        
        User u = [Select Id, Name, ContactId FROM User WHERE Name='SFDC Data' LIMIT 1];
        Contact con = new Contact(FirstName='Test', LastName='Contact');
        insert con;
        Case c = new Case(RecordTypeId = cRT.getRecordTypeId(), ContactId=con.Id);
        insert c;
        
        Reference_Terms_Transfers__c ref1 = new Reference_Terms_Transfers__c(RecordTypeId = refRT.getRecordTypeId(),Case_Lookup__c = c.Id,Stable_value_Funds__c = null, Stable_Value_Funds_Rep_Lookup__c=u.Id, Current_Step__c ='In Process');
        insert ref1;
        ref1.Stable_Value_Funds__c = 'FED CAP';
        update ref1;
        
        Case[] createdCase = [Select Id, OwnerId FROM Case WHERE OwnerId =:u.Id];
        System.assertEquals(1, createdCase.size());
    }
}