force-app/main/default/objects/Case/fields/Level1AlertDateTime__c.field-meta.xml
<CustomField>
    <fullName>Level1AlertDateTime__c</fullName>
    <description>DateTime after which alert should be sent to Level1 Supervisor - calculated by trigger setAlertTimeStamp</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Level1 Alert DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Level2AlertDateTime__c.field-meta.xml
<CustomField>
    <fullName>Level2AlertDateTime__c</fullName>
    <description>DateTime after which alert should be sent to Level1 Supervisor - calculated by trigger setAlertTimeStamp</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Level2 Alert DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/SupervisorAlert__c.field-meta.xml
<CustomField>
    <fullName>SupervisorAlert__c</fullName>
    <description>A dummy toggle field used as a workaround for constraints in time-based workflow rules.
This field is toggled between 0 and 1 by workflow rule SetALertDatetime and evaluated by a pair of time-based workflow rules.</description>
    <label>SupervisorAlert</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/User_Level_1_Supervisor__c.field-meta.xml
<CustomField>
    <fullName>User_Level_1_Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to populate level 1 supervisor/manager on case record</description>
    <inlineHelpText>Used to populate level 1 supervisor/manager on case record</inlineHelpText>
    <label>User Level 1 Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases100</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/User_Level_2_Supervisor__c.field-meta.xml
<CustomField>
    <fullName>User_Level_2_Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to populate level 2 supervisor/manager on case record</description>
    <inlineHelpText>Used to populate level 2 supervisor/manager on case record</inlineHelpText>
    <label>User Level 2 Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases121</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseSetAlertTimeStampTest.cls
/* 
 * Test methods for CaseSetAlertTimeStamp
 *
 * History
 * -------
 * 07/15/2015 Dan Carmen   Created from CaseSetAlertTimeStamp class.
   10/26/2018 Dan Carmen   Set API version to 44

 */
@isTest
private class CaseSetAlertTimeStampTest {

   static testMethod void testTimeStamp() {
      // test that the time stamp is set
      // find a user with a manager and a 2nd level manager
      User u = [Select Id, ManagerId, Manager.ManagerId from User where IsActive=true and ManagerId != null and Manager.ManagerId != null limit 1];
      // get the RecordType for 'Service Premier Record Type'
      Schema.RecordTypeInfo rt = RecordTypeHelper.getCaseRecordTypeInfo(CaseSetAlertTimeStamp.SERVICE_PREMIER_RT);
      Id servicePremierRtId = (rt != null ? rt.getRecordTypeId() : null);

      System.runAs(u) {
         Case c = new Case(Subject='Test Case', RecordTypeId = servicePremierRtId);
         insert c;
          c = [Select Id, level1AlertDateTime__c, level2AlertDateTime__c
                     ,User_Level_1_Supervisor__c, User_Level_2_Supervisor__c
                     ,SupervisorAlert__c
                from Case where Id=:c.Id];
          System.assertEquals(true,(c.level1AlertDateTime__c != null));
          System.assertEquals(true,(c.level2AlertDateTime__c == null));
          System.assertEquals(u.ManagerId,c.User_Level_1_Supervisor__c);
          System.assertEquals(u.Manager.ManagerId,c.User_Level_2_Supervisor__c);
      }
   } // testTimeStamp

} // class CaseSetAlertTimeStampTest