force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup to the Opportunity if this Case is associated with one.</description>
    <inlineHelpText>A lookup to the Opportunity if this Case is associated with one.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpptyStatusHistory__c/OpptyStatusHistory__c.object-meta.xml
<CustomObject>
    <label>Oppty Status History</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oppty Status Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpptyStatusHistory__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date/time this status changed</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OpptyStatusHistory__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Oppty Status Histories</relationshipLabel>
    <relationshipName>OpptyStatusHistories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpptyStatusHistory__c/fields/PreviousStatus__c.field-meta.xml
<CustomField>
    <fullName>PreviousStatus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The previous Opportunity Status History record.</inlineHelpText>
    <label>Previous Status History</label>
    <referenceTo>OpptyStatusHistory__c</referenceTo>
    <relationshipLabel>Oppty Status Histories</relationshipLabel>
    <relationshipName>OpptyStatusHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpptyStatusHistory__c/fields/StageName__c.field-meta.xml
<CustomField>
    <fullName>StageName__c</fullName>
    <inlineHelpText>The opportunity status</inlineHelpText>
    <label>Stage Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Future Renewal</fullName>
            </value>
            <value>
                <fullName>Needs Analysis</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>Proposal Presented</fullName>
            </value>
            <value>
                <fullName>Negotiation/Discussion</fullName>
            </value>
            <value>
                <fullName>Pre-Qualifying</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Gained Access</fullName>
            </value>
            <value>
                <fullName>IEUP</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Profile Scheduled</fullName>
            </value>
            <value>
                <fullName>1st Presentation</fullName>
            </value>
            <value>
                <fullName>Profile Completed</fullName>
            </value>
            <value>
                <fullName>Partnership Presentation Scheduled</fullName>
            </value>
            <value>
                <fullName>Executive Overview</fullName>
            </value>
            <value>
                <fullName>Business Analysis</fullName>
            </value>
            <value>
                <fullName>Actively Engaged in Sales Process</fullName>
            </value>
            <value>
                <fullName>Partnership Presentation Completed</fullName>
            </value>
            <value>
                <fullName>Demo(s)</fullName>
            </value>
            <value>
                <fullName>Demo Scheduled</fullName>
            </value>
            <value>
                <fullName>Demo Completed</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Verbal Commit - Pick Up Discussed</fullName>
            </value>
            <value>
                <fullName>Verbal Commit</fullName>
            </value>
            <value>
                <fullName>Picked Up</fullName>
            </value>
            <value>
                <fullName>Proposal / Close</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Solution/Presentation (Demo)</fullName>
            </value>
            <value>
                <fullName>Decision/Pricing</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpptyStatusHistory__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date/time this status was set</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OpptyStatusHistory__c/fields/StatusIsClosed__c.field-meta.xml
<CustomField>
    <fullName>StatusIsClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Does this status close the opportunity?</inlineHelpText>
    <label>Status Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OpptyStatusHistory.cls
/* 
 * Keep track of the status history of a record. Once we get a closed status then we'll close any previous open status. 
   Any status that is closed will have an end date of the same day (start = end)
 *
 * History
 * -------
   06/06/2017 Dan Carmen      Created
   07/17/2017 Dan Carmen      Link to previous status record
   04/23/2018 Dan Carmen      Change to log even closed statuses
   02/25/2019 Dan Carmen      Check for name length

 */
public without sharing class OpptyStatusHistory implements TriggerInterface {

   public void checkAllBeforeTrigger(SObject[] recs, Map<Id,Object> oldMap) {}

   public void checkAllAfterTrigger(SObject[] recs, Map<Id,Object> oldMap) {}

   public void checkBeforeTrigger(SObject newRec, SObject oldRec) {}
   
   public void processBeforeTriggerActions() {}
   
   public static Id[] oppStatusChangeIds = new Id[]{};
   public static Set<Id> oppIdsProcessed = new Set<Id>();
   
   public void checkAfterTrigger(SObject newRec, SObject oldRec) {
      // collect the ids of the opportunities on insert or on status change
      if (!oppIdsProcessed.contains(newRec.Id) && (oldRec == null || (oldRec != null && ((Opportunity)newRec).StageName != ((Opportunity)oldRec).StageName))) {
         oppStatusChangeIds.add(newRec.Id);
      }
   } // checkAfterTrigger
   
   public void processAfterTriggerActions() {
      if (!oppStatusChangeIds.isEmpty()) {
         if (System.isFuture() || System.isBatch() || Test.isRunningTest()) {
            processStatusChangeNow(oppStatusChangeIds);
         } else {
            processStatusChangeFuture(oppStatusChangeIds);
         }
      } // if (!oppStatusChangeIds
      oppIdsProcessed.addAll(oppStatusChangeIds);
      oppStatusChangeIds.clear();
   } // processAfterTriggerActions
   
   @future
   public static void processStatusChangeFuture(Id[] oppIds) {
      processStatusChangeNow(oppIds);
   } // processStatusChangeFuture
   
   public static Integer NAME_LENGTH=OpptyStatusHistory__c.Name.getDescribe().getLength();
   
   public static void processStatusChangeNow(Id[] oppIds) {
      System.debug('processStatusChangeNow oppIds='+oppIds.size());
      Opportunity[] opps = [Select Id, Name
                                  ,IsClosed
                                  ,LastModifiedDate
                                  ,StageName
                                  ,(Select Id, Name
                                          ,EndDate__c
                                          ,Opportunity__c
                                          ,PreviousStatus__c
                                          ,StartDate__c
                                          ,StageName__c
                                          ,StatusIsClosed__c
                                      From OpptyStatusHistories__r
                                     Where EndDate__c = null)
                              From Opportunity
                             Where Id in :oppIds];
      
      OpptyStatusHistory__c[] updateRecs = new OpptyStatusHistory__c[]{};
      OpptyStatusHistory__c[] insertRecs = new OpptyStatusHistory__c[]{};
      
      for (Opportunity opp : opps) {
         OpptyStatusHistory__c curOsh = null;
         // keep track of the previous to link to the new one.
         OpptyStatusHistory__c prevOsh = null;
         // loop through the existing history records, closing all that don't match the current status.
         // there should at most be one record, but just in case.
         for (OpptyStatusHistory__c osh : opp.OpptyStatusHistories__r) {
            if (osh.StageName__c != opp.StageName) {
               System.debug('processStatusChangeNow closing history for '+opp.Name+' StageName='+osh.StageName__c);
               // assume the last modified date is the date for the status
               osh.EndDate__c = opp.LastModifiedDate;
               if (prevOsh == null) {
                  prevOsh = osh;
               }
               updateRecs.add(osh);
            } else {
               curOsh = osh;
            }
         } // for (OpptyStatusHistory__c osh
         
         /*
         if (curOsh != null && !opp.isClosed) {
            // do nothing here - it's open and the opp is open. Shouldn't logically get here, but just in case...
         } else if (curOsh != null && opp.isClosed) {
            // shouldn't get here because we shouldn't be creating records on closed statuses. Adding just to cover all bases.
            curOsh.EndDate__c = opp.LastModifiedDate;
            updateRecs.add(curOsh);
         } else 
         */
         // this should be the only valid action we're doing here.
         if (curOsh == null) {
            System.debug('processStatusChangeNow creating history for '+opp.Name+' StageName='+opp.StageName);
            // create a new history record
            curOsh = new OpptyStatusHistory__c(Name=(String.isNotBlank(opp.Name) ? opp.Name.left(NAME_LENGTH) : null), Opportunity__c=opp.Id
                                               ,PreviousStatus__c = (prevOsh != null ? prevOsh.Id : null)
                                               ,StartDate__c=opp.LastModifiedDate, StageName__c=opp.StageName
                                               ,EndDate__c=(opp.IsClosed ? Datetime.now() : null)
                                               ,StatusIsClosed__c = opp.IsClosed
                                               );
            insertRecs.add(curOsh);
         }

      } // for (Opportunity opp
      
      DmlHelper.performDml2(updateRecs, DmlHelper.DML_UPDATE, 'OpptyStatusHistory', 'processStatusChangeNow', 'Update existing', false);
      DmlHelper.performDml2(insertRecs, DmlHelper.DML_INSERT, 'OpptyStatusHistory', 'processStatusChangeNow', 'Insert new', false);
      ErrorLog.checkSave();
   } // processStatusChangeNow

} // class OpptyStatusHistory