force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup to the Opportunity if this Case is associated with one.</description>
    <inlineHelpText>A lookup to the Opportunity if this Case is associated with one.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Object_Relationships__c/Object_Relationships__c.object-meta.xml
<CustomObject>
    <description>used by code to create or update related object record from primary object record. For example - case to reference object.</description>
    <label>Object Relationships</label>
    <nameField>
        <displayFormat>Rel-{0000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Relationships__c/fields/Primary_Object_API_name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Object_API_name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Primary Object API name</label>
    <length>75</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Relationships__c/fields/Primary_Object_Rcd_Type__c.field-meta.xml
<CustomField>
    <fullName>Primary_Object_Rcd_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>record type name of primary object</inlineHelpText>
    <label>Primary Object Rcd Type</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Relationships__c/fields/Related_Object_API_name__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_API_name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Related Object API name</label>
    <length>75</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Relationships__c/fields/Related_Object_Rcd_Type__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_Rcd_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>record type name of Related object</inlineHelpText>
    <label>Related Object Rcd Type</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Relationships_Fields__c/Object_Relationships_Fields__c.object-meta.xml
<CustomObject>
    <description>Fields populated when related object record is created/updated from a primary object. (for example: case record creating a reference object record)</description>
    <label>Object Relationships Fields</label>
    <nameField>
        <displayFormat>ObjRel-Fld-{0000}</displayFormat>
        <label>Obj Rel Fields Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Relationships Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Relationships_Fields__c/fields/Field_Constant__c.field-meta.xml
<CustomField>
    <fullName>Field_Constant__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>constant used to populate related object field</inlineHelpText>
    <label>Field Constant</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Relationships_Fields__c/fields/FilterCriteria__c.field-meta.xml
<CustomField>
    <fullName>FilterCriteria__c</fullName>
    <description>Soon to be turned on!!</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>enter all values separated by commas, Null or Not Null are also valid.</inlineHelpText>
    <label>Filter Criteria</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_Relationships_Fields__c/fields/IsFilter__c.field-meta.xml
<CustomField>
    <fullName>IsFilter__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>check if defining filter criteria</inlineHelpText>
    <label>IsFilter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Object_Relationships_Fields__c/fields/Object_Relationships__c.field-meta.xml
<CustomField>
    <fullName>Object_Relationships__c</fullName>
    <label>Object Relationships</label>
    <referenceTo>Object_Relationships__c</referenceTo>
    <relationshipLabel>Object Relationships Fields</relationshipLabel>
    <relationshipName>Object_Relationships_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Object_Relationships_Fields__c/fields/Primary_Field_API_name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Field_API_name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Primary Field API name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Relationships_Fields__c/fields/Primary_Field_type__c.field-meta.xml
<CustomField>
    <fullName>Primary_Field_type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>filled in by trigger</inlineHelpText>
    <label>Primary Field type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Relationships_Fields__c/fields/Primary_Object_API_name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Object_API_name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>if left blank, filled in with primary object from Object Relationship</inlineHelpText>
    <label>Primary Object API name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Relationships_Fields__c/fields/Primary_Relationship_API_name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Relationship_API_name__c</fullName>
    <description>show relationship of this object from originating primary object (ex Opportunity__c from Case)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>only needed for custom lookups (ex Opportunity__c on Case)</inlineHelpText>
    <label>Primary Relationship API name</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Relationships_Fields__c/fields/Queue__c.field-meta.xml
<CustomField>
    <fullName>Queue__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>name of queue for related object ownership</inlineHelpText>
    <label>Queue</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Relationships_Fields__c/fields/Queue_Id__c.field-meta.xml
<CustomField>
    <fullName>Queue_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>filled in by trigger</inlineHelpText>
    <label>Queue_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Relationships_Fields__c/fields/Related_Field_API_name__c.field-meta.xml
<CustomField>
    <fullName>Related_Field_API_name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Related Field API name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Relationships_Fields__c/fields/Related_Field_type__c.field-meta.xml
<CustomField>
    <fullName>Related_Field_type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>filled in by trigger</inlineHelpText>
    <label>Related Field type</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Relationships_Fields__c/fields/Related_Object_API_name__c.field-meta.xml
<CustomField>
    <fullName>Related_Object_API_name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>filled in by trigger</inlineHelpText>
    <label>Related Object API name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_401k_S125__c/Reference_401k_S125__c.object-meta.xml
<CustomObject>
    <description>Used by operations teams to track the status of a new plans</description>
    <label>Reference 401k/S125</label>
    <nameField>
        <displayFormat>Reference 401k/S125-{000000}</displayFormat>
        <label>Reference_401k_S125</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference_401k_S125</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_401k_S125__c/fields/Basis_Points__c.field-meta.xml
<CustomField>
    <fullName>Basis_Points__c</fullName>
    <description>BU: 401k/S125 
Manual or Fed Field: Manual 
Case#:16403046</description>
    <label>Basis Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reference_401k_S125__c/fields/Blackout_Lifted__c.field-meta.xml
<CustomField>
    <fullName>Blackout_Lifted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Was the blackout lifted?</description>
    <label>Blackout Lifted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reference_401k_S125__c/fields/Case_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Case_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Lookup</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Reference_401k_S125</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_401k_S125__c/fields/Welcome_Package_Contents_Notes__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Package_Contents_Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Welcome Package Contents Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ObjectRelationshipsFieldsBeforeTest.cls
/**
 * This class contains unit tests for validating the ObjectRelationshipsFieldsBefore trigger.
 * 
 *
 * History
 * --------
 * 03/20/2013   Cindy Freeman   created
 * 10/06/2013 	Cindy Freeman	modified to test (ID) in field constant and to use longer FilterCriteria field
 *
 */

@isTest
private class ObjectRelationshipsFieldsBeforeTest {

    static testMethod void objRelFldTest1() {
        
        // insert Object relationship
        Object_Relationships__c orc1 = new Object_Relationships__c(Primary_Object_API_name__c = 'Case'
                                                                    , Primary_Object_Rcd_Type__c = 'Service Onboarding 401k New Case'
                                                                    , Related_Object_API_name__c = 'Reference_401k_S125__c'
                                                                    , Related_Object_Rcd_Type__c = 'Service Onboarding 401k New Case');
        insert orc1;
        
        // insert good Field relationship
        Object_Relationships_Fields__c orf1 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , Primary_Field_API_name__c = 'Id'
                                                        , Related_Field_API_name__c = 'Case_Lookup__c');
        insert orf1;
        Object_Relationships_Fields__c neworf1 = [Select Id, Name, Primary_Field_API_name__c, Primary_Field_type__c, Primary_Object_API_name__c, Primary_Relationship_API_name__c, 
                                                    Related_Field_API_name__c, Related_Field_type__c, Related_Object_API_name__c, 
                                                    Field_Constant__c, Queue__c, Queue_Id__c
                                                    From Object_Relationships_Fields__c where Object_Relationships__c = :orc1.Id];
        System.assertEquals('ID', neworf1.Primary_Field_type__c);
        System.assertEquals('Case', neworf1.Primary_Object_API_name__c);
        System.assertEquals('ID', neworf1.Related_Field_type__c);
        System.assertEquals('Reference_401k_S125__c', neworf1.Related_Object_API_name__c);                                                  
        
        // insert good Field relationships
        List<Object_Relationships_Fields__c> listorfs = new List<Object_Relationships_Fields__c>();
        Object_Relationships_Fields__c orf2 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , Field_Constant__c = 'True'
                                                        , Related_Field_API_name__c = 'Blackout_Lifted__c');
        listorfs.add(orf2);
        Object_Relationships_Fields__c orf3 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , Field_Constant__c = '1234.5'
                                                        , Related_Field_API_name__c = 'Basis_Points__c');
        listorfs.add(orf3);
        Object_Relationships_Fields__c orf4 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , Field_Constant__c = 'ABC123'
                                                        , Related_Field_API_name__c = 'Welcome_Package_Contents_Notes__c');
        listorfs.add(orf4);
        Object_Relationships_Fields__c orf5 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , Queue__c = 'HRS Field Support'
                                                        , Related_Field_API_name__c = 'OwnerId');
        listorfs.add(orf5);
        Object_Relationships_Fields__c orf6 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , Primary_field_API_name__c = 'Owner.ManagerId'
                                                        , Primary_Object_API_name__c = 'Opportunity'
                                                        , Primary_Relationship_API_name__c = 'Opportunity__c'
                                                        , Related_Field_API_name__c = 'OwnerId');
        listorfs.add(orf6);
        Object_Relationships_Fields__c orf7 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , IsFilter__c = true
                                                        , Primary_Field_API_name__c = 'Status'                                                      
                                                        , FilterCriteria__c = 'New');
        listorfs.add(orf7);
        Object_Relationships_Fields__c orf8 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , IsFilter__c = true
                                                        , Primary_Field_API_name__c = 'Origin'                                                      
                                                        , FilterCriteria__c = 'Not Null');
        listorfs.add(orf8);
        
        
        insert listorfs;                                                        
        Object_Relationships_Fields__c neworf2 = [Select Id, Primary_Field_type__c from Object_Relationships_Fields__c 
                                                    where Related_Field_API_name__c = 'Blackout_Lifted__c'];
        System.assertEquals('BOOLEAN', neworf2.Primary_Field_type__c);                                                  
        Object_Relationships_Fields__c neworf3 = [Select Id, Primary_Field_type__c from Object_Relationships_Fields__c 
                                                    where Related_Field_API_name__c = 'Basis_Points__c'];
        System.assertEquals('DOUBLE', neworf3.Primary_Field_type__c);                                                   
        Object_Relationships_Fields__c neworf4 = [Select Id, Primary_Field_type__c from Object_Relationships_Fields__c 
                                                    where Related_Field_API_name__c = 'Welcome_Package_Contents_Notes__c'];
        System.assertEquals('STRING', neworf4.Primary_Field_type__c);                                                   
        Object_Relationships_Fields__c neworf5 = [Select Id, Primary_Field_type__c from Object_Relationships_Fields__c 
                                                    where Queue__c = 'HRS Field Support'];
        System.assertEquals('ID', neworf5.Primary_Field_type__c);                                                   
        Object_Relationships_Fields__c neworf6 = [Select Id, Primary_Field_type__c from Object_Relationships_Fields__c 
                                                    where Primary_Field_API_name__c = 'Owner.ManagerId'];
        System.assertEquals('ID', neworf6.Primary_Field_type__c);                                                   
        Object_Relationships_Fields__c neworf8 = [Select Id, FilterCriteria__c from Object_Relationships_Fields__c 
                                                    where Primary_Field_API_name__c = 'Origin'];
        System.assertEquals('not null', neworf8.FilterCriteria__c);

        
        // insert bad Field realtionships       
        Object_Relationships_Fields__c orfb1 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , Primary_field_API_name__c = 'Bad_Primary_Fld'
                                                        , Related_Field_API_name__c = 'Blackout_Lifted__c');
        try {
            insert orfb1;
        }
        catch (Exception e2)
        {   System.assertEquals('Failed', 'Failed');}  
                
        Object_Relationships_Fields__c orfb2 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , Primary_field_API_name__c = 'Close_Date'
                                                        , Primary_Object_API_name__c = 'Opportunity'
                                                        , Primary_Relationship_API_name__c = 'Opportunity__c'
                                                        , Related_Field_API_name__c = 'Proposed_Run_Date__c');
        try {
            insert orfb2;
        }
        catch (Exception e2)
        {   System.assertEquals('Failed', 'Failed');}  
                
        Object_Relationships_Fields__c orfb3 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , Related_Field_API_name__c = 'Bad_Related_Fld');
        try {
            insert orfb3;
        }
        catch (Exception e2)
        {   System.assertEquals('Failed', 'Failed');}    
                
        Object_Relationships_Fields__c orfb4 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , Queue__c = 'Bad Queue Name'
                                                        , Related_Field_API_name__c = 'OwnerId');
        try {
            insert orfb4;
        }
        catch (Exception e2)
        {   System.assertEquals('Failed', 'Failed');}           
        
        Object_Relationships_Fields__c orfb5 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , Primary_field_API_name__c = 'Close_Date'
                                                        , Primary_Object_API_name__c = 'Opportunity'
                                                        , Primary_Relationship_API_name__c = 'Bad_Opportunity__r'
                                                        , Related_Field_API_name__c = 'Proposed_Run_Date__c');
        try {
            insert orfb5;
        }
        catch (Exception e2)
        {   System.assertEquals('Failed', 'Failed');}  
  
        Object_Relationships_Fields__c orfb6 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , Primary_field_API_name__c = 'Id'
                                                        , Related_Field_API_name__c = 'Blackout_Lifted__c');
        try {
            insert orfb6;
        }
        catch (Exception e2)
        {   System.assertEquals('Failed', 'Failed');}  
  
        Object_Relationships_Fields__c orfb7 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , IsFilter__c = true
                                                        , FilterCriteria__c = 'not null'
                                                        , Related_Field_API_name__c = 'Blackout_Lifted__c');
        try {
            insert orfb7;
        }
        catch (Exception e2)
        {   System.assertEquals('Failed', 'Failed');}  

        Object_Relationships_Fields__c orfb8 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , IsFilter__c = true);
        try {
            insert orfb8;
        }
        catch (Exception e2)
        {   System.assertEquals('Failed', 'Failed');}  

        Object_Relationships_Fields__c orfb9 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , Primary_field_API_name__c = 'Owner.SomeText.Id'
                                                        , Related_Field_API_name__c = 'OwnerId');
        try {
            insert orfb9;
        }
        catch (Exception e2)
        {   System.assertEquals('Failed', 'Failed');}  

        Object_Relationships_Fields__c orfb10 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , Primary_field_API_name__c = 'Owner.BossId'
                                                        , Related_Field_API_name__c = 'OwnerId');
        try {
            insert orfb10;
        }
        catch (Exception e2)
        {   System.assertEquals('Failed', 'Failed');}  

		Object_Relationships_Fields__c orfb11 = new Object_Relationships_Fields__c(Object_Relationships__c = orc1.Id
                                                        , Field_Constant__c = '(ID)badid123'
                                                        , Related_Field_API_name__c = 'Comments__c');
        try {
            insert orfb11;
        }
        catch (Exception e2)
        {   System.assertEquals('Failed', 'Failed');}  

    }
    
    
}