force-app/main/default/objects/Case/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Referral Contacts for Cases related to Brokers</description>
    <label>Referral Contact</label>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field should only be completed if the Lead Source is an external partner (CPA, Bank, FA, etc.)</inlineHelpText>
    <label>Referral Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Contact__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Referral Contacts with End Dates will only appear if you click the Show All Results link below.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>OppRCs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_User_Details__c/Partner_Portal_User_Details__c.object-meta.xml
<CustomObject>
    <label>Partner Portal User Details</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Partner Portal User Details	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal User Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Portal_User_Details__c/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral Contact</label>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Partner Portal User Details</relationshipLabel>
    <relationshipName>Partner_Portal_User_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/Referral_Contact__c.object-meta.xml
<CustomObject>
    <label>Referral Contact</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ReferralContactWrapper.cls
public with sharing class ReferralContactWrapper {
    @AuraEnabled public Referral_Contact__c ReferralContact { get; set; }
    @AuraEnabled public List<ActivityDA.ActivityCombined> OpenActivities { get; set; }
    @AuraEnabled public List<Case> OpenCases { get; set; }
    @AuraEnabled public List<Opportunity> OpenOpportunities { get; set; }
    @AuraEnabled public Integer MutualClientCount { get; set; }
    @AuraEnabled public List<Account> MutualClients { get; set; }
    @AuraEnabled public Map<String,Object> refConData;
    @AuraEnabled public Partner_Portal_User_Details__c pPUDData {get;set;}
 
}