force-app/main/default/objects/Acord__c/Acord__c.object-meta.xml
<CustomObject>
    <label>Acord</label>
    <nameField>
        <displayFormat>Acord-{00000}</displayFormat>
        <label>Acord</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acords</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Acord__c/fields/Prospect_Client__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect-Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Acords</relationshipLabel>
    <relationshipName>Acords</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Quote__c/Carrier_Quote__c.object-meta.xml
<CustomObject>
    <description>Used by P&amp;C to store quotes provided by carriers</description>
    <label>Carrier Quote</label>
    <nameField>
        <displayFormat>Carrier Quote - {000000000}</displayFormat>
        <label>Carrier Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carrier Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier_Quote__c/fields/Acord_Name__c.field-meta.xml
<CustomField>
    <fullName>Acord_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Acord Name</label>
    <referenceTo>Acord__c</referenceTo>
    <relationshipLabel>Carrier Quotes</relationshipLabel>
    <relationshipName>Carrier_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Quote__c/fields/Carrier_Name__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Name__c</fullName>
    <label>Carrier Name**</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5-STAR</fullName>
            </value>
            <value>
                <fullName>ACE</fullName>
            </value>
            <value>
                <fullName>AIG</fullName>
            </value>
            <value>
                <fullName>AMTRUST NORTH AMERICA INC</fullName>
            </value>
            <value>
                <fullName>CHESAPEAKE EMP INS</fullName>
            </value>
            <value>
                <fullName>CNA</fullName>
            </value>
            <value>
                <fullName>KENTUCKY EMPLOYERS MUTUAL</fullName>
            </value>
            <value>
                <fullName>LIBERTY MUTUAL</fullName>
            </value>
            <value>
                <fullName>MARKEL CORPORATION</fullName>
            </value>
            <value>
                <fullName>MICHIGAN STATE FUND</fullName>
            </value>
            <value>
                <fullName>MINNESOTA WC ASSGND RISK</fullName>
            </value>
            <value>
                <fullName>NCCI</fullName>
            </value>
            <value>
                <fullName>NEW JERSEY WC INS. PLAN</fullName>
            </value>
            <value>
                <fullName>PA WORKERS COMP</fullName>
            </value>
            <value>
                <fullName>PIE INSURANCE</fullName>
            </value>
            <value>
                <fullName>PMC Insurance Group</fullName>
            </value>
            <value>
                <fullName>RHODE ISLAND WC</fullName>
            </value>
            <value>
                <fullName>STATE ACCIDENT INS FUND</fullName>
            </value>
            <value>
                <fullName>TEXAS WORKERS COMP</fullName>
            </value>
            <value>
                <fullName>TRAVELERS (P&amp;C)</fullName>
            </value>
            <value>
                <fullName>WISCONSIN COMP RATING BUR</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
                <label>OTHER *If Selected, Add Other Carrier Name on PDF form</label>
            </value>
            <value>
                <fullName>AmWins Group, Inc.</fullName>
            </value>
            <value>
                <fullName>California State Fund (SCIF)</fullName>
            </value>
            <value>
                <fullName>CHUBB</fullName>
            </value>
            <value>
                <fullName>Colorado State Fund</fullName>
            </value>
            <value>
                <fullName>EMPLOYERS</fullName>
            </value>
            <value>
                <fullName>GUARD(Berkshire Hathaway)</fullName>
            </value>
            <value>
                <fullName>HARTFORD</fullName>
            </value>
            <value>
                <fullName>Hiscox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Current_Step__c.field-meta.xml
<CustomField>
    <fullName>Current_Step__c</fullName>
    <description>Used by the Time and Attendance department to mark the stage of the onboarding process</description>
    <label>Current Step</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>(1 0f 7)Paperwork with Contractual</fullName>
            </value>
            <value>
                <fullName>(10 of 12) First Payroll Run</fullName>
            </value>
            <value>
                <fullName>(11 of 12) Post Run Debrief</fullName>
            </value>
            <value>
                <fullName>(12 of 12) Transfer to Ongoing Support</fullName>
            </value>
            <value>
                <fullName>(1 of 1) Waiting for 1st Tax Year</fullName>
            </value>
            <value>
                <fullName>(1 of 12) Sales Rep Conducting Needs Analysis</fullName>
            </value>
            <value>
                <fullName>(1 of 2) Introductory Call</fullName>
            </value>
            <value>
                <fullName>(1 of 2) Waiting for Appointment</fullName>
            </value>
            <value>
                <fullName>(1 of 3) Client in onboarding</fullName>
            </value>
            <value>
                <fullName>(1 of 3) Send Welcome Email</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Approval Copy Sent</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Client Load Received</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Introductory Call</fullName>
            </value>
            <value>
                <fullName>(1 of 4) PLE Welcome Call</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Waiting on IC</fullName>
            </value>
            <value>
                <fullName>(1 of 4) Waiting on Turnover Call</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Client Load Received</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Kickoff Call</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Load Received - Welcome Call In Progress</fullName>
            </value>
            <value>
                <fullName>(1 of 5) New Case Received</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Schedule Training</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Welcome Call</fullName>
            </value>
            <value>
                <fullName>(1 of 5) Welcome Email</fullName>
            </value>
            <value>
                <fullName>(1 of 6) Documentation Received/ Welcome Letter Sent</fullName>
            </value>
            <value>
                <fullName>(1 of 6) Internal Notification Email</fullName>
            </value>
            <value>
                <fullName>(1 of 6) Introductory Call</fullName>
            </value>
            <value>
                <fullName>(1 of 6) Welcome Call</fullName>
            </value>
            <value>
                <fullName>(1 of 7) Load received – IS verifying load docs</fullName>
            </value>
            <value>
                <fullName>(1 of 7) Meet &amp; Greet</fullName>
            </value>
            <value>
                <fullName>(1 of 8) Plan received - Waiting on IC</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_P_C__c/Reference_P_C__c.object-meta.xml
<CustomObject>
    <description>Used by the Property and Casualty (P&amp;C) Team to onboard clients.</description>
    <label>Reference P&amp;C</label>
    <nameField>
        <displayFormat>Reference PC - {0000}</displayFormat>
        <label>Reference P&amp;C Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference P&amp;C&apos;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_P_C__c/fields/Carrier_Name__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Name__c</fullName>
    <formula>TEXT(Carrier_Quote_Lookup__r.Carrier_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Carrier Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_P_C__c/fields/Carrier_Quote_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Quote_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the related Carrier Quote record. The Carrier Quote is related to the Acord object through the Prospect-Client.
This will be populated on creation of the Reference P&amp;C record.</description>
    <label>Carrier Quote Lookup</label>
    <referenceTo>Carrier_Quote__c</referenceTo>
    <relationshipLabel>Reference P&amp;C&apos;s</relationshipLabel>
    <relationshipName>Reference_P_C_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_P_C__c/fields/Case_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Case_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The case this reference record is related to.</description>
    <label>Case Lookup</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Reference P&amp;C&apos;s</relationshipLabel>
    <relationshipName>Reference_P_C_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_P_C__c/fields/Current_Step__c.field-meta.xml
<CustomField>
    <fullName>Current_Step__c</fullName>
    <description>Current step is set on the reference record and fed in to the case</description>
    <label>Current Step</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Client in Discrepancy</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Payroll Run/Verification</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Ready for Setup</fullName>
            </value>
            <value>
                <fullName>Escalated to Front-end Team</fullName>
            </value>
            <value>
                <fullName>Waiting on AL3</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TriggerSetup__c/TriggerSetup__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Is a particular trigger setup for use in the Trigger Methods class?</description>
    <label>Trigger Setup</label>
</CustomObject>

force-app/main/default/objects/TriggerSetupClasses__c/TriggerSetupClasses__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The classes that are executed as part of each trigger execution</description>
    <label>Trigger Setup Classes</label>
</CustomObject>

force-app/main/default/classes/ReferencePCTest.cls
/**
 * Test class for ReferencePCTest
 * 07/24/2018 Lynn Michels  Created
 * 08/06/2018 Lynn Michels  Edited to test more functionality of the class
 */
@isTest
private with sharing class ReferencePCTest {
    
     @testSetup
    static void setupData() {
        TriggerSetupClasses__c[] setupClasses = new TriggerSetupClasses__c[]{};
        TriggerSetup__c trigSetup = TriggerMethodsTest.createCustomSetting(null, 'ReferencePC', false, true, new String[]{'ReferencePC'}, setupClasses);
        insert setupClasses;
    } // setupData
    
    static testMethod void ReferencePCInsert() {
        Account acct = new Account(Name='Test Acct');
        insert acct;
        Acord__c acord = new Acord__c(Prospect_Client__c = acct.id);
        insert acord;
        Test.setCreatedDate(acord.Id, DateTime.newInstance(2012,12,11));        
        
        Carrier_Quote__c cquote = new Carrier_Quote__c(Acord_Name__c = acord.id);
        insert cquote;
        Test.setCreatedDate(cquote.Id, DateTime.newInstance(2012,12,12));
       
        //need to insert them separately so they have different created time stamps
        Acord__c acord2 = new Acord__c(Prospect_Client__c = acct.id);
        insert acord2;
        Test.setCreatedDate(acord2.Id, DateTime.newInstance(2012,12,12));
        
        Carrier_Quote__c cquote2 = new Carrier_Quote__c(Acord_Name__c = acord2.id, Carrier_Name__c = 'Test Carrier');
        insert cquote2;
        Test.setCreatedDate(cquote2.Id, DateTime.newInstance(2012,12,13));
        
        Carrier_Quote__c cquote3 = new Carrier_Quote__c(Acord_Name__c = acord2.id, Carrier_Name__c = 'test2 Carrier');
        insert cquote3;
        Test.setCreatedDate(cquote3.Id, DateTime.newInstance(2012,12,14));
        
        Id caseRTId = RecordTypeHelper.getRecordType('Service Onboarding P&C Case', 'Case').getRecordTypeID();
        Case c = new Case(AccountId = acct.id, recordtypeId = caseRTId);
        insert c;
        Id refPCTypeId = RecordTypeHelper.getRecordType('P&C Onboarding', 'Reference_P_C__c').getRecordTypeID();
        Reference_P_C__c refPC = new Reference_P_C__c(Case_Lookup__c = c.id, recordTypeId = refPCTypeId);
        
        test.startTest();
        List<Carrier_Quote__c> quoteList = [SELECT id, CreatedDate, Acord_Name__c FROM Carrier_Quote__c];
        system.debug('LM Created Date ' + quoteList);
        
            insert refPC;
            list<Reference_P_C__c> refPCList = [SELECT id, Carrier_Quote_Lookup__c FROM Reference_P_C__c];
            system.assertEquals(1,refPCList.size());
            system.assertEquals(cquote3.id,refPCList[0].Carrier_Quote_Lookup__c);
        test.stopTest();
        
    }//end ReferencePCInsert
    
    static testMethod void ReferencePCUpdate() {
        Account acct = new Account(Name='Test Acct');
        insert acct;
        Id caseRTId = RecordTypeHelper.getRecordType('Service Onboarding P&C Case', 'Case').getRecordTypeID();
        Case c = new Case(AccountId = acct.id, recordtypeId = caseRTId, Current_step__c = 'New');
        insert c;
        Id refPCTypeId = RecordTypeHelper.getRecordType('P&C Onboarding', 'Reference_P_C__c').getRecordTypeID();
        Reference_P_C__c refPC = new Reference_P_C__c(Case_Lookup__c = c.id, recordTypeId = refPCTypeId, Current_Step__c = 'New');
        insert refPC;
        
        test.startTest();
            refPC.current_step__c = 'in progress';
            update refPC;
            list<Reference_P_C__c> refPCList = [SELECT id, Current_Step__c FROM Reference_P_C__c];
            list<Case> caseList = [SELECT id, current_step__c FROM Case];
            system.assertEquals(caseList[0].current_step__c,refPCList[0].current_Step__c);
        test.stopTest();
        
    }//end ReferencePCInsert
    
    //for code coverage
    static testMethod void testMisc() {     
            ReferencePC refPC = new ReferencePC();
            refPC.checkAllBeforeTrigger(null, null);
            refPC.checkBeforeTrigger(null, null); 
            refPC.processBeforeTriggerActions();
            refPC.checkAfterTrigger(null, null);
            refPC.processAfterTriggerActions(); 
                       
    }//end testMisc
}