force-app/main/default/objects/Cost_Center__c/Cost_Center__c.object-meta.xml
<CustomObject>
    <description>Child of User_License__c object. Used to store the information about cost centers and active licenses associated to them</description>
    <label>Cost Center</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Centers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <defaultValue>&quot;0000&quot;</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Cost Center</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Creation_Type__c.field-meta.xml
<CustomField>
    <fullName>Creation_Type__c</fullName>
    <description>The method of creation of this User record. This is populated from the New User application.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The method of creation of this User record.</inlineHelpText>
    <label>Creation Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter district number as a 3 digit number with leading zero</inlineHelpText>
    <label>District</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Hire_Date__c.field-meta.xml
<CustomField>
    <fullName>Hire_Date__c</fullName>
    <description>Date of Hire</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Hire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/HR_Person_Id__c.field-meta.xml
<CustomField>
    <fullName>HR_Person_Id__c</fullName>
    <description>The Person Id from HR</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Person Id from HR</inlineHelpText>
    <label>HR Person Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Person_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Person_ID_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sales Rep ID Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org-Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>BenAdmin</fullName>
            </value>
            <value>
                <fullName>Benetrac</fullName>
            </value>
            <value>
                <fullName>BusDev</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Relations</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Center</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise Service Center</fullName>
            </value>
            <value>
                <fullName>ESR</fullName>
            </value>
            <value>
                <fullName>EW</fullName>
            </value>
            <value>
                <fullName>Field Operations Core</fullName>
            </value>
            <value>
                <fullName>HNBF</fullName>
            </value>
            <value>
                <fullName>HROI</fullName>
            </value>
            <value>
                <fullName>HR Online</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>HRS 401K-S125</fullName>
            </value>
            <value>
                <fullName>HRS Premier</fullName>
            </value>
            <value>
                <fullName>Icon</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Merchant Services</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MMS Hub</fullName>
            </value>
            <value>
                <fullName>MPSC</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>PAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>Termination_Date__c</fullName>
    <description>Ths date tracks the terminated reps</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/UserTestHelper.cls
/* 
  Methods used to help test User and associated objects.
   
  History
  -------
  01/28/2011 Dan Carmen   Created
  10/11/2012 Dan Carmen   Added in a few more join fields.
  04/24/2013 Dan Carmen   Cleaning up code for User License maintenance
  01/05/2024 Dan Carmen   Removed User License code.
   
 */
 @isTest
public class UserTestHelper {

   /** Create a user record and add to the passed in list.
    */
   public void createUser(List<User> users, Integer userNum, Profile p, UserRole ur, User curUser) {
   	  users.add(createUser(userNum,p,ur,curUser));
   } // createUser
   
   /** Create a user record.
    */	
   public User createUser(Integer userNum, Profile p, UserRole ur, User curUser) {
      // create a new user
      User u = new User(FirstName = 'Jaffe'
                        ,LastName = 'Joffer'+userNum
                        ,Title = 'King'
                        ,Username = 'jjoffer'+userNum+'@paychex.com.test'+userNum
                        ,Email = 'jjoffer'+userNum+'@paychex.com.test'+userNum
                        ,Sales_Org__c = 'PAY'
                        ,IsActive = true
                        // person id
                        ,EmployeeNumber = 'TestEmp-'+userNum
                        ,HR_Person_ID__c = 'TestId'+userNum
                        ,Hire_Date__c = Date.today()
                        ,Termination_Date__c = null
                        ,ManagerId = null
                        ,Department = 'Test Dept'
                        ,Alias = 'alias'+userNum
                        ,CommunityNickname = 'nickname'+userNum
                        ,MobilePhone = '585-123-6544'
                        ,Phone = '585-123-6543'
                        // rep code
                        ,Person_ID_Number__c = 'A123'
                        ,Street = '123 Some St'
                        ,City = 'Somewhere'
                        ,PostalCode = '14514'
                        ,State = 'NY'
                        ,UserRoleId = ur.Id
                        ,UserRole = ur
                        ,ProfileId = p.Id
                        ,Profile = p
                        ,Cost_Center__c = '0017'
                        ,District__c = '0017'
                        ,Creation_Type__c = 'NewUser'
                        );
      u.TimeZoneSidKey = curUser.TimeZoneSidKey;
      u.LocaleSidKey = curUser.LocaleSidKey;
      u.EmailEncodingKey = curUser.EmailEncodingKey;
      u.LanguageLocaleKey = curUser.LanguageLocaleKey;
      return u;
   } // createUser

   /** Get a User record by the Id.
    */
   public User getUserById(Id userId) {
      User u = [Select Id, TimeZoneSidKey, LocaleSidKey, EmailEncodingKey, LanguageLocaleKey
                      ,ProfileId, Profile.Id, Profile.Name
                      ,UserRoleId, UserRole.Id, UserRole.Name, UserRole.ParentRoleId
                      ,EmployeeNumber, HR_Person_ID__c
                      ,Termination_Date__c,Department,FirstName
                      ,LastName,Hire_Date__c,Street
                      ,City,State,PostalCode,Cost_Center__c
                      ,Person_ID_Number__c,Phone,Title
                  from User 
                 where Id = :userId];
      return u;
   } // getUserById
   
   /** Default constructor.
    */
   public UserTestHelper() {
   	  
   } // UserTestHelper


} // class UserTestHelper