force-app/main/default/objects/Chatter_Group_Setup__c/Chatter_Group_Setup__c.object-meta.xml
<CustomObject>
    <label>Chatter Group Setup</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Chatter Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chatter Group Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chatter_Group_Setup__c/fields/ChatterGroupId__c.field-meta.xml
<CustomField>
    <fullName>ChatterGroupId__c</fullName>
    <description>The Salesforce Id for the Chatter Group (CollaborationGroup).</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Salesforce Id for the Chatter Group (CollaborationGroup).</inlineHelpText>
    <label>Chatter Group Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chatter_Group_Setup__c/fields/Child_Groups__c.field-meta.xml
<CustomField>
    <fullName>Child_Groups__c</fullName>
    <description>Used so this can be table driven - all of the chatter groups included with this chatter group. List should be separated by semi-colons.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Used so this can be table driven - all of the chatter groups included with this chatter group. List should be separated by semi-colons.</inlineHelpText>
    <label>Child Groups</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Chatter_Group_Setup__c/fields/Do_Not_Include_Child_Profiles__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Include_Child_Profiles__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>By default all selected child profiles are included in the parent. If you only want to use the profiles selected specifically for this group, select this checkbox.</inlineHelpText>
    <label>Do Not Include Child Profiles</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chatter_Group_Setup__c/fields/ExecuteSetup__c.field-meta.xml
<CustomField>
    <fullName>ExecuteSetup__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Execute the setup for this record. Only one record will be executed during a trigger execution.</inlineHelpText>
    <label>Execute Setup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chatter_Group_Setup__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this group active?</description>
    <inlineHelpText>Is this group active?</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chatter_Group_Setup__c/fields/Manager_Profiles__c.field-meta.xml
<CustomField>
    <fullName>Manager_Profiles__c</fullName>
    <description>If users have these profiles and they&apos;re added to this group, they will be set as managers. Semi-colon separated list.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>If users have these profiles and they&apos;re added to this group, they will be set as managers. Semi-colon separated list.</inlineHelpText>
    <label>Manager Profiles</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Chatter_Group_Setup__c/fields/Org_Units__c.field-meta.xml
<CustomField>
    <fullName>Org_Units__c</fullName>
    <description>Used so this can be table driven - all of the org units included for this chatter group. List should be separated by semi-colons.`</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Used so this can be table driven - all of the org units included for this chatter group. List should be separated by semi-colons.</inlineHelpText>
    <label>Org Units</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Chatter_Group_Setup__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The User the process is setting as the owner of the group.</description>
    <inlineHelpText>The User the process is setting as the owner of the group.</inlineHelpText>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Chatter_Group_Setups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chatter_Group_Setup__c/fields/Owner_Profile__c.field-meta.xml
<CustomField>
    <fullName>Owner_Profile__c</fullName>
    <description>The profile to check for the owner of the group. The first person found with this profile will be the owner if an owner isn&apos;t already set with the profile.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The profile to check for the owner of the group. The first person found with this profile will be the owner if an owner isn&apos;t already set with the profile.</inlineHelpText>
    <label>Owner Profile</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chatter_Group_Setup__c/fields/Owner_Role__c.field-meta.xml
<CustomField>
    <fullName>Owner_Role__c</fullName>
    <description>The name of the Role for the Owner of the record.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the Role for the Owner of the record.</inlineHelpText>
    <label>Owner Role</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chatter_Group_Setup__c/fields/Select_From_All_Profiles__c.field-meta.xml
<CustomField>
    <fullName>Select_From_All_Profiles__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This will build the profile list from all Profiles, instead of just from the profiles that are part of its children.</inlineHelpText>
    <label>Select From All Profiles</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chatter_Group_Setup__c/fields/Selected_Profiles__c.field-meta.xml
<CustomField>
    <fullName>Selected_Profiles__c</fullName>
    <description>The profiles selected to be part of this group (separated by semi-colons)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The profiles selected to be part of this group (separated by semi-colons)</inlineHelpText>
    <label>Selected Profiles</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Chatter_Group_Setup__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Is this a public or private group?</description>
    <inlineHelpText>Is this a public or private group?</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
                <default>true</default>
                <label>Public</label>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chatter_Group_Setup__c/fields/Use_Owner__c.field-meta.xml
<CustomField>
    <fullName>Use_Owner__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Use the value in the Owner field for the Owner of the Group. If this is checked the process will not attempt to determine the Owner using the Role Hierarchy.</inlineHelpText>
    <label>Use Owner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Org_Unit__c/Org_Unit__c.object-meta.xml
<CustomObject>
    <label>Org Unit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Org Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Org_Unit__c/fields/Available_Profiles__c.field-meta.xml
<CustomField>
    <fullName>Available_Profiles__c</fullName>
    <description>The available profiles for this cost center, based on the users that are in this cost center.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The available profiles for this cost center, based on the users that are in this cost center.</inlineHelpText>
    <label>Available Profiles</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ChatterGroupSetupController.cls
/* Controller to maintain the Chatter_Group_Setup__c object. 
   This is only intended for use on editing an existing record, not in creating a new one.
   Test methods are in ChatterMethodsTest.
   
  History
  -------
  04/10/2012 Dan Carmen   Created
  06/11/2012 Dan Carmen   Modified for owner fix.
  07/31/2012 Dan Carmen   Logic to select based only on profiles - ability to use all profiles for selection.
  
 */
public with sharing class ChatterGroupSetupController {

   /** The setup object retrieved. */
   public Chatter_Group_Setup__c cgs{get;set;}
   
   /** Constructor
    */
   public ChatterGroupSetupController(ApexPages.StandardController stdController) {
      cgs = (Chatter_Group_Setup__c)stdController.getRecord();
      Id cgsId = System.currentPageReference().getParameters().get('Id');
      // if this is an existing record, will select it here
      if (cgsId != null) {
         cgs = [Select Id, Name
                      ,ChatterGroupId__c
                      ,Child_Groups__c
                      ,Do_Not_Include_Child_Profiles__c
                      ,ExecuteSetup__c
                      ,IsActive__c
                      ,Manager_Profiles__c
                      ,Org_Units__c
                      ,Owner__c
                      ,Owner_Profile__c
                      ,Owner_Role__c
                      ,Selected_Profiles__c
                      ,Select_From_All_Profiles__c
                      ,Type__c
                      ,Use_Owner__c
                  From Chatter_Group_Setup__c
                 Where Id = :cgsId];
         // set the options from the existing record
         setProfileOptions(cgs);
      } // if (cgsId

   } //ChatterGroupSetupController
   
   /** The profiles selected to be part of this group. */
   public List<String> selectedProfiles{get;set;}
   /** The options selected for the manager role. */
   public List<String> managerProfiles{get;set;}
   
   /** The options for the owner role. */
   public List<SelectOption> ownerProfileOptions{get;set;}

   /** All of the available profile options. */
   public List<SelectOption> profileOptions{get;set;}
   
   /** Set up all of the profiles that are available.
    */
   public void setProfileOptions(Chatter_Group_Setup__c cgs) {
   	ChatterMethods cm = new ChatterMethods();
      Map<Id,Chatter_Group_Setup__c> allSetupsMap = cm.getGroupAndChildren(cgs);
      
      // check for cost centers of all groups
      Org_Unit__c[] costCenters = cm.getCostCenters(allSetupsMap.keySet());
   	Set<String> profileNamesSet = new Set<String>();
   	for (Org_Unit__c costCenter : costCenters) {
   	   if (costCenter.Available_Profiles__c != null) {
   	      String[] profs = costCenter.Available_Profiles__c.split(';');
   	      profileNamesSet.addAll(profs);
   	   }
   	} // for (Org_Unit__c
   	// if the flag is set, select all profiles
   	if (cgs.Select_From_All_Profiles__c) {
   	   profileNamesSet = getAllProfiles(profileNamesSet);
   	}
   	List<String> profileNamesList = new List<String>();
   	profileNamesList.addAll(profileNamesSet);
   	profileNamesList.sort();
   	
   	profileOptions = new List<SelectOption>();
   	ownerProfileOptions = new List<SelectOption>();
   	ownerProfileOptions.add(new SelectOption('','<None>'));
   	profileOptions.add(new SelectOption('','<None>'));
   	for (String profName : profileNamesList) {
   	   profileOptions.add(new SelectOption(profName,profName));
   	   ownerProfileOptions.add(new SelectOption(profName,profName));
   	}
   	selectedProfiles = (cgs.Selected_Profiles__c != null ? cgs.Selected_Profiles__c.split(';') : new List<String>());
      managerProfiles = (cgs.Manager_Profiles__c != null ? cgs.Manager_Profiles__c.split(';') : new List<String>());
   } // setProfileOptions

   /** Concatenated the profiles into one string. */
   public String concatenateProfs(List<String> profs, Integer maxLength) {
      String retVal = '';
      for (String prof : profs) {
      	if (prof != '<None>') {
      		if (retVal.length()+prof.length()+1 < maxLength) {
               if (retVal.length() > 0) {
                  retVal += ';';
               }
               retVal += prof;
      		} else {
      		   System.debug('The maximum field length was reached!');
      		} // if
      	} // if (prof != '<None>'
      } // for
      return retVal;
   } // concatenateProfs
   
   /** Retrieve all of the profiles that are not already retrieved.
    */
   public Set<String> getAllProfiles(Set<String> p_profileNamesSet) {
   	Set<String> profileNamesSet = new Set<String>();
   	profileNamesSet.addAll(p_profileNamesSet);
   	// there shouldn't be a volume issue, but just in case...
   	for (Profile[] profs : [Select Id, Name from Profile where Name not in :p_profileNamesSet]) {
   		for (Profile prof : profs) {
   		   profileNamesSet.add(prof.Name);
   		}
   	} // for (Profile[]
   	return profileNamesSet;
   } // getAllProfiles
   
   /**  Save the record. */
   public PageReference save() {
   	cgs.Selected_Profiles__c = concatenateProfs(selectedProfiles, 2000);
   	cgs.Manager_Profiles__c = concatenateProfs(managerProfiles, 500);
   	
   	try {
   	   upsert cgs;
   	} catch (Exception e) {
   	   throw e;
   	}
      PageReference pr = new PageReference('/'+cgs.id);   
      return pr;
   } // save
   
} // class ChatterGroupSetupController