force-app/main/default/objects/Pricebook2/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The primary sales org this pricebook is used for</inlineHelpText>
    <label>Sales Org</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sales Org</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/Product_Mapping__c.object-meta.xml
<CustomObject>
    <description>Used to map products from other systems to the Salesforce Product2 object.</description>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>Map-{000000}</displayFormat>
        <label>Mapping Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Mapping__c/fields/Clear_Parent__c.field-meta.xml
<CustomField>
    <fullName>Clear_Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this product is set, should we clear the total from the parent record? (ex: Matching Core Payroll under PPS would clear the PPS line item).</description>
    <inlineHelpText>If this product is set, should we clear the total from the parent record? (ex: Matching Core Payroll under PPS would clear the PPS line item).</inlineHelpText>
    <label>Clear Parent?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/DoNotRequireProduct__c.field-meta.xml
<CustomField>
    <fullName>DoNotRequireProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If you don&apos;t require a product to be associated with this mapping</inlineHelpText>
    <label>Do Not Require Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/IsSetup__c.field-meta.xml
<CustomField>
    <fullName>IsSetup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this a setup fee field?</description>
    <inlineHelpText>Is this a setup fee field?</inlineHelpText>
    <label>IsSetup?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Mapping_Key__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Key__c</fullName>
    <description>The product key from the other system (ex OIC, Bus Plan) to use to map to the product object.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The product key from the other system (ex OIC, Bus Plan) to use to map to the product object.</inlineHelpText>
    <label>Mapping Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Parent_PricebookEntryId__c.field-meta.xml
<CustomField>
    <fullName>Parent_PricebookEntryId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent PricebookEntryId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If there is a parent for the product, list it here so it can be mapped correctly.</description>
    <inlineHelpText>If there is a parent for the product, list it here so it can be mapped correctly.</inlineHelpText>
    <label>Parent Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Mappings (Parent Product)</relationshipLabel>
    <relationshipName>Parent_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Parent_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product_Code__c</fullName>
    <description>The Product Code of the Parent object, if applicable.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Product Code of the Parent object, if applicable.</inlineHelpText>
    <label>Parent Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/PricebookEntryId__c.field-meta.xml
<CustomField>
    <fullName>PricebookEntryId__c</fullName>
    <description>The Id of the Pricebook Entry.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Id of the Pricebook Entry.</inlineHelpText>
    <label>PricebookEntryId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/PricebookId__c.field-meta.xml
<CustomField>
    <fullName>PricebookId__c</fullName>
    <description>The Id of the Pricebook.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Id of the Pricebook.</inlineHelpText>
    <label>PricebookId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Product table</description>
    <inlineHelpText>Lookup to the Product table</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>The matching Product Code in the Product table in SFDC.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The matching Product Code in the Product table in SFDC.</inlineHelpText>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Product_Parent_Child_Link__c.field-meta.xml
<CustomField>
    <fullName>Product_Parent_Child_Link__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Parent-Child Link</label>
    <referenceTo>Product_Parent_Child_Link__c</referenceTo>
    <relationshipLabel>Product Mappings</relationshipLabel>
    <relationshipName>Product_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>The sales org this is for.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The sales org this is for.</inlineHelpText>
    <label>Sales Org</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The source of the mapping data.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The source of the mapping data.</inlineHelpText>
    <label>Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Use_Net_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Use_Net_Revenue__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Put the revenue into the Net Revenue field.</description>
    <inlineHelpText>Put the revenue into the Net Revenue field.</inlineHelpText>
    <label>Use Net Revenue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Use_Revenue2__c.field-meta.xml
<CustomField>
    <fullName>Use_Revenue2__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Put the revenue into the Revenue2 field.</description>
    <inlineHelpText>Put the revenue into the Revenue2 field.</inlineHelpText>
    <label>Use Revenue2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/Use_Revenue3__c.field-meta.xml
<CustomField>
    <fullName>Use_Revenue3__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Put the revenue into the Revenue3 field.</description>
    <inlineHelpText>Put the revenue into the Revenue3 field.</inlineHelpText>
    <label>Use Revenue3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Mapping__c/fields/ZipSegmentName__c.field-meta.xml
<CustomField>
    <fullName>ZipSegmentName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>If this product mapping is associated with a specific zip segment, set the name here. Used in ZipCodeLookupController.getZipAssignment</inlineHelpText>
    <label>Zip Segment Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Parent_Child_Link__c/Product_Parent_Child_Link__c.object-meta.xml
<CustomObject>
    <description>An junction object to link two products together.</description>
    <label>Product Parent-Child Link</label>
    <nameField>
        <displayFormat>Link-{000000}</displayFormat>
        <label>Link Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Parent-Child Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Parent_Child_Link__c/fields/Child_Product__c.field-meta.xml
<CustomField>
    <fullName>Child_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The lookup to the Child product</description>
    <inlineHelpText>The lookup to the Child product</inlineHelpText>
    <label>Child Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Child Product Links</relationshipLabel>
    <relationshipName>Child_Product_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Parent_Child_Link__c/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The lookup to the Parent product</description>
    <inlineHelpText>The lookup to the Parent product</inlineHelpText>
    <label>Parent Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parent Product Links</relationshipLabel>
    <relationshipName>Parent_Product_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Parent_Child_Link__c/fields/Parent_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product_Code__c</fullName>
    <description>The Product Code of the Parent Product.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Product Code of the Parent Product.</inlineHelpText>
    <label>Parent Product Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/PilotUser__c.field-meta.xml
<CustomField>
    <fullName>PilotUser__c</fullName>
    <description>Only use this field if the value will be tied to a pricebook i.e. Steelbrick</description>
    <inlineHelpText>Only use this field if the value will be tied to a pricebook i.e. Steelbrick</inlineHelpText>
    <label>Pilot User</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Steelbrick</fullName>
            </value>
            <value>
                <fullName>CPQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org-Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>BenAdmin</fullName>
            </value>
            <value>
                <fullName>Benetrac</fullName>
            </value>
            <value>
                <fullName>BusDev</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Relations</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Center</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise Service Center</fullName>
            </value>
            <value>
                <fullName>ESR</fullName>
            </value>
            <value>
                <fullName>EW</fullName>
            </value>
            <value>
                <fullName>Field Operations Core</fullName>
            </value>
            <value>
                <fullName>HNBF</fullName>
            </value>
            <value>
                <fullName>HROI</fullName>
            </value>
            <value>
                <fullName>HR Online</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>HRS 401K-S125</fullName>
            </value>
            <value>
                <fullName>HRS Premier</fullName>
            </value>
            <value>
                <fullName>Icon</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Merchant Services</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MMS Hub</fullName>
            </value>
            <value>
                <fullName>MPSC</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductMapping.cls
/* 
 * Map the lookup fields on the object on change.
 *
 * History
 * -------
 * 09/22/2011 Dan Carmen          Created
   08/10/2012 Dan Carmen          Modified getMapping method
   10/03/2012 Dan Carmen          Added check in for Sales Org.
   07/30/2015 Dan Carmen          Change to handle pilot users
   04/05/2019 Dan Carmen          Add in the cache for the default products
   07/22/2020 Jake Hinds          Added Product Name to query

 */
public with sharing class ProductMapping {

   public static void processData(Product_Mapping__c[] pms) {
    
      Set<String> prodCodes = new Set<String>();
    Set<String> salesOrgSet = new Set<String>();
      
      // clear out lookup fields, get product codes
      for (Product_Mapping__c pm : pms) {
         pm.Product__c = null;
         pm.Parent_Product__c = null;
         pm.Product_Parent_Child_Link__c = null;
         pm.PricebookEntryId__c = null;
         pm.PricebookId__c = null;
         pm.Parent_PricebookEntryId__c = null;
         
         if (String.isNotBlank(pm.Sales_Org__c)) {
             if (String.IsNotBlank(pm.Product_Code__c)) {
                prodCodes.add(pm.Product_Code__c);
             }
             if (String.isNotBlank(pm.Parent_Product_Code__c)) {
                prodCodes.add(pm.Parent_Product_Code__c);
             }
             salesOrgSet.add(pm.Sales_Org__c);
         } // if (String.isNotBlank(pm.Sales_Org__c
      } // for (Product_Mapping__c
      
      if (prodCodes.isEmpty()) {
         // no records to process
         return;
      }
      
      String[] salesOrgs = new String[]{};
      salesOrgs.addAll(salesOrgSet);
      
      ProductQuery pq = new ProductQuery();
      Map<String,Pricebook2> pricebookMap = pq.getPricebooksBySalesOrgs(salesOrgs);
      // list of records where pricebook is found
      Product_Mapping__c[] foundPb = new Product_Mapping__c[]{}; 
      
      // check to see if matches found for all sales orgs
      for (Product_Mapping__c pm : pms) {
         if (String.isNotBlank(pm.Sales_Org__c)) {
            Pricebook2 pb = pricebookMap.get(pm.Sales_Org__c);
            if (pb != null) {
               foundPb.add(pm);
            } else if (!pm.DoNotRequireProduct__c) {
               pm.Sales_Org__c.addError('Pricebook was not found for the '+pm.Sales_Org__c+' Sales Org!');
            }
         } // if (pm.Sales_Org__c != null)
      } // for
      // if no matches found, no need to proceed.
      if (foundPb.isEmpty()) {
         return;
      }
      // only proceed with the ones where we found the pricebook
      pms = foundPb;
      
      // create a map by product code and sales org
      Map<String,PricebookEntry> productMap = new Map<String,PricebookEntry>();
      for (String salesOrg : pricebookMap.keySet()) {
        Pricebook2 pb = pricebookMap.get(salesOrg);
         for (PricebookEntry pe : pb.PricebookEntries) {
            // store the products by the sales org and product code
            String key=salesOrg+pe.Product2.ProductCode;
            System.debug('add to map key='+key+'.');
            // only add the product codes we are searching for
            if (prodCodes.contains(pe.Product2.ProductCode)) {
               productMap.put(key,pe);
            }
         } // for (PricebookEntry
      } // for (Pricebook2
      
      Map<String,Product_Mapping__c> hasParentChild = new Map<String,Product_Mapping__c>();
      Set<String> childProdCodes = new Set<String>();
      Set<String> parentProdCodes = new Set<String>();

      for (Product_Mapping__c pm : pms) {
         // get the product ids
         if (String.IsNotBlank(pm.Product_Code__c)) {
            String key = pm.Sales_Org__c+pm.Product_Code__c;
            System.debug('check in map key='+key+'.');
            if (productMap.containsKey(key)) {
               PricebookEntry pe = productMap.get(key);
               pm.PricebookEntryId__c = pe.Id;
               pm.Product__c = pe.Product2Id;
               pm.PricebookId__c = pe.Pricebook2Id;
            } else if (!pm.DoNotRequireProduct__c) {
               pm.Product_Code__c.addError('The Product Code '+pm.Product_Code__c+' could not be found for sales org '+pm.Sales_Org__c+'!');
            }
         }
         if (String.IsNotBlank(pm.Parent_Product_Code__c)) {
            String key = pm.Sales_Org__c+pm.Parent_Product_Code__c;
            if (productMap.containsKey(key)) {
               PricebookEntry pe = productMap.get(key);
               pm.Parent_PricebookEntryId__c = pe.Id;
               pm.Parent_Product__c = pe.Product2Id;
            } else if (!pm.DoNotRequireProduct__c) {
               pm.Parent_Product_Code__c.addError('The Parent Product Code '+pm.Parent_Product_Code__c+' could not be found for sales org '+pm.Sales_Org__c+'!');
            }
         } 

         // if has both parent and child products...
         if (pm.Product__c != null && pm.Parent_Product__c != null) {
            String mapKey = pm.Sales_Org__c + pm.Product__c + pm.Parent_Product__c;
            hasParentChild.put(mapKey,pm);
            childProdCodes.add(pm.Product__c);
            parentProdCodes.add(pm.Parent_Product__c);
         }
      } // for (Product_Mapping__c
      
      // if no parent child relations do not need to proceed.
      if (hasParentChild.isEmpty()) {
         return;
      }
      // get the parent-child relation objects
      for (Product_Parent_Child_Link__c ppcl : [Select Id, Sales_Org__c
                                                      ,Child_Product__c
                                                      ,Parent_Product__c
                                                  FROM Product_Parent_Child_Link__c
                                                 WHERE Child_Product__c in :childProdCodes
                                                   AND Parent_Product__c in :parentProdCodes
                                                   AND Sales_Org__c IN :salesOrgs]) {
         String mapKey = ppcl.Sales_Org__c + ppcl.Child_Product__c + ppcl.Parent_Product__c;
         Product_Mapping__c pm = hasParentChild.get(mapKey);
         if (pm != null) {
            pm.Product_Parent_Child_Link__c = ppcl.Id;
         }
      } // for (Product_Parent_Child_Link__c ppcl
      // if anything happens with the product mappings, remove from cache so they can be reselected.
      CacheManager.removeOrg(CACHE_KEY);
   } // processData
   
   /** Get a Product_Mapping__c record.
    */
   public static Product_Mapping__c getMapping(String mappingKey, String mappingType, String salesOrg) {
      Product_Mapping__c mapping = null;
      String[] mappingKeys = new String[]{mappingKey};
      String[] salesOrgs = new String[]{};
      if (salesOrg != null) {
         salesOrgs.add(salesOrg);
      }
      Product_Mapping__c[] mappings = getMappings(mappingKeys,mappingType,salesOrgs);
      // should only be one record returned - assume this
      if (!mappings.isEmpty()) {
         mapping = mappings.get(0);
      }
      return mapping;
   } // getMapping
   
   /** Get Product_Mapping__c records based on the passed in parameters.
    */
   public static Product_Mapping__c[] getMappings(String[] mappingKeys, String mappingType, String[] salesOrgs) {
      Product_Mapping__c[] mappings = [Select Id
                                             ,Clear_Parent__c
                                             ,IsSetup__c
                                             ,Mapping_Key__c
                                             ,Product__c
                                            ,Product__r.Name
                                             ,Parent_Product__c
                                             ,Product_Parent_Child_Link__c
                                             ,PricebookEntryId__c
                                             ,PricebookId__c
                                             ,Parent_PricebookEntryId__c
                                             ,Sales_Org__c
                                             ,Type__c
                                             ,Use_Net_Revenue__c
                                             ,Use_Revenue2__c
                                             ,Use_Revenue3__c
                                             ,ZipSegmentName__c
                                         from Product_Mapping__c
                                        where Mapping_Key__c in :mappingKeys
                                          and Type__c = :mappingType
                                          and Sales_Org__c in :salesOrgs];
      return mappings;
   } // getMappings
   
   // used for testing purposes.
   public static Boolean CHECK_USER=!Test.isRunningTest();

   public static String getSalesOrg(String recordTypeName, User usr) {
      return getSalesOrg(recordTypeName,usr,CHECK_USER);
   }
   
   public static String getSalesOrg(String recordTypeName, User usr, Boolean checkForPilot) {
      String salesOrg = 'none';
      try {
         if (String.isNotBlank(recordTypeName)) {
            salesOrg = RecordTypeHelper.getSalesOrgForRecordTypeName(recordTypeName);
         } else if (usr != null) {
            salesOrg = usr.Sales_Org__c;
         }
   
         // not sure if this is causing problems when running tests in production.
         if (checkForPilot && usr != null && usr.PilotUser__c != null) {
            salesOrg += '-'+usr.PilotUser__c;
         }
      } catch (Exception e) {
         
      }
      System.debug('getSalesOrg salesOrg='+salesOrg);
      return salesOrg;
   } // getSalesOrg
   
   public static String CACHE_KEY='DefaultProductMappings';
   
   public class MappingWrapper {
      public Map<String,Product_Mapping__c> byPricebookIdMap = new Map<String,Product_Mapping__c>();
      public Map<String,Product_Mapping__c> bySalesOrgMap = new Map<String,Product_Mapping__c>();
   } // class MappingWrapper
   
   // use the cache so we don't have to always retrieve this
   public static MappingWrapper getDefaultMappings() {
      MappingWrapper mapWrap = (MappingWrapper)CacheManager.getOrg(CACHE_KEY);
      if (mapWrap == null) {
         mapWrap = new MappingWrapper();
         Product_Mapping__c[] mappings = [Select Id
                                             ,Clear_Parent__c
                                             ,IsSetup__c
                                             ,Mapping_Key__c
                                             ,Product__c
                                             ,Product__r.Name
                                             ,Parent_Product__c
                                             ,Product_Parent_Child_Link__c
                                             ,PricebookEntryId__c
                                             ,PricebookId__c
                                             ,Parent_PricebookEntryId__c
                                             ,Sales_Org__c
                                             ,Type__c
                                             ,Use_Net_Revenue__c
                                             ,Use_Revenue2__c
                                             ,Use_Revenue3__c
                                             ,ZipSegmentName__c
                                         from Product_Mapping__c
                                        where Type__c = :OpptyProducts.MAP_TYPE];
         for (Product_Mapping__c mapping : mappings) {
            if (mapping.PricebookId__c != null) {
               mapWrap.byPricebookIdMap.put(mapping.PricebookId__c,mapping);
            }
            if (mapping.Sales_Org__c != null) {
               mapWrap.bySalesOrgMap.put(mapping.Sales_Org__c,mapping);
            }
         } // for (Product_Mapping__c mapping
         CacheManager.putOrg(CACHE_KEY, mapWrap);
      } // if (mappings == null
      return mapWrap;
   } // getDefaultMappings
   
} // class ProductMapping