force-app/main/default/objects/Customer_Intent_Signal__c/Customer_Intent_Signal__c.object-meta.xml
<CustomObject>
    <label>Customer Intent Signal</label>
    <nameField>
        <displayFormat>CIS-{0000000000}</displayFormat>
        <label>Customer Intent Signal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Intent Signals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Intent_Signal__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the Contact</description>
    <inlineHelpText>Links to the Contact</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Intent Signals</relationshipLabel>
    <relationshipName>Customer_Intent_Signals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Intent_Signal__c/fields/Intent_Source__c.field-meta.xml
<CustomField>
    <fullName>Intent_Source__c</fullName>
    <description>Indicates where intent/trigger came from</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Indicates where intent/trigger came from</inlineHelpText>
    <label>Intent Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Intent_Signal__c/fields/Intent_Type__c.field-meta.xml
<CustomField>
    <fullName>Intent_Type__c</fullName>
    <description>Indicates the type of intent/trigger</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Indicates the type of intent/trigger</inlineHelpText>
    <label>Intent Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Intent_Signal__c/fields/Marketing_Action__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Action__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Marketing Action</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Insights__c/Marketing_Insights__c.object-meta.xml
<CustomObject>
    <label>Marketing Insights</label>
    <nameField>
        <displayFormat>In-{0000000000}</displayFormat>
        <label>Marketing Insights Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Insights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Insights__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Marketing Insights</relationshipLabel>
    <relationshipName>Marketing_Insights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Insights__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Insights__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Email Bounce</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Solution</fullName>
            </value>
            <value>
                <fullName>Unmarketable</fullName>
            </value>
            <value>
                <fullName>Unsubscribed</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Insights__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Buyer Behavior</fullName>
            </value>
            <value>
                <fullName>Exposure</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InsightsDATest.cls
/* 

  History
  -------
  03/22/2022 Dan Carmen          Cleaned up code
  12/14/2023 Shilpa G			 APR0155814: Added method getIntentByContactId

 */
@IsTest
private class InsightsDATest {
    @IsTest
    static void getInsightsByContactId() {
        test.startTest();

        // create test account
        Account testAccount = new Account(Name = 'testAccountA', AccountNumber = '8-00081234', NumberOfEmployees = 60);
        insert testAccount;

        // create test contact
        Contact expectedContact = new Contact(FirstName = 'Test Contact', LastName = 'Contact 1', AccountId = testAccount.Id, DoNotCall = false, Email = 'c1a1@whoknows.com', HasOptedOutOfEmail = false);
        insert expectedContact;

        List<Marketing_Insights__c> testInsights = new List<Marketing_Insights__c>();

        // create some open test insights for that contact
        List<Marketing_Insights__c> expectedInsights = new List<Marketing_Insights__c>();

        Marketing_Insights__c testInsight1 = new Marketing_Insights__c(Description__c = 'test 1', Name__c = 'Action', Type__c = 'Buyer Behavior', Contact__c = expectedContact.Id);
        expectedInsights.add(testInsight1);
        
        testInsights.addAll(expectedInsights);


        insert testInsights;

        List<Marketing_Insights__c> returnInsights = InsightsDA.getInsightsById(expectedContact.Id);

        test.stopTest();

        System.assert(returnInsights.size() == expectedInsights.size(), 'Should have returned expected records, it did not');
    }
    
    @IsTest
    static void getIntentByContactId() {
        test.startTest();

        // create test account
        Account testAccount = new Account(Name = 'testAccountA', AccountNumber = '8-00081234', NumberOfEmployees = 60);
        insert testAccount;

        // create test contact
        Contact expectedContact = new Contact(FirstName = 'Test Contact', LastName = 'Contact 1', AccountId = testAccount.Id, DoNotCall = false, Email = 'c1a1@whoknows.com', HasOptedOutOfEmail = false);
        insert expectedContact;

        List<Customer_Intent_Signal__c> testIntent = new List<Customer_Intent_Signal__c>();

        // create some open test insights for that contact
        List<Customer_Intent_Signal__c> expectedIntent = new List<Customer_Intent_Signal__c>();

        Customer_Intent_Signal__c testIntent1 = new Customer_Intent_Signal__c(Intent_Source__c = 'test 1', Marketing_Action__c = 'Action', Intent_Type__c = 'Buyer Behavior', Contact__c = expectedContact.Id);
        expectedIntent.add(testIntent1);
        
        testIntent.addAll(expectedIntent);


        insert testIntent;

        List<Customer_Intent_Signal__c> returnIntent = InsightsDA.getIntentById(expectedContact.Id);

        test.stopTest();

        System.assert(returnIntent.size() == expectedIntent.size(), 'Should have returned expected records, it did not');
    }
}