force-app/main/default/objects/ErrorDetail__c/ErrorDetail__c.object-meta.xml
<CustomObject>
    <description>The field level information on a record errors, including all of the fields that we were trying to update/insert</description>
    <label>Error Detail</label>
    <nameField>
        <displayFormat>Error-{00000000}</displayFormat>
        <label>Error Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorDetail__c/fields/ErrorLog__c.field-meta.xml
<CustomField>
    <fullName>ErrorLog__c</fullName>
    <label>Error Log</label>
    <referenceTo>ErrorLog__c</referenceTo>
    <relationshipLabel>Error Details</relationshipLabel>
    <relationshipName>Error_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ErrorDetail__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The initial error message that occurred for this record</inlineHelpText>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <description>When errors occur during a process, a place we can capture and log them</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Log-{00000000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the class the error originated from</inlineHelpText>
    <label>Class Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/CodeKey__c.field-meta.xml
<CustomField>
    <fullName>CodeKey__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Something that identifies what the code is trying to do</inlineHelpText>
    <label>Code Key</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/DMLQueriesLog1End__c.field-meta.xml
<CustomField>
    <fullName>DMLQueriesLog1End__c</fullName>
    <inlineHelpText>The number of DML queries at the end of the Log1 process</inlineHelpText>
    <label>DML Queries Log1 End</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/DMLQueriesLog1Start__c.field-meta.xml
<CustomField>
    <fullName>DMLQueriesLog1Start__c</fullName>
    <inlineHelpText>The number of DML queries at the start of the Log1 process</inlineHelpText>
    <label>DML Queries Log1 Start</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/DMLQueriesLog2End__c.field-meta.xml
<CustomField>
    <fullName>DMLQueriesLog2End__c</fullName>
    <inlineHelpText>The number of queries at the end of the Log2 Process</inlineHelpText>
    <label>DML Queries Log2 End</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/DMLQueriesLog2Start__c.field-meta.xml
<CustomField>
    <fullName>DMLQueriesLog2Start__c</fullName>
    <inlineHelpText>The number of queries at the start of Log2</inlineHelpText>
    <label>DML Queries Log2 Start</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/DMLQueriesStart__c.field-meta.xml
<CustomField>
    <fullName>DMLQueriesStart__c</fullName>
    <inlineHelpText>The number of DML queries at the start of the process</inlineHelpText>
    <label>DML Queries Start</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Log1End__c.field-meta.xml
<CustomField>
    <fullName>Log1End__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>End time for a secondary process within the log</inlineHelpText>
    <label>Log1 End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Log1Start__c.field-meta.xml
<CustomField>
    <fullName>Log1Start__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Start time for a secondary process within the log</inlineHelpText>
    <label>Log1 Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Log1Type__c.field-meta.xml
<CustomField>
    <fullName>Log1Type__c</fullName>
    <inlineHelpText>The type of logging in the Log1 field</inlineHelpText>
    <label>Log1 Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LeadConvert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Log2End__c.field-meta.xml
<CustomField>
    <fullName>Log2End__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>End time for a secondary process within the log</inlineHelpText>
    <label>Log2 End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Log2Start__c.field-meta.xml
<CustomField>
    <fullName>Log2Start__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Start time for a secondary process within the log</inlineHelpText>
    <label>Log2 Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Log2Type__c.field-meta.xml
<CustomField>
    <fullName>Log2Type__c</fullName>
    <inlineHelpText>The type of logging in the Log2 field</inlineHelpText>
    <label>Log2 Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LeadConvert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the method this error originated from</inlineHelpText>
    <label>Method Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLogCS__c/ErrorLogCS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Define properties of the Error Log object - what to do for specific errors that are logged.</description>
    <label>Error Log</label>
</CustomObject>

force-app/main/default/objects/ErrorLogCS__c/fields/EmailOnError__c.field-meta.xml
<CustomField>
    <fullName>EmailOnError__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>If an error occurs, a comma separated list of names to email that the error occurred.</inlineHelpText>
    <label>Email On Error</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLogCS__c/fields/LogData__c.field-meta.xml
<CustomField>
    <fullName>LogData__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Class has to be coded to look for this.</description>
    <inlineHelpText>Log debug data from this class in an Error Log.</inlineHelpText>
    <label>LogData</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ErrorLogCS__c/fields/NbrErrorRetry__c.field-meta.xml
<CustomField>
    <fullName>NbrErrorRetry__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>If this ends in an error that can be retried (ex Row Lock), how many times to retry. Any number greater than 0 will mean that yes we retry errors for this type. Enter 0 or leave null for no retries.</inlineHelpText>
    <label>Nbr Error Retry</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ErrorLogTest.cls
/* 
 * Test methods for the ErrorLog class
 *
 * History

 * ------- * 10/06/2014 Dan Carmen   Created - rewrite of the SObjectHelper class
   03/20/2015 Dan Carmen   Added additional functionality
   02/26/2016 Dan Carmen   Added record count on the record.
   03/14/2017 Dan Carmen   Save failed records for possible reprocessing.
   10/11/2018 Dan Carmen   Add addToDescription method
   11/19/2018 Dan Carmen   Change the order of logging - the actual error message is getting dropped off in some cases.
   12/08/2020 Dan Carmen   Added start and end times for logs
   12/14/2023 Dan Carmen   Add more logging options

 */
@isTest
public class ErrorLogTest {
   
   @testSetup
   public static void setupData() {
      ErrorLogCS__c log1 = new ErrorLogCS__c(Name='Test1', NbrErrorRetry__c=1, EmailOnError__c='dcarmen@paychex.com',LogData__c=true);
      ErrorLogCS__c log1b = new ErrorLogCS__c(Name='Test1-TestA', NbrErrorRetry__c=0, EmailOnError__c='dcarmen@paychex.com');
      ErrorLogCS__c log1c = new ErrorLogCS__c(Name='Test1-TestA-TestI', NbrErrorRetry__c=0, EmailOnError__c='dcarmen@paychex.com');
      ErrorLogCS__c log2 = new ErrorLogCS__c(Name='Test2', NbrErrorRetry__c=0, EmailOnError__c='dcarmen@paychex.com',LogData__c=false);
      ErrorLogCS__c log3 = new ErrorLogCS__c(Name='Test3', NbrErrorRetry__c=3, EmailOnError__c='dcarmen@paychex.com');
      ErrorLogCS__c[] logs = new ErrorLogCS__c[]{log1,log1b,log1c,log2,log3};
      insert logs;
   } // setupData

   static testMethod void testLogCreation() {
      // generate an exception
      Exception testException = null;
      // with no close date or status this should fail
      Opportunity opp = new Opportunity(Name='Test Opp');
      try {
         insert opp;
      } catch (Exception e) {
         testException = e;
      }
      
      Account acct = new Account(Name='Test Account');
      insert acct;
      
      ErrorLog.LOG_DETAILS = true;
      
      System.assertEquals(true,(testException != null));
      
      ErrorLog.logError('ErrorLogTest', 'testLogCreation', 'test opp insert', 'testid', 'this is a test error');
      ErrorLog.logError('ErrorLogTest', 'testLogCreation', 'test opp insert', 'testid', testException);
      ErrorLog.logError('ErrorLogTest', 'testLogCreation', 'test opp insert', 'testid', testException,opp);
      
      ErrorLog.logError('ErrorLogTest', 'testLogCreation', 'test4', acct.Id, 'Description 4', acct);
      ErrorLog.logError('ErrorLogTest', 'testLogCreation', 'test5', acct.Id, 'Description 4', acct, false);
      ErrorLog.logError('ErrorLogTest', 'testLogCreation', 'test6', acct.Id, 'Description 4', 1, 1, 0, acct, false);
      ErrorLog.logError('ErrorLogTest', 'testLogCreation', 'test7', (String)acct.Id, 'Description 4', 1, 1, 0, '1', acct, false);

      ErrorLog.checkSave();
      
      System.assertEquals(7,[select count() from ErrorLog__c where ClassName__c='ErrorLogTest' and MethodName__c='testLogCreation']);
      
      ErrorLog.logError('ErrorLogTest', 'testLogCreation', 'test opp insert', 'testid', testException,opp, true);
      System.assertEquals(8,[select count() from ErrorLog__c where ClassName__c='ErrorLogTest' and MethodName__c='testLogCreation']);
      
      ErrorDetail__c[] errorDetails = new ErrorDetail__c[]{};
      errorDetails.add(new ErrorDetail__c(ErrorMessage__c='This is a test error'));
      errorDetails.add(new ErrorDetail__c(ErrorMessage__c='This is another test error'));
      ErrorLog__c errLog = ErrorLog.logError('TestWithDetails', 'AddSomeDetails', 'TestKey', null, 'This Is A description', 1, 1, 1, '1', opp, true, errorDetails);
      System.assertEquals(true, errLog.Id != null);
      System.assertEquals(2,[select count() from ErrorDetail__c where ErrorLog__c=:errLog.Id]);
      
   } // testLogCreation
   
   static testMethod void testGetCustomSetting() {
      System.assertEquals(null,ErrorLog.getCustomSetting('BadTest', 'BadTest', 'BadTest'));
      System.assertNotEquals(null,ErrorLog.getCustomSetting('Test1', 'TestA', 'TestI'));
      System.assertNotEquals(null,ErrorLog.getCustomSetting('Test1', 'TestB', 'TestI'));
      System.assertEquals(null,ErrorLog.getCustomSetting('BadTest', 'TestA', 'TestI'));
      System.assertNotEquals(null,ErrorLog.getCustomSetting('Test1', null, null));
   } // testGetCustomSetting
   
    static testMethod void testLog() {
       ErrorLog__c errLog1 = ErrorLog.getLog('Test1');
       ErrorLog__c errLog2 = ErrorLog.getLog('Test2');
       ErrorLog.saveLog(errLog1);
       System.assertNotEquals(null,errLog1.Id);
       ErrorLog.saveLog(errLog2);
       System.assertEquals(null,errLog2.Id);
    } // testLog
    
    static testMethod void testProcessLog() {
       ErrorLog__c errLog = ErrorLog.getProcessLog('TestProcessLog');
       Assert.areEqual('TestProcessLog', errLog.ClassName__c);
       Assert.areEqual('LOG_DATA', errLog.MethodName__c);
       Assert.areEqual('ProcessLog', errLog.CodeKey__c);
       Assert.isNotNull(errLog.DMLQueriesStart__c);
       ErrorLog.startLog1(errLog,'Process1');
       Assert.areEqual('Process1', errLog.Log1Type__c);
       Assert.isNotNull(errLog.Log1Start__c);
       Assert.isNull(errLog.Log1End__c);
       Assert.isNotNull(errLog.DMLQueriesLog1Start__c);
       Assert.isNull(errLog.DMLQueriesLog1End__c);
       ErrorLog.endLog1(errLog);
       Assert.isNotNull(errLog.Log1End__c);
       Assert.isNotNull(errLog.DMLQueriesLog1End__c);
       
       ErrorLog.startLog2(errLog,'Process2');
       Assert.areEqual('Process2', errLog.Log2Type__c);
       Assert.isNotNull(errLog.Log2Start__c);
       Assert.isNull(errLog.Log2End__c);
       Assert.isNotNull(errLog.DMLQueriesLog2Start__c);
       Assert.isNull(errLog.DMLQueriesLog2End__c);
       ErrorLog.endLog2(errLog);
       Assert.isNotNull(errLog.Log2End__c);
       Assert.isNotNull(errLog.DMLQueriesLog2End__c);
       ErrorLog.saveLog(errLog);

    } // testProcessLog
} // class ErrorLogTest