force-app/main/default/objects/ECommerce__c/ECommerce__c.object-meta.xml
<CustomObject>
    <description>Used as a staging table for information being sent in from the ecommerce site.</description>
    <label>ECommerce</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>ECommerce Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ecommerces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ECommerce__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Account this is associated with.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ecommerces</relationshipLabel>
    <relationshipName>Ecommerces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ECommerce__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <inlineHelpText>What action was taken?</inlineHelpText>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OCC Form 2</fullName>
            </value>
            <value>
                <fullName>OCC Form 3</fullName>
            </value>
            <value>
                <fullName>OCC Form 4</fullName>
            </value>
            <value>
                <fullName>Flex Login Completed</fullName>
            </value>
            <value>
                <fullName>Onboarding Completed</fullName>
            </value>
            <value>
                <fullName>Form 2 - Abandoned</fullName>
            </value>
            <value>
                <fullName>Form 3 - Abandoned</fullName>
            </value>
            <value>
                <fullName>Form 4 - Abandoned</fullName>
            </value>
            <value>
                <fullName>OCC Form 1</fullName>
            </value>
            <value>
                <fullName>Form 1 - Abandoned</fullName>
            </value>
            <value>
                <fullName>Client Legal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ECommerce__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the company</inlineHelpText>
    <label>Company</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECommerce__c/fields/ContactEmail__c.field-meta.xml
<CustomField>
    <fullName>ContactEmail__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Email address of the contact</inlineHelpText>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ECommerce__c/fields/ContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>ContactFirstName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The first name of the contact</inlineHelpText>
    <label>Contact First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECommerce__c/fields/ContactLastName__c.field-meta.xml
<CustomField>
    <fullName>ContactLastName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Last name of the contact</inlineHelpText>
    <label>Contact Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECommerce__c/fields/ContactPhone__c.field-meta.xml
<CustomField>
    <fullName>ContactPhone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ECommerce__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Lead this record is associated with</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Ecommerces</relationshipLabel>
    <relationshipName>Ecommerces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ECommerce__c/fields/MktgId__c.field-meta.xml
<CustomField>
    <fullName>MktgId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Id for Marketing (Marketo).</inlineHelpText>
    <label>Mktg Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECommerce__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Opportunity associated with this ecom record</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Ecommerces</relationshipLabel>
    <relationshipName>Ecommerces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ECommerce__c/fields/PayrollFrequency__c.field-meta.xml
<CustomField>
    <fullName>PayrollFrequency__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payroll Frequency</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECommerce__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OCC</fullName>
            </value>
            <value>
                <fullName>Flex</fullName>
            </value>
            <value>
                <fullName>CSO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ECommerce__c/fields/SubmittedDateTime__c.field-meta.xml
<CustomField>
    <fullName>SubmittedDateTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Submitted Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Employees_Paid_Per_Payroll__c.field-meta.xml
<CustomField>
    <fullName>Employees_Paid_Per_Payroll__c</fullName>
    <label>Employees Paid Per Payroll</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>52</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <formula>ReferralLookup__r.PartnerReferral__r.Source__c</formula>
    <label>Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EcomSubmit.cls
/* 
   Rest service to process the ecom forms

Ecommerce__c ecom = new Ecommerce__c(Action__c='OCC Form 1', OracleCommerceCloudId__c='4793022b-3fcd-4fd6-bec8-9251ebb56194'
                                    ,ContactFirstName__c='Billy', ContactLastName__c='Idol'
                                    ,ContactEmail__c='billy.idol@testing.com', ContactPhone__c='(555)555-1234', Company__c='Rebel Yell Inc'
                                    ,NumberOfEmployees__c=3, PayrollFrequency__c='monthly'
                                    ,Source__c='OCC', SubmittedDateTime__c=Datetime.now());
String output = json.serialize(ecom).replace('number_Z','number');
System.debug('output='+output);

{"attributes":{"type":"ECommerce__c"},"Action__c":"OCC Form 1","OracleCommerceCloudId__c":"4793022b-3fcd-4fd6-bec8-9251ebb56194","ContactFirstName__c":"Billy","ContactLastName__c":"Idol","ContactEmail__c":"billy.idol@testing.com","ContactPhone__c":"(555)555-1234","Company__c":"Rebel Yell Inc","NumberOfEmployees__c":3,"PayrollFrequency__c":"monthly","Source__c":"OCC","SubmittedDateTime__c":"2024-04-29T22:41:37.221+0000"}

  History
  -------
  04/29/2024 Dan Carmen        Created


*/
@RestResource(urlMapping='/EcomSubmit/*')
global without sharing class EcomSubmit {
    
   global class EcomResponse {
      global Boolean success=false;
      global Id opportunityId;
      global Id leadId;
      global Id accountId;
      global Opportunity opp;
      global String errMsg;
   } // class EcomResponse
   @HttpPost
    
   global static EcomResponse doPost() {
   	  //System.debug('doPost ecom='+ecom);
      RestRequest req = RestContext.request;
      RestResponse res = RestContext.response;
      EcomResponse eResp = new EcomResponse();
      String reqBody = (req.requestBody != null ? req.requestBody.toString() : null);
      System.debug('reqBody='+reqBody);
      if (reqBody == null) {
         return logError(eResp,false,'Record Data Not Found!');
      }
      Ecommerce__c ecom = null;
      try {
         ecom = (Ecommerce__c)JSON.deserialize(reqBody,Ecommerce__c.class);
      } catch (Exception e) {
         return logError(eResp,false,'Error with record data: '+(e.getMessage()+'; '+e.getStackTraceString()));
      }
      TriggerMethods.SKIP_TRIGGERS=true;
      if (String.isNotBlank(ecom.OracleCommerceCloudId__c) && String.isBlank(ecom.MktgId__c) ){
         ecom.MktgId__c = ecom.OracleCommerceCloudId__c;
      }
      insert ecom;
      try {
         EcomMethods.processEcoms(new Id[]{ecom.Id});
         eResp.success=true;
      } catch (Exception e) {
         return logError(eResp,false,'Error processing data: '+(e.getMessage()+'; '+e.getStackTraceString()));
      }
      Ecommerce__c[] checkEcoms = EcomMethods.getEcoms(new Id[]{ecom.Id},null);
      Ecommerce__c checkEcom = (!checkEcoms.isEmpty() ? checkEcoms[0] : null);
      System.debug('checkEcom='+checkEcom);
      eResp.success=(checkEcom != null);
      eResp.opportunityId = (checkEcom != null ? checkEcom.Opportunity__c : null);
      eResp.leadId = (checkEcom != null ? checkEcom.Lead__c : null);
      eResp.accountId = (checkEcom != null ? checkEcom.Account__c : null);
      eResp.opp = (eResp.opportunityId != null ? [Select Id, Name, CloseDate, Frequency__c, StageName, Employees_Paid_Per_Payroll__c
                                                    From Opportunity
                                                   Where Id = :eResp.opportunityId]
                                                : null);
      return eResp;
   } // doPost
    
   public static EcomResponse logError(EcomResponse eResp, Boolean isSuccess, String errMsg) {
      eResp.success=isSuccess;
      eResp.errMsg = errMsg;
      return eResp;
   } // logError

} // class EcomSubmit