force-app/main/default/objects/Org_Unit__c/Org_Unit__c.object-meta.xml
<CustomObject>
    <label>Org Unit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Org Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Org_Unit__c/fields/Org_Unit_Name__c.field-meta.xml
<CustomField>
    <fullName>Org_Unit_Name__c</fullName>
    <description>The name of this org unit</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of this org unit</inlineHelpText>
    <label>Org Unit Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Org_Unit__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Sales Org for this Org Unit</inlineHelpText>
    <label>Sales Org</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Org_Unit_User_Link__c/Org_Unit_User_Link__c.object-meta.xml
<CustomObject>
    <description>Link between the Org Unit and User objects.</description>
    <label>Org Unit User Link</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Unit User Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Org_Unit_User_Link__c/fields/Org_Unit__c.field-meta.xml
<CustomField>
    <fullName>Org_Unit__c</fullName>
    <label>Org Unit</label>
    <referenceTo>Org_Unit__c</referenceTo>
    <relationshipLabel>Org Unit User Links</relationshipLabel>
    <relationshipName>Org_Unit_User_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <displayFormat>State-{00000}</displayFormat>
        <label>State Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org-Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>BenAdmin</fullName>
            </value>
            <value>
                <fullName>Benetrac</fullName>
            </value>
            <value>
                <fullName>BusDev</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Relations</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Center</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise Service Center</fullName>
            </value>
            <value>
                <fullName>ESR</fullName>
            </value>
            <value>
                <fullName>EW</fullName>
            </value>
            <value>
                <fullName>Field Operations Core</fullName>
            </value>
            <value>
                <fullName>HNBF</fullName>
            </value>
            <value>
                <fullName>HROI</fullName>
            </value>
            <value>
                <fullName>HR Online</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>HRS 401K-S125</fullName>
            </value>
            <value>
                <fullName>HRS Premier</fullName>
            </value>
            <value>
                <fullName>Icon</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Merchant Services</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MMS Hub</fullName>
            </value>
            <value>
                <fullName>MPSC</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/Zip_Assignment__c.object-meta.xml
<CustomObject>
    <description>The Zip code assignments for the sales reps.</description>
    <label>Zip Assignment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Assignment__c/fields/Emps_Max__c.field-meta.xml
<CustomField>
    <fullName>Emps_Max__c</fullName>
    <label>Emps Max*</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/fields/Emps_Min__c.field-meta.xml
<CustomField>
    <fullName>Emps_Min__c</fullName>
    <label>Emps Min</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/fields/Paychex_Id__c.field-meta.xml
<CustomField>
    <fullName>Paychex_Id__c</fullName>
    <description>Unique identifier from Paychex</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier from Paychex</inlineHelpText>
    <label>Paychex Id*</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/fields/Zip_Code_Information__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip Code Information</label>
    <referenceTo>Zip_Code_Information__c</referenceTo>
    <relationshipLabel>Zip Assignments</relationshipLabel>
    <relationshipName>Zip_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/fields/Zip_Segment__c.field-meta.xml
<CustomField>
    <fullName>Zip_Segment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip Segment</label>
    <referenceTo>Zip_Segment__c</referenceTo>
    <relationshipLabel>Zip Assignments</relationshipLabel>
    <relationshipName>Zip_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zip_Code_Information__c/Zip_Code_Information__c.object-meta.xml
<CustomObject>
    <description>City/State information on Zip codes as provided by Zip-Codes.com</description>
    <label>Zip Code Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code_Information__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The name of the city.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the city.</inlineHelpText>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zip_Code_Information__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>2 letter state name abbreviation.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>2 letter state name abbreviation.</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zip_Code_Information__c/fields/Zip_Code_Key__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Key__c</fullName>
    <description>The value used as the key for this zip code object - standard name field cannot be used as an external id.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>The value used as the key for this zip code object - standard name field cannot be used as an external id.</inlineHelpText>
    <label>Zip Code Key</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Zip_Segment__c/Zip_Segment__c.object-meta.xml
<CustomObject>
    <description>The Zip Code segmentation information.</description>
    <label>Zip Segment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Segment__c/fields/Emps_Max__c.field-meta.xml
<CustomField>
    <fullName>Emps_Max__c</fullName>
    <description>The maximum number of employees for this segment</description>
    <inlineHelpText>The maximum number of employees for this segment</inlineHelpText>
    <label>Emps Max</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zip_Segment__c/fields/Emps_Min__c.field-meta.xml
<CustomField>
    <fullName>Emps_Min__c</fullName>
    <description>The low number of employees for this segment.</description>
    <inlineHelpText>The low number of employees for this segment.</inlineHelpText>
    <label>Emps Min</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zip_Segment__c/fields/Paychex_Id__c.field-meta.xml
<CustomField>
    <fullName>Paychex_Id__c</fullName>
    <description>Unique identifier from Paychex for this record.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier from Paychex for this record.</inlineHelpText>
    <label>Paychex Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Zip_Segment__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sales Org</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipTerritory__c/ZipTerritory__c.object-meta.xml
<CustomObject>
    <description>The Zip Code Territories by District</description>
    <label>Zip Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Territories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipTerritory__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>District__r.Sales_Org__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipTerritory__c/fields/Zip_Segment__c.field-meta.xml
<CustomField>
    <fullName>Zip_Segment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The segment for this territory</inlineHelpText>
    <label>Zip Segment</label>
    <referenceTo>Zip_Segment__c</referenceTo>
    <relationshipLabel>Zip Territories</relationshipLabel>
    <relationshipName>Zip_Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ZipCodeLookupControllerTest.cls
/* 
 * Test methods for the ZipCodeLookupController
 *
 * History
 * -------
 * 05/24/2012 Dan Carmen        Created.
   06/29/2012 Dan Carmen        Change so DSM/DSA only displayed if User is a sales rep.
   07/11/2012 Dan Carmen        Added more logic to be able to manually load DSMs/DSAs
   07/25/2012 Dan Carmen        Added in check for sales org when selected DSM/DSA.
   07/07/2020 Dan Carmen        Slight change to the getZipAssignment method for SOAR.

*/
@isTest
private class ZipCodeLookupControllerTest {

   static testMethod void testNoZip() {
      // set the page reference
      Test.setCurrentPage(Page.ZipCodeLookup);
      
      // create segments
      Zip_Segment__c[] segments = createSegments();
      ZipCodeLookupController zclc = new ZipCodeLookupController();
      // there is now segmentation data - no error should occur here
      System.assertEquals(false,ApexPages.hasMessages() );

      // perform a query with no data
      zclc.zipCodeQuery = null;
      System.assertEquals(null,zclc.queryZipCodes());
      System.assertEquals(true,ApexPages.hasMessages() );
      // get the message
      ApexPages.Message msg = ApexPages.getMessages().get(0);
      System.assertEquals('A valid 5 character zip code must be entered!',msg.getDetail());
      System.assertEquals(ApexPages.severity.ERROR,msg.getSeverity());
   } // testNoZip
   
   static testMethod void testBadZip() {
      // set the page reference
      Test.setCurrentPage(Page.ZipCodeLookup);
      
      // create segments
      Zip_Segment__c[] segments = createSegments();
      ZipCodeLookupController zclc = new ZipCodeLookupController();
      // there is now segmentation data - no error should occur here
      System.assertEquals(false,ApexPages.hasMessages() );

      // perform a query with a 6 character zip code
      zclc.zipCodeQuery = '123456';
      System.assertEquals(null,zclc.queryZipCodes());
      System.assertEquals(true,ApexPages.hasMessages() );
      // get the message
      ApexPages.Message msg = ApexPages.getMessages().get(0);
      System.assertEquals('A valid 5 character zip code must be entered!',msg.getDetail());
      System.assertEquals(ApexPages.severity.ERROR,msg.getSeverity());
   } // testBadZip
   
   /** Create some default segments. */
   private static Zip_Segment__c[] createSegments() {
      Zip_Segment__c[] segments = new Zip_Segment__c[]{};
      segments.add(new Zip_Segment__c(Name='Test Core',Sales_Org__c=UserHelper.SO_CORE,Emps_Min__c=0,Emps_Max__c=999999,Paychex_Id__c='TestCore'));
      segments.add(new Zip_Segment__c(Name='Test MMS',Sales_Org__c=UserHelper.SO_MMS,Emps_Min__c=0,Emps_Max__c=999999,Paychex_Id__c='TestMms'));
      segments.add(new Zip_Segment__c(Name='Test HNB1',Sales_Org__c=UserHelper.SO_HNB,Emps_Min__c=0,Emps_Max__c=49,Paychex_Id__c='TestHnb1'));
      segments.add(new Zip_Segment__c(Name='Test HNB2',Sales_Org__c=UserHelper.SO_HNB,Emps_Min__c=50,Emps_Max__c=999999,Paychex_Id__c='TestHnb2'));
      insert segments;
      return segments;
   } // createSegments
   
   /** Create a Zip_Code_Information__c record. */
   private static Zip_Code_Information__c createZci(String zipCode) {
   	Zip_Code_Information__c zci = new Zip_Code_Information__c(Name=zipCode,Zip_Code_Key__c=zipCode,City__c='Test City',State__c='NY');
   	insert zci;
   	return zci;
   } // create Zci
   
   /** Create Zip_Assignment__c records.
    */
   private static Zip_Assignment__c[] createZipAsgns(String zipCode, Zip_Segment__c[] segments) {
      Map<String, Org_Unit__c> districtMap = new Map<String, Org_Unit__c>();
      Map<Id, Zip_Segment__c> segmentMap = new Map<Id, Zip_Segment__c>();
      
      for (Zip_Segment__c segment : segments) {
      	segmentMap.put(segment.Id, segment);
      	if (!districtMap.containsKey(segment.Sales_Org__c)) {
            Org_Unit__c district = new Org_Unit__c(Name='1', Org_Unit_Name__c='Test '+segment.Sales_Org__c
                                  ,Sales_Org__c=segment.Sales_Org__c, Org_Type__c=OrgUnitMethods.TYPE_DISTRICT
                                  ,MgrName__c='Joe Manager', MgrEmail__c='joe.manager.@test.com'
                                  ,AssistantName__c='Jimmy Assistant', AssistantEmail__c='jimmy.assistant@test.com'
                                  ,OverrideMgr__c=true,OverrideAssistant__c=true );
            //districts.add(district);
            districtMap.put(segment.Sales_Org__c, district);
      	}
      } // for
      insert districtMap.values();
      
      // select a rep for each segment - we won't care about sales orgs
      User[] reps = [Select Id, Name
                       From User
                      Where IsActive = true
                        And Profile.Name in :Utilities.REP_PROFS
                      limit :segments.size()];
      // select a DSA and DSM
      User dsa = [Select Id, Name from User where IsActive=true and Job_Name__c=:UserHelper.JOB_DSA limit 1];
      User dsm = [Select Id, Name from User where IsActive=true and Job_Name__c=:UserHelper.JOB_DSM limit 1];
      
      // create a dsm and dsa link for each district
      Org_Unit_User_Link__c[] links = new Org_Unit_User_Link__c[]{};
      for (Org_Unit__c district : districtMap.values()) {
         Org_Unit_User_Link__c dsaLink = new Org_Unit_User_Link__c(Org_Unit__c=district.Id, User__c=dsa.Id);
         Org_Unit_User_Link__c dsmLink = new Org_Unit_User_Link__c(Org_Unit__c=district.Id, User__c=dsm.Id);
         links.add(dsaLink);
         links.add(dsmLink);
      } // for (Org_Unit__c district
      insert links;
      
      // create territories - 1 for each segment
      ZipTerritory__c[] territories = new ZipTerritory__c[]{};
      for (Zip_Segment__c segment : segments) {
         Org_Unit__c district = districtMap.get(segment.Sales_Org__c);
         User rep = reps.remove(reps.size()-1);
         ZipTerritory__c territory = new ZipTerritory__c(Name='Territory 1',District__c=district.Id
                                    ,Rep_Name__c=rep.Name, Territory_Nbr__c='1'
                                    ,TerritoryRep__c=rep.Id
                                    ,Zip_Segment__c=segment.Id);
         territories.add(territory);
      } // for (Zip_Segment__c segment
      insert territories;
      
      // create the zip assignments
      Zip_Assignment__c[] zipAssigns = new Zip_Assignment__c[]{};
      
      for (ZipTerritory__c territory : territories) {
      	Zip_Segment__c segment = segmentMap.get(territory.Zip_Segment__c);
         Zip_Assignment__c za = new Zip_Assignment__c(Name=zipCode, Emps_Max__c=segment.Emps_Max__c, Emps_Min__c=segment.Emps_Min__c);
         za.BypassDistrictTrigger__c = true;
         za.Rep_Name__c = territory.Rep_Name__c;
         za.User__c = territory.TerritoryRep__c;
         za.Zip_Segment__c = territory.Zip_Segment__c;
         za.ZipTerritory__c = territory.Id;
         za.District__c = territory.District__c;
         za.Sales_Org__c = segment.Sales_Org__c;
         zipAssigns.add(za);
      } // for (ZipTerritory__c territory
      insert zipAssigns;
      
      return zipAssigns;
   } // createZipAsgns

      
   /** Test a normal procedure. */
   static testMethod void testZips() {
      // set the page reference
      Test.setCurrentPage(Page.ZipCodeLookup);
      
      // create segments
      Zip_Segment__c[] segments = createSegments();
      ZipCodeLookupController zclc = new ZipCodeLookupController();
      // check default values
      System.assertEquals(null,zclc.zipCodeQuery);
      System.assertEquals(null,zclc.zipInfo);
      System.assertEquals(false,zclc.displayFAQ);
      System.assertEquals(false,zclc.hasZipInfo);
      System.assertEquals('Display FAQ',zclc.faqLinkTitle);
      System.assertEquals(false,zclc.hasResults);
      
      // query with a zip code that does not exist in the tables
      // perform a query with a 5 character zip code
      zclc.zipCodeQuery = '12345';
      System.assertEquals(null,zclc.queryZipCodes());
      // should be no errors
      System.assertEquals(false,ApexPages.hasMessages() );
      // still no zipInfo
      System.assertEquals(false,zclc.hasZipInfo);
      // has no results - only returns rows that have a zip_assignment record.
      System.assertEquals(false,zclc.hasResults);
      // no results were returned
      System.assertEquals(0,zclc.zipResults.size());
      
      // query with the zip info and zip assignment records
      Zip_Code_Information__c zci = createZci('12345');
      Zip_Assignment__c[] zipAsgns = createZipAsgns('12345', segments);

      zclc.zipCodeQuery = '12345';
      System.assertEquals(null,zclc.queryZipCodes());
      // should be no errors
      System.assertEquals(false,ApexPages.hasMessages() );
      // still no zipInfo
      System.assertEquals(true,zclc.hasZipInfo);
      // has results because of the zip segments
      System.assertEquals(true,zclc.hasResults);
      // number of results should equal the number of segments
      System.assertEquals(segments.size(),zclc.zipResults.size());
      // verify the showAllColumns flag
      System.assertEquals(false,zclc.showAllColumns);
      // toggle the flag
      System.assertEquals(null,zclc.toggleShowAllColumns());
      // verify the showAllColumns is now true;
      System.assertEquals(true,zclc.showAllColumns);
      
   } // testZips
   
   static testMethod void testOther() {
      ZipCodeLookupController zclc = new ZipCodeLookupController();
      System.assertEquals(false,zclc.displayFAQ);
      System.assertEquals(null,zclc.toggleFAQ());
      System.assertEquals(true,zclc.displayFAQ);
      System.assertEquals(null,zclc.toggleFAQ());
      System.assertEquals(false,zclc.displayFAQ);
      System.assertEquals(null,zclc.toggleFAQ());
      System.assertEquals(true,zclc.displayFAQ);
      
   } // testOther

   static testMethod void testGetZipAssignment() {
      Zip_Segment__c[] segments = createSegments();
      // query with the zip info and zip assignment records
      Zip_Code_Information__c zci = createZci('12345');
      Zip_Assignment__c[] zipAsgns = createZipAsgns('12345', segments);

      ZipCheckOwner.setupRecordTypeMaps();
      Id recordTypeId = ZipCheckOwner.rtByName.get(RecordTypeHelper.CORE_ACCOUNT).getRecordTypeId();
      Account acct = new Account(Name='Test Account', RecordTypeId=recordTypeId, ShippingPostalCode='12345',NumberOfEmployees=30);
      
      ZipWrapper wrapper = ZipCodeLookupController.getZipAssignment('12345', UserHelper.SO_CORE, acct);
      System.assertEquals(UserHelper.SO_CORE, wrapper.za.Sales_Org__c);
   } // testGetZipAssignment
   
} // class ZipCodeLookupControllerTest