force-app/main/default/objects/Amplifinity_AR_Status_Mapping__mdt/Amplifinity_AR_Status_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>used to map the AR Status on the Payx Referral to the appropriate AMP status on the AMP Referral</description>
    <label>Amplifinity AR Status Mapping</label>
    <pluralLabel>Amplifinity AR Status Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Amplifinity_AR_Status_Mapping__mdt/fields/Allow_Updates__c.field-meta.xml
<CustomField>
    <fullName>Allow_Updates__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If a referral has a certain AR Status no more updates should be allowed to those records.</description>
    <label>Allow Updates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Amplifinity_AR_Status_Mapping__mdt/fields/AMP_Status__c.field-meta.xml
<CustomField>
    <fullName>AMP_Status__c</fullName>
    <label>AMP Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Amplifinity_AR_Status_Mapping__mdt/fields/AR_Status__c.field-meta.xml
<CustomField>
    <fullName>AR_Status__c</fullName>
    <label>AR Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Referral_Management_Data__c/AR_Referral_Management_Data__c.object-meta.xml
<CustomObject>
    <description>staging object to hold data from AR related to opportunities that are in the reward process, will eventually update the PAYX referral object</description>
    <label>AR Referral Management Data</label>
    <nameField>
        <displayFormat>AR Referral Mgmt-{0000000000}</displayFormat>
        <label>AR Referral Management</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AR Referral Management Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AR_Referral_Management_Data__c/fields/AR_Status__c.field-meta.xml
<CustomField>
    <fullName>AR_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Referral_Management_Data__c/fields/Credit_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Credit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AR_Referral_Management_Data__c/fields/ReferralID__c.field-meta.xml
<CustomField>
    <fullName>ReferralID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ReferralID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AR_Referral_Management_Data__c/fields/Reward_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reward_Amount__c</fullName>
    <label>Reward Amount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>$200</fullName>
            </value>
            <value>
                <fullName>$500</fullName>
            </value>
            <value>
                <fullName>Free Payroll</fullName>
            </value>
            <value>
                <fullName>Already Earned Free Payroll</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Referral_Management_Data__c/fields/Term_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Term End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AR_Referral_Management_Data__c/fields/Term_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Term Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <description>An object to store Referral information</description>
    <label>Referral</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/AMP_Status__c.field-meta.xml
<CustomField>
    <fullName>AMP_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AMP Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Amplifinity_Referral__c.field-meta.xml
<CustomField>
    <fullName>Amplifinity_Referral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Amplifinity Referral</label>
    <referenceTo>amp_dev__Amp_Referral__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/AR_Status__c.field-meta.xml
<CustomField>
    <fullName>AR_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AR Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Credit_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Date__c</fullName>
    <description>passed in from AR - when referral credit is paid</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Credit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Reward_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reward_Amount__c</fullName>
    <description>passed in from AR - reward earned on a referral</description>
    <label>Reward Amount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>$200</fullName>
            </value>
            <value>
                <fullName>$500</fullName>
            </value>
            <value>
                <fullName>Free Payroll</fullName>
            </value>
            <value>
                <fullName>Already Earned Free Payroll</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Term_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_End_Date__c</fullName>
    <description>initially calculated based on enrollment date into Amplifinity reward program, after opportunity is marked Sold it will be passed in from AR - the end of a specified term in which referrals will qualify</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Term End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Term_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_Start_Date__c</fullName>
    <description>initially calculated based on enrollment date into Amplifinity reward program, after opportunity is marked Sold it will be passed in from AR - the start of a specified term in which referrals will qualify</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Term Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ARReferralManagementDataMethodsTest.cls
/* Test Methods for ARReferralManagementDataMethods

 * History
 * -------
  10/01/2019 Carrie Marciano      Created
  
*/

@isTest
public class ARReferralManagementDataMethodsTest {

    static testMethod void testARData(){
        
        amp_dev__Amp_Referral__c ampRef1 = new amp_dev__Amp_Referral__c (Name='ampRef1', amp_dev__Status__c='Submitted', AR_Reward_Amount__c='', Term_End_Date__c=Date.today().addDays(364));
        amp_dev__Amp_Referral__c ampRef2 = new amp_dev__Amp_Referral__c (Name='ampRef2', amp_dev__Status__c='SoldPendingPayroll', AR_Reward_Amount__c='$200', Term_End_Date__c=Date.today().addDays(364));
        amp_dev__Amp_Referral__c ampRef3 = new amp_dev__Amp_Referral__c (Name='ampRef3', amp_dev__Status__c='Successful', AR_Reward_Amount__c='$500', Term_End_Date__c=Date.today().addDays(364));
        amp_dev__Amp_Referral__c[] ampRefs = new amp_dev__Amp_Referral__c[]{ampRef1,ampRef2,ampRef3};
        insert ampRefs;
        
        Referral__c payxRef1 = new Referral__c (Name='payxRef1', Amplifinity_Referral__c=ampRef1.Id, AR_Status__c='Suggested', AMP_Status__c='Submitted', Credit_Date__c=null, Reward_Amount__c='', Term_Start_Date__c=Date.today(), Term_End_Date__c=Date.today().addDays(364));
        Referral__c payxRef2 = new Referral__c (Name='payxRef2', Amplifinity_Referral__c=ampRef2.Id, AR_Status__c='Validated', AMP_Status__c='SoldPendingPayroll', Credit_Date__c=null, Reward_Amount__c='$200', Term_Start_Date__c=Date.today(), Term_End_Date__c=Date.today().addDays(364));
        Referral__c payxRef3 = new Referral__c (Name='payxRef3', Amplifinity_Referral__c=ampRef3.Id, AR_Status__c='Processed', AMP_Status__c='Successful', Credit_Date__c=Date.today(), Reward_Amount__c='$500', Term_Start_Date__c=Date.today(), Term_End_Date__c=Date.today().addDays(364));
        Referral__c[] payxRefs = new Referral__c[]{payxRef1,payxRef2,payxRef3};
        insert payxRefs;
        
        AR_Referral_Management_Data__c arDataRec1 = new AR_Referral_Management_Data__c (AR_Status__c='Validated', Credit_Date__c=Date.today(), ReferralID__c=payxRef1.Id, Reward_Amount__c='$500', Term_Start_Date__c=Date.today(), Term_End_Date__c=Date.today().addDays(364)); 
        AR_Referral_Management_Data__c arDataRec2 = new AR_Referral_Management_Data__c (AR_Status__c='Processed', Credit_Date__c=Date.today(), ReferralID__c=payxRef2.Id, Reward_Amount__c='$200', Term_Start_Date__c=Date.today(), Term_End_Date__c=Date.today().addDays(364));
        AR_Referral_Management_Data__c arDataRec3 = new AR_Referral_Management_Data__c (AR_Status__c='Processed', Credit_Date__c=Date.today(), ReferralID__c=payxRef3.Id, Reward_Amount__c='Free Payroll', Term_Start_Date__c=Date.today(), Term_End_Date__c=Date.today().addDays(364));
        AR_Referral_Management_Data__c[] arDataRecs = new AR_Referral_Management_Data__c[]{arDataRec1,arDataRec2,arDataRec3};
        
        Amplifinity_AR_Status_Mapping__mdt[] statusMapping = [select MasterLabel, AR_Status__c, AMP_Status__c, Allow_Updates__c from Amplifinity_AR_Status_Mapping__mdt where label ='Processed']; 
        System.assertEquals(false,statusMapping[0].Allow_Updates__c); 
        
        Test.startTest();
        insert arDataRecs; 
        Test.stopTest();
         
        payxRef1 = [Select Id, Credit_Date__c, AR_Status__c, Reward_Amount__c from Referral__c where Id=:payxRef1.Id];
        System.assertEquals(arDataRec1.Credit_Date__c, payxRef1.Credit_Date__c);
        System.assertEquals('Validated',payxRef1.AR_Status__c);
        System.assertEquals(arDataRec1.Reward_Amount__c, payxRef1.Reward_Amount__c);
        payxRef2 = [Select Id, Credit_Date__c, AR_Status__c from Referral__c where Id=:payxRef2.Id];
        System.assertEquals(arDataRec2.Credit_Date__c, payxRef2.Credit_Date__c);
        System.assertEquals('Processed',payxRef2.AR_Status__c);
        payxRef3 = [Select Id, AR_Status__c, Reward_Amount__c from Referral__c where Id=:payxRef3.Id];
        System.assertEquals('$500',payxRef3.Reward_Amount__c);
        System.assertEquals('Processed',payxRef3.AR_Status__c);
        
   }//testARData
}