force-app/main/default/objects/WC_NAICS_To_Industry_Map__c/WC_NAICS_To_Industry_Map__c.object-meta.xml
<CustomObject>
    <label>WC NAICS To Industry Map</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>NAICS Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WC NAICS To Industry Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WC_NAICS_To_Industry_Map__c/fields/Industry_Name__c.field-meta.xml
<CustomField>
    <fullName>Industry_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Industry Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WC_NAICS_To_Industry_Map__c/fields/PEO_Industry_Title__c.field-meta.xml
<CustomField>
    <fullName>PEO_Industry_Title__c</fullName>
    <label>PEO Industry Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Retail/Wholesale</fullName>
            </value>
            <value>
                <fullName>Restaurants</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Hotels</fullName>
            </value>
            <value>
                <fullName>Home Health</fullName>
            </value>
            <value>
                <fullName>Doctor&apos;s Offices</fullName>
            </value>
            <value>
                <fullName>Auto Dealership</fullName>
            </value>
            <value>
                <fullName>Auto Service/Repair/Autobody Collision/Paint Shop</fullName>
            </value>
            <value>
                <fullName>Auto/Truck Rental</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Contractors/Construction/Service Traders including Plumbing/HVAC/Electrician</fullName>
            </value>
            <value>
                <fullName>Delivery Trucking exposure</fullName>
            </value>
            <value>
                <fullName>Marinas</fullName>
            </value>
            <value>
                <fullName>Veterinary services (State National)</fullName>
            </value>
            <value>
                <fullName>Golf/Country Club</fullName>
            </value>
            <value>
                <fullName>Landscapers</fullName>
            </value>
            <value>
                <fullName>Jewelry Store</fullName>
            </value>
            <value>
                <fullName>Gas Stations with convenience Stores or Grocery Stores</fullName>
            </value>
            <value>
                <fullName>School/Day care</fullName>
            </value>
            <value>
                <fullName>Not for Profit</fullName>
            </value>
            <value>
                <fullName>Property Management</fullName>
            </value>
            <value>
                <fullName>Fencing Contractors</fullName>
            </value>
            <value>
                <fullName>Warehouse/Storage</fullName>
            </value>
            <value>
                <fullName>Furniture</fullName>
            </value>
            <value>
                <fullName>Garment Industry</fullName>
            </value>
            <value>
                <fullName>Moving Companies</fullName>
            </value>
            <value>
                <fullName>Assisted Living Facility</fullName>
            </value>
            <value>
                <fullName>Commercial Janitorial Services</fullName>
            </value>
            <value>
                <fullName>NY Exposure</fullName>
            </value>
            <value>
                <fullName>Physical Distribution Logistics Consulting Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WC_NAICS_To_Industry_Map__c/fields/Required_With_WC_FastPass__c.field-meta.xml
<CustomField>
    <fullName>Required_With_WC_FastPass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required With WC FastPass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WC_Questionnaire_Industry_Specific__c/WC_Questionnaire_Industry_Specific__c.object-meta.xml
<CustomObject>
    <description>this to hold industry specific questions</description>
    <label>WC Questionnaire Industry Specific</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>WC Questionnaire industry Specific Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WC Questionnaire Industry Specific</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WC_Questionnaire_Industry_Specific__c/fields/Peo_IndSpecific_formStatus__c.field-meta.xml
<CustomField>
    <fullName>Peo_IndSpecific_formStatus__c</fullName>
    <label>Peo_IndSpecific_formStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Questionnaire_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WC_Questionnaire_Industry_Specific__c/fields/Peo_IndSpecific_formSubmissionTime__c.field-meta.xml
<CustomField>
    <fullName>Peo_IndSpecific_formSubmissionTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Peo_IndSpecific_formSubmissionTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WC_Questionnaire_Industry_Specific__c/fields/PEO_Underwriting_Checklist__c.field-meta.xml
<CustomField>
    <fullName>PEO_Underwriting_Checklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PEO Underwriting Checklist</label>
    <referenceTo>PEO_Onboarding_Checklist__c</referenceTo>
    <relationshipLabel>WC Questionnaire Industry Specific</relationshipLabel>
    <relationshipName>WC_Questionnaire_Industry_Specific</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Questionnaire_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <masterLabel>Questionnaire_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CommunityIndustrySpecificController.cls
/*
* Controller for workers comp component in community forms
* 
* History
* ----------------------------------------
* 08/20/2021	Ahmed Elawad	Created
* 02/01/2022	Ahmed Elawad	SFDC-10790 APR APR0131036: update saveIndustrySpecific() to update WQ on every save
*/ 

public without sharing class CommunityIndustrySpecificController {
	
    @AuraEnabled      
    public static CommunityMethods.IndustrySpecificWrap getIndustryDetails(String PEOchecklist, String peoIndustryTitle, String formName){
        return CommunityMethods.getIndustryDetails(PEOchecklist, peoIndustryTitle, formName, 'CommunityIndustrySpecificController');
    }
    
    @AuraEnabled
    public static string getIndustrySpecificStatus(String PEOchecklist) {
        return CommunityMethods.getIndustrySpecificStatus(PEOchecklist);
    }
    
    @AuraEnabled
    public static WC_Questionnaire_Industry_Specific__c saveIndustrySpecific(WC_Questionnaire_Industry_Specific__c IndustryRec, String formName){
        if(IndustryRec!=null){
            try{
                Datetime current = System.now(); 
                Date currDate = current.date();
                Time currTime = current.time();
                Datetime local = datetime.newinstance(currDate,currTime);
                //if(action == 'Save and Submit')IndustryRec.Peo_IndSpecific_formSubmissionTime__c = local;
                if(IndustryRec.Peo_IndSpecific_formStatus__c == 'Complete' && IndustryRec.Peo_IndSpecific_formSubmissionTime__c == null)IndustryRec.Peo_IndSpecific_formSubmissionTime__c = local;
                
                upsert IndustryRec;
                
                //SFDC-10790 APR APR0131036        
                Set<Id> checklistIDstoCreateIndWQs = new Set<Id>();
                checklistIDstoCreateIndWQs.add(IndustryRec.PEO_Underwriting_Checklist__c);                
                if (!checklistIDstoCreateIndWQs.isEmpty()) communityMethods.createIndSpecificWQFuture(checklistIDstoCreateIndWQs);
                
                return IndustryRec;
            }catch(Exception e){
                communityMethods.logCommunityError(e, 'saveIndustrySpecific', 'CommunityIndustrySpecificController',formName, new List<WC_Questionnaire_Industry_Specific__c>{IndustryRec});
                return null;
            }
        }
        return null;
    }
    
    @AuraEnabled
    public static List<string> getIndustryNames(String[] naicsCodes) {
        WC_NAICS_To_Industry_Map__c[] wcNaicsCodes = [SELECT ID, Name, PEO_Industry_Title__c, Industry_Name__c, Required_With_WC_FastPass__c FROM WC_NAICS_To_Industry_Map__c where Name IN :naicsCodes];
        
        List<String> industryNames = new List<String>();
        for(WC_NAICS_To_Industry_Map__c wcMap : wcNaicsCodes) {
            if(wcMap.PEO_Industry_Title__c != null && wcMap.PEO_Industry_Title__c != '' && !industryNames.contains(wcMap.PEO_Industry_Title__c)) {
                industryNames.add(wcMap.PEO_Industry_Title__c);
            }
        }
        
        return industryNames;
    }
    
}