force-app/main/default/objects/Account/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <description>this field is populated initially by the ID from war. Going forward Salesforce will generate this number on the account</description>
    <displayFormat>5{0000000}</displayFormat>
    <label>Account ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Work_Queue__c/Work_Queue__c.object-meta.xml
<CustomObject>
    <label>Work Queue</label>
    <nameField>
        <displayFormat>WQ-{00000}</displayFormat>
        <label>Work Queue Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Queue__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Queues</relationshipLabel>
    <relationshipName>Work_Queues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Queue__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Queue__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Queue__c/fields/Object_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Object_Record_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Object Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WorkQueueTriggerHandler.cls
/* Trigger Handler for Work Queue Trigger
*
*   HISTORY
*  ---------
*   05/16/2024  Jidesh     Created

*/
public class WorkQueueTriggerHandler {

    //This method checks if the Account workqueue is created
    //If yes, reset the workqueues for other objects
    public static void afterInsertHandler(Map<id,Work_Queue__c> oldMap ,Map<id,Work_Queue__c> newMap){
        System.debug('Inside afterInsertHandler');
        List<Id> accIdList = new List<Id>();
        for(Work_Queue__c newRec : newMap.values()){
            if(newRec.Object__c == ObjectHelper.OBJECT_ACCOUNT){
                accIdList.add(newRec.Account_ID__c);
            }
        }
        if(accIdList.size()>0){
            System.debug('Inside afterInsertHandler calling resetWorkquesForAccount');
            resetWorkquesForAccount(accIdList);
        }
    }
    
    //This method sets all the workqueue completed status to false when an account Worqueue is created.
    public static void resetWorkquesForAccount(List<Id> Accounts) {
        System.debug('Inside resetWorkquesForAccount');
        List<Id> accIdList = new List<Id>();
        accIdList = Accounts;
        Work_Queue__c[] refreshWorkQueues = new Work_Queue__c[]{};
        System.debug('resetWorkquesForAccount accIdList:'+accIdList);   
        List<Work_Queue__c> queues = [SELECT Account_ID__c,Completed__c,Id,Name,Object_Record_ID__c,Object__c FROM Work_Queue__c WHERE Completed__c = true AND Account_ID__c IN: accIdList AND Object__c != 'Account']; 
        System.debug('resetWorkquesForAccount queues:'+queues);    
        if(queues.size()>0){
            for(Work_Queue__c wqs: queues){
                wqs.Completed__c = false;
                refreshWorkQueues.add(wqs);
            }   
            if(refreshWorkQueues.size()>0){
                DmlHelper.performDML2(refreshWorkQueues, DmlHelper.DML_UPDATE, 'WorkQueueTriggerHandler', 'resetWorkquesForAccount', 'Refreshing related Workqueues', true);
            }
        }
    }
}