force-app/main/default/objects/Account/fields/Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_Date__c</fullName>
    <description>Will be populated by a daily Demand Tools process. Used for Preview to Flex Migration. case 21207207 
Date of last activity in migration process

6/22/18 Retiring demandtools process for SOAP integration, FFSService.cls</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2nd Level Support Queue</fullName>
            </value>
            <value>
                <fullName>401k</fullName>
            </value>
            <value>
                <fullName>401K Client Contact Meeting</fullName>
            </value>
            <value>
                <fullName>401k Enrollment</fullName>
            </value>
            <value>
                <fullName>401k Introduction</fullName>
            </value>
            <value>
                <fullName>401K Quarterly Check In</fullName>
            </value>
            <value>
                <fullName>Accident Investigation</fullName>
            </value>
            <value>
                <fullName>Affirmative Action</fullName>
            </value>
            <value>
                <fullName>AKC / AHQ Review</fullName>
            </value>
            <value>
                <fullName>Americans with Disabilities Act</fullName>
            </value>
            <value>
                <fullName>Annual Review</fullName>
            </value>
            <value>
                <fullName>Appointment</fullName>
            </value>
            <value>
                <fullName>Attempted Contact/Left Message</fullName>
            </value>
            <value>
                <fullName>Attended Branch Training</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Background Checks</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Benefit Time Recording</fullName>
            </value>
            <value>
                <fullName>Benefit Time Report</fullName>
            </value>
            <value>
                <fullName>Billing/Invoicing</fullName>
            </value>
            <value>
                <fullName>Billing-ACH Change</fullName>
            </value>
            <value>
                <fullName>Billing-ACH Issue</fullName>
            </value>
            <value>
                <fullName>Billing-Financial Issues</fullName>
            </value>
            <value>
                <fullName>Billing Issue-Discounting</fullName>
            </value>
            <value>
                <fullName>Billing Issue-Invoicing</fullName>
            </value>
            <value>
                <fullName>Business Tax Service</fullName>
            </value>
            <value>
                <fullName>Calendar of Service</fullName>
            </value>
            <value>
                <fullName>Carrier Producer Number</fullName>
            </value>
            <value>
                <fullName>Change in Account Health Status-Green to Red</fullName>
            </value>
            <value>
                <fullName>Change in Account Health Status-Green to Yellow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity/fields/Client_Summary__c.field-meta.xml
<CustomField>
    <fullName>Client_Summary__c</fullName>
    <description>field is used by HRGs to briefly describe the interaction with the client. This field is feed into the Conga Merge template for the Client Summary Report</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This will be client facing, and displayed on the Client Summary Report.</inlineHelpText>
    <label>Client Summary</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>401K</fullName>
            </value>
            <value>
                <fullName>BeneTrac</fullName>
            </value>
            <value>
                <fullName>COBRA</fullName>
            </value>
            <value>
                <fullName>CT-900</fullName>
            </value>
            <value>
                <fullName>Employee Screening Service</fullName>
            </value>
            <value>
                <fullName>Error: Invalid Data.</fullName>
            </value>
            <value>
                <fullName>ExpenseWire</fullName>
            </value>
            <value>
                <fullName>FSA</fullName>
            </value>
            <value>
                <fullName>FSA Debit Card</fullName>
            </value>
            <value>
                <fullName>H&amp;B</fullName>
            </value>
            <value>
                <fullName>HR Online</fullName>
            </value>
            <value>
                <fullName>HRR Services</fullName>
            </value>
            <value>
                <fullName>Large Market 401K</fullName>
            </value>
            <value>
                <fullName>LT-1000</fullName>
            </value>
            <value>
                <fullName>LT-2000 Bio</fullName>
            </value>
            <value>
                <fullName>LT-2000 Prox</fullName>
            </value>
            <value>
                <fullName>MMS Payroll</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>New Hire Reporting</fullName>
            </value>
            <value>
                <fullName>OSC Access Card</fullName>
            </value>
            <value>
                <fullName>OSC Advantage</fullName>
            </value>
            <value>
                <fullName>OSC Direct Deposit</fullName>
            </value>
            <value>
                <fullName>OSC EIP</fullName>
            </value>
            <value>
                <fullName>OSC Garnishment</fullName>
            </value>
            <value>
                <fullName>OSC ReadyChex</fullName>
            </value>
            <value>
                <fullName>OSC Taxpay</fullName>
            </value>
            <value>
                <fullName>Paychex Expense Manager</fullName>
            </value>
            <value>
                <fullName>PBS</fullName>
            </value>
            <value>
                <fullName>PC Reporter</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_HRG__c/Reference_HRG__c.object-meta.xml
<CustomObject>
    <label>Reference HRG Onboarding</label>
    <nameField>
        <displayFormat>HRG Onboarding {000000}</displayFormat>
        <label>Reference HRG Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference HRG Onboarding</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_HRG__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reference HRG Onboarding</relationshipLabel>
    <relationshipName>Reference_HRG</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_HRG__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(Account__r.Type)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Client Type from Prospect Client</inlineHelpText>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReferenceHRGActivity__c/ReferenceHRGActivity__c.object-meta.xml
<CustomObject>
    <label>Reference HRG Activity</label>
    <nameField>
        <displayFormat>Activity-{0000000}</displayFormat>
        <label>Reference HRG Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference HRG Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ReferenceHRGActivity__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Activity_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1st Invoice Review</fullName>
            </value>
            <value>
                <fullName>401(k) Enrollment</fullName>
            </value>
            <value>
                <fullName>401(k) Enrollment with Auto-Enrollment</fullName>
            </value>
            <value>
                <fullName>401k</fullName>
            </value>
            <value>
                <fullName>401k Client Contact Meeting</fullName>
            </value>
            <value>
                <fullName>401k Compliance Testing Review</fullName>
            </value>
            <value>
                <fullName>401k Enrollment</fullName>
            </value>
            <value>
                <fullName>Addressing Common Employee Relations Issues</fullName>
            </value>
            <value>
                <fullName>Addressing EE Relations Issues: All Modules Completed</fullName>
            </value>
            <value>
                <fullName>Addressing EE Relations Issues: Module 1</fullName>
            </value>
            <value>
                <fullName>Addressing EE Relations Issues: Module 2</fullName>
            </value>
            <value>
                <fullName>Addressing EE Relations Issues: Module 3</fullName>
            </value>
            <value>
                <fullName>Addressing EE Relations Issues: Module 4</fullName>
            </value>
            <value>
                <fullName>Addressing EE Relations Issues: Module 5</fullName>
            </value>
            <value>
                <fullName>Affirmative Action</fullName>
            </value>
            <value>
                <fullName>Americans with Disabilities Act</fullName>
            </value>
            <value>
                <fullName>Attendance Issues-Module 2</fullName>
            </value>
            <value>
                <fullName>Attended Branch Training</fullName>
            </value>
            <value>
                <fullName>Avoiding Employment Discrimination</fullName>
            </value>
            <value>
                <fullName>Background Checks</fullName>
            </value>
            <value>
                <fullName>Background Check Services</fullName>
            </value>
            <value>
                <fullName>Behavioral Interviewing</fullName>
            </value>
            <value>
                <fullName>Being an Effective Team Member</fullName>
            </value>
            <value>
                <fullName>Being an Inclusive Coworker</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Benefits – Product Discussions</fullName>
            </value>
            <value>
                <fullName>Benefits – Time Away from Work</fullName>
            </value>
            <value>
                <fullName>Bene Trac</fullName>
            </value>
            <value>
                <fullName>Billing/Invoicing</fullName>
            </value>
            <value>
                <fullName>Bridging the Generational Gap</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ReferenceHRGActivity__c/fields/Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date the last activity occurred.</inlineHelpText>
    <label>Activity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ReferenceHRGActivity__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <inlineHelpText>The type of activity</inlineHelpText>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Activity</fullName>
            </value>
            <value>
                <fullName>Delivered Client Seminars</fullName>
            </value>
            <value>
                <fullName>HR Consulting</fullName>
            </value>
            <value>
                <fullName>Products/Services</fullName>
            </value>
            <value>
                <fullName>Pilot-Advisory Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ReferenceHRGActivity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Internal (no client contact)</fullName>
            </value>
            <value>
                <fullName>Email-One Way</fullName>
            </value>
            <value>
                <fullName>Email-Two Way</fullName>
            </value>
            <value>
                <fullName>Fax-One Way</fullName>
            </value>
            <value>
                <fullName>Fax-Two Way</fullName>
            </value>
            <value>
                <fullName>Mail-One Way</fullName>
            </value>
            <value>
                <fullName>Mail-Two Way</fullName>
            </value>
            <value>
                <fullName>Onsite-One Way</fullName>
            </value>
            <value>
                <fullName>Onsite-Two Way</fullName>
            </value>
            <value>
                <fullName>Scheduled Call-One Way</fullName>
            </value>
            <value>
                <fullName>Scheduled Call-Two Way</fullName>
            </value>
            <value>
                <fullName>Social Media-One Way</fullName>
            </value>
            <value>
                <fullName>Social Media-Two Way</fullName>
            </value>
            <value>
                <fullName>Text-One Way</fullName>
            </value>
            <value>
                <fullName>Text-Two Way</fullName>
            </value>
            <value>
                <fullName>Unscheduled Call-One Way</fullName>
            </value>
            <value>
                <fullName>Unscheduled Call-Two Way</fullName>
            </value>
            <value>
                <fullName>Web-ex-One Way</fullName>
            </value>
            <value>
                <fullName>Web-ex-Two Way</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReferenceHRGControllerTest.cls
/* 
 * Test methods for the ReferenceHRGController class
 *
 * History
 * -------
 * 04/12/2013 Dan Carmen   Created
   10/01/2013 Dan Carmen   Added in check for PREMIER_PLAN_CODE_SET for mass update
 *
 */
@isTest
private class ReferenceHRGControllerTest {

   /** Test standard usage without a Reference object already created. */
   static testMethod void testStandardUsageNoRef() {
    // create an account and contacts to start from
    Account acct1 = new Account(Name='Test Account');
    insert acct1;
    Contact ctct1 = new Contact(AccountId=acct1.Id,FirstName='Test',LastName='One',Email='test.one@testaccount.com');
    Contact ctct2 = new Contact(AccountId=acct1.Id,FirstName='Test',LastName='Two',Email='test.two@testaccount.com');
    Contact[] ctcts = new Contact[]{ctct1,ctct2};
    insert ctcts;
  // add Open Salesforce Activity with no HRG Activity associated to it yet
    String RT_TASK='2008-09 Premier Service Provider Task Record Type';
    Schema.RecordTypeInfo taskRT = RecordTypeHelper.getRecordType(RT_TASK,'Task');
    Task tsk1 = new Task(RecordTypeId=taskRT.getRecordTypeId(),WhatId=acct1.id,ActivityDate=Date.today().addDays(3),Subject='Test Task',Product__c='Premier',Type='Email',Client_Summary__c='This is a test');
    insert tsk1;
      
      Test.SetCurrentPageReference(Page.ReferenceHRG);
      System.CurrentPageReference().getParameters().put('acctId',acct1.Id);
      ReferenceHRGController rhc1 = new ReferenceHRGController();
      System.assertEquals(false,rhc1.promptForAccount);
      // verify there's a new reference object
      System.assertEquals(true,rhc1.refHRG.Id == null);
      System.assertEquals(true,rhc1.okayToProceed);
      // make sure we're at the step to ask for task/event
      System.assertEquals('What Did You Do',rhc1.currentStep);

      // verify we have contacts
      System.assertEquals(true,rhc1.hasContactSelections);
      // should be three elements in the array
      System.assertEquals(3,rhc1.contactSelections.size());
      
      //Show Open Salesforce Activity on the first screen of HRG Activity VFpage 
      rhc1.checkForActivityToConfirm();
        
      // should be open 1 Salesforce activity
      System.assertEquals(1,rhc1.sortedOpenActivityList.size());
      
      rhc1.deleteKey=rhc1.sortedOpenActivityList[0].key;
      rhc1.deleteSalesforceActivity();
      rhc1 = new ReferenceHRGController();
   
      // should be open 0 Salesforce activity
      System.assertEquals(0,rhc1.sortedOpenActivityList.size());
      
      ReferenceHRGController rhc = new ReferenceHRGController();
      
      // should be open no Salesforce activity
      System.assertEquals(0,rhc.sortedOpenActivityList.size());
      
      // should not be any open activities
      System.assertEquals(false,rhc.hasOpenActivityList);
      
      // verify the step
      System.assertEquals('What Did You Do',rhc.currentStep);
      
      // toggle the different sections
      // since this is new, the onboarding section will be open.
      System.assertEquals(true,rhc.showOnboarding);
      // close then open it again
      rhc.toggleOnboarding();
      System.assertEquals(false,rhc.showOnboarding);
      rhc.toggleOnboarding();
      System.assertEquals(true,rhc.showOnboarding);
      
      // client concerns will be closed initially
      System.assertEquals(false,rhc.showClientConcerns);
      rhc.toggleShowClientConcerns();
      System.assertEquals(true,rhc.showClientConcerns);
      rhc.toggleShowClientConcerns();
      System.assertEquals(false,rhc.showClientConcerns);
      
      // setup issues will be closed initially
      System.assertEquals(false,rhc.showSetupIssues);
      rhc.toggleShowSetupIssues();
      System.assertEquals(true,rhc.showSetupIssues);
      rhc.toggleShowSetupIssues();
      System.assertEquals(false,rhc.showSetupIssues);

      // product utilization will be closed
      System.assertEquals(false,rhc.showProductUtilization);
      rhc.toggleShowProductUtilization();
      System.assertEquals(true,rhc.showProductUtilization);
      rhc.toggleShowProductUtilization();
      System.assertEquals(false,rhc.showProductUtilization);

      // log activity against the onboarding activity
      for (ReferenceHrgActivityWrapper rhaw : rhc.onboardingActivityList) {
         rhaw.activity.Type__c = ReferenceHRGActivityWrapper.ONSITE;
         rhaw.activity.Activity_Date__c = Date.today().addDays(7);
      }

      System.assertEquals((rhc.getOnboardingFields().size()/2),rhc.onboardingActivityList.size());

      // make sure there is no ongoing activity
      System.assertEquals(0,rhc.ongoingActivityList.size());
           
      // add ongoing activity
      rhc.nbrNewOngoingActivities = 2;
      System.assertEquals(null,rhc.addOngoingActivity());

      // should be two now
      System.assertEquals(2,rhc.ongoingActivityList.size());

      // log activity against the ongoing activity
      //rhc.ongoingActivityList[0].logActivity=true;
      rhc.ongoingActivityList[0].activity.Type__c = ReferenceHRGActivityWrapper.ONSITE;
      rhc.ongoingActivityList[0].activity.Activity_Type__c = 'TestType';
      rhc.ongoingActivityList[0].activity.Activity__c = 'TestActivity1';
      rhc.ongoingActivityList[0].activity.Activity_Date__c = Date.today().addDays(7);
      
      rhc.ongoingActivityList[1].activity.Type__c = ReferenceHRGActivityWrapper.ONSITE;
      rhc.ongoingActivityList[1].activity.Activity_Type__c = 'TestType';
      rhc.ongoingActivityList[1].activity.Activity__c = 'TestActivity2';
      rhc.ongoingActivityList[1].activity.Activity_Date__c = Date.today().addDays(7);
      
      // goto the next step
      rhc.setVerifyActivityStep();
      System.assertEquals('Verify Activity',rhc.currentStep);
      System.assertEquals((rhc.getOnboardingFields().size()/2)+2,rhc.nbrActivityToConfirm);
      
      // save and enter more activity
      System.assertEquals(null,rhc.saveAndNewActivity());
      
      // should be back at the main form.
      // make sure we're at the step to ask for task/event
      //System.assertEquals('Open Activity List',rhc.currentStep);

      // should be open activity
      System.assertEquals(true,rhc.hasOpenActivityList);
      
      // goto the verify step
      rhc.setVerifyActivityStep();
      System.assertEquals('Verify Activity',rhc.currentStep);

      // set the activity id we are selecting
      //System.currentPageReference().getParameters().put('activityId',rhc.openActivityList[0].activityId);
      //System.assertEquals(null,rhc.useExistingActivity());
      // should bring us to the next step.
      //System.assertEquals('Manage Open Activity',rhc.currentStep);

      // verify it's an event
      //System.assertEquals(true,rhc.selectedActivity.isEvent);
      // verify all of the HRG activity was selected
      //System.assertEquals((rhc.getOnboardingFields().size()/2)+2,rhc.selectedActivity.hrgActivity.size());
      
      // select the second HRG Activity to get the id and remove it.
      
      ReferenceHRGActivity__c hag = [Select Id, Name 
                                       from ReferenceHRGActivity__c 
                                      where Reference_HRG__r.Account__c = :acct1.Id
                                        and Type__c = :ReferenceHRGActivityWrapper.ONSITE
                                        and Activity_Type__c = 'TestType'
                                        and Activity__c = 'TestActivity2' ];

      System.currentPageReference().getParameters().put('activityKey',rhc.openActivityList[0].key);
      System.currentPageReference().getParameters().put('hrgActivityId',hag.Id);
      System.currentPageReference().getParameters().put('actionType','deleteFromVerify');
      
      rhc.selectHrgActivity();
      // verify it is no longer with this activity
      System.assertEquals((rhc.getOnboardingFields().size()/2)+1,rhc.openActivityList[0].hrgActivity.size());
      
      // set the meeting not held flag
      rhc.openActivityList[0].evnt.Meeting_Not_Held__c = true;
      
      // try to save - should fail because no reason
      rhc.saveAndNewActivity();
      // still be on the form.
      System.assertEquals('Verify Activity',rhc.currentStep);
      rhc.openActivityList[0].evnt.Reason_Canceled__c = 'They did not want to meet on this day';

      rhc.saveAndNewActivity();
      
      // activity should be deleted. No more open activity - should go to the enter activity form
      System.assertEquals('What Did You Do',rhc.currentStep);

      // all the activity should be deleted
      System.assertEquals(0,[select count() from ReferenceHRGActivity__c]);
      
      // enter activity as a task
      // log activity against the onboarding activity
      for (ReferenceHrgActivityWrapper rhaw : rhc.onboardingActivityList) {
         rhaw.activity.Type__c = 'Phone';
         rhaw.activity.Notes__c = 'This is a Note';
         rhaw.activity.Activity_Date__c = Date.today().addDays(7);
      }
      
      // goto the next step
      rhc.setVerifyActivityStep();
      System.assertEquals('Verify Activity',rhc.currentStep);
      System.assertEquals((rhc.getOnboardingFields().size()/2),rhc.nbrActivityToConfirm);
      
      // save and enter more activity
      System.assertEquals(null,rhc.saveAndNewActivity());

      // should be one open activity.
      System.assertEquals('What Did You Do',rhc.currentStep);
      System.assertEquals(true,rhc.hasOpenActivityList);
      
      System.assertEquals(true,rhc.pendingHrgActivityList.size() > 0);
      
      // go to enter activity
      //rhc.setAskForWhatTheyDidStep();
      
      // onboarding is still open - haven't closed the activity yet
      System.assertEquals(true,rhc.showOnboarding);

      // enter a new activity with the same date.
      // add ongoing activity
      rhc.nbrNewOngoingActivities = 1;
      System.assertEquals(null,rhc.addOngoingActivity());

      // should be one
      System.assertEquals(1,rhc.ongoingActivityList.size());
      System.assertEquals(true,rhc.hasOngoingActivityList);

      // log activity against the ongoing activity
      //rhc.ongoingActivityList[0].logActivity=true;
      rhc.ongoingActivityList[0].activity.Type__c = 'Phone';
      rhc.ongoingActivityList[0].activity.Activity_Type__c = 'TestType';
      rhc.ongoingActivityList[0].activity.Activity__c = 'TestActivity1';
      rhc.ongoingActivityList[0].activity.Activity_Date__c = Date.today().addDays(7);
      
      // goto the next step
      rhc.setVerifyActivityStep();
      System.assertEquals('Verify Activity',rhc.currentStep);
      // there will be 1 new activity
      System.assertEquals(1,rhc.nbrActivityToConfirm);
      
      ActivityWrapper aw = rhc.activityToSaveList[0];
      System.assertEquals(false,aw.isNew);
      Date awActivityDate = aw.activityDate;
      Integer compareResult = aw.compareTo(aw);
      System.assertEquals(-1,aw.compareTo(null));
      
      aw.removeActivityByRecId('123456');
      
      // all onboarding + the one new HRG activity on the task
      System.assertEquals((rhc.getOnboardingFields().size()/2)+1,aw.hrgActivity.size());
      System.assertEquals(true,aw.isTask);
      
      // add the complete date
      aw.tsk.Date_Activity_Completed__c = Date.today().addDays(7);
      
      
      // save and return to the account
      PageReference retUrl = rhc.saveAndReturnToAcct();
      // will have failed because client summary is required when completed
      System.assertEquals(null,retUrl);

      rhc.logActivitySelection = ReferenceHRGController.LOG_THIS;
      aw.tsk.Client_Summary__c = 'This is a summary';
      retUrl = rhc.saveAndReturnToAcct();
      //System.assertEquals(true,retUrl.getUrl().contains(acct1.Id));
      
      // verify all of the HRG activity is saved and completed
      System.assertEquals((rhc.getOnboardingFields().size()/2)+1,[Select count() from ReferenceHRGActivity__c where Account__c=:acct1.Id and Closed__c=true]);
      
      // reenter the form, make sure onboarding is showing as closed
      System.CurrentPageReference().getParameters().put('acctId',acct1.Id);
      rhc = new ReferenceHRGController();

      System.assertEquals(true,rhc.onboardingIsComplete);

      System.assertEquals(false,rhc.showOnboarding);
      
      // make sure all the onboarding fields have a value

      /*
      
      // close all of the onboarding tasks
      // log activity against the onboarding activity
      for (ReferenceHrgActivityWrapper rhaw : rhc.onboardingActivityList) {
         rhaw.completed = true;
      }

      // goto the next step
      rhc.setVerifyActivityStep();
      System.assertEquals('Verify Activity',rhc.currentStep);
      System.assertEquals(rhc.onboardingActivityList.size(),rhc.nbrActivityToConfirm);
      
      // close the event
      rhc.selectedActivity.evnt.Date_Activity_Completed__c = Date.today();
      
      // save and enter more activity
      System.assertEquals(null,rhc.saveAndNewActivity());
      
      // should not be an open activity
      System.assertEquals(false,rhc.hasOpenActivityList);
      
      // select a task
      rhc.selectedActivity.taskOrEvent = 'Task';
      rhc.selectedActivity.activityContactId = ctct1.Id;
      rhc.refHRG.DateofLastVisit__c = Date.today().addDays(14);
      rhc.setAskForWhatTheyDidStep();
      
      // verify the step
      System.assertEquals('What Did You Do',rhc.currentStep);
      // change values in product utilization
      List<Schema.FieldSetMember> productFields = rhc.getProductFields();
      rhc.refHRG.put(productFields[0].getFieldPath(),'Active');
      rhc.refHRG.put(productFields[1].getFieldPath(),'Active');
      
      // add an ongoing activity
      // there should be one activity from before
      System.assertEquals(1,rhc.ongoingActivityList.size());

      // add an ongoing activity
      rhc.nbrNewOngoingActivities = 1;
      System.assertEquals(null,rhc.addOngoingActivity());

      // should be one now
      System.assertEquals(2,rhc.ongoingActivityList.size());

      // close both activities
      //rhc.ongoingActivityList[0].logActivity=true;
      rhc.ongoingActivityList[0].activity.Type__c = 'Phone';
      rhc.ongoingActivityList[0].activity.Activity_Type__c = 'TestType';
      rhc.ongoingActivityList[0].activity.Activity__c = 'TestActivity1';
      rhc.ongoingActivityList[0].completed = true;

      
      // try to goto the next step - will fail because Type__c will be required for task
      rhc.setVerifyActivityStep();
      System.assertEquals('What Did You Do',rhc.currentStep);

      rhc.ongoingActivityList[0].activity.Type__c = 'Email';

      
      rhc.setVerifyActivityStep();
      System.assertEquals('Verify Activity',rhc.currentStep);

      // save and enter more activity
      System.assertEquals(null,rhc.saveAndNewActivity());
      
      // select the existing task - should be open still
      System.assertEquals(true,rhc.hasOpenActivityList);
      
      // set the activity id we are selecting
      System.currentPageReference().getParameters().put('activityId',rhc.openActivityList[0].activityId);
      System.assertEquals(null,rhc.useExistingActivity());
      // should bring us to the next step.
      System.assertEquals('What Did You Do',rhc.currentStep);
      // goto the next step
      rhc.setVerifyActivityStep();
      System.assertEquals('Verify Activity',rhc.currentStep);
      // close the task
      rhc.selectedActivity.tsk.Date_Activity_Completed__c = Date.today();
      // return to the account
      PageReference returnPr = rhc.saveAndReturnToAcct();
      System.assertEquals(true,returnPr.getUrl().contains(acct1.Id));
      */
   } // testStandardUsageNoRef
    
   /** Test standard usage without a Reference object already created. */
   static testMethod void testNoAccountOnEntry() {
      // create an account and contacts to start from
      Account acct1 = new Account(Name='Test Account');
      insert acct1;
      Contact ctct1 = new Contact(AccountId=acct1.Id,FirstName='Test',LastName='One',Email='test.one@testaccount.com');
      Contact ctct2 = new Contact(AccountId=acct1.Id,FirstName='Test',LastName='Two',Email='test.two@testaccount.com');
      Contact[] ctcts = new Contact[]{ctct1,ctct2};
      insert ctcts;
      
      Test.SetCurrentPageReference(Page.ReferenceHRG);

      ReferenceHRGController rhc = new ReferenceHRGController();
      System.assertEquals(true,rhc.promptForAccount);
      
      System.assertEquals(rhc.currentStep,'Prompt For Account');
      
      // set the account
      rhc.refHRG.Account__c = acct1.Id;
      
      rhc.setAccount();

      System.assertEquals(rhc.currentStep,'What Did You Do');
      
      // change the account health
      rhc.changeAccountHealth();
      System.assertEquals(rhc.currentStep,'Account Health');
      
      rhc.acct.Premier_Account_Health__c = 'Low';
      
      // try to save - no notes entered so should fail
      rhc.setAccountHealth();
      System.assertEquals(rhc.currentStep,'Account Health');

      rhc.acctHealthActivity.Notes__c = 'Because I felt like it';      
      rhc.setAccountHealth();
      System.assertEquals(rhc.currentStep,'What Did You Do');
      System.assertEquals(true, rhc.hasHealthUpdate);
      
      // verify the value was saved
      System.assertEquals(1,[select count() from Account where Id=:acct1.Id and Premier_Account_Health__c='Low']);	  

   } // testNoAccountOnEntry

       /** Test standard usage without a Reference object already created. */
   static testMethod void testStandardController() {
      // create an account and contacts to start from
      Account acct1 = new Account(Name='Test Account');
      apexPages.StandardController acct1StandardController = new apexPages.StandardController(acct1);
      insert acct1;
      Contact ctct1 = new Contact(AccountId=acct1.Id,FirstName='Test',LastName='One',Email='test.one@testaccount.com');
      Contact ctct2 = new Contact(AccountId=acct1.Id,FirstName='Test',LastName='Two',Email='test.two@testaccount.com');
      Contact[] ctcts = new Contact[]{ctct1,ctct2};
      insert ctcts;
      
      Test.SetCurrentPageReference(Page.ReferenceHRG);

      ReferenceHRGController rhc = new ReferenceHRGController(acct1StandardController);
      System.assertEquals(false,rhc.promptForAccount);
       
      System.assertEquals(rhc.currentStep,'What Did You Do');
      
      // change the account health
      rhc.changeAccountHealth();
      System.assertEquals(rhc.currentStep,'Account Health');
      
      rhc.acct.Premier_Account_Health__c = 'Low';
      
      // try to save - no notes entered so should fail
      rhc.setAccountHealth();
      System.assertEquals(rhc.currentStep,'Account Health');

      rhc.acctHealthActivity.Notes__c = 'Because I felt like it';      
      rhc.setAccountHealth();
      System.assertEquals(rhc.currentStep,'What Did You Do');
      
      // verify the value was saved
      System.assertEquals(1,[select count() from Account where Id=:acct1.Id and Premier_Account_Health__c='Low']);


   } // testSCNoAccountOnEntry
   
   static testMethod void testControlledOwnerhip() {
      Account a1 = new Account(Name='Account 1');   
      Account a2 = new Account(Name='Account 2');  
      Account a3 = new Account(Name='Account 3');
      Account[] accts = new Account[]{a1,a2,a3};
      insert accts;
      
      // create children of one of them
      Account a4 = new Account(Name='Account 4',ParentId=a1.Id);
      Account a5 = new Account(Name='Account 5',ParentId=a1.Id);
      Account[] accts2 = new Account[]{a4,a5};
      insert accts2;
      
      accts.addAll(accts2);
      
      // get a plan code from the set
      String planCode = null;
      for (String tempPlanCode : ReferenceHRGController.PREMIER_PLAN_CODE_SET) {
         planCode = tempPlanCode;
         break;
      }
      // create premier products for each one - this is a criteria for selection
      Asset[] assets = new Asset[]{};
      for (Account acct : accts) {
         Asset asst = new Asset(AccountId=acct.Id, Name='Test Asset', Start_Date__c=Date.today().addDays(-30), Product_Plan_Code__c=planCode);
         assets.add(asst);
      }
      insert assets;
      
      // add running user as account team member on all
      AccountTeamMember[] teamMembers = new AccountTeamMember[]{};
      for (Account acct: accts) {
        AccountTeamMember atm = new AccountTeamMember(AccountId=acct.Id, UserId=UserInfo.getUserId(), TeamMemberRole =ZipCheckOwner.AT_HRG);
        teamMembers.add(atm);
      } // for
      insert teamMembers;
     
      Test.SetCurrentPageReference(Page.ReferenceHRG);
      System.CurrentPageReference().getParameters().put('acctId',a1.Id);
      ReferenceHRGController rhc = new ReferenceHRGController();

      // add ongoing activity
      rhc.nbrNewOngoingActivities = 2;
      System.assertEquals(null,rhc.addOngoingActivity());

      // should be two now
      System.assertEquals(2,rhc.ongoingActivityList.size());

      // log activity against the ongoing activity
      //rhc.ongoingActivityList[0].logActivity=true;
      rhc.ongoingActivityList[0].activity.Type__c = ReferenceHRGActivityWrapper.ONSITE;
      rhc.ongoingActivityList[0].activity.Activity_Type__c = 'TestType';
      rhc.ongoingActivityList[0].activity.Activity__c = 'TestActivity1';
      rhc.ongoingActivityList[0].activity.Activity_Date__c = Date.today().addDays(7);
      
      rhc.ongoingActivityList[1].activity.Type__c = 'Phone';
      rhc.ongoingActivityList[1].activity.Activity_Type__c = 'TestType';
      rhc.ongoingActivityList[1].activity.Activity__c = 'TestActivity2';
      rhc.ongoingActivityList[1].activity.Activity_Date__c = Date.today().addDays(7);
      
      // goto the next step
      rhc.setVerifyActivityStep();
      System.assertEquals('Verify Activity',rhc.currentStep);

      // verify there are 3 options - because we're on the parent of a controlled ownership
      System.assertEquals(3,rhc.logActivityOptions.size());
      
      // complete both of the activities - task should always be first
      ActivityWrapper awEvent = rhc.activityToSaveList[1];
      ActivityWrapper awTask = rhc.activityToSaveList[0];

      System.assertEquals(true,awEvent.isEvent);
      System.assertEquals(true,awTask.isTask);
      
      // add the complete date
      awEvent.evnt.Date_Activity_Completed__c = Date.today().addDays(7);
      awEvent.evnt.Client_Summary__c = 'This is a summary';
      awTask.tsk.Date_Activity_Completed__c = Date.today().addDays(7);
      awTask.tsk.Client_Summary__c = 'This is a summary';
      
      rhc.logActivitySelection = ReferenceHRGController.LOG_CLIENTS;
      // save and return to the account
      PageReference retUrl = rhc.saveAndReturnToAcct();

      // 1 task, 1 event, 2 hrg activities should be created
      System.assertEquals(1,[select count() from Task where createdById=:UserInfo.getUserId()]);
      System.assertEquals(1,[select count() from Event where createdById=:UserInfo.getUserId()]);
      System.assertEquals(2,[select count() from ReferenceHRGActivity__c where createdById=:UserInfo.getUserId()]);

      // should be brought to the screen for additional clients
      System.assertEquals('Additional Logging',rhc.currentStep);
      System.assertEquals(4,rhc.extraAcctsList.size());
      // select all of them
      rhc.selectAllOption = true;
      rhc.changeSelectAllOption();
      
      rhc.saveAdditionalActivity();
      // 5 tasks, 5 event, 10 hrg activities should be created
      System.assertEquals(5,[select count() from Task where createdById=:UserInfo.getUserId()]);
      System.assertEquals(5,[select count() from Event where createdById=:UserInfo.getUserId()]);
      System.assertEquals(10,[select count() from ReferenceHRGActivity__c where createdById=:UserInfo.getUserId()]);
     
   } // testControlledOwnerhip
   

} // class ReferenceHRGControllerTest