force-app/main/default/objects/Account/fields/AssignedToInboundNSR__c.field-meta.xml
<CustomField>
    <fullName>AssignedToInboundNSR__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this assigned to an inbound NSR?</inlineHelpText>
    <label>Assigned To Inbound NSR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/AssignedToOutboundNSR__c.field-meta.xml
<CustomField>
    <fullName>AssignedToOutboundNSR__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this assigned to an outbound NSR?</inlineHelpText>
    <label>Assigned To Outbound NSR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AssignedToInboundNSR__c.field-meta.xml
<CustomField>
    <fullName>AssignedToInboundNSR__c</fullName>
    <formula>Account.AssignedToInboundNSR__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned To Inbound NSR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AssignedToOutboundNSR__c.field-meta.xml
<CustomField>
    <fullName>AssignedToOutboundNSR__c</fullName>
    <formula>Account.AssignedToOutboundNSR__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned To Outbound NSR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LifeOfLeadSettings__c/LifeOfLeadSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configurable time periods for each phase of the &quot;life of a lead&quot; for NSS.</description>
    <label>LifeOfLeadSettings</label>
</CustomObject>

force-app/main/default/objects/LifeOfLeadSettings__c/fields/NSS_Source__c.field-meta.xml
<CustomField>
    <fullName>NSS_Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Inbound vs Outbound (or blank for any).</inlineHelpText>
    <label>NSS Source</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LifeOfLeadSettings__c/fields/NSS_Team__c.field-meta.xml
<CustomField>
    <fullName>NSS_Team__c</fullName>
    <description>The NSS Team in the Prospect Ownership History record.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The NSS Team in the Prospect Ownership History record.</inlineHelpText>
    <label>NSS Team</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LifeOfLeadSettings__c/fields/NumComDays__c.field-meta.xml
<CustomField>
    <fullName>NumComDays__c</fullName>
    <inlineHelpText>If this stage triggers commissions, the number of days for the commission period.</inlineHelpText>
    <label>Comm Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSS_Source__c.field-meta.xml
<CustomField>
    <fullName>NSS_Source__c</fullName>
    <description>Use to tell the FSR if the Opportunity was created by NSR. Inbound NSR leads are considered to be the hottest.</description>
    <inlineHelpText>Use to tell the FSR if the Opportunity was created by NSR. Inbound NSR leads are considered to be the hottest. The value of this field is set by the custom conversion process and cannot be modified by users.</inlineHelpText>
    <label>NSS Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Inbound-BeneTrac</fullName>
            </value>
            <value>
                <fullName>Inbound-Flock</fullName>
            </value>
            <value>
                <fullName>Inbound-Oasis</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Outbound-Oasis</fullName>
            </value>
            <value>
                <fullName>Telereach</fullName>
            </value>
            <value>
                <fullName>INB-SOAR</fullName>
            </value>
            <value>
                <fullName>SurePayroll-Ecomm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/Prospect_Ownership__c.object-meta.xml
<CustomObject>
    <description>This object is used to establish an NSR&apos;s association with a Prospect-Client record to indicate ownership and commission eligibility during the Lead/ Prospect life cycle.</description>
    <label>Prospect Ownership</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Prospect Ownership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospect Ownership</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prospect_Ownership__c/fields/CommissionEnd__c.field-meta.xml
<CustomField>
    <fullName>CommissionEnd__c</fullName>
    <description>The date at which the opportunity associated with this record is no longer commissionable.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date at which the opportunity associated with this record is no longer commissionable.</inlineHelpText>
    <label>Commission End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/CommissionStart__c.field-meta.xml
<CustomField>
    <fullName>CommissionStart__c</fullName>
    <description>The date the commissionable period begins for this ownership record.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date the commissionable period begins for this ownership record.</inlineHelpText>
    <label>Commission Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>The date the current phase ended. Set by scheduled batch process when the current phase expires.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date the current phase ended. Set by scheduled batch process when the current phase expires.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/LastVerified__c.field-meta.xml
<CustomField>
    <fullName>LastVerified__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Date and Time the ownership was last verified.</inlineHelpText>
    <label>Last Verified</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/LockoutEnd__c.field-meta.xml
<CustomField>
    <fullName>LockoutEnd__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The end date of the lockout stage</inlineHelpText>
    <label>Lockout End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/LockoutStart__c.field-meta.xml
<CustomField>
    <fullName>LockoutStart__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The start date of the lockout stage</inlineHelpText>
    <label>Lockout Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/NFI_WashEnd__c.field-meta.xml
<CustomField>
    <fullName>NFI_WashEnd__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The End Date of the No Interest Period</inlineHelpText>
    <label>NFI/Wash End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/NFI_WashStart__c.field-meta.xml
<CustomField>
    <fullName>NFI_WashStart__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Start Date of the No Interest Period</inlineHelpText>
    <label>NFI/Wash Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/NSR_Name__c.field-meta.xml
<CustomField>
    <fullName>NSR_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The name of the NSR who has established &quot;ownership&quot; of the Prospect record for a particular product group.</description>
    <inlineHelpText>The name of the NSR who has established &quot;ownership&quot; of the Prospect record for a particular product group.</inlineHelpText>
    <label>NSR Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Prospect_Ownership</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/NSRSupervisor__c.field-meta.xml
<CustomField>
    <fullName>NSRSupervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The NSR Supervisor at the time of the Opportunity creation</inlineHelpText>
    <label>NSR Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProspectOwnershipSupervisor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/NSS_Source__c.field-meta.xml
<CustomField>
    <fullName>NSS_Source__c</fullName>
    <inlineHelpText>Inbound vs Outbound NSR</inlineHelpText>
    <label>NSS Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/NSS_Team__c.field-meta.xml
<CustomField>
    <fullName>NSS_Team__c</fullName>
    <description>The product group for which this ownership has been established</description>
    <inlineHelpText>The product group for which this ownership has been established</inlineHelpText>
    <label>NSS Team</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HNB</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>PAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/Ownership_Status__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Status__c</fullName>
    <description>The ownership status within the NSS process</description>
    <inlineHelpText>The ownership status within the NSS process</inlineHelpText>
    <label>Ownership Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospecting</fullName>
            </value>
            <value>
                <fullName>Lockout</fullName>
            </value>
            <value>
                <fullName>Workable</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Wash</fullName>
            </value>
            <value>
                <fullName>Commission Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/ProspectingEnd__c.field-meta.xml
<CustomField>
    <fullName>ProspectingEnd__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The end date of the prospecting stage</inlineHelpText>
    <label>Prospecting End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/ProspectingStart__c.field-meta.xml
<CustomField>
    <fullName>ProspectingStart__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The start date of the prospecting stage</inlineHelpText>
    <label>Prospecting Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>The date the current phase began. Used by scheduled batch process to determine when the current phase expires.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date the current phase began. Used by scheduled batch process to determine when the current phase expires.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/WorkableEnd__c.field-meta.xml
<CustomField>
    <fullName>WorkableEnd__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The end date of the workable stage</inlineHelpText>
    <label>Workable End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/WorkableStart__c.field-meta.xml
<CustomField>
    <fullName>WorkableStart__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The start date of the workable stage</inlineHelpText>
    <label>Workable Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/NSS_Team__c.field-meta.xml
<CustomField>
    <fullName>NSS_Team__c</fullName>
    <inlineHelpText>If this is an NSR, which NSS team are they on?</inlineHelpText>
    <label>NSS Team</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PAY</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>VS PAY</fullName>
            </value>
            <value>
                <fullName>HNB</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>Oasis SDR</fullName>
            </value>
            <value>
                <fullName>Inbound-Oasis</fullName>
            </value>
            <value>
                <fullName>Outbound-Oasis</fullName>
            </value>
            <value>
                <fullName>MMS SDR</fullName>
            </value>
            <value>
                <fullName>Virtual SMB</fullName>
            </value>
            <value>
                <fullName>SMB New Business</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProspectOwnershipTest.cls
/* 
 * Test Methods for the ProspectOwnershipMethods class
 *
 * History
 * -------
 * 10/11/2013 Dan Carmen   Created
   01/08/2016 Dan Carmen      Set the supervisor when the opportunity is set

 *
 */
@isTest
public class ProspectOwnershipTest {

   public static Contact ctct = null;
   public static Account acct = null;
   public static Map<Id,List<Prospect_Ownership__c>> acctOwnerMap = null;

   public static void setupAcctCtct() {
      // load the settings
      List<LifeOfLeadSettings__c> ls = Test.loadData(LifeOfLeadSettings__c.sObjectType, 'lifeOfLeadSettings');
      acct = new Account(Name='Test Acct');
      ZipCheckOwner.SKIP_TRIGGERS=true;
      insert acct;
      ContactMethods.CONTACT_BEFORE_TRIGGER_EXECUTING=true;
      ContactMethods.CONTACT_AFTER_TRIGGER_EXECUTING=true;
      ctct = new Contact(AccountId=acct.Id, FirstName='Sally',LastName='Test');
      insert ctct;
      // reselect the account
      acct = ReferralQueries.selectAcct(acct.Id);
   } // setupAcctCtct

   private static void runProcess(String stageName, Account p_acct, Contact p_ctct, Id ctctId, User usr, String nssTeam, String nssSource) {   
      ProspectOwnershipMethods.initializeSaveObjects();
      ProspectOwnershipMethods.checkAccountOwnership(stageName, true, p_acct, p_ctct, ctctId, (AccountTeamMember[])null, usr, null, nssTeam, nssSource, (acctOwnerMap != null ? acctOwnerMap.get(p_acct.Id) : null));
      ProspectOwnershipMethods.checkForSaves();
      // reselect the account
      acct = ReferralQueries.selectAcct(acct.Id);
      // reselect ownership records
      acctOwnerMap = ProspectOwnershipMethods.getAcctOwnerMap(new Set<Id>{acct.Id}, false, null,null);
   } // runProcess
   
   // test inbound prospecting with existing outbound not interested/wash.
   // test inbound lockout with existing outbound workable that was transferred (no commission dates).

   // Verify the account attributes.
   public static void verifyAccount(String testName, Account p_acct, Boolean outbound, Boolean inbound, Integer nbrATM, Id atmUserId) {
      System.debug('verifyAccount testName='+testName);
      // verify the account fields
      System.assertEquals(outbound,p_acct.AssignedToOutboundNSR__c);
      System.assertEquals(inbound,p_acct.AssignedToInboundNSR__c);
      // should be 1 account team member
      System.assertEquals(nbrATM,p_acct.AccountTeamMembers.size());
      if (atmUserId != null) {
         System.assertEquals(atmUserId,p_acct.AccountTeamMembers[0].UserId);
      }

   } // verifyAccount

   // Verify the Prospect_Ownership__c attributes.
   public static void checkOwnership(String testName, Prospect_Ownership__c po, String nssTeam, String nssSource, String status, Boolean hasProspectingStart
                                       ,Boolean hasLockoutStart, Boolean hasWorkableStart, Boolean hasCommission, Boolean hasNFI, Boolean hasEndDate
                                       ,Id nsrId) {
      checkOwnership(testName, po, nssTeam, nssSource, status, hasProspectingStart
                                       ,hasLockoutStart, hasWorkableStart, hasCommission, hasNFI, hasEndDate, 0 ,nsrId);
  } // checkOwnership

   public static void checkOwnership(String testName, Prospect_Ownership__c po, String nssTeam, String nssSource, String status, Boolean hasProspectingStart
                                       ,Boolean hasLockoutStart, Boolean hasWorkableStart, Boolean hasCommission, Boolean hasNFI, Boolean hasEndDate
                                       ,Integer addToCommEnd
                                       ,Id nsrId) {
      
      // to account for the status not existing in the LifeOfLeadSettings - so we can get the correct number of commission days
      String originalStatus = po.Ownership_Status__c;
      System.debug('checkOwnership testName='+testName+' originalStatus='+originalStatus);
      if (hasCommission) {
         // to get the commission dates
         po.Ownership_Status__c = ProspectOwnershipMethods.STAGE_LOCKOUT;
      }
      //if (po.Ownership_Status__c == ProspectOwnershipMethods.STAGE_COMMISSION) {
      //   po.Ownership_Status__c = ProspectOwnershipMethods.STAGE_LOCKOUT;
      //} else if (hasEndDate && hasLockoutStart && hasCommission && po.Ownership_Status__c == ProspectOwnershipMethods.STAGE_EXPIRED) {
      //   po.Ownership_Status__c = ProspectOwnershipMethods.STAGE_LOCKOUT;
      //}
      LifeOfLeadSettings__c lols = ProspectOwnershipMethods.getSetting(po);
      po.Ownership_Status__c = originalStatus;
      System.debug('checkOwnership Ownership_Status__c='+po.Ownership_Status__c);
      
      System.assertEquals(nssTeam,po.NSS_Team__c);
      System.assertEquals(nssSource,po.NSS_Source__c);
      System.assertEquals(status,po.Ownership_Status__c);
      System.assertEquals(true,(po.StartDate__c == Date.today() || po.StartDate__c == Date.today().addDays(-2)));
      System.assertEquals((hasEndDate ? Date.today() : null), po.EndDate__c);
      System.assertEquals((hasProspectingStart ? Date.today() : null), po.ProspectingStart__c);
      System.assertEquals((hasProspectingStart && (hasEndDate || hasLockoutStart) ? Date.today() : null),po.ProspectingEnd__c);
      System.assertEquals((hasLockoutStart ? Date.today() : null), po.LockoutStart__c);
      System.assertEquals((hasLockoutStart && (hasEndDate || hasWorkableStart) ? Date.today() : null),po.LockoutEnd__c);
      System.assertEquals((hasWorkableStart ? Date.today() : null), po.WorkableStart__c);
      System.assertEquals((hasWorkableStart && hasEndDate ? Date.today() : null), po.WorkableEnd__c);
      System.assertEquals((hasCommission ? Date.today() : null), po.CommissionStart__c);
      System.assertEquals((hasCommission ? Date.today().addDays(lols.NumComDays__c.intValue()+addToCommEnd) : null), po.CommissionEnd__c);
      System.assertEquals((hasNFI ? Date.today() : null), po.NFI_WashStart__c);
      System.assertEquals((hasNFI && hasEndDate ? Date.today() : null), po.NFI_WashEnd__c);
      System.assertEquals(nsrId, po.NSR_Name__c);

   } // checkOwnership
   
/*
   // Test inbound prospecting -> lockout -> expired 
   static testMethod void testInboundLifeOfLead() {
      setupAcctCtct();
      
      User[] inboundNSRs = ProspectOwnershipMethodsTest.getInboundNSRs(1);
      runProcess(ProspectOwnershipMethods.STAGE_PROSPECTING, acct, null, ctct.Id, inboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND);
      // verify 1 ownership record
      List<Prospect_Ownership__c> ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      Prospect_Ownership__c po = ownerList[0];
      checkOwnership('testInboundLifeOfLead check1', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND, ProspectOwnershipMethods.STAGE_PROSPECTING
                                       ,true  // prospecting
                                       ,false // lockout
                                       ,false // workable
                                       ,false // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,inboundNSRs[0].Id);

      // verify the account fields
      verifyAccount('testInboundLifeOfLead checkAccount1', acct, false, true, 1, inboundNSRs[0].Id);

      // change to Lockout
      runProcess(ProspectOwnershipMethods.STAGE_LOCKOUT, acct, null, ctct.Id, inboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND);

      // verify 1 ownership record
      ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      po = ownerList[0];
      checkOwnership('testInboundLifeOfLead check2', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND, ProspectOwnershipMethods.STAGE_LOCKOUT
                                       ,true  // prospecting
                                       ,true // lockout
                                       ,false // workable
                                       ,true // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,inboundNSRs[0].Id);
      // verify the account fields
      verifyAccount('testInboundLifeOfLead checkAccount2', acct, false, true, 0, null);
   } // testInboundLifeOfLead
   
   // Test outbound prospecting -> lockout -> workable 
   static testMethod void testOutboundLifeOfLead() {
      setupAcctCtct();
      
      User[] outboundNSRs = ProspectOwnershipMethodsTest.getOutboundNSRs(1);
      runProcess(ProspectOwnershipMethods.STAGE_PROSPECTING, acct, null, ctct.Id, outboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND);

      // verify 1 ownership record
      List<Prospect_Ownership__c> ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      Prospect_Ownership__c po = ownerList[0];
      checkOwnership('testOutboundLifeOfLead check1', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND, ProspectOwnershipMethods.STAGE_PROSPECTING
                                       ,true  // prospecting
                                       ,false // lockout
                                       ,false // workable
                                       ,false // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,outboundNSRs[0].Id);
      // verify the account fields
      verifyAccount('testOutboundLifeOfLead checkAccount1', acct, true, false, 1, outboundNSRs[0].Id);

      // change to Lockout
      runProcess(ProspectOwnershipMethods.STAGE_LOCKOUT, acct, null, ctct.Id, outboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND);

      // verify 1 ownership record
      ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      po = ownerList[0];
      checkOwnership('testOutboundLifeOfLead check2', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND, ProspectOwnershipMethods.STAGE_LOCKOUT
                                       ,true  // prospecting
                                       ,true // lockout
                                       ,false // workable
                                       ,true // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,outboundNSRs[0].Id);
      // verify the account fields
      verifyAccount('testOutboundLifeOfLead checkAccount2', acct, true, false, 0, null);

   } // testOutboundLifeOfLead
   
   // Test outbound prospecting with existing inbound prospecting. 
   static testMethod void testOutProsInboundPros() {
      setupAcctCtct();
      
      User[] inboundNSRs = ProspectOwnershipMethodsTest.getInboundNSRs(1);
      runProcess(ProspectOwnershipMethods.STAGE_PROSPECTING, acct, null, ctct.Id, inboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND);

      // verify 1 ownership record
      List<Prospect_Ownership__c> ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      Prospect_Ownership__c po = ownerList[0];
      checkOwnership('testOutProsInboundPros check1', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND, ProspectOwnershipMethods.STAGE_PROSPECTING
                                       ,true  // prospecting
                                       ,false // lockout
                                       ,false // workable
                                       ,false // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,inboundNSRs[0].Id);
      // verify the account fields
      verifyAccount('testOutProsInboundPros checkAccount1', acct, false, true, 1, inboundNSRs[0].Id);

      // try to create an outbound prospecting record
      User[] outboundNSRs = ProspectOwnershipMethodsTest.getOutboundNSRs(1);
      runProcess(ProspectOwnershipMethods.STAGE_PROSPECTING, acct, null, ctct.Id, outboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND);

      // should still be just one inbound ownership record
      ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      po = ownerList[0];
      checkOwnership('testOutProsInboundPros check2', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND, ProspectOwnershipMethods.STAGE_PROSPECTING
                                       ,true  // prospecting
                                       ,false // lockout
                                       ,false // workable
                                       ,false // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,inboundNSRs[0].Id);
      // verify the account fields
      verifyAccount('testOutProsInboundPros checkAccount2', acct, false, true, 1, inboundNSRs[0].Id);

   } // testOutProsInboundPros
   
   
   // Test outbound prospecting with existing inbound lockout.
   static testMethod void testOutProsInboundLockout() {
      setupAcctCtct();
      
      User[] inboundNSRs = ProspectOwnershipMethodsTest.getInboundNSRs(1);
      runProcess(ProspectOwnershipMethods.STAGE_LOCKOUT, acct, null, ctct.Id, inboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND);

      // verify 1 ownership record
      List<Prospect_Ownership__c> ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      Prospect_Ownership__c po = ownerList[0];
      checkOwnership('testOutProsInboundLockout check1', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND, ProspectOwnershipMethods.STAGE_LOCKOUT
                                       ,false  // prospecting
                                       ,true // lockout
                                       ,false // workable
                                       ,true // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,inboundNSRs[0].Id);
      // verify the account fields
      verifyAccount('testOutProsInboundLockout checkAccount1', acct, false, true, 0, null);

      // try to create an outbound prospecting record
      User[] outboundNSRs = ProspectOwnershipMethodsTest.getOutboundNSRs(1);
      runProcess(ProspectOwnershipMethods.STAGE_PROSPECTING, acct, null, ctct.Id, outboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND);

      // should still be just one inbound ownership record
      ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      po = ownerList[0];
      checkOwnership('testOutProsInboundLockout check2', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND, ProspectOwnershipMethods.STAGE_LOCKOUT
                                       ,false  // prospecting
                                       ,true // lockout
                                       ,false // workable
                                       ,true // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,inboundNSRs[0].Id);
      // verify the account fields
      verifyAccount('testOutProsInboundLockout checkAccount2', acct, false, true, 0, null);

   } // testOutProsInboundLockout
   
   // Test outbound lockout with existing inbound prospecting. 
   static testMethod void testOutLockoutInboundProspect() {
      setupAcctCtct();
      
      User[] inboundNSRs = ProspectOwnershipMethodsTest.getInboundNSRs(1);
      runProcess(ProspectOwnershipMethods.STAGE_PROSPECTING, acct, null, ctct.Id, inboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND);

      // verify 1 ownership record
      List<Prospect_Ownership__c> ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      Prospect_Ownership__c po = ownerList[0];
      checkOwnership('testOutLockoutInboundProspect check1', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND, ProspectOwnershipMethods.STAGE_PROSPECTING
                                       ,true  // prospecting
                                       ,false // lockout
                                       ,false // workable
                                       ,false // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,inboundNSRs[0].Id);

      // verify the account fields
      verifyAccount('testOutLockoutInboundProspect checkAccount1', acct, false, true, 1, inboundNSRs[0].Id);

      // try to create an outbound prospecting record
      User[] outboundNSRs = ProspectOwnershipMethodsTest.getOutboundNSRs(1);
      runProcess(ProspectOwnershipMethods.STAGE_LOCKOUT, acct, null, ctct.Id, outboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND);

      // should still be just one inbound ownership record
      ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      po = ownerList[0];
      checkOwnership('testOutLockoutInboundProspect check1', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND, ProspectOwnershipMethods.STAGE_PROSPECTING
                                       ,true  // prospecting
                                       ,false // lockout
                                       ,false // workable
                                       ,false // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,inboundNSRs[0].Id);

      // verify the account fields
      verifyAccount('testOutLockoutInboundProspect checkAccount2', acct, false, true, 1, inboundNSRs[0].Id);

   } // testOutLockoutInboundProspect
   
   // Test outbound lockout with existing inbound lockout.
   static testMethod void testOutLockoutInboundLockout() {
   	setupAcctCtct();

      User[] inboundNSRs = ProspectOwnershipMethodsTest.getInboundNSRs(1);
      runProcess(ProspectOwnershipMethods.STAGE_LOCKOUT, acct, null, ctct.Id, inboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND);

      // verify 1 ownership record
      List<Prospect_Ownership__c> ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      Prospect_Ownership__c po = ownerList[0];
      checkOwnership('testInProsOutPros check1', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND, ProspectOwnershipMethods.STAGE_LOCKOUT
                                       ,false  // prospecting
                                       ,true // lockout
                                       ,false // workable
                                       ,true // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,inboundNSRs[0].Id);

      // verify the account fields
      verifyAccount('testOutLockoutInboundLockout checkAccount1', acct, false, true, 0, null);

      // try to create an outbound prospecting record
      User[] outboundNSRs = ProspectOwnershipMethodsTest.getOutboundNSRs(1);
      runProcess(ProspectOwnershipMethods.STAGE_LOCKOUT, acct, null, ctct.Id, outboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND);

      // should still be just one inbound ownership record
      ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      po = ownerList[0];
      checkOwnership('testInProsOutPros check2', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND, ProspectOwnershipMethods.STAGE_LOCKOUT
                                       ,false  // prospecting
                                       ,true // lockout
                                       ,false // workable
                                       ,true // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,inboundNSRs[0].Id);

      // verify the account fields
      verifyAccount('testOutLockoutInboundLockout checkAccount2', acct, false, true, 0, null);

   } // testOutLockoutInboundLockout
*/

   // test inbound prospecting with existing outbound prospecting.
   static testMethod void testInProsOutPros() {
   	setupAcctCtct();
      
      User[] outboundNSRs = ProspectOwnershipMethodsTest.getOutboundNSRs(1);
      runProcess(ProspectOwnershipMethods.STAGE_PROSPECTING, acct, null, ctct.Id, outboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND);

      // verify 1 ownership record
      List<Prospect_Ownership__c> ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      Prospect_Ownership__c po = ownerList[0];
      checkOwnership('testInProsOutPros check1', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND, ProspectOwnershipMethods.STAGE_PROSPECTING
                                       ,true  // prospecting
                                       ,false // lockout
                                       ,false // workable
                                       ,false // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,outboundNSRs[0].Id);
                                       
      po.StartDate__c = Date.today().addDays(-2);
      update po;


      verifyAccount('testInProsOutPros checkAccount1', acct, true, false, 1, outboundNSRs[0].Id);

      // create an inbound prospecting record
      User[] inboundNSRs = ProspectOwnershipMethodsTest.getInboundNSRs(1);
      runProcess(ProspectOwnershipMethods.STAGE_PROSPECTING, acct, null, ctct.Id, inboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND);

      // should be 2 ownership records
      ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(2,ownerList.size());
      // verify the records
      Boolean inboundFound = false;
      Boolean outboundFound = false;
      
      for (Prospect_Ownership__c checkPo : ownerList) {
      	System.debug('testInProsOutPros checkPo='+checkPo);
      	if (checkPo.NSS_Source__c == ProspectOwnershipMethods.NSS_INBOUND) {
            System.debug('testInProsOutPros inboundFound');
            inboundFound = true;
            checkOwnership('testInProsOutPros checkForInbound', checkPo, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND, ProspectOwnershipMethods.STAGE_PROSPECTING
                                       ,true  // prospecting
                                       ,false // lockout
                                       ,false // workable
                                       ,false // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,inboundNSRs[0].Id);
      	} else if (checkPo.NSS_Source__c == ProspectOwnershipMethods.NSS_OUTBOUND) {
            System.debug('testInProsOutPros outboundFound');
            outboundFound = true;
            checkOwnership('testInProsOutPros checkForOutbound', checkPo, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND, ProspectOwnershipMethods.STAGE_EXPIRED
                                       ,true  // prospecting
                                       ,false // lockout
                                       ,false // workable
                                       ,false // commission
                                       ,false // nfi/wash
                                       ,true // end date
                                       ,outboundNSRs[0].Id);
      	}
      } // for (Prospect_Ownership__c checkPo
      
      // verify inbound and outbound are found
      System.assertEquals(true,inboundFound);
      System.assertEquals(true,outboundFound);

      verifyAccount('testInProsOutPros checkAccount2', acct, false, true, 1, inboundNSRs[0].Id);


   } // testOutLockoutInboundLockout
/*
   // test inbound prospecting with existing outbound lockout - then move inbound to lockout
   static testMethod void testInProsOutLockout() {
      setupAcctCtct();
      
      User[] outboundNSRs = ProspectOwnershipMethodsTest.getOutboundNSRs(1);
      runProcess(ProspectOwnershipMethods.STAGE_LOCKOUT, acct, null, ctct.Id, outboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND);

      // verify 1 ownership record
      List<Prospect_Ownership__c> ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      Prospect_Ownership__c po = ownerList[0];
      checkOwnership('testInProsOutLockout checkoutboundOwnership', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND, ProspectOwnershipMethods.STAGE_LOCKOUT
                                       ,false  // prospecting
                                       ,true // lockout
                                       ,false // workable
                                       ,true // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,outboundNSRs[0].Id);


      verifyAccount('testInProsOutPros checkAccount1', acct, true, false, 0, null);

      // create an inbound prospecting record
      User[] inboundNSRs = ProspectOwnershipMethodsTest.getInboundNSRs(1);
      runProcess(ProspectOwnershipMethods.STAGE_PROSPECTING, acct, null, ctct.Id, inboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND);

      // should still be 2 ownership records
      ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(2,ownerList.size());
      // verify the records
      Boolean inboundFound = false;
      Boolean outboundFound = false;
      
      for (Prospect_Ownership__c checkPo : ownerList) {
         System.debug('testInProsOutLockout checkPo='+checkPo);
         if (checkPo.NSS_Source__c == ProspectOwnershipMethods.NSS_INBOUND) {
            System.debug('testInProsOutLockout inboundFound');
            inboundFound = true;
            checkOwnership('testInProsOutLockout checkForInbound', checkPo, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND, ProspectOwnershipMethods.STAGE_PROSPECTING
                                       ,true  // prospecting
                                       ,false // lockout
                                       ,false // workable
                                       ,false // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,inboundNSRs[0].Id);
         } else if (checkPo.NSS_Source__c == ProspectOwnershipMethods.NSS_OUTBOUND) {
            System.debug('testInProsOutLockout outboundFound');
            outboundFound = true;
            checkOwnership('testInProsOutLockout checkForOutbound', checkPo, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND, ProspectOwnershipMethods.STAGE_LOCKOUT
                                       ,false  // prospecting
                                       ,true // lockout
                                       ,false // workable
                                       ,true // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,outboundNSRs[0].Id);
         }
      } // for (Prospect_Ownership__c checkPo
      
      // verify inbound and outbound are found
      System.assertEquals(true,inboundFound);
      System.assertEquals(true,outboundFound);

      // should have both inbound and outbound ownership here
      verifyAccount('testInProsOutLockout checkAccount2', acct, true, true, 1, inboundNSRs[0].Id);
      
      // change the inbound to lockout - should end date inbound and leave outbound
      runProcess(ProspectOwnershipMethods.STAGE_LOCKOUT, acct, null, ctct.Id, inboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND);

      // should still be 2 ownership records
      ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(2,ownerList.size());
      // verify the records
      inboundFound = false;
      outboundFound = false;

      for (Prospect_Ownership__c checkPo : ownerList) {
         System.debug('testInProsOutLockout checkPo='+checkPo);
         if (checkPo.NSS_Source__c == ProspectOwnershipMethods.NSS_INBOUND) {
            System.debug('testInProsOutLockout inboundFound');
            inboundFound = true;
            checkOwnership('testInProsOutLockout checkForInbound2', checkPo, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND, ProspectOwnershipMethods.STAGE_COMMISSION
                                       ,true  // prospecting
                                       ,true // lockout
                                       ,false // workable
                                       ,true // commission
                                       ,false // nfi/wash
                                       ,true // end date
                                       ,inboundNSRs[0].Id);
         } else if (checkPo.NSS_Source__c == ProspectOwnershipMethods.NSS_OUTBOUND) {
            System.debug('testInProsOutLockout outboundFound');
            outboundFound = true;
            checkOwnership('testInProsOutLockout checkForOutbound2', checkPo, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND, ProspectOwnershipMethods.STAGE_LOCKOUT
                                       ,false  // prospecting
                                       ,true // lockout
                                       ,false // workable
                                       ,true // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,outboundNSRs[0].Id);
         }
      } // for (Prospect_Ownership__c checkPo
      
      // verify inbound and outbound are found
      System.assertEquals(true,inboundFound);
      System.assertEquals(true,outboundFound);

      // should have both inbound and outbound ownership here
      verifyAccount('testInProsOutLockout checkAccount2', acct, true, false, 0, null);

   } // testInProsOutLockout

   // test inbound prospecting with existing outbound workable - then move inbound to lockout
   static testMethod void testInLockOutWorkable() {
      setupAcctCtct();
      
      User[] outboundNSRs = ProspectOwnershipMethodsTest.getOutboundNSRs(1);
      // create a lockout record to get the commission period set
      runProcess(ProspectOwnershipMethods.STAGE_LOCKOUT, acct, null, ctct.Id, outboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND);
      // verify 1 ownership record
      List<Prospect_Ownership__c> ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      Prospect_Ownership__c po = ownerList[0];
      // change the record to workable
      ProspectOwnershipMethods.initializeSaveObjects();
      ProspectOwnershipMethods.setStageExitInfo(po, acct, ctct, null, null, false, false, false);
      po.Ownership_Status__c = ProspectOwnershipMethods.STAGE_WORKABLE;
      ProspectOwnershipMethods.setStageEntryInfo(po, acct, ctct, null, null, false, false);
      ProspectOwnershipMethods.checkForSaves();
      
      // reselct the acctOwnerMap to have latest values
      acctOwnerMap = ProspectOwnershipMethods.getAcctOwnerMap(new Set<Id>{acct.Id}, false, null,null);
      ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      po = ownerList[0];
      checkOwnership('testInLockOutWorkable check1', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND, ProspectOwnershipMethods.STAGE_WORKABLE
                                       ,false  // prospecting
                                       ,true // lockout
                                       ,true // workable
                                       ,true // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,outboundNSRs[0].Id);


      verifyAccount('testInLockOutWorkable checkAccount1', acct, true, false, 0, null);

      
      // create an inbound prospecting record
      User[] inboundNSRs = ProspectOwnershipMethodsTest.getInboundNSRs(1);
      
      runProcess(ProspectOwnershipMethods.STAGE_PROSPECTING, acct, null, ctct.Id, inboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND);
      // should be 2 ownership records
      ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(2,ownerList.size());
      // verify the records
      Boolean inboundFound = false;
      Boolean outboundFound = false;
      
      for (Prospect_Ownership__c checkPo : ownerList) {
         System.debug('testInLockOutWorkable checkPo='+checkPo);
         if (checkPo.NSS_Source__c == ProspectOwnershipMethods.NSS_INBOUND) {
            System.debug('testInLockOutWorkable inboundFound');
            inboundFound = true;
            checkOwnership('testInLockOutWorkable checkForInbound1', checkPo, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND, ProspectOwnershipMethods.STAGE_PROSPECTING
                                       ,true  // prospecting
                                       ,false // lockout
                                       ,false // workable
                                       ,false // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,inboundNSRs[0].Id);
         } else if (checkPo.NSS_Source__c == ProspectOwnershipMethods.NSS_OUTBOUND) {
            System.debug('testInLockOutWorkable outboundFound');
            outboundFound = true;
            // workable stays open until inbound goes to lockout - so commission days can be calculated
            checkOwnership('testInLockOutWorkable checkForOutbound1', checkPo, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND, ProspectOwnershipMethods.STAGE_WORKABLE
                                       ,false  // prospecting
                                       ,true // lockout
                                       ,true // workable
                                       ,true // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,0
                                       ,outboundNSRs[0].Id);
         }
      } // for (Prospect_Ownership__c checkPo
      verifyAccount('testInLockOutWorkable checkAccount2', acct, true, true, 2, null);

      // verify inbound and outbound are found
      System.assertEquals(true,inboundFound);
      System.assertEquals(true,outboundFound);

      // move to lockout
      System.debug('before error');
      runProcess(ProspectOwnershipMethods.STAGE_LOCKOUT, acct, null, ctct.Id, inboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND);

      // should be 2 ownership records
      ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(2,ownerList.size());
      // verify the records
      inboundFound = false;
      outboundFound = false;
      
      for (Prospect_Ownership__c checkPo : ownerList) {
         System.debug('testInLockOutWorkable checkPo='+checkPo);
         if (checkPo.NSS_Source__c == ProspectOwnershipMethods.NSS_INBOUND) {
            System.debug('testInLockOutWorkable inboundFound');
            inboundFound = true;
            checkOwnership('testInLockOutWorkable checkForInbound2', checkPo, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_INBOUND, ProspectOwnershipMethods.STAGE_LOCKOUT
                                       ,true  // prospecting
                                       ,true // lockout
                                       ,false // workable
                                       ,true // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,inboundNSRs[0].Id);
         } else if (checkPo.NSS_Source__c == ProspectOwnershipMethods.NSS_OUTBOUND) {
            System.debug('testInLockOutWorkable outboundFound');
            outboundFound = true;
            // 90 days should be added onto the commission date
            checkOwnership('testInLockOutWorkable checkForOutbound2', checkPo, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND, ProspectOwnershipMethods.STAGE_EXPIRED
                                       ,false  // prospecting
                                       ,true // lockout
                                       ,true // workable
                                       ,true // commission
                                       ,false // nfi/wash
                                       ,true // end date
                                       ,90
                                       ,outboundNSRs[0].Id);
         }
      } // for (Prospect_Ownership__c checkPo
      
      verifyAccount('testInLockOutWorkable checkAccount3', acct, false, true, 0, null);

      // verify inbound and outbound are found
      System.assertEquals(true,inboundFound);
      System.assertEquals(true,outboundFound);

   } // testInLockOutWorkable

*/
   // test outbound not interested, then a prosecting, then a lockout.
   static testMethod void testOutNoInterestLockout() {
      setupAcctCtct();
      
      User[] outboundNSRs = ProspectOwnershipMethodsTest.getOutboundNSRs(1);
      runProcess(ProspectOwnershipMethods.STAGE_NO_INTEREST, acct, null, ctct.Id, outboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND);

      // verify 1 ownership record
      List<Prospect_Ownership__c> ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(1,ownerList.size());
      // verify the record
      Prospect_Ownership__c po = ownerList[0];
      checkOwnership('testOutNoInterestLockout checkoutboundOwnership', po, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND, ProspectOwnershipMethods.STAGE_NO_INTEREST
                                       ,false  // prospecting
                                       ,false // lockout
                                       ,false // workable
                                       ,false // commission
                                       ,true // nfi/wash
                                       ,false // end date
                                       ,outboundNSRs[0].Id);
      po.StartDate__c = Date.today().addDays(-2);

      verifyAccount('testOutNoInterestLockout checkAccount1', acct, true, false, 0, null);

      System.debug('testOutNoInterestLockout before STAGE_PROSPECTING');
      // Create a prospecting record - should end the previous record.
      runProcess(ProspectOwnershipMethods.STAGE_PROSPECTING, acct, null, ctct.Id, outboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND);

      // should be 2 ownership records
      ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(2,ownerList.size());
      // verify the records
      
      Boolean expiredFound = false;
      Boolean activeFound = false;

      for (Prospect_Ownership__c checkPo : ownerList) {
         System.debug('testOutNoInterestLockout checkPo='+checkPo);
         if (checkPo.NSS_Source__c == ProspectOwnershipMethods.NSS_OUTBOUND && checkPo.Ownership_Status__c == ProspectOwnershipMethods.STAGE_PROSPECTING) {
            System.debug('testOutNoInterestLockout activeFound');
            activeFound = true;
            checkOwnership('testOutNoInterestLockout checkForInbound2', checkPo, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND, ProspectOwnershipMethods.STAGE_PROSPECTING
                                       ,true  // prospecting
                                       ,false // lockout
                                       ,false // workable
                                       ,false // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,outboundNSRs[0].Id);
         } else if (checkPo.NSS_Source__c == ProspectOwnershipMethods.NSS_OUTBOUND && checkPo.Ownership_Status__c == ProspectOwnershipMethods.STAGE_EXPIRED) {
            System.debug('testOutNoInterestLockout expiredFound');
            expiredFound = true;
            // 90 days should be added onto the commission date
            checkOwnership('testOutNoInterestLockout checkForOutbound2', checkPo, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND, ProspectOwnershipMethods.STAGE_EXPIRED
                                       ,false  // prospecting
                                       ,false // lockout
                                       ,false // workable
                                       ,false // commission
                                       ,true // nfi/wash
                                       ,true // end date
                                       ,0
                                       ,outboundNSRs[0].Id);
         }
      } // for (Prospect_Ownership__c checkPo
      
      verifyAccount('testOutNoInterestLockout checkAccount2', acct, true, false, 1, outboundNSRs[0].Id);

      // verify inbound and outbound are found
      System.assertEquals(true,activeFound);
      System.assertEquals(true,expiredFound);

      // Move to Lockout
      runProcess(ProspectOwnershipMethods.STAGE_LOCKOUT, acct, null, ctct.Id, outboundNSRs[0], UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND);

      // should still be 2 ownership records
      ownerList = acctOwnerMap.get(acct.Id);
      System.assertEquals(2,ownerList.size());
      // verify the records
      
      expiredFound = false;
      activeFound = false;

      for (Prospect_Ownership__c checkPo : ownerList) {
         System.debug('testOutNoInterestLockout checkPo='+checkPo);
         if (checkPo.NSS_Source__c == ProspectOwnershipMethods.NSS_OUTBOUND && checkPo.Ownership_Status__c == ProspectOwnershipMethods.STAGE_LOCKOUT) {
            System.debug('testOutNoInterestLockout activeFound');
            activeFound = true;
            checkOwnership('testOutNoInterestLockout checkForInbound3', checkPo, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND, ProspectOwnershipMethods.STAGE_LOCKOUT
                                       ,true  // prospecting
                                       ,true // lockout
                                       ,false // workable
                                       ,true // commission
                                       ,false // nfi/wash
                                       ,false // end date
                                       ,outboundNSRs[0].Id);
         } else if (checkPo.NSS_Source__c == ProspectOwnershipMethods.NSS_OUTBOUND && checkPo.Ownership_Status__c == ProspectOwnershipMethods.STAGE_EXPIRED) {
            System.debug('testOutNoInterestLockout expiredFound');
            expiredFound = true;
            // 90 days should be added onto the commission date
            checkOwnership('testOutNoInterestLockout checkForOutbound3', checkPo, UserHelper.SO_CORE, ProspectOwnershipMethods.NSS_OUTBOUND, ProspectOwnershipMethods.STAGE_EXPIRED
                                       ,false  // prospecting
                                       ,false // lockout
                                       ,false // workable
                                       ,false // commission
                                       ,true // nfi/wash
                                       ,true // end date
                                       ,0
                                       ,outboundNSRs[0].Id);
         }
      } // for (Prospect_Ownership__c checkPo
      
      verifyAccount('testOutNoInterestLockout checkAccount3', acct, true, false, 0, null);

      // verify inbound and outbound are found
      System.assertEquals(true,activeFound);
      System.assertEquals(true,expiredFound);

   } // testOutNoInterestLockout
/*
   static testMethod void testProspectOwnershipBeforeTrigger() {
      Prospect_Ownership__c po = new Prospect_Ownership__c(Ownership_Status__c='Prospecting', LastVerified__c=DateTime.now());
      insert po;
      
      po.Ownership_Status__c = 'Lockout';
      update po;
      
      po = [Select Id, Ownership_Status__c, LastVerified__c from Prospect_Ownership__c where Id=:po.Id];
      System.assertEquals('Lockout',po.Ownership_Status__c);
      System.assertEquals(null,po.LastVerified__c);
      
   } // testProspectOwnershipBeforeTrigger

   static testMethod void testSetSupervisor() {
      User testUser = [Select Id, Name, ManagerId from User where IsActive=true and ManagerId != null and Manager.IsActive=true limit 1];
      Prospect_Ownership__c po = new Prospect_Ownership__c(NSR_Name__c=testUser.Id);
      insert po;
      po = [Select Id, NSR_Name__c, NSRSupervisor__c from Prospect_Ownership__c where Id=:po.Id];
      System.assertEquals(null,po.NSRSupervisor__c);
      
      Opportunity opp = new Opportunity(Name='Test Opp',StageName='Pending',CloseDate=Date.today());
      insert opp;
      
      po.Opportunity__c = opp.Id;
      update po;

      po = [Select Id, NSR_Name__c, NSRSupervisor__c from Prospect_Ownership__c where Id=:po.Id];
      System.assertEquals(testUser.ManagerId,po.NSRSupervisor__c);
      
      po = new Prospect_Ownership__c(NSR_Name__c=testUser.Id, Opportunity__c=opp.Id);
      insert po;
      po = [Select Id, NSR_Name__c, NSRSupervisor__c from Prospect_Ownership__c where Id=:po.Id];
      System.assertEquals(testUser.ManagerId,po.NSRSupervisor__c);

   } // testSetSupervisor
   */
} // class ProspectOwnershipTest