force-app/main/default/objects/Account/fields/Bis_ID__c.field-meta.xml
<CustomField>
    <fullName>Bis_ID__c</fullName>
    <description>Business ID from HRIS system
Field fed into Oracle Analytics (OBIEE) system nightly.</description>
    <externalId>true</externalId>
    <label>BIS ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Bis_ID__c.field-meta.xml
<CustomField>
    <fullName>Bis_ID__c</fullName>
    <externalId>true</externalId>
    <label>Bis ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup to the Opportunity if this Case is associated with one.</description>
    <inlineHelpText>A lookup to the Opportunity if this Case is associated with one.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>List Of Paychex Products For Case. BJ 7_14
LM - If you add products that will be available for Case Record Type Service Onboarding STM Record Type, make sure you add the product to the object relationship that creates the correct Reference TAA object.</description>
    <inlineHelpText>Select the product.</inlineHelpText>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>401K</fullName>
            </value>
            <value>
                <fullName>Advisor Select</fullName>
            </value>
            <value>
                <fullName>Ancillary Products</fullName>
            </value>
            <value>
                <fullName>ASO</fullName>
            </value>
            <value>
                <fullName>BeneTrac</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>CAOP/PNG</fullName>
            </value>
            <value>
                <fullName>Check Insertion</fullName>
            </value>
            <value>
                <fullName>Check logo service</fullName>
            </value>
            <value>
                <fullName>Check Stubs</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>COBRA</fullName>
            </value>
            <value>
                <fullName>Compliance Testing</fullName>
            </value>
            <value>
                <fullName>Corporate Complaints</fullName>
            </value>
            <value>
                <fullName>CT-900</fullName>
            </value>
            <value>
                <fullName>Data Entry Specialist</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Direct Deposit</fullName>
            </value>
            <value>
                <fullName>Disability</fullName>
            </value>
            <value>
                <fullName>EAM</fullName>
            </value>
            <value>
                <fullName>EAO</fullName>
            </value>
            <value>
                <fullName>EAP, Employee Assistance Program</fullName>
            </value>
            <value>
                <fullName>Employee Screening Service</fullName>
            </value>
            <value>
                <fullName>ESR</fullName>
            </value>
            <value>
                <fullName>Essentials</fullName>
            </value>
            <value>
                <fullName>ExpenseWire</fullName>
            </value>
            <value>
                <fullName>FBAE</fullName>
            </value>
            <value>
                <fullName>Field Support</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Flex Ben Admin</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesRepLookup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/HR_Person_Id__c.field-meta.xml
<CustomField>
    <fullName>HR_Person_Id__c</fullName>
    <description>The unique person identifier from the corporate human resources system</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>HR Person Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Flock__c.field-meta.xml
<CustomField>
    <fullName>Flock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>populated when the Flock field on Reference Agency is populated</description>
    <inlineHelpText>populated when the Flock field on Reference Agency is populated</inlineHelpText>
    <label>Flock</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Send_to_H_B_Implementation__c.field-meta.xml
<CustomField>
    <fullName>Send_to_H_B_Implementation__c</fullName>
    <label>Send to H&amp;B Implementation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type TimeTrade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_TimeTrade</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaychexSettings__c/PaychexSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings used for Paychex applications.</description>
    <label>Paychex Settings</label>
</CustomObject>

force-app/main/default/objects/PaychexSettings__c/fields/Attribute1__c.field-meta.xml
<CustomField>
    <fullName>Attribute1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Use for whatever is needed.</inlineHelpText>
    <label>Attribute1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaychexSettings__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this setting active?</inlineHelpText>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reference_BeneTrac_Onboarding__c/Reference_BeneTrac_Onboarding__c.object-meta.xml
<CustomObject>
    <label>Reference BeneTrac Onboarding</label>
    <nameField>
        <displayFormat>RefBeneTracOnboard-{0000000000}</displayFormat>
        <label>Reference BeneTrac Onboarding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference BeneTrac Onboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_BeneTrac_Onboarding__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Reference BeneTrac Onboardings</relationshipLabel>
    <relationshipName>Reference_BeneTrac_Onboardings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_BeneTrac_Onboarding__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BeneTrac</fullName>
            </value>
            <value>
                <fullName>Conversion</fullName>
            </value>
            <value>
                <fullName>Flock</fullName>
            </value>
            <value>
                <fullName>Ancillary Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_Opportunity_Product__c/Reference_Opportunity_Product__c.object-meta.xml
<CustomObject>
    <description>Used to capture products on opportunity to help populate Service Agreements</description>
    <label>Reference Opportunity Product</label>
    <nameField>
        <displayFormat>RefOpptyProduct-{0000}</displayFormat>
        <label>Reference Opportunity Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Opportunity Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_Opportunity_Product__c/fields/BalanceBenefits_Call_Center__c.field-meta.xml
<CustomField>
    <fullName>BalanceBenefits_Call_Center__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BalanceBenefits Call Center</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reference_Opportunity_Product__c/fields/COBRA_Administration_Services__c.field-meta.xml
<CustomField>
    <fullName>COBRA_Administration_Services__c</fullName>
    <defaultValue>false</defaultValue>
    <label>COBRA Administration Services</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reference_Opportunity_Product__c/fields/Employer_Shared_Responsibility__c.field-meta.xml
<CustomField>
    <fullName>Employer_Shared_Responsibility__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Employer Shared Responsibility</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reference_Opportunity_Product__c/fields/Flock__c.field-meta.xml
<CustomField>
    <fullName>Flock__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flock Benefits Administration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reference_Opportunity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Reference Opportunity Products</relationshipLabel>
    <relationshipName>Reference_Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/HR_Person_Id__c.field-meta.xml
<CustomField>
    <fullName>HR_Person_Id__c</fullName>
    <description>The Person Id from HR</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Person Id from HR</inlineHelpText>
    <label>HR Person Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Person_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Person_ID_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sales Rep ID Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Type_TimeTrade.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Demo</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Demo Strategy Call</fullName>
    </customValue>
    <customValue>
        <fullName>Discovery - Standard Appt</fullName>
    </customValue>
    <masterLabel>Type-TimeTrade</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Yes_No.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <description>Used for Yes/No Picklists</description>
    <masterLabel>Yes/No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BenAdminOnboardingEmailTest.cls
/**
* Test method for BenAdminOnboardingEmail
* 
* History
* --------
* 06/10/2022  Carrie Marciano  created
* 08/30/2023  Shilpa G		   Added Flock product in ROP records
*/

@isTest
public class BenAdminOnboardingEmailTest {
    
    // test good parsing of plain text
    @isTest(SeeAllData=false)
    static void goodParseTEXT() {
            Id hnbfOppRT = RecordTypeHelper.getRecordType('HNBF Opportunity Record Type','Opportunity').getRecordTypeId();
            
            PaychexSettings__c pxs = new PaychexSettings__c (name='BenAdminOnbErrorEmail',IsActive__c = true , Attribute1__c ='cmarciano@paychex.com'); 
            insert pxs;
            
            User runningUser = [Select Id, FirstName, LastName, Email, HR_Person_Id__c from User where Profile.Name=:Utilities.PROF_SYS_ADMIN and IsActive=true and HR_Person_Id__c != null limit 1];
            
            Account testAcct = new Account(Name = 'Test Acct', NumberOfEmployees=40, Bis_ID__c=464646, RecordTypeId='012300000000hNv');
            insert testAcct;
            
            User salesRep = [SELECT ID, Person_ID_Number__c FROM User WHERE Profile.Name = 'Core Sales - SB' and IsActive = true and Person_ID_Number__c != null LIMIT 1];
            
            Opportunity testOpp = new Opportunity(AccountId=testAcct.Id,OwnerId=salesRep.Id,Name='TestOpp',Type='Flock',StageName='Sold - Submitted',CloseDate=date.today(),RecordTypeId=hnbfOppRT,Send_to_H_B_Implementation__c='No');
            insert testOpp;
            
            Reference_Opportunity_Product__c testRop = new Reference_Opportunity_Product__c(Opportunity__c=testOpp.Id, COBRA_Administration_Services__c=True, BalanceBenefits_Call_Center__c=True, Employer_Shared_Responsibility__c=True,Flock__c=True);
            insert testRop;
            
            System.runAs(runningUser) {        
                Messaging.InboundEmail email = new Messaging.InboundEmail();
                Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
                
                // setup the data for the email
         		email.subject = 'Test BenAdmin Onboarding';
         		email.fromname = 'FirstName LastName';
		        env.fromAddress = 'someaddress@email.com';
                
                String benAdminMsg = '<BenAdminOnb>\r <AccountId>'+testAcct.Id+'</AccountId>\r <CompanyName>'+testAcct.Name+'</CompanyName>\r <OpportunityId>'+testOpp.Id+'</OpportunityId>\r';
                benAdminMsg += '<SalesRepId>'+salesRep.Person_ID_Number__c+'</SalesRepId>\r <Origin>MMS</Origin>\r <BrokerContactforImp>Josh Allen</BrokerContactforImp>\r <ClientContactforImp>Stefon Diggs</ClientContactforImp>\r';
                benAdminMsg += '<OpenEnrollmentDates>6/30/2022</OpenEnrollmentDates>\r <ClientReqDeliveryDate>9/3/2022</ClientReqDeliveryDate>\r <Notes>This is a new Flock onboarding</Notes>\r';
                benAdminMsg += '<CarrierInfo>\r <CarrierName>Test Carrier 1</CarrierName>\r <EDIConnection>No</EDIConnection>\r <GroupPolicyNumber>11111</GroupPolicyNumber>\r <CarrierContact>Dion Dawkins</CarrierContact>\r </CarrierInfo>\r';
                benAdminMsg += '</BenAdminOnb>'; 
                email.plainTextBody = benAdminMsg; 
                
                // call Helper class directly to check parsing then process list creating new account and contact       
                BenAdminOnboardingHelper.benAdminOnb bAO = new BenAdminOnboardingHelper.benAdminOnb();
                bAO = BenAdminOnboardingHelper.parseXml(email.plainTextBody);
                
                system.debug('bAO: '+bAO);
                System.assertEquals(bAO.accountId, testAcct.Id);
                System.assertEquals(bAO.opportunityId, testOpp.Id);
                System.assertEquals(bAO.salesRepId, salesRep.Person_ID_Number__c);
                System.assertEquals(bAO.origin,'MMS');
                System.assertEquals(bAO.brokerContactforImp, 'Josh Allen');
                System.assertEquals(bAO.clientContactforImp, 'Stefon Diggs');
                System.assertEquals(bAO.openEnrollmentDates, '6/30/2022');
                System.assertEquals(bAO.clientReqDeliveryDate, '9/3/2022');
                System.assertEquals(bAO.notes, 'This is a new Flock onboarding');
                
                BenAdminOnboardingEmail bAOE = new BenAdminOnboardingEmail();
                bAOE.handleInboundEmail(email, env);
                
        	} // System.runAs(runningUser
    } // goodParseTEXT 
    
    // test good parsing of html
    @isTest(SeeAllData=false)
    static void goodParseHTML() {
            Id hnbfOppRT = RecordTypeHelper.getRecordType('HNBF Opportunity Record Type','Opportunity').getRecordTypeId();
            
            PaychexSettings__c pxs = new PaychexSettings__c (name='BenAdminOnbErrorEmail',IsActive__c = true , Attribute1__c ='cmarciano@paychex.com'); 
            insert pxs;
            
            User runningUser = [Select Id, FirstName, LastName, Email, HR_Person_Id__c from User where Profile.Name=:Utilities.PROF_SYS_ADMIN and IsActive=true and HR_Person_Id__c != null limit 1];
            
            Account testAcct = new Account(Name = 'Test Acct', NumberOfEmployees=40, Bis_ID__c=464646, RecordTypeId='012300000000hNv');
            insert testAcct;
            
            User salesRep = [SELECT ID, Person_ID_Number__c FROM User WHERE Profile.Name = 'Core Sales - SB' and IsActive = true and Person_ID_Number__c != null LIMIT 1];
            
            Opportunity testOpp = new Opportunity(AccountId=testAcct.Id,OwnerId=salesRep.Id,Name='TestOpp',Type='Flock',StageName='Sold - Submitted',CloseDate=date.today(),RecordTypeId=hnbfOppRT,Send_to_H_B_Implementation__c='No');
            insert testOpp;
            
            Reference_Opportunity_Product__c testRop = new Reference_Opportunity_Product__c(Opportunity__c=testOpp.Id, COBRA_Administration_Services__c=True, BalanceBenefits_Call_Center__c=True, Employer_Shared_Responsibility__c=True,Flock__c=True);
            insert testRop;
            
            System.runAs(runningUser) {        
                Messaging.InboundEmail email = new Messaging.InboundEmail();                
                email.htmlBody = '<BenAdminOnb>';
                
                email.htmlBody += addXML('AccountId',testAcct.Id);
                email.htmlBody += addXML('CompanyName',testAcct.Name);
                email.htmlBody += addXML('OpportunityId',testOpp.Id);
                email.htmlBody += addXML('SalesRepId',salesRep.Person_ID_Number__c);
                email.htmlBody += addXML('Origin','MMS');
                email.htmlBody += addXML('BrokerContactforImp','Josh Allen');
                email.htmlBody += addXML('ClientContactforImp','Stefon Diggs');
                email.htmlBody += addXML('OpenEnrollmentDates','6/30/2022');
                email.htmlBody += addXML('ClientReqDeliveryDate','9/3/2022');
                email.htmlBody += addXML('Notes','This is a new Flock onboarding');
                email.htmlBody += '<CarrierInfo>';
                email.htmlBody += addXML('CarrierName','Test Carrier 1');
                email.htmlBody += addXML('EDIConnection','No');
                email.htmlBody += addXML('GroupPolicyNumber','11111');
                email.htmlBody += addXML('CarrierContact','Dion Dawkins');
                email.htmlBody += '</CarrierInfo>';
                email.htmlBody += '</BenAdminOnb>\r\nThe information contained';
                
                Test.startTest();
                	Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
                	BenAdminOnboardingEmail bAOE = new BenAdminOnboardingEmail();
                	bAOE.handleInboundEmail(email, env);
                Test.StopTest();
                
                Case[] caseList = [Select Id, AccountId, Opportunity__c, Sales_Rep__c from Case where Product__c = 'Flock' and Account.Id = :testAcct.Id];
                System.assertEquals(1, caseList.size());
                Reference_BeneTrac_Onboarding__c[] refBTOnbList = [Select id, Case_Number__c, Type__c from Reference_BeneTrac_Onboarding__c 
                                                                   where Type__c = 'Flock' and Case_Number__c = :caseList[0].Id];
                System.assertEquals(1, refBTOnbList.size());
                                          
        	} // System.runAs(runningUser
    } // goodParseHTML       
    
    static testMethod void testBadXML(){
        Boolean testPassed = false;
        string except;
        
        PaychexSettings__c pxs = new PaychexSettings__c (name='BenAdminOnbErrorEmail',IsActive__c = true , Attribute1__c ='cmarciano@paychex.com'); 
        insert pxs;
        
        messaging.Inboundemail email = new messaging.Inboundemail();
        email.htmlBody = '<BenAdminOnb><junk></BenAdminOnb>';
        Messaging.InboundEnvelope envBad = new Messaging.InboundEnvelope();
        BenAdminOnboardingEmail bAOE = new BenAdminOnboardingEmail();
        try{
            bAOE.handleInboundEmail(email, envBad);
        }
        catch(BenAdminOnboardingEmail.BenAdminException ba)
        {   testPassed = true;  }     // sends email instead of throwing error coz email body is empty
        System.assertEquals(false, testPassed);
        
    } //testBadXML
    
    static string addXML(string tag, string content){
        return '<' + tag + '>' + content + '</' + tag + '>\r\n';
    }
}