force-app/main/default/objects/Account/fields/Contact_Email_Available__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates the Prospect-Client has at least 1 associated Contact with an Email address. If none of the associated contacts has an email address populated, this field will be unchecked. This field is maintained by an Apex trigger.</description>
    <inlineHelpText>Indicates the Prospect-Client has at least 1 associated Contact with an Email address.</inlineHelpText>
    <label>Contact Email Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apex_Batch_Control__c/Apex_Batch_Control__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These are settings that can be used to implement some control over apex batch jobs.</description>
    <label>Apex Batch Control</label>
</CustomObject>

force-app/main/default/objects/Apex_Batch_Control__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Should the job run?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apex_Batch_Control__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <inlineHelpText>This is used by the UpdateZipOwnershipController to allow the batches to be manually launched.</inlineHelpText>
    <label>Batch Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_Batch_Control__c/fields/Minutes_till_Launch__c.field-meta.xml
<CustomField>
    <fullName>Minutes_till_Launch__c</fullName>
    <label>Minutes till Launch</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Do_Not_Sync__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Sync__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Do not sync field used for Marketo. Checked will not sync with Marketo, unchecked will be synced with Marketo. Case #25931629</description>
    <label>Do Not Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Contact__c.field-meta.xml
<CustomField>
    <fullName>Sales_Contact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicator that the contact should be seen by the sales users.  Used by sharing rules and not visible to the users.</description>
    <label>Sales Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RecordType__c/RecordType__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Additional Information for record types</description>
    <label>RecordType</label>
</CustomObject>

force-app/main/default/objects/RecordType__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the object this record type is associated with</inlineHelpText>
    <label>Object Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecordType__c/fields/RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The full name of the record type in case it&apos;s longer than the size of the name field.</inlineHelpText>
    <label>RecordType Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecordType__c/fields/UseForSync__c.field-meta.xml
<CustomField>
    <fullName>UseForSync__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this record type used in the sync to Marketo?</inlineHelpText>
    <label>Use For Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountCheckContactEmail.cls
/* 
   Check if there is at least one contact with an email address for each passed in account
   
  History
  -------
  06/24/2011 Dan Carmen   Created
  08/02/2011 Dan Carmen   Remove sharing.
  05/30/2012 Dan Carmen   Cleaning up code
  02/09/2018 Dan Carmen   Add in check for Do_Not_Sync__c flag
   
 */
global without sharing class AccountCheckContactEmail implements Database.Batchable<SObject>, Database.Stateful , Schedulable {

   /** The total number of accounts selected. */
   global Integer numberAccounts = 0;
   /** The total number of accounts where the flag is set to false. */
   global Integer numberAccountsToFalse = 0;
   /** The total number of accounts where the flag is set to true. */
   global Integer numberAccountsToTrue = 0;
   /** The time the process started. */
   global DateTime startTime;

   /** messages that occur during the process. */
   global String processNotes = '';

   global JobHelper jh = new JobHelper('AccountCheckContactEmail');
   
   // start this January 1, 2006
   global Date batchStartDate = Date.newInstance(2006,1,1);
   global Date batchEndDate = null;

   global AccountCheckContactEmail() {
      startTime = DateTime.now();
      Apex_Batch_Control__c abc = Apex_Batch_Control__c.getInstance('AccountCheckContactEmail');
      // use the Minutes_till_Launch__c field for the number of months. Default to 6
      Integer nbrMonths = (abc != null && abc.Minutes_till_Launch__c != null ? Integer.valueOf(abc.Minutes_till_Launch__c) : 6);
      batchEndDate = batchStartDate.addMonths(nbrMonths);
   } // AccountCheckContactEmail
   
   // to be able to run the batch for a certain date range
   global AccountCheckContactEmail(Date startDate, Integer nbrMonths) {
      batchStartDate = startDate;
      batchEndDate = batchStartDate.addMonths(nbrMonths);
   }
   
   global Database.QueryLocator start(Database.BatchableContext BC){
      Map<String,Schema.RecordTypeInfo> byNameMap = Account.SObjectType.getDescribe().getRecordTypeInfosByName();
      Id[] recordTypeIds = new Id[]{};
      for (RecordType__c rt : RecordType__c.getAll().values()) {
         if (rt.ObjectName__c == ObjectHelper.OBJECT_ACCOUNT && rt.UseForSync__c) {
            Schema.RecordTypeInfo rtInfo = byNameMap.get(rt.RecordTypeName__c);
            if (rtInfo != null) {
               recordTypeIds.add(rtInfo.getRecordTypeId());
            }
         }
      } // for
      System.debug('recordTypeIds='+recordTypeIds);
      // get the record types from the custom setting
      
      // save the record - show that the job started
      jh.setStarted();
      // check all accounts in the database - batch by date so that the job can complete
      return Database.getQueryLocator([Select Id, Name, Contact_Email_Available__c
                               ,(select Id, Email
                                   From Contacts
                                  where Email != null
                                    and isDeleted=false
                                    and Sales_Contact__c=true
                                    and Do_Not_Sync__c=false
                                  limit 1)
                           from Account
                          where RecordTypeId in :recordTypeIds
                            and CreatedDate >= :batchStartDate
                            and CreatedDate <= :batchEndDate]);
   } // start

   // In order to schedule a batch run
   global void execute(SchedulableContext sc) {
      Apex_Batch_Control__c abc = Apex_Batch_Control__c.getInstance('AccountCheckContactEmail');
      Integer batchSize = (abc != null ? Integer.valueOf(abc.BatchSize__c) : 1000);
      AccountCheckContactEmail acce = new AccountCheckContactEmail();
      database.executeBatch(acce, batchSize);
   } // execute

   // Execute a batch.
   global void execute(Database.BatchableContext BC, List<SObject> scope){
      List<Account> accts = (List<Account>)scope;
      Account[] updateAccts = new Account[]{};
      numberAccounts += accts.size();
      System.debug('execute numberAccounts='+numberAccounts);
      
      checkAcctFlag(accts, updateAccts);
      
      if (!updateAccts.isEmpty()) {
         DmlHelper.performDML2(updateAccts, DmlHelper.DML_UPDATE, 'AccountCheckContactEmail', 'execute', 'updating accounts', true);
      }
   } // execute
   
   public void checkAcctFlag(Account[] accts, Account[] updateAccts) {
      // loop through the accounts returned and see if the flag will change on any
      for (Account acct : accts) {
         System.debug('checkAcctFlag acct='+acct.Name+' contacts='+acct.Contacts);
         if ((acct.Contacts == null || acct.Contacts.size() == 0) && acct.Contact_Email_Available__c) {
            System.debug('checkAcctFlag Setting to false');
            acct.Contact_Email_Available__c = false;
            numberAccountsToFalse++;
            updateAccts.add(acct);
         } else if (acct.Contacts.size() > 0 && !acct.Contact_Email_Available__c) {
            System.debug('checkAcctFlag Setting to true');
            acct.Contact_Email_Available__c = true;
            numberAccountsToTrue++;
            updateAccts.add(acct);
         }
      } // for
      
      System.debug('checkAcctFlag updateAccts='+updateAccts.size()+' numberAccountsToFalse='+numberAccountsToFalse+' numberAccountsToTrue='+numberAccountsToTrue);
   } // checkAcctFlag
   
   global void finish(Database.BatchableContext bc){
      String message = '\nTotal Accounts Processed for '+batchStartDate.format()+' to '+batchEndDate.format()+': '+numberAccounts+' '; 
      message += '\nNumber accounts where Contact Email Available was set to false: '+numberAccountsToFalse+' '; 
      message += '\nNumber accounts where Contact Email Available was set to true: '+numberAccountsToTrue+' '; 
      
      message += '\n\n'+processNotes;
      
      jh.completeJob(bc, 'Account Check Contact Email update', message);
      
      if (batchEndDate < Date.today()) {
         Apex_Batch_Control__c abc = Apex_Batch_Control__c.getInstance('AccountCheckContactEmail');
         Integer nbrMonths = (abc != null && abc.Minutes_till_Launch__c != null ? Integer.valueOf(abc.Minutes_till_Launch__c) : 6);
         AccountCheckContactEmail rsb = new AccountCheckContactEmail(batchEndDate, nbrMonths);
         Integer batchSize = ((abc != null && abc.BatchSize__c != null) ? (Integer)abc.BatchSize__c : 1000);
         if (!Test.isRunningTest() && abc != null && abc.Active__c) {
            database.executeBatch(rsb, batchSize);
         }
      } // if (batchEndDate
   } // finish

   /*
   public static void checkContacts(Set<Id> accountIds) {
   	// only need to select 1 contact that has an email address.
      Account[] accts = [Select Id, Name, Contact_Email_Available__c
                               ,(select Id, Email
                                   From Contacts
                                  where Email != null
                                    and isDeleted=false
                                    and Sales_Contact__c=true
                                  limit 1)
                           from Account
                          where Id in :accountIds
                            and RecordType.Name != :SYSTEM_ADMINISTRATION_ACCOUNT];
      Account[] updateAccts = new Account[]{};
      // loop through the accounts returned and see if the flag will change on any
      for (Account acct : accts) {
      	System.debug('acct='+acct.Name+' contacts='+acct.Contacts);
         if ((acct.Contacts == null || acct.Contacts.size() == 0) && acct.Contact_Email_Available__c) {
         	System.debug('Setting to false');
            acct.Contact_Email_Available__c = false;
            numberAccountsToFalse++;
            updateAccts.add(acct);
         } else if (acct.Contacts.size() > 0 && !acct.Contact_Email_Available__c) {
         	System.debug('Setting to true');
            acct.Contact_Email_Available__c = true;
            numberAccountsToTrue++;
            updateAccts.add(acct);
         }
      } // for
      
      if (!updateAccts.isEmpty()) {
         update updateAccts;
      }
   } // checkContacts
   */
} // class AccountCheckContactEmail