force-app/main/default/objects/Account/fields/Contact_Email_Available__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates the Prospect-Client has at least 1 associated Contact with an Email address. If none of the associated contacts has an email address populated, this field will be unchecked. This field is maintained by an Apex trigger.</description>
    <inlineHelpText>Indicates the Prospect-Client has at least 1 associated Contact with an Email address.</inlineHelpText>
    <label>Contact Email Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RelatedToReports__c/RelatedToReports__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of report links by object for custom component</description>
    <label>RelatedToReports</label>
</CustomObject>

force-app/main/default/objects/RelatedToReports__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Object</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RelatedToReports__c/fields/ReportID__c.field-meta.xml
<CustomField>
    <fullName>ReportID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ReportID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RelatedToReportsControllerTest.cls
@isTest
public with sharing class RelatedToReportsControllerTest {
	@isTest
	static void allRelatedReportsTest() {
      	Account a1 = new Account(Name='Test Account 1', Contact_Email_Available__c=false);
      	insert a1;

		RelatedToReports__c reportItem = new RelatedToReports__c(Name='Test', ReportID__c='123456789', Object__c='Account');
		insert reportItem;

		Test.startTest();
		List<RelatedToReports__c> reportItems = RelatedToReportsController.allRelatedReports(a1.Id);
		Test.stopTest();

		System.assertEquals(reportItems.size() != 0, true, 'The RelatedToReports custom setting was not received');
	}

	@isTest
	static void allRelatedReports_Exception_Test() {
		Boolean caughtException = false;

		Test.startTest();
		try{
			List<RelatedToReports__c> reportItems = RelatedToReportsController.allRelatedReports('000000000000000000');
		}catch(AuraHandledException e){
			caughtException = true;
		}
		Test.stopTest();

		System.assertEquals(caughtException, true, 'An exception should have thrown');
	}
}