force-app/main/default/objects/Account/fields/CPA_Name_Ref__c.field-meta.xml
<CustomField>
    <fullName>CPA_Name_Ref__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CPA-Client Relationship</description>
    <label>CPA Full Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Contact__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>CPA-Mutual Clients</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mirror_Ref_Ctct__c.field-meta.xml
<CustomField>
    <fullName>Mirror_Ref_Ctct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If this is a referral, the matching Referral Contact object</description>
    <label>Mirror Ref Ctct</label>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Contacts (Mirror Ref Ctct)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Franchise National Account referral account.</inlineHelpText>
    <label>Referral National Account</label>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>not really used anywhere, as of 4/19/2013 is blank for all production records</description>
    <label>Referral Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Contact__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>R00N50000001WySDEA0</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>PBS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pay</fullName>
            </value>
            <value>
                <fullName>PAS</fullName>
            </value>
            <value>
                <fullName>H&amp;B</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Lead_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_Lead_Submitted__c</fullName>
    <description>Date bank lead was received</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Lead Submitted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityType__c.field-meta.xml
<CustomField>
    <fullName>OpportunityType__c</fullName>
    <description>Used to determine whether or not an Opportunity is a duplicate. After resorting picklist order, always move the following values to the end of the list: Adjustment; True-Up; Chargeback; Balance.</description>
    <inlineHelpText>Is this a payroll or an HRS opportunity?</inlineHelpText>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Add-On ID</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>ASO</fullName>
                <label>HR Pro</label>
            </value>
            <value>
                <fullName>AUTO</fullName>
            </value>
            <value>
                <fullName>Balance</fullName>
            </value>
            <value>
                <fullName>BeneTrac Gold</fullName>
            </value>
            <value>
                <fullName>BeneTrac Platinum</fullName>
            </value>
            <value>
                <fullName>BND (ERISA BOND)</fullName>
            </value>
            <value>
                <fullName>BOP (Business Owners Package)</fullName>
            </value>
            <value>
                <fullName>Chargeback</fullName>
            </value>
            <value>
                <fullName>Conversion</fullName>
            </value>
            <value>
                <fullName>Cyber A Basic $250</fullName>
            </value>
            <value>
                <fullName>Cyber A Basic $300</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 1 $1,725</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 1 $750</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 2 $1,200</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 2 $1,940.63</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 3 $1,500</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 3 $3,151.58</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 4 $2,650</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 4 $5,304.38</fullName>
            </value>
            <value>
                <fullName>Digital Marketing</fullName>
            </value>
            <value>
                <fullName>Directors and Officers</fullName>
            </value>
            <value>
                <fullName>Disability</fullName>
            </value>
            <value>
                <fullName>Employment Practice Liability (EPLI)</fullName>
            </value>
            <value>
                <fullName>ERISA</fullName>
            </value>
            <value>
                <fullName>Errors and Omissions</fullName>
            </value>
            <value>
                <fullName>ERTC</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Referral Account of the Referral Contact at the time of the Opportunity. This is so we know at a company level the referrals made, even if the contact changes companies.</description>
    <inlineHelpText>The Referral Account of the Referral Contact at the time of the Opportunity.</inlineHelpText>
    <label>Referral Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Account__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field should only be completed if the Lead Source is an external partner (CPA, Bank, FA, etc.)</inlineHelpText>
    <label>Referral Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Contact__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Referral Contacts with End Dates will only appear if you click the Show All Results link below.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>OppRCs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/Referral_Account__c.object-meta.xml
<CustomObject>
    <description>Referral Source Company Information</description>
    <label>Referral Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Referral Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Account__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/fields/MutualClientTier__c.field-meta.xml
<CustomField>
    <fullName>MutualClientTier__c</fullName>
    <inlineHelpText>Which tier does the mutual client count fall into?</inlineHelpText>
    <label>Accountant Program Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/Referral_Contact__c.object-meta.xml
<CustomObject>
    <label>Referral Contact</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Contact__c/fields/Admin_CPA__c.field-meta.xml
<CustomField>
    <fullName>Admin_CPA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin CPA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Referred</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Referral_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/CPA_portal_shared__c.field-meta.xml
<CustomField>
    <fullName>CPA_portal_shared__c</fullName>
    <label>CPA portal shared client access</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Referral Contact Email</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Referral Contact First Name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Account__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Referral Contacts</relationshipLabel>
    <relationshipName>Referral_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MyAccountStatusCtrlTest.cls
/* 
* The test methods for the MyAccountStatusCtrl class.
*
* History
* -------
  01/11/2023 Jidesh         Created

*/
@isTest
public class MyAccountStatusCtrlTest {

    static testMethod void testLoadData() {
        Profile prof = [SELECT Id FROM Profile where name='CPA Customer Community Login User Clone' LIMIT 1];
        User otherAdmin = [SELECT id FROM User WHERE Profile.Name = 'System Administrator' AND isActive = true AND Id!=:UserInfo.getUserId() LIMIT 1];
        
        Referral_Account__c refAcc = new Referral_Account__c();
        refAcc.Name = 'Peo test';
        refAcc.MutualClientTier__c = 'Core';
        insert refAcc;
        
        System.debug('refAcc:'+refAcc);
        
        Account acc = new Account();
        acc.Name = 'Peo test';
        //acc.CPA_Name_Ref__r.Referral_Account__c = refAcc.Id;
        insert acc;
        
        
        Contact ctct = new Contact(AccountId=acc.id,
                                    FirstName = 'test',
                                    LastName = 'user',
                                    Email='testing@testingtestTest.com'); 
        insert ctct;
        
        Referral_Contact__c refCon = new Referral_Contact__c(Referral_Account__c = refAcc.Id, 
                                                             First_Name__c = 'test',
                                                             Last_Name__c = 'user',
                                                             Email__c = 'testing@testingtestTest.com',
                                                             Contact__c = ctct.Id,
                                                            Admin_CPA__c = false,
                                                            CPA_portal_shared__c = 'Yes');
        insert refCon;
        
        ctct.Mirror_Ref_Ctct__c = refCon.Id;
        Update ctct;
        
        
        Opportunity opp = new Opportunity(
            AccountId = acc.id,
            Name = 'Test Opty',
            CloseDate = System.today(),
            StageName = 'Proposal',
            Referral_Contact__c = refCon.Id,
            Date_Lead_Submitted__c = system.today(),
            Referral_Account__c = refAcc.Id,
            OpportunityType__c='Payroll'        
        );
        Insert opp;
        
        //Referral_Contact__c rCon = [Select id, Name, Referral_Account__c from Referral_Contact__c where id=:refCon.id limit 1];
        //System.debug('rCon:'+rCon);
        //acc.CPA_Name_Ref__c = refCon.Id;
        //acc.CPA_Name_Ref__r.Referral_Account__c = rCon.Referral_Account__c;
        //Update acc;
            
        Id vfpageUserId;
        system.runAs(otherAdmin){
            User testUser = new User(
                UserName = ctct.email,
                FirstName = ctct.FirstName,
                LastName =ctct.LastName,
                Alias = 'alias',
                email = ctct.Email,
                ContactId = ctct.id,
                ProfileId = prof.Id,
                EmailEncodingKey = 'UTF-8',
                CommunityNickname = 'nickName',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US',
                Sales_Org__c = 'PAS'
            );
         
            insert testUser;
           
            vfpageUserId = testUser.Id;
            System.debug('vfpageUserId :'+vfpageUserId);
            //MyAccountStatusCtrl mstCtrl = new MyAccountStatusCtrl();
        }
        User vfPageUser = [SELECT id FROM User WHERE Id =:vfpageUserId LIMIT 1];
        system.runAs(vfPageUser){
            System.debug('vfPageUser :'+vfPageUser);
            MyAccountStatusCtrl mstCtrl = new MyAccountStatusCtrl();
            mstCtrl.displayImage('Signature');
            mstCtrl.displayImage('Elite');
            //mstCtrl.loadAcctInList(0,1);
            //mstCtrl.loadOppInList(0,1);
            mstCtrl.handleAcctIsNext();
            mstCtrl.handleOppIsNext();
            mstCtrl.acceptTermAndCondition = true;
            mstCtrl.hideModelPopup();
            mstCtrl.loadOppMoreResult();
            mstCtrl.loadAcctMoreResult();
            mstCtrl.redirectToReferClientPage();
          MyAccountStatusCtrl.AccountWrapper objAW = new MyAccountStatusCtrl.AccountWrapper();
            objAW.acctName = 'test';
            objAW.rcName = 'test';
            objAW.lastmodifiedDate = Date.today();
            //mstCtrl.AccountWrapper();
            //MyAccountStatusCtrl.AccountWrapper acctWrap = new MyAccountStatusCtrl.AccountWrapper();
            //Need to write asserts
        }
        List<Referral_Contact__c> refConResults = [Select id, name, Admin_CPA__c, Contact__c, CPA_Program_status__c,CPA_portal_shared__c from Referral_Contact__c];
        System.debug('refConResults:'+refConResults);
        System.assertEquals(1, refConResults.size());
        System.assertEquals(true, refConResults[0].Admin_CPA__c);
        
       
    }
    
   static testMethod void testdisplayImage() {
       
    }
}