force-app/main/default/objects/Account/fields/Current_Prior_Method__c.field-meta.xml
<CustomField>
    <fullName>Current_Prior_Method__c</fullName>
    <description>Fed in from HRIS and Payroll nightly. 
Field fed into Oracle Analytics (OBIEE) system nightly.</description>
    <label>Payroll Current-Prior Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AccessPoint</fullName>
            </value>
            <value>
                <fullName>Adam&apos;s Keegan-PEO</fullName>
            </value>
            <value>
                <fullName>Administaff-PEO</fullName>
            </value>
            <value>
                <fullName>ADP</fullName>
            </value>
            <value>
                <fullName>ADP Pay eXpert</fullName>
            </value>
            <value>
                <fullName>ADP Payforce</fullName>
            </value>
            <value>
                <fullName>ADP PC/Payroll for Windows</fullName>
            </value>
            <value>
                <fullName>ADP Run</fullName>
            </value>
            <value>
                <fullName>ADP TotalSource-PEO</fullName>
            </value>
            <value>
                <fullName>ADP Workforce Now</fullName>
            </value>
            <value>
                <fullName>Advantage HR-PEO</fullName>
            </value>
            <value>
                <fullName>Advantage Payroll</fullName>
            </value>
            <value>
                <fullName>AEG (American Employer Group)-PEO</fullName>
            </value>
            <value>
                <fullName>Agile HR</fullName>
            </value>
            <value>
                <fullName>Allstaff-PEO</fullName>
            </value>
            <value>
                <fullName>Alpha Staff-PEO</fullName>
            </value>
            <value>
                <fullName>Ambassador-PEO</fullName>
            </value>
            <value>
                <fullName>Amstaff-PEO</fullName>
            </value>
            <value>
                <fullName>Asure Software</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>BambooHR</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>BBSI</fullName>
            </value>
            <value>
                <fullName>BenefitMall</fullName>
            </value>
            <value>
                <fullName>Ceridian</fullName>
            </value>
            <value>
                <fullName>Certipay</fullName>
            </value>
            <value>
                <fullName>Co-Advantage-PEO</fullName>
            </value>
            <value>
                <fullName>Complete Payroll</fullName>
            </value>
            <value>
                <fullName>Computer</fullName>
            </value>
            <value>
                <fullName>Connect Pay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Fed in from HRIS and Payroll nightly. 
Field fed into Oracle Analytics (OBIEE) system nightly.</description>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 Weekly</fullName>
            </value>
            <value>
                <fullName>2 Bi-weekly</fullName>
            </value>
            <value>
                <fullName>3 Semi-monthly</fullName>
            </value>
            <value>
                <fullName>4 Monthly</fullName>
            </value>
            <value>
                <fullName>5 Quarterly</fullName>
            </value>
            <value>
                <fullName>6 Semi-annually</fullName>
            </value>
            <value>
                <fullName>7 Annually</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/HR_Person_Id__c.field-meta.xml
<CustomField>
    <fullName>HR_Person_Id__c</fullName>
    <description>The unique person identifier from the corporate human resources system</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>HR Person Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/MktgId__c.field-meta.xml
<CustomField>
    <fullName>MktgId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Id from Marketing (Marketo) used to identify this record in that system.</inlineHelpText>
    <label>Mktg Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OwnedByPrev__c.field-meta.xml
<CustomField>
    <fullName>OwnedByPrev__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The previous value of the owned by field</inlineHelpText>
    <label>OwnedByPrev</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <description>When errors occur during a process, a place we can capture and log them</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Log-{00000000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <inlineHelpText>Number of records submitted for save</inlineHelpText>
    <label>Batch Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the class the error originated from</inlineHelpText>
    <label>Class Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/CodeKey__c.field-meta.xml
<CustomField>
    <fullName>CodeKey__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Something that identifies what the code is trying to do</inlineHelpText>
    <label>Code Key</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>A description of the error</inlineHelpText>
    <label>Description</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the method this error originated from</inlineHelpText>
    <label>Method Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Bank_Product_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Bank_Product_of_Interest__c</fullName>
    <description>Field to be used to store the original product of interest for incoming leads.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Field to be used to store the original product of interest for incoming leads.</inlineHelpText>
    <label>3rd Party Product of Interest</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Current_Prior_Method__c.field-meta.xml
<CustomField>
    <fullName>Current_Prior_Method__c</fullName>
    <label>Payroll Current-Prior Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AccessPoint</fullName>
            </value>
            <value>
                <fullName>Adam&apos;s Keegan-PEO</fullName>
            </value>
            <value>
                <fullName>Administaff-PEO</fullName>
            </value>
            <value>
                <fullName>ADP</fullName>
            </value>
            <value>
                <fullName>ADP Pay eXpert</fullName>
            </value>
            <value>
                <fullName>ADP Payforce</fullName>
            </value>
            <value>
                <fullName>ADP PC/Payroll for Windows</fullName>
            </value>
            <value>
                <fullName>ADP Run</fullName>
            </value>
            <value>
                <fullName>ADP Total Source-PEO</fullName>
            </value>
            <value>
                <fullName>ADP Workforce Now</fullName>
            </value>
            <value>
                <fullName>Advantage HR-PEO</fullName>
            </value>
            <value>
                <fullName>Advantage Payroll</fullName>
            </value>
            <value>
                <fullName>AEG (American Employer Group)-PEO</fullName>
            </value>
            <value>
                <fullName>Agile HR</fullName>
            </value>
            <value>
                <fullName>Allstaff-PEO</fullName>
            </value>
            <value>
                <fullName>Alpha Staff-PEO</fullName>
            </value>
            <value>
                <fullName>Ambassador-PEO</fullName>
            </value>
            <value>
                <fullName>Amstaff-PEO</fullName>
            </value>
            <value>
                <fullName>Asure Software</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>BenefitMall</fullName>
            </value>
            <value>
                <fullName>Ceridian</fullName>
            </value>
            <value>
                <fullName>Certipay</fullName>
            </value>
            <value>
                <fullName>Co-Advantage-PEO</fullName>
            </value>
            <value>
                <fullName>Computer</fullName>
            </value>
            <value>
                <fullName>Connect Pay</fullName>
            </value>
            <value>
                <fullName>Core Client</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>Current Broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Payroll frequency</description>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 Weekly</fullName>
            </value>
            <value>
                <fullName>2 Bi-weekly</fullName>
            </value>
            <value>
                <fullName>3 Semi-monthly</fullName>
            </value>
            <value>
                <fullName>4 Monthly</fullName>
            </value>
            <value>
                <fullName>5 Quarterly</fullName>
            </value>
            <value>
                <fullName>6 Semi-annually</fullName>
            </value>
            <value>
                <fullName>7 Annually</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/MktgId__c.field-meta.xml
<CustomField>
    <fullName>MktgId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Id from Marketing (Marketo) used to identify this record in that system.</inlineHelpText>
    <label>Mktg Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/OwnedByPrev__c.field-meta.xml
<CustomField>
    <fullName>OwnedByPrev__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The previous value of the owned by field.</inlineHelpText>
    <label>OwnedByPrev</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TaskOrphanCall__c/TaskOrphanCall__c.object-meta.xml
<CustomObject>
    <description>These are tasks that are calls that are not linked to a lead, contact, or account.</description>
    <label>Task Orphan Call</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Task Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Orphan Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskOrphanCall__c/fields/CallDateTime__c.field-meta.xml
<CustomField>
    <fullName>CallDateTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Date and Time of the call</inlineHelpText>
    <label>Call Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TaskOrphanCall__c/fields/Drift_Activity__c.field-meta.xml
<CustomField>
    <fullName>Drift_Activity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Drift Activity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TaskOrphanCall__c/fields/EventId__c.field-meta.xml
<CustomField>
    <fullName>EventId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>EventId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TaskOrphanCall__c/fields/MatchId__c.field-meta.xml
<CustomField>
    <fullName>MatchId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>If this task is matched to a lead, contact, or account put the id here.</inlineHelpText>
    <label>Match Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TaskOrphanCall__c/fields/NbrAttempts__c.field-meta.xml
<CustomField>
    <fullName>NbrAttempts__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The number of attempts made to match this record</inlineHelpText>
    <label>Nbr Attempts</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskOrphanCall__c/fields/TaskId__c.field-meta.xml
<CustomField>
    <fullName>TaskId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Task Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TaskOrphanCallMethods.cls
/** Trigger on the TaskOrphanCall__c object.
 *
 * History
 * -------
   03/31/2017 Dan Carmen        Created.
   12/10/2018 Dan Carmen        Set to work with DialSource
   04/13/2021 Brandon Vidro     Modified to work with Drift Chats/Meetings
   04/17/2021 Dan Carmen        Added call to queryActivityEmailMap
   
*/
public without sharing class TaskOrphanCallMethods {
   
   public static Boolean SKIP_TRIGGER=false;

   // do we want to search tasks if there's nothing connected to them?
   public static Boolean SEARCH_TASKS = Label.TaskHelper_SearchTasks == 'Y';
   public static Boolean PROCESS_DRIFT_TASKS = Label.TaskOrphan_ProcessDriftTasks == 'Y';

   public static void handleTrigger(TaskOrphanCall__c[] newRecs, Map<Id, TaskOrphanCall__c> oldMap) {
      if (SEARCH_TASKS) {
         Id[] taskIds = new Id[]{};
         Id[] eventIds = new Id[]{};
         Set<Id> orphanIdSet = new Set<Id>();
         Set<Id> orphanEvtIdSet = new Set<Id>();
         for (TaskOrphanCall__c toc : newRecs) {
            if (String.isBlank(toc.MatchId__c) && String.isNotBlank(toc.TaskId__c)) {
               taskIds.add((Id)toc.TaskId__c);
               orphanIdSet.add(toc.Id);
            }
            if (String.isNotBlank(toc.TaskId__c) && toc.Drift_Activity__c) {
               taskIds.add((Id)toc.TaskId__c);
               orphanIdSet.add(toc.Id);                
            }
            if (String.isNotBlank(toc.EventId__c) && toc.Drift_Activity__c) {
                eventIds.add((Id)toc.EventId__c);
                orphanEvtIdSet.add(toc.Id);                
            }
         } // for (TaskOrphanCall__c toc
         if (!orphanIdSet.isEmpty()) {
            checkProcessIds(orphanIdSet, taskIds);
         }
         if (!orphanEvtIdSet.isEmpty()) {
             checkProcessIdsEvts(orphanEvtIdSet, eventIds);
         }
      } // if (SEARCH_TASKS
   } // handleTrigger
   
   public static void checkProcessIds(Set<Id> orphanIdSet, Id[] taskIds) {
      if (System.isFuture() || System.isBatch()) {
         processIds(orphanIdSet, taskIds);
      } else {
         processIdsFuture(orphanIdSet, taskIds);
      }
   } // checkProcessIds
   
   @future
   public static void processIdsFuture(Set<Id> orphanIdSet, Id[] taskIds) {
      processIds(orphanIdSet, taskIds);
   } // processIdsFuture
   
   public class TskWrapper {
      public TaskOrphanCall__c toc;
      public Task tsk;
   } // classTskWrapper
    
    public static void checkProcessIdsEvts(Set<Id> orphanIdSet, Id[] eventIds) {
        if (System.isFuture() || System.isBatch()) {
            processEvtIds(orphanIdSet, eventIds);
        } else {
            processIdsFutureEvts(orphanIdSet, eventIds);
        }
    } // checkProcessIds
    
    @future
    public static void processIdsFutureEvts(Set<Id> orphanIdSet, Id[] eventIds) {
        processEvtIds(orphanIdSet, eventIds);
    } // processIdsFuture
    
    public class EvtWrapper {
        public TaskOrphanCall__c toc;
        public Event evt;
    } // classTskWrapper
   
   public static void processIds(Set<Id> orphanIdSet, Id[] taskIds) {
      System.debug('processIds orphanIdSet='+orphanIdSet.size()+' taskIds='+taskIds.size());
      TaskOrphanCall__c[] tocs = [Select Id, Name
                                        ,MatchId__c
                                        ,NbrAttempts__c
                                        ,Phone__c
                                        ,Email__c
                                        ,TaskId__c
                                    From TaskOrphanCall__c
                                   Where Id in :orphanIdSet];
                   
      Map<Id,Task> taskMap = TaskHelper.queryTaskMap(taskIds);
      Id[] whoIds = new Id[]{};
      for (Task tsk : taskMap.values()) {
          if (tsk.WhoId != null) {
              whoIds.add(tsk.WhoId);
          }
      }
      Map<Id, String> emailMap = TaskHelper.queryActivityEmailMap(whoIds);
      Map<String, TskWrapper[]> tskByPhoneMap = new Map<String, TskWrapper[]>();
      Map<String, TskWrapper[]> tskByEmailMap = new Map<String, TskWrapper[]>();
      DateTime earliestCallTime = DateTime.now();
            
      for (TaskOrphanCall__c toc : tocs) {
         Task tsk = taskMap.get(toc.TaskId__c);
         String email = emailMap.get(tsk.WhoId);
         if (tsk != null) {
            toc.NbrAttempts__c = (toc.NbrAttempts__c == null ? 0 : toc.NbrAttempts__c) + 1;
            
            if (toc.Phone__c == null && tsk.DS_Denali__DialSource_Action__r != null && tsk.DS_Denali__DialSource_Action__r.DS_Denali__Phone__c != null) {
               toc.Phone__c = tsk.DS_Denali__DialSource_Action__r.DS_Denali__Phone__c;
            }
            if (toc.Email__c == null && tsk.Subject.contains(Label.Drift_Task_Subject) && (tsk.Type.contains(Label.TrackRecord_Chat) || tsk.Type.contains(Label.Drift_Task_Type)) && email != null) {
               toc.Email__c = email; 
            }
            String phoneKey = Utilities.removeExtraChars(toc.Phone__c, Utilities.ALL_NUMBERS);
            String emailNew = '';
            if(String.isNotBlank(toc.Email__c)) {
            	emailNew = (String)toc.Email__c;
            }
            if (String.isNotBlank(phoneKey)) {
               phoneKey = phoneKey.left(10);
            }
            // make sure we have the right sized string
            if (phoneKey != null && phoneKey.length() == 10) {
               TskWrapper wrap = new TskWrapper();
               wrap.toc = toc; 
               wrap.tsk = tsk;
               TskWrapper[] wraps = (tskByPhoneMap.containsKey(phoneKey) ? tskByPhoneMap.get(phoneKey) : new TskWrapper[]{});
               wraps.add(wrap);
               tskByPhoneMap.put(phoneKey, wraps);
               if (tsk.CallDateTime__c != null && tsk.CallDateTime__c < earliestCallTime) {
                  earliestCallTime = tsk.CallDateTime__c;
               }
            } // if (phoneKey.length() == 10
            if (email != null && String.isNotBlank(email)) {
               TskWrapper wrap = new TskWrapper();
               wrap.toc = toc; 
               wrap.tsk = tsk;
               TskWrapper[] wraps = (tskByEmailMap.containsKey(email) ? tskByEmailMap.get(email) : new TskWrapper[]{});
               wraps.add(wrap);
               tskByEmailMap.put(email, wraps);
               if (tsk.CallDateTime__c != null && tsk.CallDateTime__c < earliestCallTime) {
                  earliestCallTime = tsk.CallDateTime__c;
               }               
            } 
         } // if (tsk != null
      } // for (TaskOrphanCall__c toc
      if (!tskByPhoneMap.isEmpty()) {
         searchForRelatedTaskRecords(earliestCallTime, tskByPhoneMap, tocs);
      }
      if (!tskByEmailMap.isEmpty()) {
         searchForRelatedTaskRecordsByEmail(earliestCallTime, tskByEmailMap, tocs);
      }
      SKIP_TRIGGER = true;
      DmlHelper.performDML2(tocs, DmlHelper.DML_UPDATE, 'TaskOrphanCallMethods', 'searchForRelatedTaskRecords', 'Update Orphan Record', true);

   } // processIds
    
    public static void processEvtIds(Set<Id> orphanEvtIdSet, Id[] eventIds) {
      System.debug('processIds orphanEvtIdSet='+orphanEvtIdSet.size()+' eventIds='+eventIds.size());
      TaskOrphanCall__c[] tocs = [Select Id, Name
                                        ,MatchId__c
                                        ,NbrAttempts__c
                                        ,Phone__c
                                        ,Email__c
                                        ,TaskId__c
										,EventId__c
                                    From TaskOrphanCall__c
                                   Where Id in :orphanEvtIdSet];
                   
      Map<Id,Event> eventMap = queryEventMap(eventIds);
      Id[] whoIds = new Id[]{};
      for (Event evt : eventMap.values()) {
         if (evt.WhoId != null) {
            whoIds.add(evt.WhoId);
         }
      }
      Map<Id, String> emailMap = TaskHelper.queryActivityEmailMap(whoIds);
      Map<String, EvtWrapper[]> evtByPhoneMap = new Map<String, EvtWrapper[]>();
      Map<String, EvtWrapper[]> evtByEmailMap = new Map<String, EvtWrapper[]>();
      DateTime earliestCallTime = DateTime.now();
            
      for (TaskOrphanCall__c toc : tocs) {
         Event evt = eventMap.get(toc.EventId__c);
         String email = emailMap.get(evt.WhoId);
         if (evt != null) {
            toc.NbrAttempts__c = (toc.NbrAttempts__c == null ? 0 : toc.NbrAttempts__c) + 1;

            if (toc.Email__c == null && evt.Subject == Label.Drift_Event_Subject) {
               toc.Email__c = email; 
            }
            String emailNew = '';
            if(toc.Email__c != null && String.isNotBlank(toc.Email__c)) {
            	emailNew = (String)toc.Email__c;
            }
            if (email != null && String.isNotBlank(email)) {
               EvtWrapper wrap = new EvtWrapper();
               wrap.toc = toc; 
               wrap.evt = evt;
               EvtWrapper[] wraps = (evtByEmailMap.containsKey(email) ? evtByEmailMap.get(email) : new EvtWrapper[]{});
               wraps.add(wrap);
               evtByEmailMap.put(email, wraps);         
            } 
         } // if (evt != null
      } // for (TaskOrphanCall__c toc
      if (!evtByEmailMap.isEmpty()) {
         searchForRelatedEvtRecordsByEmail(earliestCallTime, evtByEmailMap, tocs);
      }
      SKIP_TRIGGER = true;
      DmlHelper.performDML2(tocs, DmlHelper.DML_UPDATE, 'TaskOrphanCallMethods', 'searchForRelatedEvtRecordsByEmail', 'Update Orphan Record', true);

   } // processIds
   
   // do we log the search results in the error log object?
   public static Boolean LOG_TASK_SEARCH = Label.TaskHelper_LogTaskSearch=='Y';

   public static ErrorLog__c errLog;
   public static void addToErrorDescription(String descToAdd) {
      if (errLog != null) {
         errLog.Description__c = ((String.isNotBlank(errLog.Description__c) ? errLog.Description__c+'\n' : '') 
                                      + descToAdd).left(ErrorLog.DESCRIPTION_SIZE);
      }
   } // addToErrorDescription

   public static List<List<SObject>> TEST_QUERY_RESULTS = new List<List<SObject>>();
    
   public static void searchForRelatedTaskRecordsByEmail(DateTime earliestCallTime, Map<String,TskWrapper[]> tskByEmailMap, TaskOrphanCall__c[] tocs) {
      String emailStr = '';
      for (String emailKey : tskByEmailMap.keySet()) {
         emailStr += (String.isNotBlank(emailStr) ? ' OR ' : '')+'"'+emailKey+'"';
      }
      
      if (String.isNotBlank(emailStr)) {
         TaskOrphanCall__c[] updateOrphans = new TaskOrphanCall__c[]{};
         Task[] updateTasks = new Task[]{};
         Lead[] updateLeads = new Lead[]{};
         Contact[] updateContacts = new Contact[]{};
         List<List<SObject>> queryResults;
          
            DateTime queryTime = earliestCallTime.addHours(-1);
            queryResults = [FIND :emailStr IN EMAIL FIELDS RETURNING
                            Lead(Id, OwnerId, Email, Company, Street, City, State, PostalCode, FirstName, LastName, Phone, NumberOfEmployees, Frequency__c, OwnedByPrev__c, LeadSource, MktgId__c,
                                 Current_Prior_Method__c, LastModifiedDate, CreatedDate, RecordTypeId, Bank_Product_Of_Interest__c where 
                                 IsConverted=false and MktgId__c != null order by LastModifiedDate desc)
                            ,Contact(Id, AccountId, LastModifiedDate, CreatedDate, Email, MktgId__c, MailingStreet, MailingCity, MailingState, MailingPostalCode, Name, Phone
                                     where HR_Person_Id__c = null and MktgId__c != null
                                     order by LastModifiedDate desc)
                           ];
                   
         if (!queryResults.isEmpty()) {
            if (!tskByEmailMap.isEmpty()) {
            	checkResultsEmail((queryResults.size() >= 1 ? queryResults[0] : new Sobject[]{})
                              , ObjectHelper.OBJECT_LEAD, tskByEmailMap, updateOrphans, updateTasks, updateLeads, updateContacts);
            }
            if (!tskByEmailMap.isEmpty()) {
                checkResultsEmail((queryResults.size() >= 2 ? queryResults[1] : new Sobject[]{})
                              , ObjectHelper.OBJECT_CONTACT, tskByEmailMap, updateOrphans, updateTasks, updateLeads, updateContacts);
            }
            if (!updateTasks.isEmpty()) {
               TaskHelper.SKIP_TRIGGERS=true;
               DmlHelper.performDML2(updateTasks, DmlHelper.DML_UPDATE, 'TaskOrphanCallMethods', 'searchForRelatedTaskRecordsByEmail', 'Update Tasks', true);
            }
            if (!updateLeads.isEmpty()) {
               TriggerMethods.SKIP_TRIGGERS=true;
               DmlHelper.performDML2(updateLeads, DmlHelper.DML_UPDATE, 'TaskOrphanCallMethods', 'searchForRelatedTaskRecordsByEmail', 'Update Leads', true);
            }
            if (!updateContacts.isEmpty()) {
               ContactMethods.CONTACT_BEFORE_TRIGGER_EXECUTING=true;
               ContactMethods.CONTACT_AFTER_TRIGGER_EXECUTING=true;
               DmlHelper.performDML2(updateContacts, DmlHelper.DML_UPDATE, 'TaskOrphanCallMethods', 'searchForRelatedTaskRecordsByEmail', 'Update Contacts', true);
            }             
         }
      } // if (String.isNotBlank(emailStr
   } // searchForRelatedTaskRecordsByEmail
    
  public static void searchForRelatedEvtRecordsByEmail(DateTime earliestCallTime, Map<String,EvtWrapper[]> evtByEmailMap, TaskOrphanCall__c[] tocs) {
      String emailStr = '';
      for (String emailKey : evtByEmailMap.keySet()) {
         emailStr += (String.isNotBlank(emailStr) ? ' OR ' : '')+'"'+emailKey+'"';
      }
      
      if (String.isNotBlank(emailStr)) {
         TaskOrphanCall__c[] updateOrphans = new TaskOrphanCall__c[]{};
         Event[] updateEvents = new Event[]{};
         Lead[] updateLeads = new Lead[]{};
         Contact[] updateContacts = new Contact[]{};
         List<List<SObject>> queryResults;
          
            DateTime queryTime = earliestCallTime.addHours(-1);
            // order by the last modified date to use the latest first.
            queryResults = [FIND :emailStr IN EMAIL FIELDS RETURNING
                            Lead(Id, OwnerId, Email, Company, Street, City, State, PostalCode, FirstName, LastName, Phone, NumberOfEmployees, Frequency__c, Current_Prior_Method__c, LeadSource, MktgId__c,
                                 LastModifiedDate, CreatedDate, Bank_Product_Of_Interest__c, RecordTypeId, OwnedByPrev__c
                                 where IsConverted=false and MktgId__c != null order by LastModifiedDate desc)
                            ,Contact(Id, AccountId, LastModifiedDate, CreatedDate, Email, MktgId__c, MailingStreet, MailingCity, MailingState, MailingPostalCode, Name, Phone
                                     where HR_Person_Id__c = null and MktgId__c != null
                                     order by LastModifiedDate desc)
                           ];
                   
         if (!queryResults.isEmpty()) {
            if (!evtByEmailMap.isEmpty()) {
            	checkResultsEmailEvents((queryResults.size() >= 1 ? queryResults[0] : new Sobject[]{})
                              , ObjectHelper.OBJECT_LEAD, evtByEmailMap, updateOrphans, updateEvents, updateLeads, updateContacts);
            }
            if (!evtByEmailMap.isEmpty()) {
                checkResultsEmailEvents((queryResults.size() >= 2 ? queryResults[1] : new Sobject[]{})
                              , ObjectHelper.OBJECT_CONTACT, evtByEmailMap, updateOrphans, updateEvents, updateLeads, updateContacts);
            }
            if (!updateEvents.isEmpty()) {
               DmlHelper.performDML2(updateEvents, DmlHelper.DML_UPDATE, 'TaskOrphanCallMethods', 'searchForRelatedEvtRecordsByEmail', 'Update Events', true);
            }
            if (!updateLeads.isEmpty()) {
               TriggerMethods.SKIP_TRIGGERS=true;
               DmlHelper.performDML2(updateLeads, DmlHelper.DML_UPDATE, 'TaskOrphanCallMethods', 'searchForRelatedEvtRecordsByEmail', 'Update Leads', true);
            }
            if (!updateContacts.isEmpty()) {
               ContactMethods.CONTACT_BEFORE_TRIGGER_EXECUTING=true;
               ContactMethods.CONTACT_AFTER_TRIGGER_EXECUTING=true;
               DmlHelper.performDML2(updateContacts, DmlHelper.DML_UPDATE, 'TaskOrphanCallMethods', 'searchForRelatedEvtRecordsByEmail', 'Update Contacts', true);
            }             
         }
      } // if (String.isNotBlank(emailStr
   } // searchForRelatedEvtRecordsByEmail

   public static void searchForRelatedTaskRecords(DateTime earliestCallTime, Map<String,TskWrapper[]> tskByPhoneMap, TaskOrphanCall__c[] tocs) {
      // create an ErrorLog__c record to record what's happening.
      if (LOG_TASK_SEARCH) {
         errLog = new ErrorLog__c(ClassName__c='TaskOrphanCallMethods',MethodName__c='searchForRelatedTaskRecords',CodeKey__c='LOG_DATA', BatchSize__c=tskByPhoneMap.size(), NbrSuccess__c=0);
      }
      String phoneStr = '';
      for (String phoneKey : tskByPhoneMap.keySet()) {
         phoneStr += (String.isNotBlank(phoneStr) ? ' OR ' : '')+'"'+phoneKey+'"';
      }
      addToErrorDescription('Earliest Call Time='+earliestCallTime.format('M/d/yyyy HH:mm:ss'));
      
      if (String.isNotBlank(phoneStr)) {
         TaskOrphanCall__c[] updateOrphans = new TaskOrphanCall__c[]{};
         Task[] updateTasks = new Task[]{};
             
         List<List<SObject>> queryResults;
          
            DateTime queryTime = earliestCallTime.addDays(-2);
            // order by the last modified date to use the latest first.
            queryResults = [FIND :phoneStr IN PHONE FIELDS RETURNING
                            Lead(Id, Phone, MobilePhone, LastModifiedDate where IsConverted=false and LastModifiedDate >= :queryTime order by LastModifiedDate desc)
                            ,Contact(Id, AccountId, Phone, HomePhone, MobilePhone, OtherPhone, LastModifiedDate 
                                            where LastModifiedDate >= :queryTime
                                              and HR_Person_Id__c = null    // exclude employee contacts 
                                            order by LastModifiedDate desc)
                            ,Account(Id, Phone, LastModifiedDate 
                                            where LastModifiedDate >= :queryTime
                                              and Name != :Label.Paychex_Account
                                            order by LastModifiedDate desc)
                           ];
                   
         if (!queryResults.isEmpty()) {
            
            checkResults((queryResults.size() >= 1 ? queryResults[0] : new Sobject[]{})
                              , ObjectHelper.OBJECT_LEAD, tskByPhoneMap, updateOrphans, updateTasks);
            if (!tskByPhoneMap.isEmpty()) {
               checkResults((queryResults.size() >= 2 ? queryResults[1] : new Sobject[]{})
                              , ObjectHelper.OBJECT_CONTACT, tskByPhoneMap, updateOrphans, updateTasks);
            }
            if (!tskByPhoneMap.isEmpty()) {
               checkResults((queryResults.size() >= 3 ? queryResults[2] : new Sobject[]{})
                              , ObjectHelper.OBJECT_ACCOUNT, tskByPhoneMap, updateOrphans, updateTasks);
            }

            if (!updateTasks.isEmpty()) {
               TaskHelper.SKIP_TRIGGERS=true;
               DmlHelper.performDML2(updateTasks, DmlHelper.DML_UPDATE, 'TaskOrphanCallMethods', 'searchForRelatedTaskRecords', 'Update Tasks', true);
            }

         }
      } // if (String.isNotBlank(phoneStr
      if (LOG_TASK_SEARCH && errLog != null) {
         errLog.NbrFailure__c = tskByPhoneMap.size();
         Database.insert(errLog,false);
      }
   } // searchForRelatedTaskRecords
   
   public static void checkResults(SObject[] objectList, String objectType, Map<String,TskWrapper[]> tskByPhoneMap
                                             , TaskOrphanCall__c[] updateOrphans, Task[] updateTasks) {
      addToErrorDescription('objectType='+objectType+' objectList='+objectList+' tskByPhoneMap='+tskByPhoneMap.size());
                                                 
      for (SObject obj : objectList) {
         TskWrapper[] wraps = checkForWraps(obj, 'Phone', tskByPhoneMap);
         if (wraps == null && (objectType == ObjectHelper.OBJECT_LEAD || objectType == ObjectHelper.OBJECT_CONTACT)) {
            wraps = checkForWraps(obj, 'MobilePhone', tskByPhoneMap);
         }
         if (wraps == null && objectType == ObjectHelper.OBJECT_CONTACT) {
            wraps = checkForWraps(obj, 'HomePhone', tskByPhoneMap);
         }
         if (wraps == null && objectType == ObjectHelper.OBJECT_CONTACT) {
            wraps = checkForWraps(obj, 'OtherPhone', tskByPhoneMap);
         }
            if (wraps != null) {
               for (TskWrapper wrap : wraps) {
                  wrap.tsk.Description = 'TaskOrphanCallMethods Found match by phone on '+objectType;
                  if (objectType == ObjectHelper.OBJECT_LEAD) {
                     wrap.tsk.WhoId = obj.Id;
                  } else if (objectType == ObjectHelper.OBJECT_CONTACT) {
                     Contact ctct = (Contact)obj;
                     wrap.tsk.WhoId = ctct.Id;
                     wrap.tsk.WhatId = ctct.AccountId;
                  } else if (objectType == ObjectHelper.OBJECT_ACCOUNT) {
                     wrap.tsk.WhatId = obj.Id;
                  }
                  addToErrorDescription('   tsk='+wrap.tsk.Id+' match='+obj.Id);
                  updateTasks.add(wrap.tsk);
                  wrap.toc.MatchId__c = obj.Id;
                  updateOrphans.add(wrap.toc);
               } // for (TskWrapper wrap
               errLog.NbrSuccess__c++;
            } // if (wraps != null
      } // for (Object obj
   } // checkResults
    
   public static Boolean chatterSent = false;
   public static Boolean chatterSentTsk = false;
   public static Boolean chatterSentEvt = false;
   public static Boolean chatterAdded = false;
   public static Boolean chatterAddedEvt = false;
   public static Boolean chatterAddedTsk = false;
   
    public static void checkResultsEmail(SObject[] objectList, String objectType, Map<String,TskWrapper[]> tskByEmailMap
                                             , TaskOrphanCall__c[] updateOrphans, Task[] updateTasks, Lead[] updateLeads, Contact[] updateContacts) {
      System.debug('checkResultsEmail objectList='+objectList.size());
      if(!PROCESS_DRIFT_TASKS)  {
      	return;
      }                                         
      Id mentionId = null;
      Id mentionIdTask = null;                                          
      List<String> chatterMsgs = new List<String>();
      List<String> chatterMsgsTsks = new List<String>();                                           
      List<Id> mentionIds = new List<Id>(); 
      List<Id> mentionIdsTsks = new List<Id>();
                                         
      for (SObject obj : objectList) {
         TskWrapper[] wraps = checkForWrapsEmail(obj, 'Email', tskByEmailMap);
         System.debug('checkResultsEmail wraps='+(wraps == null ? -1 : wraps.size()));
         if (wraps == null && (objectType == ObjectHelper.OBJECT_LEAD || objectType == ObjectHelper.OBJECT_CONTACT)) {
            wraps = checkForWrapsEmail(obj, 'Email', tskByEmailMap);
         }
            if (wraps != null) {
               for (TskWrapper wrap : wraps) {
                  wrap.tsk.Description += '\nTaskOrphanCallMethods Found match by email on '+objectType;
                  if (objectType == ObjectHelper.OBJECT_LEAD) {
                      Lead ld = (Lead)obj;
                      wrap.tsk.WhoId = obj.Id;
                      wrap.tsk.RecordTypeId = RecordTypeHelper.getRecordType('NSS Task','Task').getRecordTypeId(); 
                      if(ld.OwnerId != null && ld.OwnerId == Label.Drift_Chat_Queue_Id) {
                          ld.OwnerId = wrap.tsk.OwnerId;
                          if(!chatterAdded){
                              mentionId = ld.OwnerId;
                              mentionIds.add(mentionId);
                              String chatterMsg = 'This Lead record has been assigned to you.\n';
                              chatterMsg += ChatterMentionPost.buildChatterMessage(ld);
                              chatterMsgs.add(chatterMsg);
                              chatterAdded = true;
						  }
                          updateLeads.add(ld);
                      }
                      if(!chatterAddedTsk) {
                      	mentionIdTask= wrap.tsk.OwnerId;
                        mentionIdsTsks.add(mentionIdTask);
                        String chatterMsgTsk = 'This Task record has been assigned to you.\n';
						chatterMsgTsk += ChatterMentionPost.buildChatterMessage(ld);
						chatterMsgsTsks.add(chatterMsgTsk);
                        chatterAddedTsk = true;
                      }
                  } else if (objectType == ObjectHelper.OBJECT_CONTACT) {
                      Contact ctct = (Contact)obj;
                      wrap.tsk.WhoId = obj.Id;
                      wrap.tsk.RecordTypeId = RecordTypeHelper.getRecordType('NSS Task','Task').getRecordTypeId(); 
                      if(!chatterAddedTsk) {
                      	mentionIdTask= wrap.tsk.OwnerId;
                        mentionIdsTsks.add(mentionIdTask);
                        String chatterMsgTsk = 'This Task record has been assigned to you.\n';
						chatterMsgTsk += ChatterMentionPost.buildChatterMessage(ctct);
						chatterMsgsTsks.add(chatterMsgTsk);
                        chatterAddedTsk = true;
                      }
                  }
                  updateTasks.add(wrap.tsk);
                  wrap.toc.MatchId__c = obj.Id;
                  updateOrphans.add(wrap.toc);
                  if(!chatterSentTsk){
                  	ChatterMentionPost.createChatterMentionPost(wrap.tsk.Id, mentionIdsTsks, chatterMsgsTsks, false, true);
           	 		chatterSentTsk = true; 
                  }
               } // for (TskWrapper wrap
            } // if (wraps != null
          	if(!chatterSent) {
          		ChatterMentionPost.createChatterMentionPost(obj.Id, mentionIds, chatterMsgs, false, false);
           	 	chatterSent = true;
            }
      } // for (Object obj   
   } // checkResults
    
   public static void checkResultsEmailEvents(SObject[] objectList, String objectType, Map<String,EvtWrapper[]> evtByEmailMap
                                             , TaskOrphanCall__c[] updateOrphans, Event[] updateEvents, Lead[] updateLeads, Contact[] updateContacts) {
      Id mentionIdEvent = null;                                          
      List<String> chatterMsgsEvts = new List<String>();                                           
      List<Id> mentionIdsEvts = new List<Id>(); 
      
      if(!PROCESS_DRIFT_TASKS)  {
      	return;
      }                                               
      for (SObject obj : objectList) {
         EvtWrapper[] wraps = checkForWrapsEmailEvent(obj, 'Email', evtByEmailMap);
         if (wraps == null && (objectType == ObjectHelper.OBJECT_LEAD || objectType == ObjectHelper.OBJECT_CONTACT)) {
            wraps = checkForWrapsEmailEvent(obj, 'Email', evtByEmailMap);
         }
            if (wraps != null) {
               for (EvtWrapper wrap : wraps) {
                  wrap.evt.Description += '\nTaskOrphanCallMethods Found match by email on '+objectType;
                  if (objectType == ObjectHelper.OBJECT_LEAD) {
                      Lead ld = (Lead)obj;
                      wrap.evt.WhoId = obj.Id;
                      wrap.evt.RecordTypeId = ld.RecordTypeId;
                          if(!chatterAddedEvt){
                              mentionIdEvent= wrap.evt.OwnerId;
                              mentionIdsEvts.add(mentionIdEvent);
                              String chatterMsgEvt = 'This Event record has been assigned to you.\n';
                              chatterMsgEvt += ChatterMentionPost.buildChatterMessage(ld);
                              chatterMsgsEvts.add(chatterMsgEvt);
                              chatterAddedEvt = true;
                          }
                  } else if (objectType == ObjectHelper.OBJECT_CONTACT) {
                      Contact ctct = (Contact)obj;
                      wrap.evt.WhoId = obj.Id;
                      if(!chatterAddedEvt) {
                      	mentionIdEvent= wrap.evt.OwnerId;
                        mentionIdsEvts.add(mentionIdEvent);
                        String chatterMsgEvt = 'This Event record has been assigned to you.\n';
						chatterMsgEvt += ChatterMentionPost.buildChatterMessage(ctct);
						chatterMsgsEvts.add(chatterMsgEvt);
                        chatterAddedEvt = true;
                      }
                  } 
                  updateEvents.add(wrap.evt);
                  wrap.toc.MatchId__c = obj.Id;
                  updateOrphans.add(wrap.toc);
                  if(!chatterSentEvt){
                  	ChatterMentionPost.createChatterMentionPost(wrap.evt.Id, mentionIdsEvts, chatterMsgsEvts, false, true);
           	 		chatterSentEvt = true; 
                  }
               } // for (TskWrapper wrap
            } // if (wraps != null
      } // for (Object obj   
   } // checkResults
   
   public static TskWrapper[] checkForWraps(SObject obj, String phoneFld, Map<String,TskWrapper[]> tskByPhoneMap) {
      TskWrapper[] wraps = null;
      String phoneNbr = (String)obj.get(phoneFld);
      String phoneKey = (String.isNotBlank(phoneNbr) ? Utilities.removeExtraChars(phoneNbr, Utilities.ALL_NUMBERS).left(10) : null);
      if (String.isNotBlank(phoneKey)) {
         wraps = tskByPhoneMap.remove(phoneKey);
      }
      if (wraps != null) {
         addToErrorDescription('TaskOrphanCallMethods checkForWraps found match on '+phoneFld+' for number '+phoneNbr+' match='+obj.Id);
      }
      return wraps;
   }
       
   public static TskWrapper[] checkForWrapsEmail(SObject obj, String emailFld, Map<String,TskWrapper[]> tskByEmailMap) {
      TskWrapper[] wraps = null;
      String emailKey = (String)obj.get(emailFld);
      if (String.isNotBlank(emailKey)) {
         wraps = tskByEmailMap.remove(emailKey);
      }
      return wraps;
   } // checkForWraps
    
  public static EvtWrapper[] checkForWrapsEmailEvent(SObject obj, String emailFld, Map<String,EvtWrapper[]> evtByEmailMap) {
        EvtWrapper[] wraps = null;
        String emailKey = (String)obj.get(emailFld);
        if (String.isNotBlank(emailKey)) {
            wraps = evtByEmailMap.remove(emailKey);
        }
        return wraps;
    } // checkForWraps
    
   public static Map<Id,Event> queryEventMap(Id[] eventIds) {
        
      DateTime queryDate = DateTime.now().addDays(-TaskHelper.TASK_NBR_DAYS);
      Map<Id,Event> eventMap = new Map<Id,Event>([Select Id, WhoId, WhatId, AccountId, OwnerId
                             ,ActivityDate
                             ,RecordTypeId
                             ,RecordType.Id,RecordType.Name
                             ,CreatedDate
                             ,Subject
                             ,Description
                             ,ReminderDateTime
                             ,Type
                         from Event
                        Where Id in :eventIds
                          and CreatedDate >= :queryDate 
                          ]);
      return eventMap;
   } // queryEventMap
    /*
   public static Map<Id,String> queryEventEmailMap(Id[] eventIds) {
        
      DateTime queryDate = DateTime.now().addDays(-TaskHelper.TASK_NBR_DAYS);
      Map<Id,String> emailMap = new Map<Id,String>();
      List<Event> evts = new List<Event>();
      List<Lead> leads = new List<Lead>();
      List<Contact> contacts = new List<Contact>();
      Set<Id> whoIds = new Set<Id>();
      evts = [Select Id, WhoId, WhatId, AccountId, OwnerId
                             ,ActivityDate
                             ,RecordTypeId
                             ,RecordType.Id,RecordType.Name
                             ,CreatedDate
                             ,Subject
                             ,Description
                             ,ReminderDateTime
                             ,Type
                         from Event
                        Where Id in :eventIds
                          and CreatedDate >= :queryDate];
      if(evts != null) {
          for(Event evt: evts) {
              whoIds.add(evt.WhoId);
          }   
      }
      leads = [Select Id, Email from Lead where Id in :whoIds];
      contacts = [Select Id, Email from Contact where Id in :whoIds];
      if(leads != null) {
          for(Lead ld: leads) {
              emailMap.put(ld.Id, ld.Email);
          }
      }
      if(contacts != null) {
          for(Contact ct: contacts) {
              emailMap.put(ct.Id, ct.Email);
          }
      }
      return emailMap;
   } // queryTaskEmailMap
   */
} // class TaskOrphanCallMethods