force-app/main/default/objects/Account/fields/CurrentClient__c.field-meta.xml
<CustomField>
    <fullName>CurrentClient__c</fullName>
    <formula>OR(
AND( (Bis_ID__c &gt; 0)
,NOT(ISBLANK(First_Run_Date__c))
,ISBLANK(Lost_Date__c)
,( TEXT(Type) != &quot;Lost Client&quot;)
,( TEXT(Type) != &quot;HRS Client (Only)&quot;)
,( TEXT(Type) != &quot;HR Solutions NPR Client&quot;))
,(TEXT(Type) = &quot;HROi Client&quot;)
,(TEXT(Type) = &quot;Oasis Client&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Is this a current client?</inlineHelpText>
    <label>Current Client?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/PEO_ASO_Permanent_Hold_Out_Description__c.field-meta.xml
<CustomField>
    <fullName>PEO_ASO_Permanent_Hold_Out_Description__c</fullName>
    <inlineHelpText>The Reason for the PEO-ASO Holdout</inlineHelpText>
    <label>HR Services Hold Out Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>672249</fullName>
            </value>
            <value>
                <fullName>DNC Protected</fullName>
            </value>
            <value>
                <fullName>Field Account Managed</fullName>
            </value>
            <value>
                <fullName>FY23 Protected Accounts</fullName>
            </value>
            <value>
                <fullName>International Zip</fullName>
            </value>
            <value>
                <fullName>Market Segmentation Policy</fullName>
            </value>
            <value>
                <fullName>MMS-ASO Partnership</fullName>
            </value>
            <value>
                <fullName>Multi-ID Child Record</fullName>
            </value>
            <value>
                <fullName>PEO Expansion</fullName>
            </value>
            <value>
                <fullName>PO Box Exception</fullName>
            </value>
            <value>
                <fullName>Private Equity</fullName>
            </value>
            <value>
                <fullName>Project Blue Phase 0</fullName>
            </value>
            <value>
                <fullName>Shared Zip</fullName>
            </value>
            <value>
                <fullName>Strategic Account Team</fullName>
            </value>
            <value>
                <fullName>SurePayroll ERTC</fullName>
            </value>
            <value>
                <fullName>SurePayroll HR Sale</fullName>
            </value>
            <value>
                <fullName>Territory Exception</fullName>
            </value>
            <value>
                <fullName>Up Market (50+ employees)</fullName>
            </value>
            <value>
                <fullName>VS Account Managed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Premier_PBS_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Premier_PBS_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>HRS PEO-ASO Sales territory rep owner</description>
    <label>HR Services Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Premier_PBS_Hold_Out__c.field-meta.xml
<CustomField>
    <fullName>Premier_PBS_Hold_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To signify Hold Out accounts that should not be transferred during PEO-ASO territory changes</description>
    <label>HR Services Hold Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Premier_PBS_Hold_Out_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Premier_PBS_Hold_Out_Expiration__c</fullName>
    <description>Date when Account-Contact should be returned to territory PEO-ASO rep ownership.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>HR Services Hold Out Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apex_Batch_Control__c/Apex_Batch_Control__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These are settings that can be used to implement some control over apex batch jobs.</description>
    <label>Apex Batch Control</label>
</CustomObject>

force-app/main/default/objects/Apex_Batch_Control__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Should the job run?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apex_Batch_Control__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <inlineHelpText>This is used by the UpdateZipOwnershipController to allow the batches to be manually launched.</inlineHelpText>
    <label>Batch Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_Batch_Control__c/fields/NbrOfAttempts__c.field-meta.xml
<CustomField>
    <fullName>NbrOfAttempts__c</fullName>
    <inlineHelpText>How many attempts to we make on each record?</inlineHelpText>
    <label>Nbr of Attempts</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Tracker__c/Job_Tracker__c.object-meta.xml
<CustomObject>
    <description>Track the status and output for Apex batch jobs.</description>
    <label>Job Tracker</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Tracker Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Tracker__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Job Id</inlineHelpText>
    <label>Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Tracker__c/fields/Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Job_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the Apex class for this job.</inlineHelpText>
    <label>Job Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Tracker__c/fields/Nbr_Batches__c.field-meta.xml
<CustomField>
    <fullName>Nbr_Batches__c</fullName>
    <inlineHelpText>The number of batches that ran</inlineHelpText>
    <label>Nbr Batches</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Tracker__c/fields/Nbr_Errors__c.field-meta.xml
<CustomField>
    <fullName>Nbr_Errors__c</fullName>
    <inlineHelpText>The number of batches that had errors</inlineHelpText>
    <label>Nbr Errors</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Tracker__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The output for this apex job.</inlineHelpText>
    <label>Notes</label>
    <length>15000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Tracker__c/fields/Process_End__c.field-meta.xml
<CustomField>
    <fullName>Process_End__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>When did this Process End?</inlineHelpText>
    <label>Process End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Job_Tracker__c/fields/Process_Start__c.field-meta.xml
<CustomField>
    <fullName>Process_Start__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>When did this job start?</inlineHelpText>
    <label>Process Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Job_Tracker__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The status of this job</inlineHelpText>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityType__c.field-meta.xml
<CustomField>
    <fullName>OpportunityType__c</fullName>
    <description>Used to determine whether or not an Opportunity is a duplicate. After resorting picklist order, always move the following values to the end of the list: Adjustment; True-Up; Chargeback; Balance.</description>
    <inlineHelpText>Is this a payroll or an HRS opportunity?</inlineHelpText>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Add-On ID</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>ASO</fullName>
                <label>HR Pro</label>
            </value>
            <value>
                <fullName>AUTO</fullName>
            </value>
            <value>
                <fullName>Balance</fullName>
            </value>
            <value>
                <fullName>BeneTrac Gold</fullName>
            </value>
            <value>
                <fullName>BeneTrac Platinum</fullName>
            </value>
            <value>
                <fullName>BND (ERISA BOND)</fullName>
            </value>
            <value>
                <fullName>BOP (Business Owners Package)</fullName>
            </value>
            <value>
                <fullName>Chargeback</fullName>
            </value>
            <value>
                <fullName>Conversion</fullName>
            </value>
            <value>
                <fullName>Cyber A Basic $250</fullName>
            </value>
            <value>
                <fullName>Cyber A Basic $300</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 1 $1,725</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 1 $750</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 2 $1,200</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 2 $1,940.63</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 3 $1,500</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 3 $3,151.58</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 4 $2,650</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 4 $5,304.38</fullName>
            </value>
            <value>
                <fullName>Digital Marketing</fullName>
            </value>
            <value>
                <fullName>Directors and Officers</fullName>
            </value>
            <value>
                <fullName>Disability</fullName>
            </value>
            <value>
                <fullName>Employment Practice Liability (EPLI)</fullName>
            </value>
            <value>
                <fullName>ERISA</fullName>
            </value>
            <value>
                <fullName>Errors and Omissions</fullName>
            </value>
            <value>
                <fullName>ERTC</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/HR_Services_Partner__c.field-meta.xml
<CustomField>
    <fullName>HR_Services_Partner__c</fullName>
    <description>The HR Services Partner is assigned to the Payx PEO-ASO Account Owner field</description>
    <label>HR Services Partner</label>
    <relationshipName>HrPayrollPartner</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/objects/User/fields/Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Job_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is populated by a trigger on save of a record. Only Sales Jobs are populated with values like Sales Representative, District Assistant, District Manager...</inlineHelpText>
    <label>Job Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MMSASOPartnerQueueable.cls
/* 
 * Set ASO Ownership on Accounts Owned by MMS rep when ASO Partner is set.
 *
 * History
 * -------
 * 05/21/2018 Jake Hinds    Created
 * 03/07/2020 Jake Hinds    Adding in SMB
 * 05/18/2021 Jermaine Stukes	Add HRS Partner logic
   08/09/2021 Dan Carmen        Rewrite for efficiency

 */

public with sharing class MMSASOPartnerQueueable implements Queueable{
    
    public static String CLASSNAME='MMSASOPartnerQueueable';
            
    public User[] owners;
    //public Integer rowLimit = Integer.valueOf(Label.MMSASOPartnerQueueableRowLimit);
    public Integer attemptNbr = 1;
    
    public MMSASOPartnerQueueable(User[] p_owners){
        owners = p_owners;
    }//MMSASOPartnerQueueable  

   public void execute(QueueableContext context) {
      //remove rep from stack.  if query limit is hit, add user back into the stack to finish processing
      User owner = (owners != null && !owners.isEmpty() ? owners.remove(0) : null);
      if (owner == null) {
         return;
      }
      //create job tracker to track job
      Job_Tracker__c jt= new Job_Tracker__c(Process_Start__c=system.now(),Job_Name__c = CLASSNAME);
      jt.Job_Id__c = owner.Id;
      jt.Notes__c = 'Processing user: '+owner.Id+' attemptNbr='+attemptNbr+' owners='+owners.size();
      jt.Nbr_Batches__c = 0;
      jt.Nbr_Errors__c = 0;  

      Apex_Batch_Control__c abc = Apex_Batch_Control__c.getInstance(CLASSNAME);
      Integer rowLimit = (abc != null && abc.BatchSize__c != null ? Integer.valueOf(abc.BatchSize__c) : 500);

      Boolean skipTriggers = (owner.HR_Services_Partner__c != null);
      Account[] searchAccts = null;
       
      Id mmsRTID = RecordTypeHelper.getRecordType(Label.RT_MMS_Account,'Account').getRecordTypeId();
      Id smbRTID = RecordTypeHelper.getRecordType(Label.RT_Core_Account,'Account').getRecordTypeId();
      Id[] rtIds = new Id[]{mmsRTId,smbRTId};
                
      //if HR Services Partner is null, find accounts owned by rep which had previously been set with partner
      if (owner.HR_Services_Partner__c != null) {
         searchAccts = [Select Id, Premier_PBS_Account_Owner__c, Premier_PBS_Hold_Out__c, Premier_PBS_Hold_Out_Expiration__c
                              ,PEO_ASO_Permanent_Hold_Out_Description__c
                          From Account
                         Where OwnerId = :owner.Id
                           and Owner.HR_Services_Partner__c != null
                           and CurrentClient__c = false
                           and Premier_PBS_Hold_Out__c = false
                           and RecordTypeId in :rtIds
                           and Id in (Select AccountId from Opportunity
                                       Where OwnerId = :owner.Id
                                         and OpportunityType__c = 'Payroll' and isClosed = false)
                        limit :rowLimit]; 
             /*
                acctsToUpdate = [SELECT Id,(Select Id,OwnerId
                                            From Opportunities
                                            Where OwnerId =: owner.Id and OpportunityType__c = 'Payroll' and isClosed = false)
                                 From Account WHERE OwnerID = :owner.Id AND Owner.HR_Services_Partner__c != null 
                                           AND CurrentClient__c = false and Premier_PBS_Hold_Out__c = false LIMIT :rowLimit];
       */
       } else {
        
          String[] holdoutReasons = new String[]{Label.Account_Partnership_Holdout_Reason, Label.Account_HR_Partnership_Holdout_Reason};
          //May need to incorporate Current Non Payroll Client field
          searchAccts = [Select ID, Premier_PBS_Account_Owner__c, Premier_PBS_Hold_Out__c, Premier_PBS_Hold_Out_Expiration__c
                              ,PEO_ASO_Permanent_Hold_Out_Description__c
                           From Account 
                          WHERE OwnerID = :owner.Id 
                            AND RecordTypeId in:rtIds 
                            AND CurrentClient__c = false
                            AND Premier_PBS_Hold_Out__c = true AND PEO_ASO_Permanent_Hold_Out_Description__c in :holdoutReasons LIMIT :rowLimit];
              /*
                    acctsToUpdate = [SELECT ID From Account WHERE OwnerID = :owner.Id AND RecordTypeId in:rtIds AND CurrentClient__c = false
                                     AND Premier_PBS_Hold_Out__c = true AND PEO_ASO_Permanent_Hold_Out_Description__c in:holdoutReasons LIMIT :rowLimit];
              */
       } // if (owner.HR_Services_Partner__c != null
       
       // if there are too many accounts selected, continue to process
       if (searchAccts !=null && searchAccts.size( )>=rowLimit ) {
          owners.add(owner);
       }
       
       if (searchAccts != null && !searchAccts.isEmpty()) {
          jt.Nbr_Batches__c = searchAccts.size();
          for (Account acct : searchAccts) {
             if (owner.HR_Services_Partner__c != null){
                acct.Premier_PBS_Account_Owner__c = owner.HR_Services_Partner__c;
                acct.Premier_PBS_Hold_Out__c = true;
                acct.Premier_PBS_Hold_Out_Expiration__c = null;
                acct.PEO_ASO_Permanent_Hold_Out_Description__c = Label.Account_HR_Partnership_Holdout_Reason;
             } else {
                //if no partner set, remove holdout
                acct.Premier_PBS_Account_Owner__c = null;
                acct.Premier_PBS_Hold_Out__c = false;
                acct.PEO_ASO_Permanent_Hold_Out_Description__c = null;
                acct.Use_Zip_Assignment_Rules__c = true;
             }
         } // for (Account acct : searchAccts
         jt.Notes__c += '\nTotal Accts processed: '+ searchAccts.size();
         try {
            ZipCheckOwner.SKIP_TRIGGERS=skipTriggers;
            update searchAccts;
         } catch (DMLException e) {
            //loop through and capture any errors, add to notes
            for (Integer i = 0; i < e.getNumDml(); i++) {
               Id acctId = searchAccts[e.getDMLIndex(i)].Id; 
               jt.Notes__c += '\n Error at Id:'+acctId+' - '+e.getDMLMessage(i);
               jt.Nbr_Errors__c ++;
            } // for (Integer i = 0; i < e.getNumDml(); i++
         } // try
      } else {
         jt.Notes__c += '\nNo Accts found';
      } // if (searchAccts != null && !searchAccts.isEmpty
        

        //kick another job off to process the next rep in line.  Use the Apex_Batch_Control__c to allow to chain jobs. 
        Integer nbrAttempts = (abc != null && abc.NbrOfAttempts__c != null ? Integer.valueOf(abc.NbrOfAttempts__c) : 10);
        if (!owners.isEmpty() && abc != null && abc.Active__c && attemptNbr <= nbrAttempts) {
            jt.Notes__c += '\n Hit Limit, requeuing list';
            MMSASOPartnerQueueable mapq = new MMSASOPartnerQueueable(owners);
            mapq.attemptNbr = attemptNbr+1;
            System.enqueueJob(mapq);
        }
        jt.Status__c = 'Completed' + (jt.Nbr_Errors__c > 0 ? ' With Errors' : '');
        //jt.Job_Id__c = context.getJobId();
        jt.Process_End__c = system.now();
        insert jt;
    } //execute
    
} // class MMSASOPartnerQueueable