force-app/main/default/objects/Account/fields/DBA__c.field-meta.xml
<CustomField>
    <fullName>DBA__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DBA</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/HR_Person_Id__c.field-meta.xml
<CustomField>
    <fullName>HR_Person_Id__c</fullName>
    <description>The unique person identifier from the corporate human resources system</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>HR Person Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <description>When errors occur during a process, a place we can capture and log them</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Log-{00000000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OasisSync__c/OasisSync__c.object-meta.xml
<CustomObject>
    <description>Object used to share data between Paychex and Oasis</description>
    <label>Oasis Sync</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Oasis Sync Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oasis Syncs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OasisSync__c/fields/AccountIdPayx__c.field-meta.xml
<CustomField>
    <fullName>AccountIdPayx__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>The Salesforce Id of the Account in the Salesforce Instance</inlineHelpText>
    <label>Account IdPayx</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/ContactIdPayx__c.field-meta.xml
<CustomField>
    <fullName>ContactIdPayx__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>The Salesforce Id of the Contact in the Paychex Instance</inlineHelpText>
    <label>Contact Id Payx</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/DBA__c.field-meta.xml
<CustomField>
    <fullName>DBA__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DBA</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/NbrTransits__c.field-meta.xml
<CustomField>
    <fullName>NbrTransits__c</fullName>
    <inlineHelpText>The number of times this record transits between the salesforce orgs</inlineHelpText>
    <label>Nbr Transits</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/OwnerHRPersonID__c.field-meta.xml
<CustomField>
    <fullName>OwnerHRPersonID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Owner HR Person ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paychex</fullName>
            </value>
            <value>
                <fullName>Oasis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/SyncType__c.field-meta.xml
<CustomField>
    <fullName>SyncType__c</fullName>
    <label>Sync Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Record</fullName>
            </value>
            <value>
                <fullName>Record Update</fullName>
            </value>
            <value>
                <fullName>Record Id Update</fullName>
            </value>
            <value>
                <fullName>Lead Converted</fullName>
            </value>
            <value>
                <fullName>Duplicate Result</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Title</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/HR_Person_Id__c.field-meta.xml
<CustomField>
    <fullName>HR_Person_Id__c</fullName>
    <description>The Person Id from HR</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Person Id from HR</inlineHelpText>
    <label>HR Person Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OasisSyncAcctCtctTest.cls
/* Test Methods for the OasisSyncAcctCtct class


  History
  -------
  05/20/2019 Dan Carmen        Created
  03/10/2020 Dan Carmen        Comment out all code
  
 */
@isTest
private class OasisSyncAcctCtctTest {
    static testMethod void testNothing() {
        OasisSyncAcctCtct.sendAccounts((Account[])null, (Map<Id,Account>)null, (ErrorLog__c)null);
        OasisSyncAcctCtct.sendContacts((Contact[])null, (Map<Id,Contact>)null, (ErrorLog__c)null);
    }
  /*
   @testSetup
   public static void setupTestData() {
      OasisSyncHelperTest.setupCustomSettings();
   } // setupTestData
   
   static testMethod void testAcctCtct() {
      OasisSyncHelper.SKIP_NAME_SET.clear();
      // get a client space user
      User csUser = OasisSyncHelperTest.getTestCSUser();
      Account acct = new Account(OwnerId=csUser.Id, Name='Disney World', BillingState='FL', BillingPostalCode='32830');
      insert acct;
      
      Contact ctct = new Contact(AccountId=acct.Id, OwnerId=csUser.Id, FirstName='Mickey', LastName='Mouse', Email='mickey@disneyworld.com');
      insert ctct;
      
      // an OasisSync__c record should have been created
      Map<String,OasisSync__c> syncMap = OasisSyncHelper.getExistingSyncMap(new Contact[]{ctct});
      System.assertEquals(1,syncMap.size());
      OasisSync__c sync = syncMap.get(ctct.Id);
      System.assertEquals(OasisSyncHelper.SOURCE_PAYX, sync.Source__c);
      System.assertEquals(OasisSyncHelper.SYNC_NEW, sync.SyncType__c);
      System.assertEquals(1,sync.NbrTransits__c);
      System.assertEquals(ctct.Id, sync.ContactIdPayx__c);
      System.assertEquals(ctct.FirstName, sync.FirstName__c);
      System.assertEquals(ctct.LastName, sync.LastName__c);
      System.assertEquals(ctct.Email, sync.Email__c);
      System.assertEquals(acct.Id, sync.AccountIdPayx__c);
      System.assertEquals(acct.Name, sync.Company__c);
      System.assertEquals(acct.BillingPostalCode, sync.PostalCode__c);
      System.assertEquals(csUser.HR_Person_Id__c, sync.OwnerHrPersonId__c);
      
      OasisSyncHelper.ALREADY_RAN_SET.clear();
      acct.BillingCity='Lake Buena Vista';
      acct.DBA__c='Happiest Place On Earth';
      acct.Website='www.disneyworld.com';
      update acct;
      
      syncMap = OasisSyncHelper.getExistingSyncMap(new Account[]{acct});
      System.assertEquals(1,syncMap.size());
      sync = syncMap.get(acct.Id);
      
      System.assertEquals(OasisSyncHelper.SYNC_UPDATE, sync.SyncType__c);
      System.assertEquals(2,sync.NbrTransits__c);
      System.assertEquals(acct.Id, sync.AccountIdPayx__c);
      System.assertEquals(acct.Name, sync.Company__c);
      System.assertEquals(acct.BillingCity, sync.City__c);
      System.assertEquals(acct.BillingPostalCode, sync.PostalCode__c);
      System.assertEquals(acct.DBA__c, sync.DBA__c);
      System.assertEquals(acct.Website, sync.Website__c);
      
      OasisSyncHelper.ALREADY_RAN_SET.clear();
      ctct.Title='Head Mouse';
      ctct.Phone='(407) 934-7639';
      update ctct;

      syncMap = OasisSyncHelper.getExistingSyncMap(new Contact[]{ctct});
      System.assertEquals(1,syncMap.size());
      sync = syncMap.get(ctct.Id);
      
      System.assertEquals(OasisSyncHelper.SYNC_UPDATE, sync.SyncType__c);
      System.assertEquals(3,sync.NbrTransits__c);
      System.assertEquals(acct.Id, sync.AccountIdPayx__c);
      System.assertEquals(acct.Name, sync.Company__c);
      System.assertEquals(acct.BillingCity, sync.City__c);
      System.assertEquals(acct.BillingPostalCode, sync.PostalCode__c);
      System.assertEquals(acct.DBA__c, sync.DBA__c);
      System.assertEquals(acct.Website, sync.Website__c);
      System.assertEquals(ctct.Id, sync.ContactIdPayx__c);
      System.assertEquals(ctct.FirstName, sync.FirstName__c);
      System.assertEquals(ctct.LastName, sync.LastName__c);
      System.assertEquals(ctct.Email, sync.Email__c);
      System.assertEquals(ctct.Title, sync.Title__c);
      System.assertEquals(ctct.Phone, sync.Phone__c);
        
   } // testAcctCtct
   */
} // class OasisSyncAcctCtctTest