force-app/main/default/objects/Account/fields/DBA__c.field-meta.xml
<CustomField>
    <fullName>DBA__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DBA</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Federal_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Federal_ID_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Federal ID Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NAICS_Code__c.field-meta.xml
<CustomField>
    <fullName>NAICS_Code__c</fullName>
    <description>Mapped from NAICS Code field on the Lead object, fed from Salesgenie. Created part of BAU case 16410673.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>NAICS Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/PEO_Onboarding_Checklist__c.object-meta.xml
<CustomObject>
    <label>PEO Underwriting Checklist</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PEO Underwriting Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PEO Underwriting Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Medical_Benefits_Underwriting_Reques_del__c.field-meta.xml
<CustomField>
    <fullName>Medical_Benefits_Underwriting_Reques_del__c</fullName>
    <description>Sales rep to fill if medical benefits uw has been requested.</description>
    <label>Medical Benefits Underwriting Requested</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>yes</fullName>
            </value>
            <value>
                <fullName>no</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Peo_401k_formStatus__c.field-meta.xml
<CustomField>
    <fullName>Peo_401k_formStatus__c</fullName>
    <label>401k Form Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Questionnaire_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Peo_401k_SubmissionTime__c.field-meta.xml
<CustomField>
    <fullName>Peo_401k_SubmissionTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>401k Submit Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Peo_Covid_formStatus__c.field-meta.xml
<CustomField>
    <fullName>Peo_Covid_formStatus__c</fullName>
    <label>COVID Form Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Questionnaire_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Peo_Covid_formSubmissionTime__c.field-meta.xml
<CustomField>
    <fullName>Peo_Covid_formSubmissionTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>COVID Submit Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Peo_EPLI_formStatus__c.field-meta.xml
<CustomField>
    <fullName>Peo_EPLI_formStatus__c</fullName>
    <label>EPLI Form Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Questionnaire_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Peo_EPLI_SubmissionTime__c.field-meta.xml
<CustomField>
    <fullName>Peo_EPLI_SubmissionTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>EPLI Submit Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Peo_Medical_formStatus__c.field-meta.xml
<CustomField>
    <fullName>Peo_Medical_formStatus__c</fullName>
    <label>Medical Questionnaire Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Peo_WC_formStatus__c.field-meta.xml
<CustomField>
    <fullName>Peo_WC_formStatus__c</fullName>
    <label>WC Form Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Questionnaire_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Peo_WC_SubmissionTime__c.field-meta.xml
<CustomField>
    <fullName>Peo_WC_SubmissionTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>WC Submit Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Prospect_Client__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup to the related account.</description>
    <label>Prospect-Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>PEO_Onboarding_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Medical_Questionnaire__c/PEO_Onboarding_Medical_Questionnaire__c.object-meta.xml
<CustomObject>
    <label>PEO Underwriting Medical Questionnaire</label>
    <nameField>
        <displayFormat>of-{0000}</displayFormat>
        <label>PEO Underwriting Medical Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PEO Underwriting Medical Questionnaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PEO_Onboarding_Medical_Questionnaire__c/fields/PEO_Onboarding_Checklist__c.field-meta.xml
<CustomField>
    <fullName>PEO_Onboarding_Checklist__c</fullName>
    <label>PEO Underwriting Checklist</label>
    <referenceTo>PEO_Onboarding_Checklist__c</referenceTo>
    <relationshipLabel>PEO Underwriting Medical Questionnaires</relationshipLabel>
    <relationshipName>PEO_Onboarding_Medical_Questionnaires</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Questionnaire_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <masterLabel>Questionnaire_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CommunityWorkersCompControllerTest.cls
/*
* Tests for CommunityWorkersCompController methods
* 
* History
* ----------------------------------------
* 08/23/2021	Ahmed	Elawad		Created
*/ 

@isTest
public class CommunityWorkersCompControllerTest {
    
    // Setup requires insertion of various records for testing.
    @testSetup
    Static void setupData() {
        Schema.RecordTypeInfo rtAcct = RecordTypeHelper.getRecordType(RecordTypeHelper.CORE_ACCOUNT, 'Account');
        Account acctA = new Account(Name = 'ParentTestAccountCommunities', AccountNumber = '8-00081234', RecordTypeId=rtAcct.getRecordTypeId(), NumberOfEmployees = 60, BillingStreet = 'This is a Test Billing Address', 
                                    BillingPostalCode='1234', BillingState='NY', BillingCity='Buffalo', Federal_Id_Number__c='1234', Phone='123-456-7890', DBA__c='TEST', NAICS_Code__c='12345');
        insert acctA;
        
        PEO_Onboarding_Checklist__c checklist = new PEO_Onboarding_Checklist__c(Prospect_Client__c=acctA.Id, Medical_Benefits_Underwriting_Reques_del__c='Yes',
                                                                                Peo_401k_formStatus__c='', Peo_EPLI_formStatus__c='',Peo_Covid_formStatus__c='',Peo_WC_formStatus__c='');
        insert checklist;
        
        PEO_Onboarding_Medical_Questionnaire__c medFormA = new PEO_Onboarding_Medical_Questionnaire__c(PEO_Onboarding_Checklist__c=checklist.Id);
        insert medFormA;
    }
    
    // Test for savePeoOnboardingChecklist
    static testMethod void savePeoOnboardingChecklistTest(){
        Account parentAcc = [SELECT Id, Name FROM Account WHERE name='ParentTestAccountCommunities' LIMIT 1];
        PEO_Onboarding_Checklist__c peoOnbChecklist = [SELECT ID, Peo_401k_formStatus__c, Peo_EPLI_formStatus__c, Peo_Covid_formStatus__c,
                                                       Peo_WC_formStatus__c, Peo_401k_SubmissionTime__c, Peo_EPLI_SubmissionTime__c,
                                                       Peo_Covid_formSubmissionTime__c, Peo_WC_SubmissionTime__c, Peo_Medical_formStatus__c
                                                       FROM PEO_Onboarding_Checklist__c
                                                       WHERE Prospect_Client__c=:parentAcc.Id];
        peoOnbChecklist.Peo_401k_formStatus__c = 'Complete';
        peoOnbChecklist.Peo_EPLI_formStatus__c = 'Complete';
        peoOnbChecklist.Peo_Covid_formStatus__c = 'Complete';
        peoOnbChecklist.Peo_WC_formStatus__c = 'Complete';
        
        
        Test.startTest();
        CommunityWorkersCompController.savePeoOnboardingChecklist(peoOnbChecklist, '');
        Test.stopTest();
        
        PEO_Onboarding_Checklist__c updatedCheclist = [SELECT ID, Peo_401k_formStatus__c, Peo_EPLI_formStatus__c, Peo_Covid_formStatus__c,
                                                       Peo_WC_formStatus__c, Peo_401k_SubmissionTime__c, Peo_EPLI_SubmissionTime__c,
                                                       Peo_Covid_formSubmissionTime__c, Peo_WC_SubmissionTime__c, Peo_Medical_formStatus__c
                                                       FROM PEO_Onboarding_Checklist__c
                                                       WHERE Prospect_Client__c=:parentAcc.Id];
        
        System.assertEquals(updatedCheclist.Peo_401k_formStatus__c, 'Complete', 'updatedCheclist status Peo_401k_formStatus__c not updated');
        System.assertEquals(updatedCheclist.Peo_EPLI_formStatus__c, 'Complete', 'updatedCheclist status Peo_EPLI_formStatus__c not updated');
        System.assertEquals(updatedCheclist.Peo_Covid_formStatus__c, 'Complete', 'updatedCheclist status Peo_Covid_formStatus__c not updated');
        System.assertEquals(updatedCheclist.Peo_WC_formStatus__c, 'Complete', 'updatedCheclist status Peo_WC_formStatus__c not updated');
        System.assertNotEquals(updatedCheclist.Peo_401k_SubmissionTime__c,null, 'Failed to update Peo_401k_SubmissionTime__c');
        System.assertNotEquals(updatedCheclist.Peo_EPLI_SubmissionTime__c,null, 'Failed to update Peo_EPLI_SubmissionTime__c');
        System.assertNotEquals(updatedCheclist.Peo_Covid_formSubmissionTime__c,null, 'Failed to update Peo_Covid_formSubmissionTime__c');
        System.assertNotEquals(updatedCheclist.Peo_WC_SubmissionTime__c,null, 'Failed to update Peo_WC_SubmissionTime__c');
    }
    
}