force-app/main/default/objects/Account/fields/EmailLastOpened__c.field-meta.xml
<CustomField>
    <fullName>EmailLastOpened__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date/time an email from a contact was last opened.</inlineHelpText>
    <label>Email Last Opened</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/EmailLastSent__c.field-meta.xml
<CustomField>
    <fullName>EmailLastSent__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date/time an email was last sent by a contact</inlineHelpText>
    <label>Email Last Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumberOfOpens__c.field-meta.xml
<CustomField>
    <fullName>NumberOfOpens__c</fullName>
    <inlineHelpText>Number of times emails have been opened against the contacts linked to this account</inlineHelpText>
    <label>Number Of Opens</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_Batch_Control__c/Apex_Batch_Control__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These are settings that can be used to implement some control over apex batch jobs.</description>
    <label>Apex Batch Control</label>
</CustomObject>

force-app/main/default/objects/Apex_Batch_Control__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Should the job run?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apex_Batch_Control__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <inlineHelpText>This is used by the UpdateZipOwnershipController to allow the batches to be manually launched.</inlineHelpText>
    <label>Batch Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_Batch_Control__c/fields/Minutes_till_Launch__c.field-meta.xml
<CustomField>
    <fullName>Minutes_till_Launch__c</fullName>
    <label>Minutes till Launch</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_Batch_Control__c/fields/NbrOfAttempts__c.field-meta.xml
<CustomField>
    <fullName>NbrOfAttempts__c</fullName>
    <inlineHelpText>How many attempts to we make on each record?</inlineHelpText>
    <label>Nbr of Attempts</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EmailLastOpened__c.field-meta.xml
<CustomField>
    <fullName>EmailLastOpened__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The last time an html email message was opened</inlineHelpText>
    <label>Email Last Opened</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EmailLastSent__c.field-meta.xml
<CustomField>
    <fullName>EmailLastSent__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date/time the last email was sent (not via workflow)</inlineHelpText>
    <label>Email Last Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NumberOfOpens__c.field-meta.xml
<CustomField>
    <fullName>NumberOfOpens__c</fullName>
    <inlineHelpText>Number of times emails have been opened for this Contact</inlineHelpText>
    <label>Number Of Opens</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EmailMessage/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Account this email was sent from</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Email Messages</relationshipLabel>
    <relationshipName>EmailMessages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EmailMessage/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Contact this Email was sent to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Email Messages</relationshipLabel>
    <relationshipName>EmailMessages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EmailMessage/fields/EmailTemplateId__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Salesforce Id of the email template used for this email</inlineHelpText>
    <label>Email Template Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessage/fields/EmailTemplateName__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the email template used for this email.</inlineHelpText>
    <label>Email Template Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessage/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>What lead is this email related to</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Email Messages</relationshipLabel>
    <relationshipName>EmailMessages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EmailMessage/fields/NumberOfOpens__c.field-meta.xml
<CustomField>
    <fullName>NumberOfOpens__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number of times the email was opened</inlineHelpText>
    <label>Number of Opens</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NumberOfOpens__c.field-meta.xml
<CustomField>
    <fullName>NumberOfOpens__c</fullName>
    <inlineHelpText>Number of times email was opened for this Lead</inlineHelpText>
    <label>Number Of Opens</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Securities_License__c.field-meta.xml
<CustomField>
    <fullName>Securities_License__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Securities License checkbox should be checked for the list of users (AllLicensedTitles)</description>
    <inlineHelpText>“DO NOT UPDATE! Please reach out to FINRACompliance@paychex.com for modifications or questions”.</inlineHelpText>
    <label>Securities License</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EmailMessageMethodsTest.cls
/* 
   Test methods for the EmailMessageMethods class

   
History
-------
04/16/2021 Dan Carmen   Created
09/28/2021 Eric Porter  Check Activity Test Added 
02/25/2022 Dan Carmen   Added check if runningUser is null
07/11/2022 Dan Carmen   Change query for checkAcctOpens
05/17/2023 Dan Carmen   Additional logic around the Securities_License__c user field
03/06/2024 Dan Carmen   Exclude paychex contacts from the ctctMap

 */
@isTest
public class EmailMessageMethodsTest {
    
   @testSetup
   public static void setupData() {
      Apex_Batch_Control__c  abc1 = new Apex_Batch_Control__c(Name=EmailMessageBatch.CLASSNAME,Active__c=true, NbrOfAttempts__c=1, BatchSize__c=100, Minutes_till_Launch__c=1);
      insert abc1;
   } // setupData
    
   static testMethod void testTemplateId() {
      System.assertEquals(0,[select count() from EmailMessage]);
      // select a random email template
      EmailTemplate template = [Select Id, Name from EmailTemplate limit 1];
       
      EmailMessage msg = new EmailMessage(EmailTemplateId=template.Id);
      insert msg;
       
      System.assertEquals(1,[select count() from EmailMessage]);
       
      msg = [Select Id, EmailTemplateId__c, EmailTemplateName__c from EmailMessage where Id=:msg.Id];
      System.assertEquals(template.Id, msg.EmailTemplateId__c);
      System.assertEquals(template.Name, msg.EmailTemplateName__c);
   } // testTemplateId
    
   static testMethod void testCheckActivityContact(){

      Account acct = new Account(Name='testAccount');
      ZipCheckOwner.SKIP_TRIGGERS=true;
      insert acct;
      Contact ctct = new Contact(LastName='Stark',Email='tstark@test.com', AccountId= acct.Id);
      ContactMethods.CONTACT_BEFORE_TRIGGER_EXECUTING=true;
      ContactMethods.CONTACT_AFTER_TRIGGER_EXECUTING=true;
      insert ctct;
       
      Lead ld = new Lead(LastName='Richards',Company='QENG', Email='richards@test.com');
      TriggerMethods.SKIP_TRIGGERS=true;
      insert ld;

      Messaging.SingleEmailMessage msg1 = new Messaging.SingleEmailMessage();
      msg1.setTargetObjectId(ctct.Id);
      msg1.setSubject('Test Email1');
      msg1.setPlainTextBody('This is an Email Body');
      msg1.setSaveAsActivity(true);
       
      Messaging.SingleEmailMessage msg2 = new Messaging.SingleEmailMessage();
      msg2.setTargetObjectId(ld.Id);
      msg2.setSubject('Test Email2');
      msg2.setPlainTextBody('This is an Email Body');
      msg2.setSaveAsActivity(true);
       
      Messaging.SingleEmailMessage[] emails = new Messaging.SingleEmailMessage[]{msg1,msg2};
      Utilities.SKIP_FUTURE=false;
      System.debug('testCheckActivityContact before email send');
       
      Test.startTest(); 
      Messaging.sendEmail(emails);
      Test.stopTest();
       
      System.assertEquals(2,[Select count() from EmailMessage]);
       
      EmailTemplate template = [Select Id, Name from EmailTemplate limit 1];

      //EmailMessage msgCtct = new EmailMessage(ActivityId=ctctTask.Id, Status='3', FromName='Some Person1', Subject='This is the Subject!', HtmlBody='<html><body><b>Hello</b></body></html>', EmailTemplateId=template.Id);
      //EmailMessage msgLead = new EmailMessage(ActivityId=leadTask.Id, Status='3', FromName='Some Person2', Subject='This is the Subject!', HtmlBody='<html><body><b>Hello</b></body></html>', EmailTemplateId=template.Id);
      //EmailMessage[] msgs = new EmailMessage[]{msgCtct, msgLead};

      //insert msgs;
      EmailMessage[] msgs = [Select Id, Lead__c, Contact__c, Account__c, LastOpenedDate, CreatedDate, Subject, NumberOfOpens__c
                                                                    ,Lead__r.Id, Lead__r.EmailLastSent__c, Lead__r.EmailLastOpened__c, Lead__r.NumberOfOpens__c
                                                                    ,Contact__r.Id, Contact__r.EmailLastSent__c, Contact__r.EmailLastOpened__c, Contact__r.NumberOfOpens__c
                                                                    ,Account__r.Id, Account__r.EmailLastSent__c, Account__r.EmailLastOpened__c, Account__r.NumberOfOpens__c
                                                                from EmailMessage];
      EmailMessage msgCtct = null;
      EmailMessage msgLd = null;
      for (EmailMessage msg : msgs) {
         System.debug('testCheckActivity msg='+msg);
         if (msg.Subject == 'Test Email1') {
            msgCtct = msg;
            System.assertEquals(null, msg.Lead__c);
            System.assertEquals(ctct.Id, msg.Contact__c);
            System.assertEquals(acct.Id, msg.Account__c); 
            System.assertEquals(null, msg.Contact__r.EmailLastOpened__c);
            System.assertEquals(msg.CreatedDate, msg.Contact__r.EmailLastSent__c);
            System.assertEquals(null, msg.Account__r.EmailLastOpened__c);
            System.assertEquals(msg.CreatedDate, msg.Account__r.EmailLastSent__c);
         } else if (msg.Subject == 'Test Email2') {
            msgLd = msg;
            System.assertEquals(ld.Id, msg.Lead__c);
            System.assertEquals(null, msg.Contact__c);
            System.assertEquals(null, msg.Account__c); 
            System.assertEquals(null, msg.Lead__r.EmailLastOpened__c);
            System.assertEquals(msg.CreatedDate, msg.Lead__r.EmailLastSent__c);

         }
      }
      System.assertNotEquals(null,msgCtct);
      System.assertNotEquals(null,msgLd);
       
      msgCtct.LastOpenedDate = Datetime.now().addMinutes(1);
      msgLd.LastOpenedDate = Datetime.now().addMinutes(1);
      Utilities.SKIP_FUTURE=true;
      update msgs;
       
      msgs = [Select Id, Lead__c, Contact__c, Account__c, LastOpenedDate, CreatedDate, Subject, NumberOfOpens__c
                                                                    ,Lead__r.Id, Lead__r.EmailLastSent__c, Lead__r.EmailLastOpened__c, Lead__r.NumberOfOpens__c
                                                                    ,Contact__r.Id, Contact__r.EmailLastSent__c, Contact__r.EmailLastOpened__c, Contact__r.NumberOfOpens__c
                                                                    ,Account__r.Id, Account__r.EmailLastSent__c, Account__r.EmailLastOpened__c, Account__r.NumberOfOpens__c
                                                                from EmailMessage];
      for (EmailMessage msg : msgs) {
         System.debug('testCheckActivity msg='+msg);
         if (msg.Subject == 'Test Email1') {
            System.assertEquals(null, msg.Lead__c);
            System.assertEquals(ctct.Id, msg.Contact__c);
            System.assertEquals(acct.Id, msg.Account__c); 
            System.assertEquals(msg.LastOpenedDate, msg.Contact__r.EmailLastOpened__c);
            System.assertEquals(msg.CreatedDate, msg.Contact__r.EmailLastSent__c);
            System.assertEquals(msg.LastOpenedDate, msg.Account__r.EmailLastOpened__c);
            System.assertEquals(msg.CreatedDate, msg.Account__r.EmailLastSent__c);
         } else if (msg.Subject == 'Test Email2') {
            System.assertEquals(ld.Id, msg.Lead__c);
            System.assertEquals(null, msg.Contact__c);
            System.assertEquals(null, msg.Account__c); 
            System.assertEquals(msg.LastOpenedDate, msg.Lead__r.EmailLastOpened__c);
            System.assertEquals(msg.CreatedDate, msg.Lead__r.EmailLastSent__c);

         }
      }
      System.assertNotEquals(null,msgCtct);
      System.assertNotEquals(null,msgLd);
       
      msgCtct.LastOpenedDate = Datetime.now().addMinutes(2);
      msgLd.LastOpenedDate = Datetime.now().addMinutes(2);
      Utilities.SKIP_FUTURE=true;
      EmailMessageMethods.SKIP_TRIGGER=false;
      update msgs;

      msgs = [Select Id, Lead__c, Contact__c, Account__c, LastOpenedDate, CreatedDate, Subject, NumberOfOpens__c
                                                                    ,Lead__r.Id, Lead__r.EmailLastSent__c, Lead__r.EmailLastOpened__c, Lead__r.NumberOfOpens__c
                                                                    ,Contact__r.Id, Contact__r.EmailLastSent__c, Contact__r.EmailLastOpened__c, Contact__r.NumberOfOpens__c
                                                                    ,Account__r.Id, Account__r.EmailLastSent__c, Account__r.EmailLastOpened__c, Account__r.NumberOfOpens__c
                                                                from EmailMessage];
      for (EmailMessage msg : msgs) {
         System.debug('testCheckActivity checkNbrOpens msg='+msg);
         if (msg.Subject == 'Test Email1') {
            System.assertEquals(null, msg.Lead__c);
            System.assertEquals(ctct.Id, msg.Contact__c);
            System.assertEquals(acct.Id, msg.Account__c); 
            System.assertEquals(1,msg.NumberOfOpens__c);
            System.assertEquals(msg.LastOpenedDate, msg.Contact__r.EmailLastOpened__c);
            System.assertEquals(msg.CreatedDate, msg.Contact__r.EmailLastSent__c);
            System.assertEquals(1,msg.Contact__r.NumberOfOpens__c);
            System.assertEquals(msg.LastOpenedDate, msg.Account__r.EmailLastOpened__c);
            System.assertEquals(msg.CreatedDate, msg.Account__r.EmailLastSent__c);
            System.assertEquals(1,msg.Account__r.NumberOfOpens__c);
         } else if (msg.Subject == 'Test Email2') {
            System.assertEquals(ld.Id, msg.Lead__c);
            System.assertEquals(null, msg.Contact__c);
            System.assertEquals(null, msg.Account__c); 
            System.assertEquals(1,msg.NumberOfOpens__c);
            System.assertEquals(msg.LastOpenedDate, msg.Lead__r.EmailLastOpened__c);
            System.assertEquals(msg.CreatedDate, msg.Lead__r.EmailLastSent__c);
            System.assertEquals(1,msg.Lead__r.NumberOfOpens__c);
         }
      }

      Database.executeBatch(new EmailMessageBatch(), 20);
   } // testCheckActivity

   static testMethod void testScheduler() {
      TestHelper.testScheduler('testEmailMessageBatch', new EmailMessageBatch());
   } // testScheduler


} // class EmailMessageMethodsTest