force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>not really used anywhere, as of 4/19/2013 is blank for all production records</description>
    <label>Referral Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Contact__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>R00N50000001WySDEA0</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>PBS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pay</fullName>
            </value>
            <value>
                <fullName>PAS</fullName>
            </value>
            <value>
                <fullName>H&amp;B</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Portal_User_Details__c/Partner_Portal_User_Details__c.object-meta.xml
<CustomObject>
    <label>Partner Portal User Details</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Partner Portal User Details	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal User Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Portal_User_Details__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_User_Details__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_User_Details__c/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral Contact</label>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Partner Portal User Details</relationshipLabel>
    <relationshipName>Partner_Portal_User_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_User_Details__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/Referral_Contact__c.object-meta.xml
<CustomObject>
    <label>Referral Contact</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Referred</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Referral_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Referral Contact Email</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Referral Contact First Name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Referral Contact Phone</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Paychex Sales Division</description>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PAY</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>PBS</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>NSS</fullName>
            </value>
            <value>
                <fullName>BENETRAC</fullName>
            </value>
            <value>
                <fullName>DSR</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GENERIC</fullName>
            </value>
            <value>
                <fullName>HNB</fullName>
            </value>
            <value>
                <fullName>HNBF</fullName>
            </value>
            <value>
                <fullName>PAI</fullName>
            </value>
            <value>
                <fullName>PAI GENERI</fullName>
            </value>
            <value>
                <fullName>PAO</fullName>
            </value>
            <value>
                <fullName>PAS</fullName>
            </value>
            <value>
                <fullName>Stromberg</fullName>
            </value>
            <value>
                <fullName>TCS</fullName>
            </value>
            <value>
                <fullName>TIB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Community_User_Created_By__c.field-meta.xml
<CustomField>
    <fullName>Community_User_Created_By__c</fullName>
    <description>Used for welcome email template</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Community User Created By</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Community_User_First_Login__c.field-meta.xml
<CustomField>
    <fullName>Community_User_First_Login__c</fullName>
    <description>Created as a part of US38( When community user logins for the first time)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Community User First Login</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <description>The license group this user belongs to.</description>
    <inlineHelpText>The license group this user belongs to.</inlineHelpText>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Benetrac</fullName>
            </value>
            <value>
                <fullName>BusDev</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Relations</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>EW</fullName>
            </value>
            <value>
                <fullName>Field Operations Core</fullName>
            </value>
            <value>
                <fullName>HNBF</fullName>
            </value>
            <value>
                <fullName>HR Online</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>HRS 401K-S125</fullName>
            </value>
            <value>
                <fullName>HRS Premier</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MMS Hub</fullName>
            </value>
            <value>
                <fullName>MPSC</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>NSS</fullName>
            </value>
            <value>
                <fullName>PAS</fullName>
            </value>
            <value>
                <fullName>PAY</fullName>
            </value>
            <value>
                <fullName>Payroll Online</fullName>
            </value>
            <value>
                <fullName>PBS</fullName>
            </value>
            <value>
                <fullName>PEO Finance</fullName>
            </value>
            <value>
                <fullName>PEO HROi</fullName>
            </value>
            <value>
                <fullName>PEO New Business</fullName>
            </value>
            <value>
                <fullName>PEO Oasis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/ProfileName__c.field-meta.xml
<CustomField>
    <fullName>ProfileName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the profile - so we don&apos;t have to use an object relationship in formulas</inlineHelpText>
    <label>Profile Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Requested_Invite_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Invite_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Requested Invite Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org-Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>BenAdmin</fullName>
            </value>
            <value>
                <fullName>Benetrac</fullName>
            </value>
            <value>
                <fullName>BusDev</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Relations</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Center</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise Service Center</fullName>
            </value>
            <value>
                <fullName>ESR</fullName>
            </value>
            <value>
                <fullName>EW</fullName>
            </value>
            <value>
                <fullName>Field Operations Core</fullName>
            </value>
            <value>
                <fullName>HNBF</fullName>
            </value>
            <value>
                <fullName>HROI</fullName>
            </value>
            <value>
                <fullName>HR Online</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>HRS 401K-S125</fullName>
            </value>
            <value>
                <fullName>HRS Premier</fullName>
            </value>
            <value>
                <fullName>Icon</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Merchant Services</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MMS Hub</fullName>
            </value>
            <value>
                <fullName>MPSC</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConvertContactToCPACommunityUser.cls
/** 
* Create an external community user. 
*
* History
* -------
* 06/08/2022    Varun              Created.
* 12/16/2022    Vinay              Added resendWelcomeEmail, addProspectPermissionSet,
                                   getProfileIdBasedOnName methods.
* 01/20/2023    Josh Cartwright    removing chatter posts - no need  
* 02/20/2023    Vinay              Added End_Date__c filed to SOQL query in getReferralContactData method.
*/

public without sharing class ConvertContactToCPACommunityUser {
    
    @AuraEnabled(cacheable=true)
    public static Referral_Contact__c getReferralContactData(String refContactId) {
        return [SELECT Id, OwnerId , Name, First_Name__c, Last_Name__c, Email__c, Phone__c, Contact__c, End_Date__c FROM Referral_Contact__c Where Id=: refContactId];
    }

    @AuraEnabled
    public static void resendWelcomeEmail(Id contactId) {
        System.debug('In resend Welcome Email');
        User communityUser = [SELECT Id,ContactId,Community_User_First_Login__c,ProfileName__c FROM User WHERE ContactId =:contactId AND IsActive=true];
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name='CPA_Getting_Started_Prospect' LIMIT 1];

        PermissionSetAssignment[] psaToInsert = new PermissionSetAssignment[]{};
        PermissionSetAssignment[] psaToDelete = new PermissionSetAssignment[]{};
        
        if(communityUser!=null){
           //get existing permission set assignments
            PermissionSetAssignment[] existingPSAs = [SELECT Id,AssigneeId,PermissionSetId FROM PermissionSetAssignment 
                                                       WHERE PermissionSetId =:ps.Id AND AssigneeId =:communityUser.Id];
            if(communityUser.Community_User_First_Login__c == null && communityUser.ProfileName__c == 'CPA Customer Community Login User Clone') {
                if(existingPSAs!=null && !existingPSAs.isEmpty()){
                    for(PermissionSetAssignment psa:existingPSAs){
                        psaToDelete.add(psa);
                    }
                }
                PermissionSetAssignment newPSA = new PermissionSetAssignment(PermissionSetId=ps.Id,AssigneeId=communityUser.Id);
                psaToInsert.add(newPSA);
                //delete existing assignments and insert new ones to retrigger welcome email
                if(!psaToDelete.isEmpty()) {
                    System.debug('In resend Welcome Email DML===>'+ psaToDelete);
                    DmlHelper.performDML2(psaToDelete, DmlHelper.DML_DELETE, 'ConvertContactToCPACommunityUser', 'resendWelcomeEmailNow', 'deleting existing PSA', true);
                }
                if(!psaToInsert.isEmpty()) {
                    DmlHelper.performDML2(psaToInsert, DmlHelper.DML_INSERT, 'ConvertContactToCPACommunityUser', 'resendWelcomeEmailNow', 'inserting new PSA', true);
                }
            }
        }
    }
    
    
    /**
* Queries the user object using a contact ID and returns a user record if a match is found
* @Params: {Id(The contact record id)} - Community User records have a lookup to the contact record that was used to create them
* @Return: {User record, null}
*/


    @AuraEnabled
    public static User verifyExistingUserForContact(Id conId) {
        System.debug('In verifyExistingUserForContact Method');
        User[] usrs = [SELECT Name,IsActive,ContactId,AccountId, Username, CommunityNickname, Alias,Email,LastLoginDate, Community_User_First_Login__c FROM User WHERE ContactId =: conId LIMIT 100];
        for (User u : usrs) {
            System.debug('In verifyExistingUserForContact Method User =====>' + u);
            if (conId == u.ContactId) {
                return u;
            }
        }
        return null;
    }
    
    
    /**
* Creates a community user record
* @Params {String(username), String(nickName), Id(contact record ID), String(user alias), String(community audiance)}
* @Return: {Id(new user record id on success, null on failure)}
*/
    @AuraEnabled
    public static String createCommunityUserNew(String uName, String nickName, Id conId, String alias,String email) {
        System.debug('Start user creation request');
        //Bharat Changes - Renamed usrId to retVal, changed returntype from Id to String, Added query and If-else block
        String returnValue;
        String newUserId;
        String accId = [SELECT AccountId FROM Contact WHERE Id=:conId LIMIT 1].AccountId;
        Profile prof = [SELECT Id FROM Profile where name='CPA Customer Community Login User Clone'];
        // create an instance of the class or is this call fine??
        Contact conRec = ConvertContactToCommunityUser.getContactForId(conId);
        DateTime inviteDate;
        //it would be better to pass this into the method.
        String runningUser = UserInfo.getName();
        inviteDate = system.now();
        
        User communityUsr = new User(
            UserName = uName,
            FirstName = conRec.FirstName,
            LastName = conRec.LastName,
            Alias = alias,
            email = email,//conRec.Email,
            ContactId = conId,
            ProfileId = prof.Id,
            EmailEncodingKey = 'UTF-8',
            CommunityNickname = nickName,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            Sales_Org__c = 'Community',
            License_Type__c = 'Community',
            UserPermissionsKnowledgeUser = true,
            Community_User_Created_By__c = runningUser,
            Requested_Invite_Date__c = inviteDate
        );
        
        System.debug('New user profile: '+communityUsr);
        try {
            // insert communityUsr;
            // Database.DMLOptions dlo = new Database.DMLOptions();
            // dlo.EmailHeader.triggerUserEmail = true;
            Database.SaveResult sr =  Database.insert(communityUsr);
            if (!sr.isSuccess()) {
                for (Database.Error err : sr.getErrors()) {
                    if(err.getStatusCode() == StatusCode.DUPLICATE_USERNAME){
                        returnValue = 'DUPLICATE_USERNAME';
                    } else {
                        returnValue = null;
                    }
                }
            } else {
                system.debug('User created: ' + sr.getId());
                newUserId = communityUsr.Id;
                assignProspectPermissionSet(newUserId);
                // CS Helper method checks the existing locations in CS for the account which the contact
                // is related to to ensure locations are stood up for the process. Good placement for already 
                // existing accounts to ensure all locations exist as needed in CS.
                //assignProspectPermissionSet(communityUsr.Id);
                //updateChecklistWithUser(accId,communityUsr.Id, inviteDate);
                // ClientSpaceHelper.checkLocationsForAccount(conRec.AccountId);
                returnValue = null;
            }
        } catch(DmlException ex) {
            system.debug('Error creating user' + ex);
            ErrorLog.logError('ConvertContactToCommunityUser', 'createCommunityUser', 'createCommunityUser Error', communityUsr.Id, ex, communityUsr, true);
            returnValue = ex.getMessage();
        } catch (Exception e) {
            ErrorLog.logError('ConvertContactToCommunityUser', 'createCommunityUser', 'General Process Error', communityUsr.Id, e, communityUsr, true);
            returnValue = e.getMessage();
        }
        return returnValue;
    }

    @future
    public static void assignProspectPermissionSet(Id commUserId) {
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name='CPA_Getting_Started_Prospect' LIMIT 1];
        if(ps!=null && commUserId!=null){
            PermissionSetAssignment psa = new PermissionSetAssignment(PermissionSetId=ps.id,AssigneeId=commuserId);
            insert psa;
        }
    }
    
    @AuraEnabled
    public static void saveRefCnt(Id referralCt, string cpaStatus, string email) {
        Partner_Portal_User_Details__c ppud = new Partner_Portal_User_Details__c();
        ppud.Referral_Contact__c = referralCt; 
        ppud.Request_Date__c = datetime.now();
        ppud.Event__c='Invited'; 
        system.debug('jc ppud' + ppud);
        insert ppud; 
        //Referral_Contact__c con =  new Referral_Contact__c(Id=referralCt, CPA_Program_Status__c=cpaStatus, Email__c=email);
        ReferralAccountMethods.SKIP_TRIGGERS = True;
       // update con; 
    
    }

    @AuraEnabled
    public static void updateUser(Id userId, string userName, string email, Boolean reactivateUser) {
        List<User> userListToUpdate = new List<User>();
        User u = [SELECT Id, Username, Email, Requested_Invite_Date__c, IsActive FROM User WHERE Id=: userId];
        u.Username = userName;
        u.Email = email;
        u.Requested_Invite_Date__c = System.now();
        if(reactivateUser == true) {
            u.IsActive = true;
        }
        userListToUpdate.add(u);
        if(!userListToUpdate.isEmpty()) {
            DmlHelper.performDML2(userListToUpdate, DmlHelper.DML_UPDATE, 'ConvertContactToCPACommunityUser', 'updateUser', 'updating existing User', true);
        }
    }
}