force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Referral_Type__c.field-meta.xml
<CustomField>
    <fullName>Referral_Type__c</fullName>
    <label>Referral Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Firm</fullName>
            </value>
            <value>
                <fullName>Bank - Tier 1</fullName>
            </value>
            <value>
                <fullName>Bank - Tier 2</fullName>
            </value>
            <value>
                <fullName>52 Bank Tier 1</fullName>
            </value>
            <value>
                <fullName>52 Bank Tier 2</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>100 Broker</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Strategic Account</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/To_Be_Deleted__c.field-meta.xml
<CustomField>
    <fullName>To_Be_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box to have the Account deleted during the next delete process</description>
    <label>To Be Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mirror_Ref_Ctct__c.field-meta.xml
<CustomField>
    <fullName>Mirror_Ref_Ctct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If this is a referral, the matching Referral Contact object</description>
    <label>Mirror Ref Ctct</label>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Contacts (Mirror Ref Ctct)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Franchise National Account referral account.</inlineHelpText>
    <label>Referral National Account</label>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>not really used anywhere, as of 4/19/2013 is blank for all production records</description>
    <label>Referral Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Contact__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>R00N50000001WySDEA0</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Referral_Type__c.field-meta.xml
<CustomField>
    <fullName>Referral_Type__c</fullName>
    <label>Referral Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100 Broker</fullName>
            </value>
            <value>
                <fullName>10 CPA Referring 3-4/Year</fullName>
            </value>
            <value>
                <fullName>11 CPA2BIZ Call</fullName>
            </value>
            <value>
                <fullName>12 CPA Call</fullName>
            </value>
            <value>
                <fullName>19 CPA2BIZ Referral</fullName>
            </value>
            <value>
                <fullName>30 CPA Referring &lt;3/Year</fullName>
            </value>
            <value>
                <fullName>50 CPA Non-referring</fullName>
            </value>
            <value>
                <fullName>52 Bank Call</fullName>
            </value>
            <value>
                <fullName>5 CPA Referring &gt;4/Year</fullName>
            </value>
            <value>
                <fullName>60 Financial Advisor</fullName>
            </value>
            <value>
                <fullName>70 IIA Contracted</fullName>
            </value>
            <value>
                <fullName>70 IIA General</fullName>
            </value>
            <value>
                <fullName>76 Money Manager</fullName>
            </value>
            <value>
                <fullName>77 IIA Contracted</fullName>
            </value>
            <value>
                <fullName>80 Remote Program</fullName>
            </value>
            <value>
                <fullName>90 Employee</fullName>
            </value>
            <value>
                <fullName>Strategic Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>PBS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pay</fullName>
            </value>
            <value>
                <fullName>PAS</fullName>
            </value>
            <value>
                <fullName>H&amp;B</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/To_Be_Deleted__c.field-meta.xml
<CustomField>
    <fullName>To_Be_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box to have this contact deleted with the next delete process</description>
    <label>To Be Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/Referral_Account__c.object-meta.xml
<CustomObject>
    <description>Referral Source Company Information</description>
    <label>Referral Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Referral Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Account__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/fields/Referral_Type__c.field-meta.xml
<CustomField>
    <fullName>Referral_Type__c</fullName>
    <label>Referral Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>52 Bank Tier 1</fullName>
            </value>
            <value>
                <fullName>52 Bank Tier 2</fullName>
            </value>
            <value>
                <fullName>70 IIA Contracted</fullName>
            </value>
            <value>
                <fullName>70 IIA General</fullName>
            </value>
            <value>
                <fullName>76 Money Manager</fullName>
            </value>
            <value>
                <fullName>90 Employee</fullName>
            </value>
            <value>
                <fullName>Accounting Firm</fullName>
            </value>
            <value>
                <fullName>Bank - Tier 1</fullName>
            </value>
            <value>
                <fullName>Bank - Tier 2</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Oasis</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Strategic Account</fullName>
            </value>
            <value>
                <fullName>Trusted Advisor</fullName>
            </value>
            <value>
                <fullName>Bank - Non-partner</fullName>
            </value>
            <value>
                <fullName>IFA Sourced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral_Account__c/fields/To_Be_Deleted__c.field-meta.xml
<CustomField>
    <fullName>To_Be_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag for deletion</description>
    <label>To Be Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/Referral_Contact__c.object-meta.xml
<CustomObject>
    <label>Referral Contact</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Contact__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Referral Contact Email</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Referral Contact Phone</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Account__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Referral Contacts</relationshipLabel>
    <relationshipName>Referral_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Referral_Type__c.field-meta.xml
<CustomField>
    <fullName>Referral_Type__c</fullName>
    <description>The Type of Referral</description>
    <label>Referral Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10 CPA Referring 3-4/Year</fullName>
            </value>
            <value>
                <fullName>11 CPA2BIZ Call</fullName>
            </value>
            <value>
                <fullName>12 CPA Call</fullName>
            </value>
            <value>
                <fullName>19 CPA2BIZ Referral</fullName>
            </value>
            <value>
                <fullName>3(16) Fiduciary Partner</fullName>
            </value>
            <value>
                <fullName>30 CPA Referring &lt;3/Year</fullName>
            </value>
            <value>
                <fullName>50 CPA Non-referring</fullName>
            </value>
            <value>
                <fullName>5 CPA Referring &gt;4/Year</fullName>
            </value>
            <value>
                <fullName>80 Remote Program</fullName>
            </value>
            <value>
                <fullName>90 Employee</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Bank Employee</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Financial Advisor</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>IIA Contracted</fullName>
            </value>
            <value>
                <fullName>IIA General</fullName>
            </value>
            <value>
                <fullName>Insurance Agent</fullName>
            </value>
            <value>
                <fullName>Money Manager</fullName>
            </value>
            <value>
                <fullName>MSP Partner</fullName>
            </value>
            <value>
                <fullName>Portfolio Manager</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Strategic Partner</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Financial Advisor Assistant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MyAcctHelpTest.cls
/**
 * This class contains unit tests for validating the MyAcctHelp class.
 * 
 *
 * History
 * --------
 * 01/11/2023   Vinay   created
 *
 */
@isTest
public without sharing class MyAcctHelpTest {
    static testMethod void testReferralContactData() {
        ReferralObjectsSync.SKIP_SYNC = false;

        String referralAccRcId = Schema.getGlobalDescribe().get('Referral_Account__c').getDescribe().getRecordTypeInfosByName().get('Core Referral Source Record Type').getRecordTypeId();
        String referralContRcId = Schema.getGlobalDescribe().get('Referral_Contact__c').getDescribe().getRecordTypeInfosByName().get('Core Referral Record Type').getRecordTypeId();
        String contactRecordType = Schema.getGlobalDescribe().get('Contact').getDescribe().getRecordTypeInfosByName().get('Core Referral Record Type').getRecordTypeId();
        
        Referral_Account__c refacct = new Referral_Account__c (name = 'Referral Account1'
                                ,RecordTypeId=referralAccRcId
                                ,Referral_Type__c = 'Broker'
                                ,Zip_Postal_Code__c = '10000'
                                ,To_Be_Deleted__c = false);
        insert refacct;
        Referral_Contact__c refcon1 = new Referral_Contact__c(Name = 'First Ref Ctct1'
                                ,RecordTypeId=referralContRcId
                                ,Phone__c = '585-555-1212'
                                ,Email__c = 'fLast1@abc.com'
                                ,Referral_Type__c = '100 Broker'
                                ,Referral_Account__c = refacct.Id);
        insert refcon1;
        
        Account acc = new Account();
        acc.Name = 'Peo test';
        acc.ShippingState = 'Texas';
        insert acc;
        
        Contact c = new Contact(AccountId=acc.id,
                               FirstName = 'test',
                               LastName = 'contact',
                               RecordTypeId = contactRecordType,
                               Mirror_Ref_Ctct__c = refcon1.Id,
                               Email='testing@testing.com');
        insert c;
        
        Profile prof = [SELECT Id FROM Profile where name='CPA Customer Community Login User Clone'];
        
        User communityUsr = new User(
            UserName = c.email,
            FirstName = c.FirstName,
            LastName = c.LastName,
            Alias = 'alias',
            email = c.Email,
            ContactId = c.id,
            ProfileId = prof.Id,
            EmailEncodingKey = 'UTF-8',
            CommunityNickname = 'nickName',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            Sales_Org__c = 'Community'
        );
        insert communityUsr;
		test.startTest();
        System.runAs(communityUsr) {
            PageReference pref = Page.MyAcctHelp;
            pref.getParameters().put('userId', communityUsr.Id);
            Test.setCurrentPage(pref);
            MyAcctHelp controller = new MyAcctHelp();
        }
        test.stopTest();
    }
}