force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DuplicateCheckStatus__c.field-meta.xml
<CustomField>
    <fullName>DuplicateCheckStatus__c</fullName>
    <inlineHelpText>If a duplicate check was performed on this record, what is the result of the check?</inlineHelpText>
    <label>Duplicate Check Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Match Found</fullName>
            </value>
            <value>
                <fullName>Lead Match</fullName>
            </value>
            <value>
                <fullName>Contact Match</fullName>
            </value>
            <value>
                <fullName>Account Match</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/DuplicateNotWorkableReason__c.field-meta.xml
<CustomField>
    <fullName>DuplicateNotWorkableReason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The reason this record is not workable</inlineHelpText>
    <label>Duplicate Not Workable Reason</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OasisId__c.field-meta.xml
<CustomField>
    <fullName>OasisId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>The Salesforce Id of the record from the Oasis System</inlineHelpText>
    <label>Oasis Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <description>When errors occur during a process, a place we can capture and log them</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Log-{00000000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/ObjectId__c.field-meta.xml
<CustomField>
    <fullName>ObjectId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The id of the related object</inlineHelpText>
    <label>Object Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DisqualifiedReason__c.field-meta.xml
<CustomField>
    <fullName>DisqualifiedReason__c</fullName>
    <inlineHelpText>The Disqualified Reason from the Oasis system</inlineHelpText>
    <label>Disqualified Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Add to Do Not Call List</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>High Risk - Benefits</fullName>
            </value>
            <value>
                <fullName>High Risk - WC</fullName>
            </value>
            <value>
                <fullName>Low Budget</fullName>
            </value>
            <value>
                <fullName>Low Employee Count</fullName>
            </value>
            <value>
                <fullName>Low Interest</fullName>
            </value>
            <value>
                <fullName>Non-Profit</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Not a Fit</fullName>
            </value>
            <value>
                <fullName>Out of Business or Acquired or Paychex</fullName>
            </value>
            <value>
                <fullName>Send for data update</fullName>
            </value>
            <value>
                <fullName>Send to ASO</fullName>
            </value>
            <value>
                <fullName>Send to Marketing for nurturing</fullName>
            </value>
            <value>
                <fullName>Too Large</fullName>
            </value>
            <value>
                <fullName>Wrong Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/DuplicateCheckStatus__c.field-meta.xml
<CustomField>
    <fullName>DuplicateCheckStatus__c</fullName>
    <inlineHelpText>If a duplicate check was performed on this record, what is the result of the check?</inlineHelpText>
    <label>Duplicate Check Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Match Found</fullName>
            </value>
            <value>
                <fullName>Lead Match</fullName>
            </value>
            <value>
                <fullName>Contact Match</fullName>
            </value>
            <value>
                <fullName>Account Match</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/OasisId__c.field-meta.xml
<CustomField>
    <fullName>OasisId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>The Salesforce Id of the matching record from the Oasis Salesforce.</inlineHelpText>
    <label>Oasis Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OasisSync__c/OasisSync__c.object-meta.xml
<CustomObject>
    <description>Object used to share data between Paychex and Oasis</description>
    <label>Oasis Sync</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Oasis Sync Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oasis Syncs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OasisSync__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Street Address</inlineHelpText>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/DisqualifiedReason__c.field-meta.xml
<CustomField>
    <fullName>DisqualifiedReason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Disqualified Reason</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/DuplicateNotWorkableReason__c.field-meta.xml
<CustomField>
    <fullName>DuplicateNotWorkableReason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Duplicate Not Workable Reason</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/Fax__c.field-meta.xml
<CustomField>
    <fullName>Fax__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fax</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Oasis Syncs</relationshipLabel>
    <relationshipName>Oasis_Syncs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/LeadIdOasis__c.field-meta.xml
<CustomField>
    <fullName>LeadIdOasis__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>The Salesforce Id of the Lead from the Oasis Salesforce instance</inlineHelpText>
    <label>Lead Id Oasis</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/LeadIdPayx__c.field-meta.xml
<CustomField>
    <fullName>LeadIdPayx__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>The salesforce Id of the lead in the Paychex Instance</inlineHelpText>
    <label>Lead Id Payx</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OasisSync__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paychex</fullName>
            </value>
            <value>
                <fullName>Oasis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <formula>ReferralLookup__r.PartnerReferral__r.Source__c</formula>
    <label>Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartnerReferral__c/PartnerReferral__c.object-meta.xml
<CustomObject>
    <description>Referrals that are coming from a partner (ex bank, cpa, et al)</description>
    <label>Partner Referral</label>
    <nameField>
        <displayFormat>L{00000000}</displayFormat>
        <label>Referral Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PartnerReferral__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the company the referral is for.</inlineHelpText>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartnerReferral__c/fields/DuplicateCheckStatus__c.field-meta.xml
<CustomField>
    <fullName>DuplicateCheckStatus__c</fullName>
    <inlineHelpText>If a duplicate check was performed on this record, what is the result of the check?</inlineHelpText>
    <label>Duplicate Check Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Match Found</fullName>
            </value>
            <value>
                <fullName>Lead Match</fullName>
            </value>
            <value>
                <fullName>Contact Match</fullName>
            </value>
            <value>
                <fullName>Account Match</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PartnerReferral__c/fields/DuplicateNotWorkableReason__c.field-meta.xml
<CustomField>
    <fullName>DuplicateNotWorkableReason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The reason this record is not workable</inlineHelpText>
    <label>Duplicate Not Workable Reason</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartnerReferral__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The best email address that can be used to contact the prospect.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PartnerReferral__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The first name of the contact at the prospect.</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartnerReferral__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Partner Referrals</relationshipLabel>
    <relationshipName>Partner_Referral_Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PartnerReferral__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>How did this get created?</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartnerReferral__c/fields/Workable__c.field-meta.xml
<CustomField>
    <fullName>Workable__c</fullName>
    <inlineHelpText>Is this instance of the incoming lead workable?</inlineHelpText>
    <label>Workable</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Workable</fullName>
            </value>
            <value>
                <fullName>Not Workable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/CSUserId__c.field-meta.xml
<CustomField>
    <fullName>CSUserId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>The ClientSpace User Id</inlineHelpText>
    <label>CS User Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OasisSyncLeads.cls
/* Methods to process on the Oasis Sync object with the Lead

  History
  -------
  05/15/2019 Dan Carmen        Created
  08/09/2019 Dan Carmen        Changes to move workable code to DuplicateCheckQueueable
  03/10/2020 Dan Carmen        Comment out all code
  
 */
public without sharing class OasisSyncLeads {
    
   /*
   If this is coming from OasisSyncQueueable
       Check the DuplicateCheckStatus__c field
           If "No Match Found" - just return the value
           If "Lead Match" - see if the lead is workable
           If "Contact Match" or "Account Match" - see if the record is workable
   */
    
   public static Boolean processLeads(Lead[] lds, Map<Id,Lead> oldMap, String overrideSyncType, ErrorLog__c runLog) {
      /*
      Boolean recordsSent = false;

      Map<Id,User> userMap = OasisSyncHelper.getUserMap(lds);
      // check leads for the OasisId__c or PEO record type or User is a client space user
      Id peoRecordTypeId = null;
      Map<Id,Lead> leadsToProcessMap = new Map<Id,Lead>();
      if (String.isNotBlank(overrideSyncType)) {
         leadsToProcessMap = new Map<Id,Lead>(lds);
      } else {
         for (Lead ld : lds) {
            User usr = userMap.get(ld.OwnerId);
            if (ld.DuplicateCheckStatus__c != 'Pending'  // don't allow pending records to go through
                  && (String.isNotBlank(ld.OasisId__c) 
                   || (usr != null && usr.CSUserId__c != null)
                   || (ld.RecordTypeId == peoRecordTypeId))) {
               leadsToProcessMap.put(ld.Id,ld);
            } 
         } // for
      }
      
      System.debug('processLeads leadsToProcessMap='+leadsToProcessMap.size()+' overrideSyncType='+overrideSyncType);
      if (leadsToProcessMap.isEmpty()) {
         return false;
      }

      Map<Id,PartnerReferral__c> partRefMap = (overrideSyncType == OasisSyncHelper.SYNC_DUPE_RESULT ? getPartRefMap(leadsToProcessMap.keySet())
                                                : new Map<Id,PartnerReferral__c>());
      ErrorLog.addToDescription(runLog,'overrideSyncType='+overrideSyncType+' partRefMap='+partRefMap.size());
      OasisSync__c[] insertSyncs = new OasisSync__c[]{};
      OasisSync__c[] updateSyncs = new OasisSync__c[]{};
      
      Map<String,OasisSync__c> syncMap = OasisSyncHelper.getExistingSyncMap(leadsToProcessMap.values());
      
      // get the users identified on the syncs (if any) - only need to do this right now if the overrideSyncType is passed in
      Map<String,User> personIdUserMap = (String.isNotBlank(overrideSyncType) ? OasisSyncHelper.getUsersByPersonIdMap(syncMap.values()) : new Map<String,User>()); 
      
      Boolean isConnectionUser = OasisSyncHelper.isRunningUserConnectionUser();
      Set<Id> convertedLeadIdSet = new Set<Id>();
      
      ErrorLog.addToDescription(runLog,'processLeads leadsToProcessMap='+leadsToProcessMap.size()+' userMap='+userMap.size()+' syncMap='+syncMap.size()+' isConnectionUser='+isConnectionUser);
      System.debug('processLeads leadsToProcessMap='+leadsToProcessMap.size()+' userMap='+userMap.size()+' syncMap='+syncMap.size()+' isConnectionUser='+isConnectionUser);
      
      for (Lead ld : leadsToProcessMap.values()) {
         // log the info 
         if (runLog != null && String.isBlank(runLog.ObjectId__c)) {
            runLog.ObjectId__c = ld.Id;
            ErrorLog.addToObjectInfo(runLog,String.valueOf(ld));
         }
         Lead oldLd = (oldMap != null ? oldMap.get(ld.Id) : null);
         User usr = userMap.get(ld.OwnerId);
         Boolean clientSpaceUser = (usr != null && usr.CSUserId__c != null);
         OasisSync__c sync = OasisSyncHelper.getSync(ld,syncMap);
         User syncUsr = OasisSyncHelper.getUserFromMap(sync, personIdUserMap);
         
         System.debug('processLeads clientSpaceUser='+clientSpaceUser+' has sync='+(sync != null));

         if (oldLd == null && sync != null
                  && String.isNotBlank(overrideSyncType)
                  && overrideSyncType == OasisSyncHelper.SYNC_DUPE_RESULT 
                  //&& isConnectionUser
                  //&& String.isNotBlank(ld.DuplicateCheckStatus__c)
                  ) {
            System.debug('processLeads handling from here1');
            ErrorLog.addToDescription(runLog,'handling duplicate results: '+ld.DuplicateCheckStatus__c);
            // set the attributes on the sync record
            processLead(ld, oldLd, overrideSyncType, usr, sync, runLog, partRefMap.get(ld.Id), insertSyncs, updateSyncs);
            // check for additional criteria.
            //if (ld.DuplicateCheckStatus__c == 'Lead Match') {
               // check if the lead is workable
            //   checkAdditionalLeadCriteria(ld, sync, syncUsr, runLog);
            //} else if (ld.DuplicateCheckStatus__c == 'Contact Match' || ld.DuplicateCheckStatus__c == 'Account Match') {
            //   checkAddtionalAcctCtctCriteria(ld, sync, syncUsr, runLog);
            //} else if (ld.DuplicateCheckStatus__c == 'No Match Found') {
               // if no match then process the lead as is.
            //}
         } else if (isConnectionUser && oldLd == null && String.isBlank(overrideSyncType)) {
            // do not send the record on the insert from the connection user unless the overrideSyncType has a value
         } else if ((isConnectionUser && String.isNotBlank(overrideSyncType))
                      || (!isConnectionUser && (String.isNotBlank(ld.OasisId__c) || clientSpaceUser))) {
            // send if it's the connection user and overrideSyncType has a value (coming from dupe checking)
            // or not the connection user and has an oasis id or the user is a client space user

            System.debug('processLeads ld.IsConverted='+(ld.isConverted==true)+' has sync='+(sync != null));
            if (!ld.isConverted) {
               System.debug('processLeads handling from here2');
               // as long as the lead isn't converted just send as usual
               processLead(ld, oldLd, overrideSyncType, usr, sync, runLog, null, insertSyncs, updateSyncs);
            } else if (ld.isConverted) {
               // if the lead is converted we have to get some additional information
               convertedLeadIdSet.add(ld.Id);
            }
            recordsSent = true;
         }
      } // for (Lead ld
      
      ErrorLog.addToDescription(runLog,'convertedLeadIdSet='+convertedLeadIdSet.size());
      System.debug('processLeads convertedLeadIdSet='+convertedLeadIdSet.size());
      
      if (!convertedLeadIdSet.isEmpty()) {
         handleConvertedLeads(convertedLeadIdSet, syncMap, insertSyncs, updateSyncs, runLog);
      }
      
      ErrorLog.addToDescription(runLog,'insertSyncs='+insertSyncs.size()+' updateSyncs='+updateSyncs.size());
      recordsSent = (!insertSyncs.isEmpty() || !updateSyncs.isEmpty());
      OasisSyncHelper.checkSave(insertSyncs, updateSyncs);
      return recordsSent;
      */
      return false;
   } // processLeads
   
   /*
   public static Map<Id,PartnerReferral__c> getPartRefMap(Set<Id> leadIdSet) {
      Map<Id,PartnerReferral__c> partRefMap = new Map<Id,PartnerReferral__c>();
      PartnerReferral__c[] partRefs = [Select Id, Name, Lead__c
                                             ,DuplicateCheckStatus__c
                                             ,DuplicateNotWorkableReason__c
                                             ,Source__c
                                             ,Workable__c
                                         From PartnerReferral__c
                                        Where Lead__c in :leadIdSet
                                        order by CreatedDate desc];
      for (PartnerReferral__c partRef : partRefs) {
         // only store the latest in the map
         if (!partRefMap.containsKey(partRef.Lead__c)) {
            partRefMap.put(partRef.Lead__c,partRef);
         }
      } // for (PartnerReferral__c partRef
      System.debug('getPartRefMap leadIdSet='+leadIdSet.size()+' partRefMap='+partRefMap.size());
      return partRefMap;
   } // getPartRefMap
   
   public static void processLead(Lead ld, Lead oldLd, String syncType, User usr, OasisSync__c sync, ErrorLog__c runLog
                               ,PartnerReferral__c partRef
                               ,OasisSync__c[] insertSyncs, OasisSync__c[] updateSyncs) {
      if (String.isBlank(syncType)) {
         syncType = OasisSyncHelper.getSyncType(oldLd != null);
      }
      String msg = 'processLead ld='+ld.lastName+' syncType='+syncType+' has sync='+(sync != null)+' usr='+(usr != null ? usr.Name : 'noUser')+' partRef='+(partRef != null ? partRef.Name : 'NoPartRef');
      System.debug(msg);
      ErrorLog.addToDescription(runLog,msg);
      sync = OasisSyncHelper.prepareSync(sync, (ld.FirstName+' '+ld.LastName));
      
      sync.LeadIdPayx__c = ld.Id;
      sync.LeadIdOasis__c = ld.OasisId__c;
      
      sync.Address__c = ld.Street;
      sync.City__c = ld.City;
      sync.Company__c = ld.Company;
      sync.DisqualifiedReason__c = ld.DisqualifiedReason__c;
      sync.Email__c = ld.Email;
      sync.Fax__c = ld.Fax;
      sync.FirstName__c = ld.FirstName;
      sync.LastName__c = ld.LastName;
      sync.MobilePhone__c = ld.MobilePhone;
      sync.NumberOfEmployees__c = ld.NumberOfEmployees;
      sync.Phone__c = ld.Phone;
      sync.PostalCode__c = ld.PostalCode;
      sync.State__c = ld.State;
      sync.Title__c = ld.Title;
      sync.LeadStatus__c = ld.Status;
      sync.LeadSource__c = ld.LeadSource;
      sync.Lead__c = ld.Id;
 
      if (usr != null && usr.HR_Person_Id__c != null) {
         sync.OwnerHRPersonID__c = usr.HR_Person_Id__c;
      }
      sync.SyncType__c = syncType;
      if (syncType == OasisSyncHelper.SYNC_DUPE_RESULT && partRef != null) {
         sync.DuplicateCheckResult__c = ld.DuplicateCheckStatus__c+'-'+partRef.Workable__c;
         sync.DuplicateNotWorkableReason__c = partRef.DuplicateNotWorkableReason__c;
         ErrorLog.addToDescription(runLog,sync.DuplicateCheckResult__c);
      }

      if (ld.IsConverted) {      
         sync.ContactIdPayx__c = ld.ConvertedContactId;
         sync.AccountIdPayx__c = ld.ConvertedAccountId;
      }
      
      if (sync.Id == null) {
         insertSyncs.add(sync);
      } else {
         updateSyncs.add(sync);
      }
   } // processLead
   */
   public static void handleConvertedLeads(Set<Id> convertedLeadIdSet,Map<String,OasisSync__c> syncMap, OasisSync__c[] insertSyncs, OasisSync__c[] updateSyncs, ErrorLog__c runLog) {
      /*
      Set<String> querySet = new Set<String>();
      for (Id recId : convertedLeadIdSet) {
         querySet.add(recId);
      }

      //Map<String,OasisSync__c> syncMap = OasisSyncHelper.getExistingSyncMap(querySet);
      
      Lead[] convertedleads = [Select Id
                                     ,FirstName, LastName
                                     ,ConvertedAccountId
                                     ,ConvertedContactId
                                     ,ConvertedDate
                                     ,IsConverted
                                     ,OasisId__c
                                 From Lead
                                Where Id in :convertedLeadIdSet
                                  and IsConverted=true];
      System.debug('handleConvertedLeads convertedLeadIdSet='+convertedLeadIdSet.size()+' convertedleads='+convertedleads.size());
      ErrorLog.addToDescription(runLog,'handleConvertedLeads convertedLeadIdSet='+convertedLeadIdSet.size()+' convertedleads='+convertedleads.size());

      for (Lead ld : convertedLeads) {
         // get the existing sync record (if it exists)
         OasisSync__c sync = OasisSyncHelper.prepareSync(syncMap.get(ld.Id), (ld.FirstName+' '+ld.LastName));
         sync.SyncType__c=OasisSyncHelper.SYNC_LEAD_CONVERTED;
         sync.LeadIdPayx__c = ld.Id;
         sync.ContactIdPayx__c = ld.ConvertedContactId;
         sync.AccountIdPayx__c = ld.ConvertedAccountId;
         sync.LeadIdOasis__c = ld.OasisId__c;
         
         sync.Lead__c = ld.Id;
         sync.Contact__c = ld.ConvertedContactId;
         sync.Account__c = ld.ConvertedAccountId;
         
         if (sync.Id == null) {
            insertSyncs.add(sync);
         } else {
            updateSyncs.add(sync);
         }
      } // for (Lead ld
      */
   } // handleConvertedLeads

/*
   // a match occurred on a lead. Check if there is any activity attached to it.   
   public static Boolean checkAdditionalLeadCriteria(Lead ld, OasisSync__c sync, User syncUsr, ErrorLog__c runLog) {
      Boolean okay = true;
      sync.DuplicateNotWorkableReason__c = '';
      Date activityDate = Date.today().addDays(-30);
      // check open activities
      Task[] tasks = [Select Id, ActivityDate, IsClosed from Task where WhoId=:ld.Id and ActivityDate >= :activityDate order by ActivityDate limit 5];
      ErrorLog.addToDescription(runLog,'checkAdditionalLeadCriteria tasks='+tasks.size());
      Boolean activityFound = (!tasks.isEmpty());
      if (!activityFound) {
         Event[] events = [Select Id, ActivityDate from Event where WhoId=:ld.Id and ActivityDate >= :activityDate order by ActivityDate limit 5];
         ErrorLog.addToDescription(runLog,'events='+events.size());
         activityFound = (!events.isEmpty());
         if (activityFound) {
            sync.DuplicateNotWorkableReason__c = 'Open Events found';
         }
      } else {
         sync.DuplicateNotWorkableReason__c = 'Open Tasks found';
      }
      sync.DuplicateCheckResult__c = ld.DuplicateCheckStatus__c+ (!activityFound ? '-Workable' : '-Not Workable');
      ErrorLog.addToDescription(runLog,'CheckStatus__c='+sync.DuplicateCheckResult__c+' NotWorkableReason='+sync.DuplicateNotWorkableReason__c);
      return okay;
   } // checkAdditionalLeadCriteria
*/
/*
o  If the incoming Oasis Lead is matched to a Prospect Client (Current Client? Is False) within the Paychex Salesforce instance AND has no Open Opportunity AND has no activity in the last 6 months, then the Lead is considered workable by the BDR
  Workable information is sent back to Oasis instance
•  This will be worked as usual by the BDR
  Partner Referral is created with the incoming information
  Record type is updated to Prospect Record Type
  Type is set to Oasis Prospect
  Hold Out – True
  Hold Out Description – Oasis Prospect
  Owner – New Oasis Generic User for placeholder. Upon the BDR working and converting they will send the Account record which should match to this one and then the owner will be updated then

If there are Open Opps with activity in the last 6 months – not workable by Oasis BDR
If there are no Open Opps but activity in the last 90 days – not workable by the Oasis BDR
If there are no Open Opps but future activity in the next 90 days – not workable by the Oasis BDR
All else is workable.
if they have an open opportunity and no activity for three months, it can be worked.

*/
/*
   // a match occurred on an account or contact. Check if there is any activity attached to it.   
   public static Boolean checkAddtionalAcctCtctCriteria(Lead ld, OasisSync__c sync, User syncUsr, ErrorLog__c runLog) {
      Boolean okay = true;
      sync.DuplicateNotWorkableReason__c = '';
      Date oppCheckDate = Date.today().addMonths(-6);
      Date activityQueryDate = Date.today().addMonths(-6);
      // check if activity in this range
      Date activityCheckDate = Date.today().addDays(-90);
      Date activityFutureDate = Date.today().addDays(90);
      Boolean workable = true;
      Lead convertedLead = null;
      String processNotes = 'checkAddtionalAcctCtctCriteria';
      try {
         convertedLead = [Select Id
                                     ,FirstName, LastName
                                     ,ConvertedAccountId
                                     ,ConvertedAccount.Id
                                     ,ConvertedAccount.Name
                                     ,ConvertedAccount.OwnerId
                                     ,ConvertedAccount.RecordType.Name
                                     ,ConvertedAccount.RecordTypeId
                                     ,ConvertedAccount.Type
                                     ,ConvertedAccount.Hold_Out__c
                                     ,ConvertedAccount.Permanent_Hold_Out_Description__c
                                     ,ConvertedContactId
                                     ,ConvertedDate
                                     ,IsConverted
                                     ,OasisId__c
                                 From Lead
                                Where Id = :ld.Id
                                  and IsConverted=true];
      } catch (Exception e) {
         //ErrorLog.addToDescription(runLog,'Error finding the converted lead for Id='+ld.Id);
         StringHelper.addToProcessNotes(sync,'Error finding the converted lead for Id='+ld.Id);
      }
      if (convertedLead == null) {
         return false;
      }
      // collect the converted account/contact info
      sync.ContactIdPayx__c = ld.ConvertedContactId;
      sync.AccountIdPayx__c = ld.ConvertedAccountId;
      Account acct = null;
      try {
         acct = [Select Id, Name, CurrentClient__c, RecordTypeId, RecordType.Id, RecordType.Name, Type
                       ,(Select Id, ActivityDate, IsClosed 
                           from Tasks 
                          where ActivityDate >= :activityQueryDate
                            and ActivityDate <= :activityFutureDate
                           order by ActivityDate desc limit 10)  // order by newest first so we just have to check the date of the first to see if recent
                       ,(Select Id, ActivityDate 
                           from Events 
                          where ActivityDate >= :activityQueryDate 
                            and ActivityDate <= :activityFutureDate
                          order by ActivityDate desc limit 10)  // order by newest first so we just have to check the date of the first to see if recent
                       ,(Select Id, Name, CloseDate from Opportunities where IsClosed = false and CreatedDate >= :oppCheckDate limit 5)
                    From Account
                   Where Id = :convertedLead.ConvertedAccountId];
      } catch (Exception e) {
         StringHelper.addToProcessNotes(sync,'Error selecting the account: '+e.getMessage()+'; '+e.getStackTraceString());
         //ErrorLog.addToDescription(runLog,'Error selecting the account: '+e.getMessage()+'; '+e.getStackTraceString());
         System.debug('checkAddtionalAcctCtctCriteria exception: '+e.getMessage()+'; '+e.getStackTraceString());
         okay = false;
      }
      
      if (acct != null) {
         System.debug('checkAddtionalAcctCtctCriteria acct='+acct.Name+' currentClient='+acct.CurrentClient__c);
         //StringHelper.addToProcessNotes(sync,'currentClient='+acct.CurrentClient__c);
         processNotes += ('; currentClient='+acct.CurrentClient__c);
         if (acct.CurrentClient__c) {
            sync.DuplicateNotWorkableReason__c = 'Current Paychex Client';
            workable=false;
         } else {
            Boolean openOpps = (!acct.Opportunities.isEmpty());
            Boolean hasTasks = (!acct.Tasks.isEmpty());
            Boolean hasEvents = (!acct.Events.isEmpty());
            System.debug('checkAddtionalAcctCtctCriteria openOpps='+openOpps+' hasTasks='+hasTasks+' hasEvents='+hasEvents);
            processNotes += ('; openOpps='+openOpps+' hasTasks='+hasTasks+' hasEvents='+hasEvents);
            if (openOpps && (hasTasks || hasEvents)) {
               //has an Open Opportunity AND has any activity in the last 6 months, then the Lead is considered not workable by the BDR
               workable = false;
               sync.DuplicateNotWorkableReason__c = 'Has Open Opportunities and Activity';
            } else { 
               // check if any of the activity is recent - just have to check the first one in the list since sorted by newest date
               Boolean hasRecentActivity = (hasTasks && acct.Tasks[0].ActivityDate >= activityCheckDate);
               if (!hasRecentActivity) {
                  hasRecentActivity = (hasEvents && acct.Events[0].ActivityDate >= activityCheckDate);
               }
               workable = !hasRecentActivity;
               if (hasRecentActivity) {
                  sync.DuplicateNotWorkableReason__c = 'Has Recent Activity';
               }
            }
         }
         
         if (workable) {
            Account updateAcct = new Account(Id=acct.Id);
            Map<String,Schema.RecordTypeInfo> byNameMap = Account.SObjectType.getDescribe().getRecordTypeInfosByName();
            Schema.RecordTypeInfo prospectRtInfo = byNameMap.get(Label.RT_Prospect_Acct);
            if (prospectRtInfo != null) {
               updateAcct.RecordTypeId = prospectRtInfo.getRecordTypeId();
            }
            updateAcct.PEOLeasing__c = true;
            updateAcct.Type = 'Oasis Prospect';
            if (syncUsr != null) {
               updateAcct.OwnerId = syncUsr.Id;
            }
            updateAcct.Hold_Out__c=true;
            updateAcct.Permanent_Hold_Out_Description__c='Oasis Prospect';
            ZipCheckOwner.SKIP_TRIGGERS=true;
            DmlHelper.performDML2(new Account[]{updateAcct}, DmlHelper.DML_UPDATE, 'OasisSyncLeads', 'checkAddtionalAcctCtctCriteria', 'Update hold out info on Account', true);
         } // if (workable
      } // if (acct != null
      sync.DuplicateCheckResult__c = ld.DuplicateCheckStatus__c+ (workable ? '-Workable' : '-Not Workable');
      //ErrorLog.addToDescription(runLog,'CheckStatus__c='+sync.DuplicateCheckResult__c+' NotWorkableReason='+sync.DuplicateNotWorkableReason__c);
      StringHelper.addToProcessNotes(sync,(processNotes+'; CheckStatus__c='+sync.DuplicateCheckResult__c+' NotWorkableReason='+sync.DuplicateNotWorkableReason__c));
      System.debug('checkAddtionalAcctCtctCriteria CheckStatus__c='+sync.DuplicateCheckResult__c+' NotWorkableReason='+sync.DuplicateNotWorkableReason__c);
      return okay;
   } // checkAddtionalAcctCtctCriteria
    */
} // class OasisSyncLeads