force-app/main/default/objects/Account/fields/Federal_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Federal_ID_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Federal ID Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup to the Opportunity if this Case is associated with one.</description>
    <inlineHelpText>A lookup to the Opportunity if this Case is associated with one.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HNBF_Sales_Type__c.field-meta.xml
<CustomField>
    <fullName>HNBF_Sales_Type__c</fullName>
    <label>Opportunity SubType</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OpportunityType__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Aflac</fullName>
            </value>
            <value>
                <fullName>AOR</fullName>
            </value>
            <value>
                <fullName>AOR with Renewal</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>Commuter Benefits</fullName>
            </value>
            <value>
                <fullName>Cyber Liability</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Directors and Officers</fullName>
            </value>
            <value>
                <fullName>Disability</fullName>
            </value>
            <value>
                <fullName>Employment Practice Liability (EPLI)</fullName>
            </value>
            <value>
                <fullName>Errors and Omissions</fullName>
            </value>
            <value>
                <fullName>Fiduciary Liability</fullName>
            </value>
            <value>
                <fullName>FSA</fullName>
            </value>
            <value>
                <fullName>FSA/PBA</fullName>
            </value>
            <value>
                <fullName>HRA</fullName>
            </value>
            <value>
                <fullName>HSA</fullName>
            </value>
            <value>
                <fullName>Incentive Split</fullName>
            </value>
            <value>
                <fullName>Life</fullName>
            </value>
            <value>
                <fullName>Misc Bond (This includes ID Fraud, Travelers MISC Bond(CRIME BOND))</fullName>
            </value>
            <value>
                <fullName>MS – Full Revenue 100%</fullName>
                <label>MS Full Revenue 100%</label>
            </value>
            <value>
                <fullName>MS Referral Split 70/30</fullName>
            </value>
            <value>
                <fullName>MS Team + Referral 35/35/30</fullName>
            </value>
            <value>
                <fullName>MS – Team Split 50/50</fullName>
                <label>MS Team Split 50/50</label>
            </value>
            <value>
                <fullName>Multiple Lines</fullName>
            </value>
            <value>
                <fullName>New Case</fullName>
            </value>
            <value>
                <fullName>New Group</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Oasis Internal Referral Split</fullName>
            </value>
            <value>
                <fullName>Oasis SOAR Split</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityType__c.field-meta.xml
<CustomField>
    <fullName>OpportunityType__c</fullName>
    <description>Used to determine whether or not an Opportunity is a duplicate. After resorting picklist order, always move the following values to the end of the list: Adjustment; True-Up; Chargeback; Balance.</description>
    <inlineHelpText>Is this a payroll or an HRS opportunity?</inlineHelpText>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Add-On ID</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>ASO</fullName>
                <label>HR Pro</label>
            </value>
            <value>
                <fullName>AUTO</fullName>
            </value>
            <value>
                <fullName>Balance</fullName>
            </value>
            <value>
                <fullName>BeneTrac Gold</fullName>
            </value>
            <value>
                <fullName>BeneTrac Platinum</fullName>
            </value>
            <value>
                <fullName>BND (ERISA BOND)</fullName>
            </value>
            <value>
                <fullName>BOP (Business Owners Package)</fullName>
            </value>
            <value>
                <fullName>Chargeback</fullName>
            </value>
            <value>
                <fullName>Conversion</fullName>
            </value>
            <value>
                <fullName>Cyber A Basic $250</fullName>
            </value>
            <value>
                <fullName>Cyber A Basic $300</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 1 $1,725</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 1 $750</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 2 $1,200</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 2 $1,940.63</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 3 $1,500</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 3 $3,151.58</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 4 $2,650</fullName>
            </value>
            <value>
                <fullName>Cyber Enhanced 4 $5,304.38</fullName>
            </value>
            <value>
                <fullName>Digital Marketing</fullName>
            </value>
            <value>
                <fullName>Directors and Officers</fullName>
            </value>
            <value>
                <fullName>Disability</fullName>
            </value>
            <value>
                <fullName>Employment Practice Liability (EPLI)</fullName>
            </value>
            <value>
                <fullName>ERISA</fullName>
            </value>
            <value>
                <fullName>Errors and Omissions</fullName>
            </value>
            <value>
                <fullName>ERTC</fullName>
            </value>
            <value>
                <fullName>Umbrella</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tarmika_Quote__c.field-meta.xml
<CustomField>
    <fullName>Tarmika_Quote__c</fullName>
    <description>URL to Tarmika quote</description>
    <encryptionScheme>None</encryptionScheme>
    <label>PC Quote</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/P_C_Carrier_Data__c/P_C_Carrier_Data__c.object-meta.xml
<CustomObject>
    <description>each carrier/Line of Business instance quoted thru Huckleberry</description>
    <label>P&amp;C Carrier Data</label>
    <nameField>
        <displayFormat>PC Carrier Data-{0000}</displayFormat>
        <label>P&amp;C Carrier Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>P&amp;C Carrier Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/P_C_Carrier_Data__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Line of Business</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/P_C_Carrier_Data__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>P&amp;C Carrier Data</relationshipLabel>
    <relationshipName>P_C_Carrier_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P_C_Carrier_Data__c/fields/P_C_Quote_Data__c.field-meta.xml
<CustomField>
    <fullName>P_C_Quote_Data__c</fullName>
    <label>P&amp;C Quote Data</label>
    <referenceTo>PC_Quote_Data__c</referenceTo>
    <relationshipLabel>P&amp;C Carrier Data</relationshipLabel>
    <relationshipName>P_C_Carrier_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PC_Quote_Data__c/PC_Quote_Data__c.object-meta.xml
<CustomObject>
    <description>Used to store data sent from SF to Tarmika and Tarmika&apos;s response back into SF</description>
    <label>P&amp;C Quote Data</label>
    <nameField>
        <displayFormat>P&amp;C Quote Data {00000000}</displayFormat>
        <label>P&amp;C Quote Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>P&amp;C Quote Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PC_Quote_Data__c/fields/Contact_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Address__c</fullName>
    <description>pulled in from related opportunity/contact</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PC_Quote_Data__c/fields/Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_First_Name__c</fullName>
    <description>pulled in from related opportunity/contact</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_Quote_Data__c/fields/Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Last_Name__c</fullName>
    <description>pulled in from related opportunity/contact</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_Quote_Data__c/fields/Contact_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Phone_Number__c</fullName>
    <description>pulled in from related opportunity/contact</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/PC_Quote_Data__c/fields/Federal_Id_Number__c.field-meta.xml
<CustomField>
    <fullName>Federal_Id_Number__c</fullName>
    <description>pulled in from related opportunity/account</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Federal Id Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_Quote_Data__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Tarmika_Integrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PC_Quote_Data__c/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <description>pulled from related Opportunity</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Opportunity Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_Quote_Data__c/fields/Prospect_Client__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect-Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>P&amp;C Quote Data</relationshipLabel>
    <relationshipName>P_C_Quote_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PC_Quote_Data__c/fields/Prospect_Client_City__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Client_City__c</fullName>
    <description>pulled in from related opportunity/account</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Prospect-Client City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_Quote_Data__c/fields/Prospect_Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Client_Name__c</fullName>
    <description>pulled in from related opportunity</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Prospect-Client Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_Quote_Data__c/fields/Prospect_Client_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Client_Postal_Code__c</fullName>
    <description>pulled in from related opportunity/account</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Prospect-Client Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_Quote_Data__c/fields/Prospect_Client_State__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Client_State__c</fullName>
    <description>pulled in from related opportunity/account</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Prospect-Client State</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PC_Quote_Data__c/fields/Prospect_Client_Street__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Client_Street__c</fullName>
    <description>pulled in from related opportunity/account</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Prospect-Client Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_P_C__c/Reference_P_C__c.object-meta.xml
<CustomObject>
    <description>Used by the Property and Casualty (P&amp;C) Team to onboard clients.</description>
    <label>Reference P&amp;C</label>
    <nameField>
        <displayFormat>Reference PC - {0000}</displayFormat>
        <label>Reference P&amp;C Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference P&amp;C&apos;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_P_C__c/fields/Prospect_Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect-Client Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reference P&amp;C&apos;s</relationshipLabel>
    <relationshipName>Reference_P_C_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PCCarrierDataMethodsTest.cls
/* 
   Test methods for the P_C_Carrier_Data__c object

   
  History
  -------
  12/22/2023 Carrie Marciano        Created

*/
@isTest
public class PCCarrierDataMethodsTest {
	public static String [] dqSalesOrgs = Label.PCQuoteDataSalesOrg.split(',');
    public static ID pcRT = Label.PCQuoteDataRecordTypeId;
    
    static testMethod void testSingleCarrierDataSameOppLOB() {    	                    
        Account acct = new Account(Name='ACCT1', Federal_ID_Number__c='86-7530913'
                                   ,ShippingStreet='23 Some Street', ShippingCity='SomeCity', ShippingState='NY', ShippingPostalCode='14623', ShippingCountry='US');
        insert acct;
        
        Contact ctct = new Contact(FirstName='Louis',LastName='Test1a',Email='louis@test1.com', MobilePhone='(585) 111-2222', AccountId=acct.id);
        insert ctct;
        
        Opportunity opp = new Opportunity(Name='PC OPP', AccountId=acct.Id, RecordTypeId = pcRT, OpportunityType__c = 'AUTO', HNBF_Sales_Type__c = 'New Case', CloseDate=Date.today().addDays(7), StageName = 'Discovery', Probability = 40, Tarmika_Quote__c = 'https://bridge.tarmika.com');
        insert opp;
        
        //initial insert of P&C Quote Data 
        PC_Quote_Data__c pcqD = new PC_Quote_Data__c(Opportunity__c = opp.Id, Prospect_Client__c=acct.Id, Opportunity_Type__c=opp.OpportunityType__c,Prospect_Client_Name__c=acct.Name,
                                                     Prospect_Client_Street__c=acct.ShippingStreet, Prospect_Client_City__c=acct.ShippingCity, Prospect_Client_State__c=acct.ShippingState,
                                                     Prospect_Client_Postal_Code__c=acct.ShippingPostalCode, Contact_First_Name__c=ctct.FirstName, Contact_Last_Name__c=ctct.LastName,
                                                     Contact_Phone_Number__c=ctct.Phone, Contact_Email_Address__c=ctct.Email);
        insert pcqD;
               
        //inserting P&C Carrier Data with inital response from Huckleberry
        P_C_Carrier_Data__c pccD = new P_C_Carrier_Data__c(P_C_Quote_Data__c = pcqD.Id, Line_of_Business__c = 'CA', Carrier_Name__c = 'Farmers', Quote_Carrier_ID__c = '47-87451233', Quote_Request_ID__c = '8754210000', Quote_Premium__c = 1205.36, Quote_Status__c = 'BINDABLE');
        insert pccD;
        
    	P_C_Carrier_Data__c pccD2 = [Select Id, P_C_Quote_Data__c, Opportunity__c, Opportunity__r.StageName, Line_of_Business__c, Carrier_Name__c, Quote_Carrier_ID__c, Quote_Premium__c, Quote_Status__c from P_C_Carrier_Data__c where Id =:pccD.Id];
        System.assertEquals('BINDABLE', pccD2.Quote_Status__c);
        System.assertEquals('Proposal', pccD2.Opportunity__r.StageName);
        
        //updating P&C Carrier Data with Policy Number adn Policy Bind Date response from Huckleberry - update opportunity
        pccD.Policy_Carrier_ID__c = '25478152';
        pccD.Policy_Bind_Date__c = Date.today();
        update pccD;
        
        P_C_Carrier_Data__c pccD3 = [Select Id, P_C_Quote_Data__c, Opportunity__c, Opportunity__r.StageName, Policy_Carrier_ID__c, Policy_Bind_Date__c from P_C_Carrier_Data__c where Id =:pccD.Id];
        System.assertEquals('25478152', pccD3.Policy_Carrier_ID__c);
        System.assertEquals(Date.today(), pccD3.Policy_Bind_Date__c);
        System.assertEquals('Sold-Submitted', pccD3.Opportunity__r.StageName);
        
    } //testSingleCarrierDataSameOppLOB
    
    static testMethod void testSingleCarrierDataSameOppLOBUpdates(){ 	                    
        Account acct = new Account(Name='ACCT1', Federal_ID_Number__c='86-7530913'
                                   ,ShippingStreet='23 Some Street', ShippingCity='SomeCity', ShippingState='NY', ShippingPostalCode='14623', ShippingCountry='US');
        insert acct;
        
        Contact ctct = new Contact(FirstName='Louis',LastName='Test1a',Email='louis@test1.com', MobilePhone='(585) 111-2222', AccountId=acct.id);
        insert ctct;
        
        Opportunity opp = new Opportunity(Name='PC OPP', AccountId=acct.Id, RecordTypeId = pcRT, OpportunityType__c = 'AUTO', HNBF_Sales_Type__c = 'New Case', CloseDate=Date.today().addDays(7), StageName = 'Discovery', Probability = 40, Tarmika_Quote__c = 'https://bridge.tarmika.com');
        insert opp;
        
        Id caseRTId = RecordTypeHelper.getRecordType('Service Onboarding P&C Case', 'Case').getRecordTypeID();
        Case kase  = new Case(AccountId = acct.id, Opportunity__c = opp.id, recordtypeId = caseRTId);
        insert kase;
        
        Id refPCTypeId = RecordTypeHelper.getRecordType('P&C Onboarding', 'Reference_P_C__c').getRecordTypeID();
        Reference_P_C__c refPC = new Reference_P_C__c(Case_Lookup__c = kase.id, Opportunity_Lookup__c = opp.id, recordTypeId = refPCTypeId);
        insert refPC;
        
        //initial insert of P&C Quote Data 
        PC_Quote_Data__c pcqD = new PC_Quote_Data__c(Opportunity__c = opp.Id, Prospect_Client__c=acct.Id, Opportunity_Type__c=opp.OpportunityType__c,Prospect_Client_Name__c=acct.Name,
                                                     Prospect_Client_Street__c=acct.ShippingStreet, Prospect_Client_City__c=acct.ShippingCity, Prospect_Client_State__c=acct.ShippingState,
                                                     Prospect_Client_Postal_Code__c=acct.ShippingPostalCode, Contact_First_Name__c=ctct.FirstName, Contact_Last_Name__c=ctct.LastName,
                                                     Contact_Phone_Number__c=ctct.Phone, Contact_Email_Address__c=ctct.Email);
        insert pcqD;
               
        //inserting P&C Carrier Data with inital response from Huckleberry
        P_C_Carrier_Data__c pccD = new P_C_Carrier_Data__c(P_C_Quote_Data__c = pcqD.Id, Line_of_Business__c = 'CA', Carrier_Name__c = 'Farmers', Quote_Carrier_ID__c = '47-87451233', Quote_Request_ID__c = '8754210000', Quote_Premium__c = 1205.36, Quote_Status__c = 'Quoted');
        insert pccD;
        
    	P_C_Carrier_Data__c pccD2 = [Select Id, P_C_Quote_Data__c, Opportunity__c, Opportunity__r.StageName, Line_of_Business__c, Carrier_Name__c, Quote_Carrier_ID__c, Quote_Premium__c, Quote_Status__c from P_C_Carrier_Data__c where Id =:pccD.Id];
        System.assertEquals('Quoted', pccD2.Quote_Status__c);
        
        //updating P&C Carrier Data with Quote Status response from Huckleberry - update opportunity
        pccD.Quote_Status__c = 'BINDABLE';
        update pccD;
        
        P_C_Carrier_Data__c pccD3 = [Select Id, P_C_Quote_Data__c, Opportunity__c, Opportunity__r.StageName, Line_of_Business__c, Carrier_Name__c, Quote_Carrier_ID__c, Quote_Premium__c, Quote_Status__c from P_C_Carrier_Data__c where Id =:pccD.Id];
        System.assertEquals('BINDABLE', pccD3.Quote_Status__c);
        System.assertEquals('Proposal', pccD3.Opportunity__r.StageName);
        
        //updating P&C Carrier Data with Policy Number adn Policy Bind Date response from Huckleberry - update opportunity
        pccD.Policy_Carrier_ID__c = '25478152';
        pccD.Policy_Bind_Date__c = Date.today();
        pccD.Renewal_Date__c = Date.today()+365;
        update pccD;
        
        P_C_Carrier_Data__c pccD4 = [Select Id, P_C_Quote_Data__c, Opportunity__c, Opportunity__r.StageName, Renewal_Date__c, Policy_Carrier_ID__c, Policy_Bind_Date__c from P_C_Carrier_Data__c where Id =:pccD.Id];
        System.assertEquals('25478152', pccD4.Policy_Carrier_ID__c);
        System.assertEquals(Date.today(), pccD4.Policy_Bind_Date__c);
        System.assertEquals('Sold-Submitted', pccD4.Opportunity__r.StageName);
        
    } //testSingleCarrierDataSameOppLOBUpdates
    
    static testMethod void testSingleCarrierDataNonOppLOB() {
    	 Account acct = new Account(Name='ACCT1', Federal_ID_Number__c='86-7530913'
                                   ,ShippingStreet='23 Some Street', ShippingCity='SomeCity', ShippingState='NY', ShippingPostalCode='14623', ShippingCountry='US');
        insert acct;
        
        Contact ctct = new Contact(FirstName='Louis',LastName='Test1a',Email='louis@test1.com', MobilePhone='(585) 111-2222', AccountId=acct.id);
        insert ctct;
        
        Opportunity opp = new Opportunity(Name='PC OPP', AccountId=acct.Id, RecordTypeId = pcRT, OpportunityType__c = 'BOP (Business Owners Package)', HNBF_Sales_Type__c = 'New Case', CloseDate=Date.today().addDays(7), StageName = 'Discovery', Probability = 40, Tarmika_Quote__c = 'https://bridge.tarmika.com');
        insert opp;
        
        //initial insert of P&C Quote Data 
        PC_Quote_Data__c pcqD = new PC_Quote_Data__c(Opportunity__c = opp.Id, Prospect_Client__c=acct.Id, Opportunity_Type__c=opp.OpportunityType__c,Prospect_Client_Name__c=acct.Name,
                                                     Prospect_Client_Street__c=acct.ShippingStreet, Prospect_Client_City__c=acct.ShippingCity, Prospect_Client_State__c=acct.ShippingState,
                                                     Prospect_Client_Postal_Code__c=acct.ShippingPostalCode, Contact_First_Name__c=ctct.FirstName, Contact_Last_Name__c=ctct.LastName,
                                                     Contact_Phone_Number__c=ctct.Phone, Contact_Email_Address__c=ctct.Email);
        insert pcqD;
               
        //inserting P&C Carrier Data with inital response from Huckleberry
        P_C_Carrier_Data__c pccD = new P_C_Carrier_Data__c(P_C_Quote_Data__c = pcqD.Id, Line_of_Business__c = 'Financial', Carrier_Name__c = 'Citizens', Quote_Carrier_ID__c = '784522-45', Quote_Request_ID__c = '00000452', Quote_Premium__c = 1205.36, Quote_Status__c = 'BINDABLE');
        insert pccD;
        
    	P_C_Carrier_Data__c pccD2 = [Select Id, P_C_Quote_Data__c, Opportunity__c, Opportunity__r.StageName, Opportunity__r.AdditionalProductsOfInterest__c, Line_of_Business__c, Carrier_Name__c, Quote_Carrier_ID__c, Quote_Premium__c, Quote_Status__c from P_C_Carrier_Data__c where Id =:pccD.Id];
        System.assertEquals(null, pccD2.Opportunity__c);
        Opportunity origOpp = [Select Id, Name, OpportunityType__c, AdditionalProductsOfInterest__c from Opportunity where Id = :opp.Id];
        System.assertEquals('Financial', origOpp.AdditionalProductsOfInterest__c);
         
    } //testSingleCarrierDataNonOppLOB 
    
    static testMethod void testMultipleCarrierDataSameOppLOB() {    	                    
	 	Account acct = new Account(Name='ACCT1', Federal_ID_Number__c='86-7530913'
                                   ,ShippingStreet='23 Some Street', ShippingCity='SomeCity', ShippingState='NY', ShippingPostalCode='14623', ShippingCountry='US');
        insert acct;
        
        Contact ctct = new Contact(FirstName='Louis',LastName='Test1a',Email='louis@test1.com', MobilePhone='(585) 111-2222', AccountId=acct.id);
        insert ctct;
        
        Opportunity opp = new Opportunity(Name='PC OPP', AccountId=acct.Id, RecordTypeId = pcRT, OpportunityType__c = 'Umbrella', HNBF_Sales_Type__c = 'New Case', CloseDate=Date.today().addDays(7), StageName = 'Discovery', Probability = 40, Tarmika_Quote__c = 'https://bridge.tarmika.com');
        insert opp;
        
        //initial insert of P&C Quote Data 
        PC_Quote_Data__c pcqD = new PC_Quote_Data__c(Opportunity__c = opp.Id, Prospect_Client__c=acct.Id, Opportunity_Type__c=opp.OpportunityType__c,Prospect_Client_Name__c=acct.Name,
                                                     Prospect_Client_Street__c=acct.ShippingStreet, Prospect_Client_City__c=acct.ShippingCity, Prospect_Client_State__c=acct.ShippingState,
                                                     Prospect_Client_Postal_Code__c=acct.ShippingPostalCode, Contact_First_Name__c=ctct.FirstName, Contact_Last_Name__c=ctct.LastName,
                                                     Contact_Phone_Number__c=ctct.Phone, Contact_Email_Address__c=ctct.Email);
        insert pcqD;
               
        //inserting P&C Carrier Data with inital response from Huckleberry
        P_C_Carrier_Data__c pccD1 = new P_C_Carrier_Data__c(P_C_Quote_Data__c = pcqD.Id, Line_of_Business__c = 'UMB', Carrier_Name__c = 'Farmers', Quote_Carrier_ID__c = '47-87451233', Quote_Request_ID__c = '8754210000', Quote_Premium__c = 1205.36, Quote_Status__c = 'BINDABLE');
        P_C_Carrier_Data__c pccD2 = new P_C_Carrier_Data__c(P_C_Quote_Data__c = pcqD.Id, Line_of_Business__c = 'UMB', Carrier_Name__c = 'Mutual', Quote_Carrier_ID__c = '35-8547521', Quote_Request_ID__c = '8754210001', Quote_Premium__c = 1300.66, Quote_Status__c = 'BINDABLE');
        P_C_Carrier_Data__c pccD3 = new P_C_Carrier_Data__c(P_C_Quote_Data__c = pcqD.Id, Line_of_Business__c = 'UMB', Carrier_Name__c = 'Liberty', Quote_Carrier_ID__c = '60-74125896', Quote_Request_ID__c = '8754210002', Quote_Premium__c = 1175.42, Quote_Status__c = 'BINDABLE');
        P_C_Carrier_Data__c[] pccDs = new P_C_Carrier_Data__c[]{pccD1,pccD2,pccD3};
        insert pccDs;
        
    	P_C_Carrier_Data__c[] pccDs2 = [Select Id, P_C_Quote_Data__c, Opportunity__c, Opportunity__r.StageName, Line_of_Business__c, Carrier_Name__c, Quote_Carrier_ID__c, Quote_Premium__c, Quote_Status__c from P_C_Carrier_Data__c where Id in :pccDs];
        System.assertEquals(opp.Id, pccDs2[0].Opportunity__c);
        System.assertEquals(opp.Id, pccDs2[1].Opportunity__c);
        System.assertEquals(opp.Id, pccDs2[2].Opportunity__c);
       
    } //testMultipleCarrierDataSameOppLOB

    static testMethod void testMultipleCarrierDataMultipleLOB() {
    	Account acct = new Account(Name='ACCT1', Federal_ID_Number__c='86-7530913'
                                   ,ShippingStreet='23 Some Street', ShippingCity='SomeCity', ShippingState='NY', ShippingPostalCode='14623', ShippingCountry='US');
        insert acct;
        
        Contact ctct = new Contact(FirstName='Louis',LastName='Test1a',Email='louis@test1.com', MobilePhone='(585) 111-2222', AccountId=acct.id);
        insert ctct;
        
        Opportunity opp = new Opportunity(Name='PC OPP', AccountId=acct.Id, RecordTypeId = pcRT, OpportunityType__c = 'BOP (Business Owners Package)', HNBF_Sales_Type__c = 'New Case', CloseDate=Date.today().addDays(7), StageName = 'Discovery', Probability = 40, Tarmika_Quote__c = 'https://bridge.tarmika.com');
        insert opp;
        
        OpportunityContactRole ocr = new OpportunityContactRole(OpportunityId=opp.Id,ContactId=ctct.Id,IsPrimary=true,Role='Other');
      	insert ocr;
        
        User[] users = [Select Id, Name from User where IsActive=true and Id != :UserInfo.getUserId() and Sales_Org__c in :UserHelper.DIVISION_LIST limit 3];
        OpportunityTeamMember otm1 = new OpportunityTeamMember(OpportunityId=opp.Id,UserId=users[0].Id,TeamMemberRole='Test Role');
        OpportunityTeamMember otm2 = new OpportunityTeamMember(OpportunityId=opp.Id,UserId=users[1].Id,TeamMemberRole='Test Role');
        OpportunityTeamMember[] otms = new OpportunityTeamMember[]{otm1,otm2};
        insert otms;
        
        //initial insert of P&C Quote Data 
        PC_Quote_Data__c pcqD = new PC_Quote_Data__c(Opportunity__c = opp.Id, Prospect_Client__c=acct.Id, Opportunity_Type__c=opp.OpportunityType__c,Prospect_Client_Name__c=acct.Name,
                                                     Prospect_Client_Street__c=acct.ShippingStreet, Prospect_Client_City__c=acct.ShippingCity, Prospect_Client_State__c=acct.ShippingState,
                                                     Prospect_Client_Postal_Code__c=acct.ShippingPostalCode, Contact_First_Name__c=ctct.FirstName, Contact_Last_Name__c=ctct.LastName,
                                                     Contact_Phone_Number__c=ctct.Phone, Contact_Email_Address__c=ctct.Email);
        insert pcqD;
               
        //inserting P&C Carrier Data with inital response from Huckleberry
        P_C_Carrier_Data__c pccD1 = new P_C_Carrier_Data__c(P_C_Quote_Data__c = pcqD.Id, Line_of_Business__c = 'WC', Carrier_Name__c = 'Farmers', Quote_Carrier_ID__c = '47-87451233', Quote_Request_ID__c = '8754210000', Quote_Premium__c = 1205.36, Quote_Status__c = 'BINDABLE');
        P_C_Carrier_Data__c pccD2 = new P_C_Carrier_Data__c(P_C_Quote_Data__c = pcqD.Id, Line_of_Business__c = 'CYB', Carrier_Name__c = 'Mutual', Quote_Carrier_ID__c = '35-8547521', Quote_Request_ID__c = '8754210001', Quote_Premium__c = 1300.66, Quote_Status__c = 'BINDABLE');
        P_C_Carrier_Data__c pccD3 = new P_C_Carrier_Data__c(P_C_Quote_Data__c = pcqD.Id, Line_of_Business__c = 'GL', Carrier_Name__c = 'Liberty', Quote_Carrier_ID__c = '60-74125896', Quote_Request_ID__c = '8754210002', Quote_Premium__c = 1175.42, Quote_Status__c = 'BINDABLE');
        P_C_Carrier_Data__c[] pccDs = new P_C_Carrier_Data__c[]{pccD1,pccD2,pccD3};
        insert pccDs;
        
    	P_C_Carrier_Data__c[] pccDs2 = [Select Id, P_C_Quote_Data__c, Opportunity__c, Opportunity__r.StageName, Line_of_Business__c, Carrier_Name__c, Quote_Carrier_ID__c, Quote_Premium__c, Quote_Status__c from P_C_Carrier_Data__c where Id in :pccDs];
        System.assertNotEquals(opp.Id, pccDs2[0].Opportunity__c);
        System.assertNotEquals(opp.Id, pccDs2[1].Opportunity__c);
        System.assertNotEquals(opp.Id, pccDs2[2].Opportunity__c);    
    } //testMultipleCarrierDataMultipleLOB 
    
    
}