force-app/main/default/objects/Account/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Fed in from HRIS and Payroll nightly. 
Field fed into Oracle Analytics (OBIEE) system nightly.</description>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 Weekly</fullName>
            </value>
            <value>
                <fullName>2 Bi-weekly</fullName>
            </value>
            <value>
                <fullName>3 Semi-monthly</fullName>
            </value>
            <value>
                <fullName>4 Monthly</fullName>
            </value>
            <value>
                <fullName>5 Quarterly</fullName>
            </value>
            <value>
                <fullName>6 Semi-annually</fullName>
            </value>
            <value>
                <fullName>7 Annually</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MMS_Onboarding_Documents__c/MMS_Onboarding_Documents__c.object-meta.xml
<CustomObject>
    <description>master list of all documents that may be required for MMS onboarding with product category they are related to</description>
    <label>MMS Onboarding Documents</label>
    <nameField>
        <displayFormat>MMS-Doc-{0000}</displayFormat>
        <label>MMS Onboarding Documents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MMS Onboarding Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MMS_Onboarding_Documents__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MMS_Onboarding_Documents__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>mandatory document for all MMS onboarding</inlineHelpText>
    <label>Mandatory for MMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MMS_Onboarding_Documents__c/fields/Mandatory_for_MPSC__c.field-meta.xml
<CustomField>
    <fullName>Mandatory_for_MPSC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This box should be checked if this document is mandatory for MPSC</description>
    <label>Mandatory for MPSC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MMS_Onboarding_Documents__c/fields/MMS_Payroll_Document__c.field-meta.xml
<CustomField>
    <fullName>MMS_Payroll_Document__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this an MMS Payroll Document?</description>
    <label>MMS Payroll Document</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MMS_Onboarding_Documents__c/fields/MPSC_Onboarding_Document__c.field-meta.xml
<CustomField>
    <fullName>MPSC_Onboarding_Document__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this an MPSC Onboarding Document?</description>
    <label>MPSC Onboarding Document</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MMS_Onboarding_Documents__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>used by Reference object trigger to create Reference MMS Payroll Document records based on the opportunity products</description>
    <inlineHelpText>not needed if a Mandatory doc</inlineHelpText>
    <label>Product Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Mandatory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Additional Printed Reports</fullName>
            </value>
            <value>
                <fullName>Additional State &amp; Local Taxes</fullName>
            </value>
            <value>
                <fullName>Addl Packages</fullName>
            </value>
            <value>
                <fullName>A La Carte</fullName>
            </value>
            <value>
                <fullName>ASO</fullName>
            </value>
            <value>
                <fullName>Badge Rack</fullName>
            </value>
            <value>
                <fullName>Batteries</fullName>
            </value>
            <value>
                <fullName>Bell Relay</fullName>
            </value>
            <value>
                <fullName>Benefit Accrual</fullName>
            </value>
            <value>
                <fullName>Board</fullName>
            </value>
            <value>
                <fullName>Check Insertion</fullName>
            </value>
            <value>
                <fullName>Check Signing</fullName>
            </value>
            <value>
                <fullName>Clock</fullName>
            </value>
            <value>
                <fullName>COBRA</fullName>
            </value>
            <value>
                <fullName>CORBA / POP</fullName>
            </value>
            <value>
                <fullName>Custon Interface</fullName>
            </value>
            <value>
                <fullName>Direct Deposit</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Employee Access Online</fullName>
            </value>
            <value>
                <fullName>Expenses Manager</fullName>
            </value>
            <value>
                <fullName>Flex Hiring</fullName>
            </value>
            <value>
                <fullName>Garnishment Payment Service</fullName>
            </value>
            <value>
                <fullName>GL Reporting Svc</fullName>
            </value>
            <value>
                <fullName>Human Resources Module</fullName>
            </value>
            <value>
                <fullName>Logo Service</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PayCard</fullName>
            </value>
            <value>
                <fullName>Paychex® HR Online</fullName>
            </value>
            <value>
                <fullName>Payroll Processing</fullName>
            </value>
            <value>
                <fullName>POP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Employees_Paid_Per_Payroll__c.field-meta.xml
<CustomField>
    <fullName>Employees_Paid_Per_Payroll__c</fullName>
    <label>Employees Paid Per Payroll</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>52</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Summary__c.field-meta.xml
<CustomField>
    <fullName>Product_Summary__c</fullName>
    <description>populated by OpptyLineItem class with product family</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Summary*-</label>
    <length>3500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll__c/Reference_MMS_Payroll__c.object-meta.xml
<CustomObject>
    <description>Object used to store additional information for on-boarding MMS Payroll.</description>
    <label>Reference Preview Payroll</label>
    <nameField>
        <displayFormat>PRVW-{000000000}</displayFormat>
        <label>Reference MMS Payroll Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Preview Payrolls</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_MMS_Payroll__c/fields/Client_Load_Submission_Method__c.field-meta.xml
<CustomField>
    <fullName>Client_Load_Submission_Method__c</fullName>
    <description>Used on the MMS Payroll Onboarding Case in order to track the sales submitted through the Mid Market Sales Tool.</description>
    <inlineHelpText>Used to track sales submitted through the Mid Market Sales Tool.</inlineHelpText>
    <label>Client Load Submission Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mid-Market Sales Tool</fullName>
            </value>
            <value>
                <fullName>Paper Submission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll__c/fields/Date_Client_Load_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Client_Load_Received__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Client Load Received</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 Weekly</fullName>
            </value>
            <value>
                <fullName>2 Bi-weekly</fullName>
            </value>
            <value>
                <fullName>3 Semi-monthly</fullName>
            </value>
            <value>
                <fullName>4 Monthly</fullName>
            </value>
            <value>
                <fullName>5 Quarterly</fullName>
            </value>
            <value>
                <fullName>6 Semi-annually</fullName>
            </value>
            <value>
                <fullName>7 Annually</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll__c/fields/New_Business_Indicator__c.field-meta.xml
<CustomField>
    <fullName>New_Business_Indicator__c</fullName>
    <label>New Business Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Set with create trigger</description>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Reference_MMS_Payrolls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll__c/fields/Product_Summary__c.field-meta.xml
<CustomField>
    <fullName>Product_Summary__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Summary</label>
    <length>3500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll__c/fields/Taxpay_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Taxpay_Indicator__c</fullName>
    <label>Taxpay Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll__c/fields/Zero_Wage_Start__c.field-meta.xml
<CustomField>
    <fullName>Zero_Wage_Start__c</fullName>
    <label>Zero Wage Start</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll_Documents__c/Reference_MMS_Payroll_Documents__c.object-meta.xml
<CustomObject>
    <description>linked to Reference MMS Payroll, shows only documents needed for onboarding</description>
    <label>Reference MMS Payroll Documents</label>
    <nameField>
        <displayFormat>Ref-MMS-Doc-{0000}</displayFormat>
        <label>Reference MMS Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference MMS Payroll Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_MMS_Payroll_Documents__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <description>used with vf page, code populates document name from MMS Onboarding Documents when add doc to MMS reference obj rcd</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>filled in from vf page</inlineHelpText>
    <label>Document</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll_Documents__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll_Documents__c/fields/MMS_Onboarding_Documents__c.field-meta.xml
<CustomField>
    <fullName>MMS_Onboarding_Documents__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MMS Onboarding Documents</label>
    <referenceTo>MMS_Onboarding_Documents__c</referenceTo>
    <relationshipLabel>Reference MMS Payroll Documents</relationshipLabel>
    <relationshipName>Reference_MMS_Payroll_Documents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll_Documents__c/fields/Reference_MMS_Payroll__c.field-meta.xml
<CustomField>
    <fullName>Reference_MMS_Payroll__c</fullName>
    <label>Reference MMS Payroll</label>
    <referenceTo>Reference_MMS_Payroll__c</referenceTo>
    <relationshipLabel>Reference MMS Payroll Documents</relationshipLabel>
    <relationshipName>Reference_MMS_Payroll_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RefMMSPayrollHelperTest.cls
/**
 * This class contains unit tests for validating the RefMMSPayrollHelper class which is called by RefMMSPayrollAfter trigger
 *
 * History
 * --------
 * 03/21/2013	Cindy Freeman	created
 * 12/14/2015   Lynn Michels	edited to pass and test MPSC documents also.
 * 03/25/2024 Carrie Marciano	CanBeDeleted old MPSC tech debt
 */
 @isTest
private class RefMMSPayrollHelperTest {
    static testMethod void myUnitTest() {
        new RefMMSPayrollHelper();
    }
/*
    static testMethod void refMMSPayrollTest() {
		
		// create test onboarding documents
		List<MMS_Onboarding_Documents__c> mmsOnbrdingDocs = new List<MMS_Onboarding_Documents__c>();
		MMS_Onboarding_Documents__c doc1 = new MMS_Onboarding_Documents__c(Document_Name__c = 'Payroll Doc1'
																			, Mandatory__c = true
																			, MMS_Payroll_Document__c = true
																			, Product_Category__c = null );
		mmsOnbrdingDocs.add(doc1);
		MMS_Onboarding_Documents__c doc2 = new MMS_Onboarding_Documents__c(Document_Name__c = 'Taxpay Doc2'
																			, Mandatory__c = false
																			, MMS_Payroll_Document__c = true
																			, Product_Category__c = 'TaxPay' );
		mmsOnbrdingDocs.add(doc2);
		MMS_Onboarding_Documents__c doc3 = new MMS_Onboarding_Documents__c(Document_Name__c = 'Signature Doc3'
																			, Mandatory__c = false
																			, MMS_Payroll_Document__c = true
																			, Product_Category__c = 'CheckSign;Logo Service' );
		mmsOnbrdingDocs.add(doc3);
		insert mmsOnbrdingDocs;
		  	
		   	
        CreateTestData.createTestAandC();
        Account a1 = [select Id, Name from Account where name = 'Test Account2'];
		Contact ctct1 = [select Id, Name from Contact where AccountId = :a1.Id and FirstName = 'First'];
		
		List<Id> testOptyIds = new List<Id>();		
		// create and mark Sold MMS opty that will create Case and Reference Object and Onboarding Documents
		testOptyIds.add(CreateTestData.createTestMMSSoldOptys(a1.Id, ctct1.Id));       
        	
        Date testDate = Date.valueOf(System.now());	
		Reference_MMS_Payroll__c refmmsObj = new Reference_MMS_Payroll__c(Date_Client_Load_Received__c = testDate
																		, Client_Load_Submission_Method__c ='Mid-Market Sales Tool'
																		, Zero_Wage_Start__c = 'Yes'
																		, Taxpay_Indicator__c = 'Yes'
																		, New_Business_Indicator__c = 'Yes'
																		, Opportunity_Name__c = testOptyIds.get(0)
																		, Product_Summary__c = 'Payroll;TaxPay'
																		);
		insert refmmsObj;
		Reference_MMS_Payroll_Documents__c[] mmsDocs = [SELECT Id, Document__c, Mandatory__c from Reference_MMS_Payroll_Documents__c
														WHERE Reference_MMS_Payroll__c = :refmmsObj.Id];
		
		System.assertEquals(2, mmsDocs.size());

    }
    
     static testMethod void refCorePayrollTest() {
		
		// create test onboarding documents
		List<MMS_Onboarding_Documents__c> mmsOnbrdingDocs = new List<MMS_Onboarding_Documents__c>();
		MMS_Onboarding_Documents__c doc1 = new MMS_Onboarding_Documents__c(Document_Name__c = 'Payroll Doc1'
																			, Mandatory_for_MPSC__c = true
																			, MPSC_Onboarding_Document__c = true
																			, Product_Category__c = null );
		mmsOnbrdingDocs.add(doc1);
		MMS_Onboarding_Documents__c doc2 = new MMS_Onboarding_Documents__c(Document_Name__c = 'Taxpay Doc2'
																			, Mandatory_for_MPSC__c = false
																			, MPSC_Onboarding_Document__c = true
																			, Product_Category__c = 'TaxPay' );
		mmsOnbrdingDocs.add(doc2);
		MMS_Onboarding_Documents__c doc3 = new MMS_Onboarding_Documents__c(Document_Name__c = 'Signature Doc3'
																			, Mandatory_for_MPSC__c = false
																			, MPSC_Onboarding_Document__c = true
																			, Product_Category__c = 'CheckSign;Logo Service' );
		mmsOnbrdingDocs.add(doc3);
		insert mmsOnbrdingDocs;
		  	
		   	
        // create account, contact   
        CreateTestData.createTestAandC();
        Account a1 = [select Id, Name from Account where name = 'Test Account2'];
		Contact ctct1 = [select Id, Name from Contact where AccountId = :a1.Id and FirstName = 'First'];
		List<Id> testOptyIds = new List<Id>();	
                                
		// create a Core Opportunity, mark it Sold - that will create Case and Reference Object and Onboarding Documents
		testOptyIds.add(CreateTestData.createTestCoreOptys(a1.Id, ctct1.Id)); 
		List<Opportunity> opps = [SELECT Id, OwnerId, Product_Summary__c FROM Opportunity WHERE AccountId =: a1.id]; 
		opps.get(0).Product_Summary__c = 'TaxPay;Payroll';
		opps.get(0).TotalOpportunityQuantity = 1;
        opps.get(0).Employees_Paid_Per_Payroll__c = 2;
        opps.get(0).Frequency__c = '1';
        opps.get(0).Amount = 100;
        opps.get(0).StageName = 'Sold';
        opps.get(0).Service_Location__c = 'Foxboro Branch 0008';
        opps.get(0).Prod_Payroll__c = true;
		update opps;
	
    	Reference_MPSC_Onboarding_Document__c[] refMPSCDoc = [SELECT Id, Document__c, Received_State__c, Comments__c, 
														    	Discrepancy_Resolution_Date__c, Check_In_Date__c
														    	FROM Reference_MPSC_Onboarding_Document__c];
		System.assertEquals(2, refMPSCDoc.size());

    }
*/	
}