force-app/main/default/objects/Account/fields/Hold_Out__c.field-meta.xml
<CustomField>
    <fullName>Hold_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To signify Hold Out accounts that should not be transferred during territory changes</description>
    <label>Hold Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hold_Out_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Hold_Out_Expiration__c</fullName>
    <description>Date when Account-Contact should be returned to territory rep ownership.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Hold Out Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Permanent_Hold_Out_Description__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Hold_Out_Description__c</fullName>
    <inlineHelpText>This field will be populated when there is a Hold Out for the Hold Out Reason Owner for BOTH perm and temp hold outs. If the Hold Out Expiration Date is populated, the Hold Out is temporary. If the Date Field is blank, the Hold Out is permanent.</inlineHelpText>
    <label>Hold Out Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>672249</fullName>
            </value>
            <value>
                <fullName>ADMIN</fullName>
            </value>
            <value>
                <fullName>Advantage Rep</fullName>
            </value>
            <value>
                <fullName>Bank Centric Team</fullName>
            </value>
            <value>
                <fullName>Client Centric Rep</fullName>
            </value>
            <value>
                <fullName>Core Rep (20-49 ees)</fullName>
            </value>
            <value>
                <fullName>Core Rep - NYSIF</fullName>
            </value>
            <value>
                <fullName>CPA Centric Team</fullName>
            </value>
            <value>
                <fullName>Crossover Request</fullName>
            </value>
            <value>
                <fullName>Decision Maker Elsewhere</fullName>
            </value>
            <value>
                <fullName>DNC Protected</fullName>
            </value>
            <value>
                <fullName>DSR</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Field Account Managed</fullName>
            </value>
            <value>
                <fullName>Financial Advisor Team</fullName>
            </value>
            <value>
                <fullName>Hosted Client</fullName>
            </value>
            <value>
                <fullName>HROI</fullName>
            </value>
            <value>
                <fullName>IA Centric Team</fullName>
            </value>
            <value>
                <fullName>International Zip</fullName>
            </value>
            <value>
                <fullName>Market Segmentation Policy</fullName>
            </value>
            <value>
                <fullName>Micro Size Client Sold by Virtual</fullName>
            </value>
            <value>
                <fullName>Micro Size Prospect worked by Virtual</fullName>
            </value>
            <value>
                <fullName>MMS CSR</fullName>
            </value>
            <value>
                <fullName>MMS Enterprise Rep (1000+ ees)</fullName>
            </value>
            <value>
                <fullName>MMS Hybrid Rep (500-999 ees)</fullName>
            </value>
            <value>
                <fullName>MMS PNG Sale</fullName>
            </value>
            <value>
                <fullName>MMS Rep (250+ ees)</fullName>
            </value>
            <value>
                <fullName>Multicultural</fullName>
            </value>
            <value>
                <fullName>Multi-ID Child Record</fullName>
            </value>
            <value>
                <fullName>MyCorporation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Hold_Out__c.field-meta.xml
<CustomField>
    <fullName>Hold_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hold Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Hold_Out_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Hold_Out_Expiration__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date the hold out expires</inlineHelpText>
    <label>Hold Out Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/HR_Person_Id__c.field-meta.xml
<CustomField>
    <fullName>HR_Person_Id__c</fullName>
    <description>The unique person identifier from the corporate human resources system</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>HR Person Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>PBS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pay</fullName>
            </value>
            <value>
                <fullName>PAS</fullName>
            </value>
            <value>
                <fullName>H&amp;B</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Use_Zip_Assignment_Rules__c.field-meta.xml
<CustomField>
    <fullName>Use_Zip_Assignment_Rules__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this is checked on insert of a record, the process will use the zip code to determine the ownership fields.</inlineHelpText>
    <label>Use Zip Assignment Rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/User_Lookup__c.field-meta.xml
<CustomField>
    <fullName>User_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Paychex Employees, this provides a link to the active user record for this contact.</description>
    <label>User Lookup</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Admin.recordType-meta.xml
<RecordType>
    <fullName>Admin</fullName>
    <active>true</active>
    <description>Salesforce Support Admin</description>
    <label>Admin</label>
</RecordType>

force-app/main/default/objects/User/fields/HR_Person_Id__c.field-meta.xml
<CustomField>
    <fullName>HR_Person_Id__c</fullName>
    <description>The Person Id from HR</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Person Id from HR</inlineHelpText>
    <label>HR Person Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Job_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is populated by a trigger on save of a record. Only Sales Jobs are populated with values like Sales Representative, District Assistant, District Manager...</inlineHelpText>
    <label>Job Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Division__c.field-meta.xml
<CustomField>
    <fullName>Sales_Division__c</fullName>
    <description>Used to translate old sales org names to new ones without messing with sales org code</description>
    <formula>IF(TEXT(Sales_Division_Override__c)&lt;&gt;&quot;&quot;,
TEXT(Sales_Division_Override__c),
IF( AND ( ISPICKVAL( Sales_Org__c, &quot;PAY&quot;), CONTAINS(UserRole.Name,&quot;VIRTUAL SALES CORE&quot;), CONTAINS(UserRole.Name, &quot;HICKS&quot;) || CONTAINS(UserRole.Name, &quot;ROBERTSON&quot;) || CONTAINS(UserRole.Name, &quot;MANGIAVELLANO&quot;)|| CONTAINS(UserRole.Name, &quot;CLARK&quot;)|| CONTAINS(UserRole.Name, &quot;LOUVAIN&quot;)|| CONTAINS(UserRole.Name, &quot;278&quot;)|| CONTAINS(UserRole.Name, &quot;STANGIS&quot;)),
&apos;Virtual SMB Inbound&apos;,
IF( AND ( ISPICKVAL( Sales_Org__c, &quot;PAY&quot;), CONTAINS(UserRole.Name,&quot;SMB Virtual Channel&quot;)),
&apos;SMB Virtual Channel&apos;,
IF( AND ( CONTAINS(UserRole.Name,&quot;VIRTUAL SALES REP - DISTRICT 214-DIVINCENZO (HRD&quot;)),
&apos;Virtual Merchant Services&apos;,
IF( AND ( ISPICKVAL( Sales_Org__c, &quot;PAY&quot;),
OR(CONTAINS(UserRole.Name,&quot;HYBRID DEDICATED&quot;),CONTAINS(UserRole.Name,&quot;VIRTUAL DEDICATED&quot;),
CONTAINS(UserRole.Name,&quot;SMB New Business&quot;))),&apos;SMB New Business&apos;,
IF( AND( ISPICKVAL( Sales_Org__c, &quot;HNBF&quot;), CONTAINS(UserRole.Name, &quot;Virtual Sales&quot;)|| CONTAINS(UserRole.Name, &quot;VIRTUAL SALES&quot;)),
&apos;Virtual HNBF&apos;,
IF(ISPICKVAL( Sales_Org__c, &quot;TAA&quot;),
&quot;Virtual TAA&quot;,
IF( AND( ISPICKVAL( Sales_Org__c, &quot;HNBF&quot;), NOT(CONTAINS(UserRole.Name,&quot;VIRTUAL&quot;))),
&apos;Field HNBF&apos;,
IF( AND( ISPICKVAL( Sales_Org__c, &quot;PC&quot;), CONTAINS(UserRole.Name,&quot;VIRTUAL SALES&quot;)),
&apos;Virtual PC&apos;,
IF( AND( ISPICKVAL( Sales_Org__c, &quot;ESR&quot;), CONTAINS(UserRole.Name,&quot;VIRTUAL SALES&quot;)),
&apos;Virtual ESR&apos;,
IF( AND( ISPICKVAL( Sales_Org__c, &quot;PBA&quot;), CONTAINS(UserRole.Name,&quot;VIRTUAL SALES&quot;)),
&apos;Virtual PBA&apos;,
IF( AND( ISPICKVAL( Sales_Org__c, &quot;MS&quot;), CONTAINS(UserRole.Name,&quot;VIRTUAL SALES&quot;)),
&apos;Virtual Merchant Services&apos;,
IF( AND ( OR( ISPICKVAL( Sales_Org__c, &quot;BusDev&quot;),ISPICKVAL( Sales_Org__c, &quot;PAY&quot;)), OR ( BEGINS(UserRole.Name,&quot;Bank Centric&quot;), (BEGINS(UserRole.Name, &quot;Bank Channel&quot;)))),
&apos;Bank Channel&apos;,
IF( AND( ISPICKVAL( Sales_Org__c, &quot;PAS&quot;), CONTAINS(UserRole.Name,&quot;MMS&quot;)),
&apos;RSR&apos;,
IF( AND ( CONTAINS(UserRole.Name,&quot;NSC&quot;)),
&apos;NSC&apos;,
IF ( AND ( OR( ISPICKVAL( Sales_Org__c, &quot;BusDev&quot;),ISPICKVAL( Sales_Org__c, &quot;PAY&quot;)), OR ( CONTAINS(UserRole.Name,&quot;Sales Account Manager&quot;), (CONTAINS(UserRole.Name, &quot;Strategic Accounts&quot;)) ) ) ,
&apos;Strategic Accounts&apos;,
IF(TEXT(Sales_Org__c) = &apos;PAY&apos;,
&apos;SMB Channel&apos;,
IF( AND( ISPICKVAL(Sales_Org__c, &quot;MMS&quot;), CONTAINS(UserRole.Name, &quot;CSR&quot;)),
&apos;CSSR&apos;,
IF(AND(TEXT(Sales_Org__c) = &apos;MMS&apos;, CONTAINS(UserRole.Name, &apos;SALES DEVELOPMENT&apos;)),
&apos;MMS SDR&apos;,
IF(AND(TEXT(Sales_Org__c) = &apos;MMS&apos;, NOT(CONTAINS(UserRole.Name, &apos;SALES DEVELOPMENT&apos;))),
&apos;Field MMS&apos;,
IF( AND ( CONTAINS(UserRole.Name,&quot;NSS Outbound Rep 1.6 - Client ITB Hybrid&quot;)),
&apos;Agency NSS&apos;,
IF(TEXT(Sales_Org__c) = &apos;PAS&apos;,
&apos;ASO&apos;,
IF( AND ( ISPICKVAL( Sales_Org__c, &quot;HRS&quot;), CONTAINS(UserRole.Name, &quot;288&quot;) || CONTAINS(UserRole.Name, &quot;289&quot;) || CONTAINS(UserRole.Name, &quot;290&quot;)|| CONTAINS(UserRole.Name, &quot;291&quot;)|| CONTAINS(UserRole.Name, &quot;292&quot;) || CONTAINS(UserRole.Name, &quot;293&quot;)),
&apos;Virtual Retirement&apos;,
TEXT(Sales_Org__c)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
))))))</formula>
    <label>Sales Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org-Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>BenAdmin</fullName>
            </value>
            <value>
                <fullName>Benetrac</fullName>
            </value>
            <value>
                <fullName>BusDev</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Relations</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Center</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise Service Center</fullName>
            </value>
            <value>
                <fullName>ESR</fullName>
            </value>
            <value>
                <fullName>EW</fullName>
            </value>
            <value>
                <fullName>Field Operations Core</fullName>
            </value>
            <value>
                <fullName>HNBF</fullName>
            </value>
            <value>
                <fullName>HROI</fullName>
            </value>
            <value>
                <fullName>HR Online</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>HRS 401K-S125</fullName>
            </value>
            <value>
                <fullName>HRS Premier</fullName>
            </value>
            <value>
                <fullName>Icon</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Merchant Services</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MMS Hub</fullName>
            </value>
            <value>
                <fullName>MPSC</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InactiveUserAccountQueueableTest.cls
/* Test for reassigning Accounts owned by inactive users.
   
  History
  -------
  02/08/2021 Matt Fritschi	Created
  05/18/2021 Carrie Marciano   Changed to use OppStage Labels
  02/04/2022 Dan Carmen     Add check for user lookup on contact if status changes
  11/01/2023 Dan Carmen     Change call to checkUserLookups

*/

@isTest
public class InactiveUserAccountQueueableTest {
    
    public static String SOLD_STARTED=Label.OppStage_Sold_Started;
    public static String NOT_SOLD=Label.OppStage_Lost;
    
    static testmethod void testSMBChannelOpportunity() {
        
        User[] smbChannelRep = [select Id from User where Job_Name__c=:UserHelper.JOB_REP and Sales_Org__c=:UserHelper.SO_CORE and isActive=true and Sales_Division__c = 'SMB Channel' and (not title like '%Inbound%') and (not title like 'Virtual%') and (not title like '%Micro%') limit 2];
        Map<Id, User> userMap = new Map<Id, User>();
        
        userMap.put(smbChannelRep[0].Id, smbChannelRep[0]);
        userMap.put(smbChannelRep[1].Id, smbChannelRep[1]);
        
        List<Account> acctList = new List<Account>();
        Account acct1 = new Account(OwnerId = smbChannelRep[0].Id, Name = 'Test Account 1', Hold_Out__c=true, Permanent_Hold_Out_Description__c='ADMIN', Hold_Out_Expiration__c=System.Date.Today() + 1, Use_Zip_Assignment_Rules__c = false, Type='Lost Client');
        acctList.add(acct1);
        Account acct2 = new Account(OwnerId = smbChannelRep[1].Id, Name = 'Test Account 2', Hold_Out__c=true, Permanent_Hold_Out_Description__c='ADMIN', Hold_Out_Expiration__c=System.Date.Today() + 1, Use_Zip_Assignment_Rules__c = false);
        acctList.add(acct2);
        insert acctList;
        
        List<Opportunity> opptyList = new List<Opportunity>();
        Opportunity smbChannelOppty1 = new Opportunity(Name='Test oppty 1', Type = 'Payroll', StageName = SOLD_STARTED, CloseDate=System.Date.today(), AccountId=acct1.Id);
        opptyList.add(smbChannelOppty1);
        Opportunity smbChannelOppty2 = new Opportunity(Name='Test oppty 2', Type = 'Payroll', StageName = NOT_SOLD, CloseDate=System.Date.today(), AccountId=acct2.Id);
        opptyList.add(smbChannelOppty2);
        insert opptyList;
        
        Test.startTest();        
        System.enqueueJob(new InactiveUserAccountQueueable(userMap, new Set<Id>()));
        Test.stopTest();
        
        acct1 = [SELECT OwnerId, Name, Hold_Out__c, Permanent_Hold_Out_Description__c, Hold_Out_Expiration__c, Use_Zip_Assignment_Rules__c FROM Account WHERE Id = :acct1.Id];
        System.assertEquals(acct1.Hold_Out__c, false);
        System.assertEquals(acct1.Permanent_Hold_Out_Description__c, null);
        System.assertEquals(acct1.Hold_Out_Expiration__c, null);

        acct2 = [SELECT OwnerId, Name, Hold_Out__c, Permanent_Hold_Out_Description__c, Hold_Out_Expiration__c, Use_Zip_Assignment_Rules__c FROM Account WHERE Id = :acct2.Id];
        System.assertEquals(acct2.Hold_Out__c, false);
        System.assertEquals(acct2.Permanent_Hold_Out_Description__c, null);
        System.assertEquals(acct2.Hold_Out_Expiration__c, null);
    }
    
    
    static testmethod void testUserTitle() {
        
        User smbChannelRep = [select Id from User where Job_Name__c=:UserHelper.JOB_REP and Sales_Org__c=:UserHelper.SO_CORE and isActive=true and (Title LIKE '%Inbound%' or Title LIKE 'Virtual%' or Title LIKE '%Micro%') limit 1];
        Map<Id, User> userMap = new Map<Id, User>();
        userMap.put(smbChannelRep.Id, smbChannelRep);
        
        Account acct = new Account(OwnerId = smbChannelRep.Id, Name = 'Test Account', Hold_Out__c=true, Permanent_Hold_Out_Description__c='ADMIN', Hold_Out_Expiration__c=System.Date.Today() + 1, Use_Zip_Assignment_Rules__c = false);
        insert acct;
        
        Opportunity soldOppty = new Opportunity(Name='Test oppty 1', Type = 'Payroll', StageName = SOLD_STARTED, CloseDate=System.Date.today(), AccountId=acct.Id);
        insert soldOppty;
        
        Test.startTest();        
        System.enqueueJob(new InactiveUserAccountQueueable(userMap, new Set<Id>()));
        Test.stopTest();
        
        acct = [SELECT OwnerId, Name, Hold_Out__c, Permanent_Hold_Out_Description__c, Hold_Out_Expiration__c, Use_Zip_Assignment_Rules__c FROM Account WHERE Id = :acct.Id];
        System.assertEquals(acct.Hold_Out__c, false);
        System.assertEquals(acct.Permanent_Hold_Out_Description__c, null);
        System.assertEquals(acct.Hold_Out_Expiration__c, null);
    } // testUserTitle
    
    static testMethod void testUserLookup() {
        User[] users = [Select Id, Name, LastName, HR_Person_Id__c from User where Job_Name__c=:UserHelper.JOB_REP and IsActive=true and HR_Person_Id__c != null limit 3];
        Contact[] ctcts = new Contact[]{};
        Set<String> personIdSet = new Set<String>();
        for (User usr : users) {
           ctcts.add(new Contact(LastName=usr.LastName, HR_Person_Id__c = usr.HR_Person_Id__c));
           personIdSet.add(usr.HR_Person_Id__c);
        } // for (User usr : users
        ContactMethods.CONTACT_BEFORE_TRIGGER_EXECUTING=true;
        ContactMethods.CONTACT_AFTER_TRIGGER_EXECUTING=true;
        insert ctcts;
        
        Test.startTest();        
        System.enqueueJob(new InactiveUserAccountQueueable(new Map<Id, User>(), personIdSet));
        Test.stopTest();
        
        ctcts = [Select id, Name, User_Lookup__c from Contact where Id in :ctcts];
        for (Contact ctct : ctcts) {
            System.assertNotEquals(null,ctct.User_Lookup__c);
        }

    } // testUserLookup
    
    
} // class InactiveUserAccountQueueableTest