force-app/main/default/objects/Account/fields/Hold_Out__c.field-meta.xml
<CustomField>
    <fullName>Hold_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To signify Hold Out accounts that should not be transferred during territory changes</description>
    <label>Hold Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apex_Batch_Control__c/Apex_Batch_Control__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These are settings that can be used to implement some control over apex batch jobs.</description>
    <label>Apex Batch Control</label>
</CustomObject>

force-app/main/default/objects/Apex_Batch_Control__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <inlineHelpText>This is used by the UpdateZipOwnershipController to allow the batches to be manually launched.</inlineHelpText>
    <label>Batch Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_Batch_Control__c/fields/Check_Days__c.field-meta.xml
<CustomField>
    <fullName>Check_Days__c</fullName>
    <description>Number of days to look back in a query</description>
    <label>Check Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_Batch_Control__c/fields/Minutes_till_Launch__c.field-meta.xml
<CustomField>
    <fullName>Minutes_till_Launch__c</fullName>
    <label>Minutes till Launch</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cadence_Assignment_Record__c/Cadence_Assignment_Record__c.object-meta.xml
<CustomObject>
    <label>Cadence Assignment Record</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CAR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cadence_Assignment_Record__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cadence_Assignment_Record__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cadence_Assignment_Record__c/fields/LeadId__c.field-meta.xml
<CustomField>
    <fullName>LeadId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Lead associated with this cadence</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cadence_Assignment_Record__c/fields/ReferralAccount__c.field-meta.xml
<CustomField>
    <fullName>ReferralAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Referral Account associated with this CAR record</inlineHelpText>
    <label>Referral Account</label>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Test field containing the account id because of duplicate management matching on the name, not the actual account id.</inlineHelpText>
    <label>Account Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Decision_Maker__c.field-meta.xml
<CustomField>
    <fullName>Decision_Maker__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For field sales to indicate the decision maker Contact in a company. To be used to identify &apos;one contact per company&apos;.</description>
    <inlineHelpText>To indicate the decision maker of the company.</inlineHelpText>
    <label>Decision Maker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Hold_Out__c.field-meta.xml
<CustomField>
    <fullName>Hold_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hold Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OwnerMismatch__c.field-meta.xml
<CustomField>
    <fullName>OwnerMismatch__c</fullName>
    <description>This is used to determine if the contact ownership is not correct.</description>
    <formula>AND( Hold_Out__c = false
, Sales_Contact__c = true
, OwnerId != Account.OwnerId
, Account.Owner.IsActive = true )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This is true if the owner of the contact does not match the owner of the account.</inlineHelpText>
    <label>Owner Mismatch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Use_Zip_Assignment_Rules__c.field-meta.xml
<CustomField>
    <fullName>Use_Zip_Assignment_Rules__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this is checked on insert of a record, the process will use the zip code to determine the ownership fields.</inlineHelpText>
    <label>Use Zip Assignment Rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/Prospect_Ownership__c.object-meta.xml
<CustomObject>
    <description>This object is used to establish an NSR&apos;s association with a Prospect-Client record to indicate ownership and commission eligibility during the Lead/ Prospect life cycle.</description>
    <label>Prospect Ownership</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Prospect Ownership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospect Ownership</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prospect_Ownership__c/fields/Decision_Maker__c.field-meta.xml
<CustomField>
    <fullName>Decision_Maker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the decision maker contact reference in the conversion process.</description>
    <inlineHelpText>Lookup to the decision maker contact reference in the conversion process.</inlineHelpText>
    <label>Decision Maker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Prospect Ownership</relationshipLabel>
    <relationshipName>Prospect_Ownership</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/DialSource_Action_That_Created_PO__c.field-meta.xml
<CustomField>
    <fullName>DialSource_Action_That_Created_PO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DialSource Action That Created PO</label>
    <referenceTo>DS_Denali__DialSource_Action__c</referenceTo>
    <relationshipLabel>Prospect Ownership</relationshipLabel>
    <relationshipName>Prospect_Ownership</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look-up to the lead record with which this record is related. If it is null, it means the prospect started out as a client or lost client. When a lead is related, this record shows the entire progression of the lead through qualification and sales phases.</description>
    <inlineHelpText>Look-up to the lead record with which this record is related.</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Prospect Ownership</relationshipLabel>
    <relationshipName>Prospect_Ownership</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/ProcessTracker__c.field-meta.xml
<CustomField>
    <fullName>ProcessTracker__c</fullName>
    <description>updated by code to track verification process</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Process Tracker</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Prospect_Ownership__c/fields/Prospect_Client__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Prospect-Client record to which the Prospect Ownership record applies. Set automatically by the system.</description>
    <inlineHelpText>The Prospect-Client record to which the Prospect Ownership record applies. Set automatically by the system.</inlineHelpText>
    <label>Prospect-Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Prospect Ownership History</relationshipLabel>
    <relationshipName>Prospect_Ownership</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountZipCodeBatch.cls
/** Batch job to check the owner of an account against a referral account

  AccountZipCodeBatch azcb = new AccountZipCodeBatch();
  Database.executeBatch(azcb, 20);

  Check_Days__c=number of days to look back for record check
  BatchSize__c = batch size for account zip ownership
  Minutes_till_Launch__c = batch size for contact ownership

* History
* -------
  03/04/2022 Dan Carmen       Created
  04/10/2022 Susmitha Somavarapu Daily job is run to re-evaluate all records to ensure that they are updated
*/
global without sharing class AccountZipCodeBatch implements Database.Batchable<SObject>, Database.Stateful, Schedulable {

    public static final String CLASS_NAME='AccountZipCodeBatch';
    
    public static final String MODE_ZIPS='UseZipAssignmentRules';
    public static final String CTCT_OWNER='ContactOwnership';
    public static final String MODE_PO='ProspectOwnership';
    public static final String Mode_Cadence = 'CadenceQue'; 
        
    global JobHelper jh = new JobHelper(CLASS_NAME);
    
    global Integer numRecordsFound = 0;
    global Integer nbrUpdated = 0;
    global String mode = null;

    // In order to schedule a batch run
    global void execute(SchedulableContext sc) { 
       launchBatch(MODE_ZIPS);
    } // execute
    
    global static Apex_Batch_Control__c getAbc(String p_mode) {
        Apex_Batch_Control__c abc = Apex_Batch_Control__c.getInstance(RecordTypeHelper.cleanRtName(CLASS_NAME+p_mode));
        if (abc == null) {
           abc = Apex_Batch_Control__c.getInstance(CLASS_NAME);
        }
        return abc;
    } // getAbc
    
    global static void launchBatch(String mode) {
        AccountZipCodeBatch azcb = new AccountZipCodeBatch();
        azcb.mode = mode;
        // so we can set a different value for each mode
        Apex_Batch_Control__c abc = getAbc(mode);
        // we want to keep a small batch because of row locks
        Integer batchSize = ((abc != null && abc.BatchSize__c != null) ? (Integer)abc.BatchSize__c : 10);
        //if (String.isBlank(mode) || mode == MODE_ZIPS) {
        //   batchSize = ((abc != null && abc.BatchSize__c != null) ? (Integer)abc.BatchSize__c : 10);
        //} else if (mode == CTCT_OWNER || mode == MODE_PO || mode == Mode_Cadence) {
        //   batchSize = ((abc != null && abc.Minutes_till_Launch__c != null) ? (Integer)abc.Minutes_till_Launch__c : 200);
        //}
        
        database.executeBatch(azcb, batchSize);
      
    } // launchBatch

    global Database.QueryLocator start(Database.BatchableContext BC){
        jh.setStarted();
        
        // get the number of days to query back in time for to limit the result set
        Apex_Batch_Control__c abc = getAbc(mode);
        
        Integer queryDays = (abc != null && abc.Check_Days__c != null ? (Integer)abc.Check_Days__c : 10);
        Datetime queryDate = Datetime.now().addDays(-queryDays);
        
        mode = (String.isBlank(mode) ? MODE_ZIPS : mode);
        
        if (mode == CTCT_OWNER) {
           return Database.getQueryLocator([Select Id, Name, OwnerId, OwnerMismatch__c, LastActivityDate
                                                  ,AccountId, Account.Name, Account.OwnerId, Account.Owner.IsActive
                                                  ,LastModifiedBy.Name 
                                              from Contact 
                                             where (LastModifiedDate > :queryDate or Account.LastModifiedDate > :queryDate)
                                               and Account.Owner.IsActive=true
                                               and OwnerMismatch__c=true and Hold_Out__c=false]);
        } else if (mode == MODE_PO) {
           return Database.getQueryLocator([Select Id, Name, CreatedDate, Decision_Maker__c, Lead__c
                                                  ,DialSource_Action_That_Created_PO__c, ProcessTracker__c,Prospect_Client__c
                                              From Prospect_Ownership__c
                                             Where DialSource_Action_That_Created_PO__c = null
                                               and (Decision_Maker__c != null or Lead__c != null)
                                               and CreatedDate > :queryDate]);
        }
        else if(mode == Mode_Cadence){
           Date closeDateCheck = Date.today().addDays(-queryDays);
           return Database.getQueryLocator([Select Id, Name, CreatedDate, AccountId__c, LeadId__c, ReferralAccount__c from Cadence_Assignment_Record__c 
                                      Where CreatedDate >= :queryDate or Close_Date__c >= :closeDateCheck]);
        }
        
        return Database.getQueryLocator([Select Id, Name, Use_Zip_Assignment_Rules__c
                                           From Account
                                          Where LastModifiedDate >= :queryDate
                                            and Use_Zip_Assignment_Rules__c = true]);

    } // start
    
    global void execute(Database.BatchableContext BC, List<SObject> scope){
       numRecordsFound += scope.size();
       if (mode == MODE_ZIPS) {
          Account[] accts = (Account[])scope;
          nbrUpdated += accts.size();
          DmlHelper.performDML2(accts, DmlHelper.DML_UPDATE, CLASS_NAME, 'execute', 'Update Accounts', true);
       } else if (mode == CTCT_OWNER) {
          Contact[] ctcts = (Contact[])scope;       
          for (Contact ctct : ctcts) {
             ctct.OwnerId = ctct.Account.OwnerId;
          }
          // we can skip the triggers here.
          ContactMethods.CONTACT_BEFORE_TRIGGER_EXECUTING=true;
          ContactMethods.CONTACT_AFTER_TRIGGER_EXECUTING=true;
          nbrUpdated += ctcts.size();
          DmlHelper.performDML2(ctcts, DmlHelper.DML_UPDATE, CLASS_NAME, 'execute', 'Update Contact Owners', true);
       } else if (mode == MODE_PO) {
          handleProspectOwnership((Prospect_Ownership__c[])scope);
       }
       else if (mode == Mode_Cadence) {
         List<String> quryIds = new List<String>(); 
         for (Cadence_Assignment_Record__c loopRec : (List<Cadence_Assignment_Record__c>)scope) {
            if (loopRec.AccountId__c != null ) {
               quryIds.add(loopRec.AccountId__c);
            }
            if (loopRec.LeadId__c != null ) {
               quryIds.add(loopRec.LeadId__c);
               
            }
            if (loopRec.ReferralAccount__c != null ) {
               quryIds.add(loopRec.ReferralAccount__c);  
            }  
         }
          
         CadenceQueueable caq = new CadenceQueueable(quryIds);
         CadenceQueueable.RUN_INLINE=true;
         CadenceQueueable.launchQueueable(caq);

          
       }
    } // execute
                 
    public static Integer timeOffset = Integer.valueOf(System.Label.DialSourceCreatedDate);

    global void handleProspectOwnership(Prospect_Ownership__c[] pos) {
       Map<Id,Prospect_Ownership__c> updateMap = new Map<Id,Prospect_Ownership__c>();
       ProspectOwnershipMethods.MapDialSourceActionToPO(pos, updateMap);
       nbrUpdated += updateMap.size();
       DmlHelper.performDML2(updateMap.values(), DmlHelper.DML_UPDATE, CLASS_NAME, 'execute', 'Update Contact Owners', true);
    } // handleProspectOwnership
    
    global void finish(Database.BatchableContext bc) {
       String message = 'Mode='+mode;
       message += '\nRecords Found: '+numRecordsFound;
       message += '\nRecords Update: '+nbrUpdated;
       jh.completeJob(bc, 'AccountZipCodeBatch', message);
       if (mode == MODE_ZIPS && !Test.isRunningTest()) {
          launchBatch(CTCT_OWNER);
       } else if (mode == CTCT_OWNER && !Test.isRunningTest()) {
          launchBatch(MODE_PO);
       } else if (mode == MODE_PO && !Test.isRunningTest()) {
          launchBatch(Mode_Cadence);
       }
    } // finish
    
} // class AccountZipCodeBatch