force-app/main/default/objects/Account/fields/HR_Generalist__c.field-meta.xml
<CustomField>
    <fullName>HR_Generalist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HR Generalist</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (HR Generalist)</relationshipLabel>
    <relationshipName>R00N70000002FnrDEAS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/HRO_Implementation_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>HRO_Implementation_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HRO Implementation Coordinator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Prospects_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/MMS_AS__c.field-meta.xml
<CustomField>
    <fullName>MMS_AS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Changed field label on 11/19/2014 per request in case #16019992</description>
    <label>Payroll Implementation Specialist</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Payroll Implementation Specialist)</relationshipLabel>
    <relationshipName>R00N70000002Fnr3EAC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/MMS_MAM_NAM__c.field-meta.xml
<CustomField>
    <fullName>MMS_MAM_NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (MMS MAM/NAM)</relationshipLabel>
    <relationshipName>R00N70000002FnfpEAC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/MyPaychex_com_Client__c.field-meta.xml
<CustomField>
    <fullName>MyPaychex_com_Client__c</fullName>
    <description>Used to indicate if the client is a my paychex.com client.  Manually updated by Susan Milner and Tony Mymern</description>
    <label>MyPaychex.com Client*-</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SSO Legacy</fullName>
            </value>
            <value>
                <fullName>SSO Legacy Admin</fullName>
            </value>
            <value>
                <fullName>One Source Solutions Portal</fullName>
            </value>
            <value>
                <fullName>One Source Solutions Portal Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MyPaychex_com_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>MyPaychex_com_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>MyPaychex.com Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/HR_Generalist__c.field-meta.xml
<CustomField>
    <fullName>HR_Generalist__c</fullName>
    <formula>Account.HR_Generalist__r.FirstName + &apos; &apos; +  Account.HR_Generalist__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HR Generalist</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/HR_Person_Id__c.field-meta.xml
<CustomField>
    <fullName>HR_Person_Id__c</fullName>
    <description>The unique person identifier from the corporate human resources system</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>HR Person Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/MyPaychex_com_Client__c.field-meta.xml
<CustomField>
    <fullName>MyPaychex_com_Client__c</fullName>
    <formula>TEXT( Account.MyPaychex_com_Client__c )</formula>
    <label>MyPaychex.com Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll__c/Reference_MMS_Payroll__c.object-meta.xml
<CustomObject>
    <description>Object used to store additional information for on-boarding MMS Payroll.</description>
    <label>Reference Preview Payroll</label>
    <nameField>
        <displayFormat>PRVW-{000000000}</displayFormat>
        <label>Reference MMS Payroll Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Preview Payrolls</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_MMS_Payroll__c/fields/Assigned_Prospect_Client_Number__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Prospect_Client_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter Prospect-Client Number when Prospect-Client Number is assigned during client load process.  Prospect-Client Number will update to Prospect-Client record for not-integrated records.</inlineHelpText>
    <label>Assigned Prospect-Client Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Set value with create trigger</description>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Reference_MMS_Payrolls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll__c/fields/HRG__c.field-meta.xml
<CustomField>
    <fullName>HRG__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HRG</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>HRG_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll__c/fields/HRO_Onboarding__c.field-meta.xml
<CustomField>
    <fullName>HRO_Onboarding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MPSC CSS</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HRO_Onboarding_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll__c/fields/MMS_MAM_NAM__c.field-meta.xml
<CustomField>
    <fullName>MMS_MAM_NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MMS MAM/NAM</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Reference_MMS_MAMNAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll__c/fields/MyPaychex_com_Client__c.field-meta.xml
<CustomField>
    <fullName>MyPaychex_com_Client__c</fullName>
    <description>Used to indicate if the client is a my paychex.com client.</description>
    <inlineHelpText>Used to indicate if the client is a my paychex.com client.</inlineHelpText>
    <label>MyPaychex.com Client</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SSO Legacy</fullName>
            </value>
            <value>
                <fullName>SSO Legacy Admin</fullName>
            </value>
            <value>
                <fullName>One Source Solutions Portal</fullName>
            </value>
            <value>
                <fullName>One Source Solutions Portal Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_MMS_Payroll__c/fields/MyPaychex_com_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>MyPaychex_com_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>MyPaychex.com Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/HR_Person_Id__c.field-meta.xml
<CustomField>
    <fullName>HR_Person_Id__c</fullName>
    <description>The Person Id from HR</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Person Id from HR</inlineHelpText>
    <label>HR Person Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReferenceMMSUpdate.cls
/* 
 * If the owner of the reference MMS record changes, update Case owner and Account.MMS_AS__c
 * Called from trigger ReferenceMMSPayrollAfter
 *
 * History
 * -------
 * 08/29/2013 Cindy Freeman   Created
 * 11/27/3013 Cindy Freeman	  added method to update AccountNumber, MyPaychex_com_Client and MyPaychex_com_Start_Date
 *
 */

public with sharing class ReferenceMMSUpdate {

	public static void processMMSOwner(Id[] mmstoUpdateAcct) {
		List<Id> caseIds = new List<Id>();							// temp list of case ids, used to query
		List<Id> acctIds = new List<Id>();							// temp list of account ids, used to query
		List<Id> userIds = new List<Id>();							// temp list of owner(user) ids, used to query

		Reference_MMS_Payroll__c[] mmsList = [Select Id, Case_Number__c, OwnerId, HRG__c, HRO_Onboarding__c, MMS_MAM_NAM__c 
	    									from Reference_MMS_Payroll__c where Id in :mmstoUpdateAcct];
		
		
		Map<Id, String> mapOwnertoHR = new Map<Id, String>();		//	owner(user).Id -> hr person id
		Map<String, Id> mapHRtoCtct = new Map<String, Id>();		//  hr person id -> contact.Id
		
		for (Reference_MMS_Payroll__c mms : mmsList)
		{	//mapOwnertoHR.put(mms.OwnerId, mms.Owner__r.HR_Person_Id__c);
			userIds.add(mms.OwnerId);	
			caseIds.add(mms.Case_Number__c);
		}
		
		// gather related users, cases and accounts
		Map<Id, User> mapUsers = new Map<Id, User>([Select Id, HR_Person_Id__c from User where Id in :userIds]);
		for (User u : mapUsers.values())
		{	mapOwnertoHR.put(u.Id, u.HR_Person_Id__c);	}
		Map<Id, Case> mapCases = new Map<Id, Case>([Select Id, OwnerId, AccountId from Case where Id in :caseIds]);
		for (Case c : mapCases.values())
		{	acctIds.add(c.AccountId);	}
		Map<Id, Account> mapAccts = new Map<Id, Account>([Select Id, MMS_AS__c, HR_Generalist__c,
															HRO_Implementation_Coordinator__c,
															MMS_MAM_NAM__c from Account where Id in :acctIds]);
		
		// get contact record based on mms owner HR_Person_id
		Contact[] ctcts = [Select Id, HR_Person_Id__c from Contact where HR_Person_Id__c in :mapOwnertoHR.values()];	
		for (Contact ct : ctcts)
		{	mapHRtoCtct.put(ct.HR_Person_Id__c, ct.Id);	}
		                                                    
	    Case[] updateCases = new Case[]{};
	    Account[] updateAccts = new Account[]{};
	    Reference_MMS_Payroll__c[] updateRefMMS = new Reference_MMS_Payroll__c[]{};
	    
	    for (Reference_MMS_Payroll__c mms : mmsList)
	    {	Case c = mapCases.get(mms.Case_Number__c);
	    	if (c != null)
	    	{	c.OwnerId = mms.OwnerId;
	    		updateCases.add(c);
	    		Account a = mapAccts.get(c.AccountId);
	    		if (a != Null)
	    		{	Id ctId = mapHRtoCtct.get(mapOwnertoHR.get(mms.OwnerId));
	    			a.MMS_AS__c = ctId;
	    			updateAccts.add(a);
	    			mms.HRG__c = a.HR_Generalist__c;
	    			mms.HRO_Onboarding__c = a.HRO_Implementation_Coordinator__c;
	    			mms.MMS_MAM_NAM__c = a.MMS_MAM_NAM__c;
	    			updateRefMMS.add(mms);
	    		} // if a!=Null
	    	} // if c!=Null
	    } // for mms
	    
	    if (!updateCases.isEmpty())
	    {	update updateCases;	}
	    
	    if (!updateAccts.isEmpty())
	    {	update updateAccts;	}
	    
	    if (!updateRefMMS.IsEmpty())
	    {	update updateRefMMs;	}

	} // processMMSOwner


	public static void processMMSAccount(Id[] mmstoUpdateAcct) {
		List<Id> acctIds = new List<Id>();							// temp list of account ids, used to query
		List<Account> acctUpdates = new List<Account>();			// list of accounts to update
		
		Reference_MMS_Payroll__c[] mmsList = [Select Id, Case_Number__c, Case_Number__r.AccountId, OwnerId, 
						 					Assigned_Prospect_Client_Number__c, MyPaychex_com_Client__c, MyPaychex_com_Start_Date__c 
	    									from Reference_MMS_Payroll__c where Id in :mmstoUpdateAcct];

		for (Reference_MMS_Payroll__c mms: mmsList)
		{	acctIds.add(mms.Case_Number__r.AccountId);	}
		
		Map<Id, Account> mapAccts = new Map<Id, Account>([Select Id, AccountNumber, MyPaychex_com_Client__c, myPaychex_com_Start_Date__c 
							from Account where Id in :acctIds]);
		Boolean acctUp;
		for (Reference_MMS_Payroll__c mms: mmsList)
		{	acctUp = false;
			Account acct = mapAccts.get(mms.Case_Number__r.AccountId);
			if (mms.Assigned_Prospect_Client_Number__c != null && acct.AccountNumber == null)
			{	acct.AccountNumber = mms.Assigned_Prospect_Client_Number__c;
				acctUp = true;
			} // if Assigned_Prospect_Client_Number__c
			if (mms.MyPaychex_com_Client__c != null && mms.MyPaychex_com_Client__c != acct.MyPaychex_com_Client__c)
			{	acct.MyPaychex_com_Client__c = mms.MyPaychex_com_Client__c;
				acct.MyPaychex_com_Start_Date__c = mms.MyPaychex_com_Start_Date__c;
				acctUp = true;
			} // if MyPaychex_com_Client__c
			if (acctUp)
			{	acctUpdates.add(acct);	}
		} // for
		
		if (!acctUpdates.isEmpty())
		{	update acctUpdates;	}
	
	} // processMMSAccount



} // ReferenceMMSUpdate