force-app/main/default/objects/Account/fields/MMS__c.field-meta.xml
<CustomField>
    <fullName>MMS__c</fullName>
    <formula>IMAGE( 
CASE( MMS_Account_Health__c, 
&quot;Stable&quot;, &quot;/img/samples/light_green.gif&quot;, 
&quot;Potential Risk&quot;, &quot;/img/samples/light_yellow.gif&quot;, 
&quot;At Risk&quot;, &quot;/img/samples/light_red.gif&quot;, 
&quot;/s.gif&quot;), 
&quot;status color&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Preview</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TAA__c.field-meta.xml
<CustomField>
    <fullName>TAA__c</fullName>
    <formula>IMAGE( 
CASE( TAA_Account_Health__c, 
&quot;Stable&quot;, &quot;/img/samples/light_green.gif&quot;, 
&quot;Potential Risk&quot;, &quot;/img/samples/light_yellow.gif&quot;, 
&quot;At Risk&quot;, &quot;/img/samples/light_red.gif&quot;, 
&quot;/s.gif&quot;), 
&quot;status color&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TAA</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/Client_Admin__c.object-meta.xml
<CustomObject>
    <description>The admins attached to a Client.</description>
    <label>Client Admin</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Client Admin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Admins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Admin__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The account this Product Admin is attached to</description>
    <inlineHelpText>The account this Product Admin is attached to</inlineHelpText>
    <label>Prospect-Client Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Admins</relationshipLabel>
    <relationshipName>Product_Admins</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/ADM401__c.field-meta.xml
<CustomField>
    <fullName>ADM401__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this an ADM401 admin?</description>
    <inlineHelpText>Is this an ADM401 admin?</inlineHelpText>
    <label>ADM401</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/Contact_Types__c.field-meta.xml
<CustomField>
    <fullName>Contact_Types__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The different types of roles this contact performs.</inlineHelpText>
    <label>Contact Types</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/Envelopes__c.field-meta.xml
<CustomField>
    <fullName>Envelopes__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this an Envelopes Admin?</description>
    <inlineHelpText>Is this an Envelopes Admin?</inlineHelpText>
    <label>Envelopes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/HRS125__c.field-meta.xml
<CustomField>
    <fullName>HRS125__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this an HRS125 Admin?</description>
    <inlineHelpText>Is this an HRS125 Admin?</inlineHelpText>
    <label>HRS125</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/HRSADM__c.field-meta.xml
<CustomField>
    <fullName>HRSADM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this an HRSADM Admin?</description>
    <inlineHelpText>Is this an HRSADM Admin?</inlineHelpText>
    <label>HRSADM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/MMS__c.field-meta.xml
<CustomField>
    <fullName>MMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/Premier_Cobra__c.field-meta.xml
<CustomField>
    <fullName>Premier_Cobra__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Premier field</description>
    <label>Premier Cobra</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/Premier_Compliance__c.field-meta.xml
<CustomField>
    <fullName>Premier_Compliance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Premier field</description>
    <label>Premier Compliance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/Premier_EAP__c.field-meta.xml
<CustomField>
    <fullName>Premier_EAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Premier field</description>
    <label>Premier EAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/Premier_Handbooks__c.field-meta.xml
<CustomField>
    <fullName>Premier_Handbooks__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Premier field</description>
    <label>Premier Handbooks</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/Premier_Mailing_Labels__c.field-meta.xml
<CustomField>
    <fullName>Premier_Mailing_Labels__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Premier field</description>
    <label>Premier Mailing Labels</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/Premier_Payroll__c.field-meta.xml
<CustomField>
    <fullName>Premier_Payroll__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Premier field</description>
    <label>Premier Payroll</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/Premier_Posters__c.field-meta.xml
<CustomField>
    <fullName>Premier_Posters__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Premier field</description>
    <label>Premier Posters</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/Premier_Safety__c.field-meta.xml
<CustomField>
    <fullName>Premier_Safety__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Premier field</description>
    <label>Premier Safety</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/Premier_Seminars__c.field-meta.xml
<CustomField>
    <fullName>Premier_Seminars__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Premier</description>
    <label>Premier Seminars</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/Premier_Survey__c.field-meta.xml
<CustomField>
    <fullName>Premier_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Premier field</description>
    <label>Premier Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/Premier_Welcome_Letter__c.field-meta.xml
<CustomField>
    <fullName>Premier_Welcome_Letter__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Premier</description>
    <label>Premier Welcome Letter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Admin__c/fields/TAA__c.field-meta.xml
<CustomField>
    <fullName>TAA__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if this is a TAA Admin.</inlineHelpText>
    <label>TAA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Types__c.field-meta.xml
<CustomField>
    <fullName>Contact_Types__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The different types of roles this contact performs.</inlineHelpText>
    <label>Contact Types</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Envelopes__c.field-meta.xml
<CustomField>
    <fullName>Envelopes__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Maps from the HRIS address table</description>
    <label>Envelopes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/HRS125__c.field-meta.xml
<CustomField>
    <fullName>HRS125__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Address type from HRIS address table</description>
    <label>HRS125</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MMS__c.field-meta.xml
<CustomField>
    <fullName>MMS__c</fullName>
    <description>To maintain MMS Contact / Administrator role</description>
    <label>MMS Contact Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>IT/MIS</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClientAdminChkAddrTest.cls
/* The methods to test ClientAdminChkAddr class and ClientAdminChkAddrTypes trigger.
   
  History
  -------
  05/01/2009 Dan Carmen   Created
  04/20/2011 Tom Muskatevc Added MMS to test  
  01/15/2013 Dan Carmen   Changed to use Contact Types field
  04/09/2013 Dan Carmen   Changed back to use Address Types until code can be updated
  11/13/2013 Dan Carmen   Change back to use Contact Types field
 */
@isTest
private class ClientAdminChkAddrTest {

    private static Client_Admin__c getCA(Id id) {
       return [select id, name, ADM401__c, Envelopes__c, HRS125__c, HRSADM__c, TAA__c, MMS__c
                     ,Premier_Cobra__c, Premier_Compliance__c, Premier_EAP__c, Premier_Handbooks__c
                     ,Premier_Payroll__c, Premier_Safety__c, Premier_Survey__c
                     ,Premier_Mailing_Labels__c,Premier_Posters__c,Premier_Seminars__c,Premier_Welcome_Letter__c
                     ,Contact_Types__c 
                 from Client_Admin__c where id=:id];
    } // getCA
    
    static testMethod void testAddrTypes() {
       Account a1 = new Account(name='test acct');
       insert a1;
       //****** test for all types on an insert   ****
       Client_Admin__c ca1 = new Client_Admin__c(name='test1',Contact_Types__c='401ADM;ENVELOPES;HRS125;HRSADM;TIB;TLO;MMS;CBR;CI;EAP;HBK;PAYROLL;SAFETY_LOSS;SURVEY;COBRA_LETTER;PST;SEM;WELCOME_LETTER',account__c=a1.id);
       insert ca1;
       ca1 = getCA(ca1.Id);
       System.assertEquals(true, ca1.ADM401__c);
       System.assertEquals(true, ca1.Envelopes__c);
       System.assertEquals(true, ca1.HRS125__c);
       System.assertEquals(true, ca1.HRSADM__c);
       System.assertEquals(true, ca1.TAA__c);
       System.assertEquals(true, ca1.MMS__c);
              
       System.assertEquals(true, ca1.Premier_Cobra__c);
       System.assertEquals(true, ca1.Premier_Compliance__c);
       System.assertEquals(true, ca1.Premier_EAP__c);
       System.assertEquals(true, ca1.Premier_Handbooks__c);
       System.assertEquals(true, ca1.Premier_Payroll__c);
       System.assertEquals(true, ca1.Premier_Safety__c);
       System.assertEquals(true, ca1.Premier_Survey__c);
       
       System.assertEquals(true, ca1.Premier_Mailing_Labels__c);
       System.assertEquals(true, ca1.Premier_Posters__c);
       System.assertEquals(true, ca1.Premier_Seminars__c);
       System.assertEquals(true, ca1.Premier_Welcome_Letter__c);
       
       //****** remove envelopes *****
       ca1.Contact_Types__c = '401ADM;HRS125;HRSADM;TIB;TLO;MMS';
       update ca1;
       ca1 = getCA(ca1.Id);
       System.assertEquals(true, ca1.ADM401__c);
       System.assertEquals(false, ca1.Envelopes__c);
       System.assertEquals(true, ca1.HRS125__c);
       System.assertEquals(true, ca1.HRSADM__c);
       System.assertEquals(true, ca1.TAA__c);
       System.assertEquals(true, ca1.MMS__c);

       
       System.assertEquals(false, ca1.Premier_Cobra__c);
       System.assertEquals(false, ca1.Premier_Compliance__c);
       System.assertEquals(false, ca1.Premier_EAP__c);
       System.assertEquals(false, ca1.Premier_Handbooks__c);
       System.assertEquals(false, ca1.Premier_Payroll__c);
       System.assertEquals(false, ca1.Premier_Safety__c);
       System.assertEquals(false, ca1.Premier_Survey__c);
       
       System.assertEquals(false, ca1.Premier_Mailing_Labels__c);
       System.assertEquals(false, ca1.Premier_Posters__c);
       System.assertEquals(false, ca1.Premier_Seminars__c);
       System.assertEquals(false, ca1.Premier_Welcome_Letter__c);
       
       //****** remove 401ADM, TLO (TAA should still be true because TIB is still there)  ****
       ca1.Contact_Types__c = 'HRS125;HRSADM;TIB;MMS';
       update ca1;
       ca1 = getCA(ca1.Id);
       System.assertEquals(false, ca1.ADM401__c);
       System.assertEquals(false, ca1.Envelopes__c);
       System.assertEquals(true, ca1.HRS125__c);
       System.assertEquals(true, ca1.HRSADM__c);
       System.assertEquals(true, ca1.TAA__c);
       System.assertEquals(true, ca1.MMS__c);
       
       System.assertEquals(false, ca1.Premier_Cobra__c);
       System.assertEquals(false, ca1.Premier_Compliance__c);
       System.assertEquals(false, ca1.Premier_EAP__c);
       System.assertEquals(false, ca1.Premier_Handbooks__c);
       System.assertEquals(false, ca1.Premier_Payroll__c);
       System.assertEquals(false, ca1.Premier_Safety__c);
       System.assertEquals(false, ca1.Premier_Survey__c);

       System.assertEquals(false, ca1.Premier_Mailing_Labels__c);
       System.assertEquals(false, ca1.Premier_Posters__c);
       System.assertEquals(false, ca1.Premier_Seminars__c);
       System.assertEquals(false, ca1.Premier_Welcome_Letter__c);

       //****** only envelopes and hrs125   ****
       ca1.Contact_Types__c = 'ENVELOPES;HRS125';
       update ca1;
       ca1 = getCA(ca1.Id);
       System.assertEquals(false, ca1.ADM401__c);
       System.assertEquals(true, ca1.Envelopes__c);
       System.assertEquals(true, ca1.HRS125__c);
       System.assertEquals(false, ca1.HRSADM__c);
       System.assertEquals(false, ca1.TAA__c);
       System.assertEquals(false, ca1.MMS__c);

       System.assertEquals(false, ca1.Premier_Cobra__c);
       System.assertEquals(false, ca1.Premier_Compliance__c);
       System.assertEquals(false, ca1.Premier_EAP__c);
       System.assertEquals(false, ca1.Premier_Handbooks__c);
       System.assertEquals(false, ca1.Premier_Payroll__c);
       System.assertEquals(false, ca1.Premier_Safety__c);
       System.assertEquals(false, ca1.Premier_Survey__c);
       
       System.assertEquals(false, ca1.Premier_Mailing_Labels__c);
       System.assertEquals(false, ca1.Premier_Posters__c);
       System.assertEquals(false, ca1.Premier_Seminars__c);
       System.assertEquals(false, ca1.Premier_Welcome_Letter__c);

       //****** null out address types  ****
       ca1.Contact_Types__c = null;
       update ca1;
       ca1 = getCA(ca1.Id);
       System.assertEquals(false, ca1.ADM401__c);
       System.assertEquals(false, ca1.Envelopes__c);
       System.assertEquals(false, ca1.HRS125__c);
       System.assertEquals(false, ca1.HRSADM__c);
       System.assertEquals(false, ca1.TAA__c);
       System.assertEquals(false, ca1.MMS__c);

       System.assertEquals(false, ca1.Premier_Cobra__c);
       System.assertEquals(false, ca1.Premier_Compliance__c);
       System.assertEquals(false, ca1.Premier_EAP__c);
       System.assertEquals(false, ca1.Premier_Handbooks__c);
       System.assertEquals(false, ca1.Premier_Payroll__c);
       System.assertEquals(false, ca1.Premier_Safety__c);
       System.assertEquals(false, ca1.Premier_Survey__c);
       
       System.assertEquals(false, ca1.Premier_Mailing_Labels__c);
       System.assertEquals(false, ca1.Premier_Posters__c);
       System.assertEquals(false, ca1.Premier_Seminars__c);
       System.assertEquals(false, ca1.Premier_Welcome_Letter__c);

       //****** only TLO  ****
       ca1.Contact_Types__c = 'TLO';
       update ca1;
       ca1 = getCA(ca1.Id);
       System.assertEquals(false, ca1.ADM401__c);
       System.assertEquals(false, ca1.Envelopes__c);
       System.assertEquals(false, ca1.HRS125__c);
       System.assertEquals(false, ca1.HRSADM__c);
       System.assertEquals(true, ca1.TAA__c);
       System.assertEquals(false, ca1.MMS__c);

       
       System.assertEquals(false, ca1.Premier_Cobra__c);
       System.assertEquals(false, ca1.Premier_Compliance__c);
       System.assertEquals(false, ca1.Premier_EAP__c);
       System.assertEquals(false, ca1.Premier_Handbooks__c);
       System.assertEquals(false, ca1.Premier_Payroll__c);
       System.assertEquals(false, ca1.Premier_Safety__c);
       System.assertEquals(false, ca1.Premier_Survey__c);
       
       System.assertEquals(false, ca1.Premier_Mailing_Labels__c);
       System.assertEquals(false, ca1.Premier_Posters__c);
       System.assertEquals(false, ca1.Premier_Seminars__c);
       System.assertEquals(false, ca1.Premier_Welcome_Letter__c);

       //****** only Handbooks and Safety ****
       ca1.Contact_Types__c = 'HBK;SAFETY_LOSS';
       update ca1;
       ca1 = getCA(ca1.Id);
       System.assertEquals(false, ca1.ADM401__c);
       System.assertEquals(false, ca1.Envelopes__c);
       System.assertEquals(false, ca1.HRS125__c);
       System.assertEquals(false, ca1.HRSADM__c);
       System.assertEquals(false, ca1.TAA__c);
       System.assertEquals(false, ca1.MMS__c);
       
       System.assertEquals(false, ca1.Premier_Cobra__c);
       System.assertEquals(false, ca1.Premier_Compliance__c);
       System.assertEquals(false, ca1.Premier_EAP__c);
       System.assertEquals(true, ca1.Premier_Handbooks__c);
       System.assertEquals(false, ca1.Premier_Payroll__c);
       System.assertEquals(true, ca1.Premier_Safety__c);
       System.assertEquals(false, ca1.Premier_Survey__c);
       
       System.assertEquals(false, ca1.Premier_Mailing_Labels__c);
       System.assertEquals(false, ca1.Premier_Posters__c);
       System.assertEquals(false, ca1.Premier_Seminars__c);
       System.assertEquals(false, ca1.Premier_Welcome_Letter__c);

       //****** only Survey and Payroll  ****
       ca1.Contact_Types__c = 'SURVEY;PAYROLL';
       update ca1;
       ca1 = getCA(ca1.Id);
       System.assertEquals(false, ca1.ADM401__c);
       System.assertEquals(false, ca1.Envelopes__c);
       System.assertEquals(false, ca1.HRS125__c);
       System.assertEquals(false, ca1.HRSADM__c);
       System.assertEquals(false, ca1.TAA__c);
       System.assertEquals(false, ca1.MMS__c);
       
       System.assertEquals(false, ca1.Premier_Cobra__c);
       System.assertEquals(false, ca1.Premier_Compliance__c);
       System.assertEquals(false, ca1.Premier_EAP__c);
       System.assertEquals(false, ca1.Premier_Handbooks__c);
       System.assertEquals(true, ca1.Premier_Payroll__c);
       System.assertEquals(false, ca1.Premier_Safety__c);
       System.assertEquals(true, ca1.Premier_Survey__c);
       
       System.assertEquals(false, ca1.Premier_Mailing_Labels__c);
       System.assertEquals(false, ca1.Premier_Posters__c);
       System.assertEquals(false, ca1.Premier_Seminars__c);
       System.assertEquals(false, ca1.Premier_Welcome_Letter__c);

       //****** only Mailing labels, posters, seminars, welcome letter  ****
       ca1.Contact_Types__c = 'COBRA_LETTER;PST;SEM;WELCOME_LETTER';
       update ca1;
       ca1 = getCA(ca1.Id);
       System.assertEquals(false, ca1.ADM401__c);
       System.assertEquals(false, ca1.Envelopes__c);
       System.assertEquals(false, ca1.HRS125__c);
       System.assertEquals(false, ca1.HRSADM__c);
       System.assertEquals(false, ca1.TAA__c);
       System.assertEquals(false, ca1.MMS__c);
       
       System.assertEquals(false, ca1.Premier_Cobra__c);
       System.assertEquals(false, ca1.Premier_Compliance__c);
       System.assertEquals(false, ca1.Premier_EAP__c);
       System.assertEquals(false, ca1.Premier_Handbooks__c);
       System.assertEquals(false, ca1.Premier_Payroll__c);
       System.assertEquals(false, ca1.Premier_Safety__c);
       System.assertEquals(false, ca1.Premier_Survey__c);
       
       System.assertEquals(true, ca1.Premier_Mailing_Labels__c);
       System.assertEquals(true, ca1.Premier_Posters__c);
       System.assertEquals(true, ca1.Premier_Seminars__c);
       System.assertEquals(true, ca1.Premier_Welcome_Letter__c);

    } // testAddrTypes
    
} // class ClientAdminChkAddrTest