force-app/main/default/objects/Account/fields/PartnerId__c.field-meta.xml
<CustomField>
    <fullName>PartnerId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vendor Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Referral_Account__c/Referral_Account__c.object-meta.xml
<CustomObject>
    <description>Referral Source Company Information</description>
    <label>Referral Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Referral Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Account__c/fields/PartnerId__c.field-meta.xml
<CustomField>
    <fullName>PartnerId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Unique id that identifies the parent in a referral relationship.</inlineHelpText>
    <label>Vendor Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/Referral_Contact__c.object-meta.xml
<CustomObject>
    <label>Referral Contact</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Contact__c/fields/Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Contact_ID__c</fullName>
    <description>This number is initially populated by the ID from WAR. Going forward this number is auto generated from the contact</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Contact ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Account__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Referral Contacts</relationshipLabel>
    <relationshipName>Referral_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/cpaServices.cls
/* 
 * A class used for CPA web service calls
 *
 * History
 * -------
 * 06/25/2017 	Jermaine Stukes   Created
   03/04/2019  Dan Carmen        Add more logging to the Web Service Log
 
 */
global with sharing class cpaServices {
 
    global class RepInfo {
        webservice String repFirstName;
        webservice String repLastName;
        webservice String repEmail;
        webservice String repPhone;
        webservice String repPhoneExt;
        webservice String acctName;
        webservice String partnerId;
    } // RepInfo
      
    //Return Rep info, Account name, and PartnerId
	static webservice RepInfo getRepInfo(string contactId)
    {
        RepInfo ri = new RepInfo();
        Boolean successful;
        String errorLog;
        String notes = 'contactId='+contactId;
        try
        {
            Referral_Contact__c RC = [Select Id, Name, Contact_ID__c, Referral_Account__r.Id, Referral_Account__r.Name, Referral_Account__r.PartnerId__c,OwnerId, Owner.Id, Owner.FirstName, Owner.LastName, Owner.Email, Owner.Phone from Referral_Contact__c where Contact_ID__c=:contactId limit 1];
            notes += ' rc='+rc;
            if(RC != Null)
            {
                if(RC.Owner.Phone!=Null)
                {
                    string parsedPhone = Utilities.removeExtraChars(RC.Owner.Phone, '1234567890');
                    if(parsedPhone.length() > 10)
                    {
                        ri.repPhone = parsedPhone.substring(0,10);
                        ri.repPhoneExt = parsedPhone.substring(10);
                    }
                    else
                    {ri.repPhone = RC.Owner.Phone;}
                }
                else
                {
                    ri.repPhone = null;
                }
                ri.repFirstName = RC.Owner.FirstName;
                ri.repLastName = RC.Owner.LastName;
                ri.repEmail = RC.Owner.Email;
                ri.acctName = RC.Referral_Account__r.Name;
                ri.partnerId = RC.Referral_Account__r.PartnerId__c;
                successful = true;
            }
        }
        catch(Exception e)
        {
            ri = null;
            successful = false;
            errorlog+= 'Cpa Services issue: '+e.getMessage();
        }
        WebServicesHelper.logServiceCall('cpaServices', successful, (String.isNotBlank(errorlog) ? errorlog: null), notes);
        return ri;
    }
} // cpaServices