force-app/main/default/objects/Account/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>Specific products that the lead may be interested in.</description>
    <inlineHelpText>Select the specific product(s) in which the lead has expressed interest.</inlineHelpText>
    <label>Product of Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>Team Selling</fullName>
            </value>
            <value>
                <fullName>401K</fullName>
            </value>
            <value>
                <fullName>Advantage Associate Office Leads</fullName>
            </value>
            <value>
                <fullName>Advantage Inbound Leads Only</fullName>
            </value>
            <value>
                <fullName>Expense Manager</fullName>
            </value>
            <value>
                <fullName>ESR</fullName>
            </value>
            <value>
                <fullName>Flexible Spending Account</fullName>
            </value>
            <value>
                <fullName>Handbooks</fullName>
            </value>
            <value>
                <fullName>Health And Benefits</fullName>
            </value>
            <value>
                <fullName>HR Essentials</fullName>
            </value>
            <value>
                <fullName>Insurance Products</fullName>
            </value>
            <value>
                <fullName>Major Markets Services</fullName>
            </value>
            <value>
                <fullName>Paychex Premier Human Resources</fullName>
            </value>
            <value>
                <fullName>Professional Employment Services</fullName>
            </value>
            <value>
                <fullName>Section 125</fullName>
            </value>
            <value>
                <fullName>Smart Time</fullName>
            </value>
            <value>
                <fullName>Sure Payroll 401K</fullName>
            </value>
            <value>
                <fullName>Time In a Box</fullName>
            </value>
            <value>
                <fullName>Premium Only Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Referral__c.field-meta.xml
<CustomField>
    <fullName>Referral__c</fullName>
    <label>Referral Source Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Firm</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Dealer</fullName>
            </value>
            <value>
                <fullName>Broker Dealer Branch</fullName>
            </value>
            <value>
                <fullName>Business Consultant</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Full Service Agency</fullName>
            </value>
            <value>
                <fullName>Health Insurance Broker</fullName>
            </value>
            <value>
                <fullName>Insurance Broker</fullName>
            </value>
            <value>
                <fullName>Insurance Carrier</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>MSP Partner</fullName>
            </value>
            <value>
                <fullName>National Account</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paychex Co</fullName>
            </value>
            <value>
                <fullName>Payroll Company</fullName>
            </value>
            <value>
                <fullName>PEO Broker</fullName>
            </value>
            <value>
                <fullName>Private Equity Firm</fullName>
            </value>
            <value>
                <fullName>Property and Casualty Broker</fullName>
            </value>
            <value>
                <fullName>Strategic Account</fullName>
            </value>
            <value>
                <fullName>Strategic Accountant Firm</fullName>
            </value>
            <value>
                <fullName>Trusted Advisor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>Specific products that the lead may be interested in.</description>
    <inlineHelpText>Select the specific product(s) in which the lead has expressed interest.</inlineHelpText>
    <label>Product of Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Loans Payments</fullName>
            </value>
            <value>
                <fullName>Business Insurance</fullName>
            </value>
            <value>
                <fullName>Employee Benefits</fullName>
            </value>
            <value>
                <fullName>Hiring Onboarding</fullName>
            </value>
            <value>
                <fullName>HR Services</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>PEO</fullName>
            </value>
            <value>
                <fullName>Startup Services</fullName>
            </value>
            <value>
                <fullName>Time Attendance</fullName>
            </value>
            <value>
                <fullName>Retirement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Referral__c.field-meta.xml
<CustomField>
    <fullName>Referral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If this is created directly from an incoming referral, link directly to that referral.</inlineHelpText>
    <label>Referral</label>
    <referenceTo>Referral__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The referral source for this lead</description>
    <label>Referral Contact</label>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Referral_ID__c.field-meta.xml
<CustomField>
    <fullName>Referral_ID__c</fullName>
    <description>This field was created for the Influitive Integration.  Unfortunately the api name needs to be named exactly like this, as it is passed into an outbound message and they&apos;ve indicated the field needed to be named in this way.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Influitive Referral ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral__c.field-meta.xml
<CustomField>
    <fullName>Referral__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this a referral?</description>
    <label>Referral</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field should only be completed if the Lead Source is an external partner (CPA, Bank, FA, etc.)</inlineHelpText>
    <label>Referral Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Contact__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Referral Contacts with End Dates will only appear if you click the Show All Results link below.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>OppRCs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral_ID__c.field-meta.xml
<CustomField>
    <fullName>Referral_ID__c</fullName>
    <description>This field was created for the Influitive Integration. Unfortunately the api name needs to be named exactly like this, as it is passed into an outbound message and they&apos;ve indicated the field needed to be named in this way.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Influitive Referral ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <description>An object to store Referral information</description>
    <label>Referral</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Referral_Id__c.field-meta.xml
<CustomField>
    <fullName>Referral_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Unique id for the referral.</inlineHelpText>
    <label>Referral Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/SecondaryLeadSource__c.field-meta.xml
<CustomField>
    <fullName>SecondaryLeadSource__c</fullName>
    <formula>IF (NOT(ISBLANK(PartnerDetail__c ))
    , PartnerDetail__r.SecondaryLeadSource__c 
    , IF (NOT(ISBLANK( Referral_Account__c ))
          , IF (NOT(ISBLANK( Referral_Account__r.Parent_Referral_Account__c ))
                 , Referral_Account__r.Parent_Referral_Account__r.SecondaryLeadSource__c
                 , Referral_Account__r.SecondaryLeadSource__c 
            )
          ,&quot;&quot;)
 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secondary Lead Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Selling_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Selling_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Opportunity for the Selling Rep.</inlineHelpText>
    <label>Selling Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Referrals-Selling</relationshipLabel>
    <relationshipName>Selling_Opps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/SellingLeadSource__c.field-meta.xml
<CustomField>
    <fullName>SellingLeadSource__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Lead Source for the Selling Opportunity</inlineHelpText>
    <label>Selling Lead Source</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/SourceLead__c.field-meta.xml
<CustomField>
    <fullName>SourceLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Lead that identifies the contact. This should only be a temporary relationship - conversion should move it to the contact.</inlineHelpText>
    <label>Source Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/Referral_Account__c.object-meta.xml
<CustomObject>
    <description>Referral Source Company Information</description>
    <label>Referral Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Referral Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The matching account to this Referral Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referral Accounts (Account)</relationshipLabel>
    <relationshipName>ReferralAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/fields/SecondaryLeadSource__c.field-meta.xml
<CustomField>
    <fullName>SecondaryLeadSource__c</fullName>
    <formula>IF (ISPICKVAL(Referral_Type__c, &quot;52 Bank Tier 2&quot;)
    , IF (AND(PartnerId__c != null
         , NOT(ISBLANK(ReferralPaymentStart__c)), ReferralPaymentStart__c &lt;= TODAY()
         , OR (ISBLANK(ReferralPaymentEnd__c), ReferralPaymentEnd__c &gt;= TODAY())
        )
        ,&quot;Local Bank with Agreement&quot;
        ,&quot;Local Bank without Agreement&quot;)
    , IF (AND(ISPICKVAL(Referral_Type__c, &quot;52 Bank Tier 1&quot;), PartnerId__c != null)
         ,SecondaryLeadSourceValue__c
         ,&quot;&quot;)
)</formula>
    <label>Secondary Lead Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/Referral_Contact__c.object-meta.xml
<CustomObject>
    <label>Referral Contact</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Contact__c/fields/Referral_ID__c.field-meta.xml
<CustomField>
    <fullName>Referral_ID__c</fullName>
    <description>WAR Referral Source ID Number</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Referral ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CreateBankReferralCrossover.cls
/*
* 07/22/2019	Matt Fritschi		Created Class.
* 
* Called on Bank Referral Lead convert. Finds the created Account, updates ownership based on Zip Assignment Rules, and creates a crossover request.
* 
*/

public without sharing class CreateBankReferralCrossover {
    
    public final Map<Id, Opportunity> oppMap;
    public String leadType;
    public boolean didUpdate = false;
    public Map <Id,Referral__c> referralByOppId;
    public Map<Id, Id> oppToAcct;
    public Map<Id, Account> accountByOppId;
    
    public CreateBankReferralCrossover(Map<Id, Opportunity> opptyMap)
    {
        oppMap = opptyMap;
        startChange();
    }
    
    public void startChange()
    {
        
        //Use the oppMap keyset to find the referral based on the referral's ID
        //Create a map of all opportunity ID's and the referrals linked with those opportunities.
        referralByOppId = new Map<Id,Referral__c>();
        Referral__c[] rfrls = [Select Id, Name, Account__c,Referral_Id__c
                               ,SecondaryLeadSource__c
                               ,SellingLeadSource__c
                               ,Selling_Opportunity__c
                               ,SourceLead__c
                               ,SourceLead__r.Id
                               ,SourceLead__r.OwnerId
                               ,SourceLead__r.IsConverted
                               ,SourceLead__r.LeadSource
                               ,SourceLead__r.Products__c
                               ,Referral_Contact__r.Referral_Account__r.Bank_Centric_Rep__c
                               ,Account__r.OwnerId
                               From Referral__c
                               Where ID in :oppMap.keySet()];
        
        //Check that there is a referral. If not, the lead was manually created and did not come through the form. 
        if(rfrls.size() > 0)
        {
            System.debug('oppMap: '+oppMap);
            System.debug('The Referral is: '+rfrls[0]);
            System.debug('The products are: '+rfrls[0].SourceLead__r.Products__c);
            
            //check if the lead was Payroll or 401k
            if(rfrls[0].SourceLead__r.Products__c == null || rfrls[0].SourceLead__r.Products__c.contains('Payroll'))
            {
                leadType='Payroll';
            }
            else
            {
                leadType='401k';
            }
            
            
            for(Referral__c rfrl : rfrls){
                referralByOppId.put(rfrl.Selling_Opportunity__c,rfrl);
                System.debug('CreateBankReferralCrossover The referral returned is: '+ rfrl);
            }
            
            
            //Create a map of Opportunity Ids and the newly created Account Ids they have liniked
            oppToAcct = new Map<Id, Id>();
            for(Opportunity opp : oppMap.values())
            {
                oppToAcct.put(opp.AccountId, opp.Id);
            }
            
            
            //Create a map from the Opportunity ID to the Account associated with it.
            System.debug('The number of accounts is='+oppToAcct.size() + ' They are: '+oppToAcct.keySet());
            
            accountByOppId = new Map<Id, Account>();
            Account[] accts = [Select Id, Name, OwnerId, NumberOfEmployees
                               From Account
                               Where Id in :oppToAcct.keySet()];
            
            for(Account acct : accts)
            {
                System.debug('The returned account is: '+acct);
                accountByOppId.put(oppToAcct.get(acct.Id), acct);
            } //for(Account acct : accts)
            
            //See if a crossover request needs to be created
            Opportunity opp = oppMap.get(rfrls[0].ID);
            
            //Get the Account associated with the opportunity
            Account checkAccount = (accountByOppId.get(opp.Id) != null ? accountByOppId.get(opp.Id) : null);
            
            //Get the Referral associated with the opportunity
            Referral__c rfrl = referralByOppId.get(opp.Id);
            
            //System.debug('CreateBankReferralCrossover rfrl.SourceLead__r.LeadSource='+rfrl.SourceLead__r.LeadSource+' rfrl.Referral_Contact__r.Referral_Account__r.Bank_Centric_Rep__c='+rfrl.Referral_Contact__r.Referral_Account__r.Bank_Centric_Rep__c);
            
            //check that all conditions are met
            if((rfrl.SourceLead__r.LeadSource == LABEL.LeadSource_ReferralBank && rfrl.Referral_Contact__r.Referral_Account__r.Bank_Centric_Rep__c == null) 
               || (rfrl.SourceLead__r.LeadSource == LABEL.LeadSource_ReferralBank && checkAccount != null && checkAccount.OwnerId == rfrl.Referral_Contact__r.Referral_Account__r.Bank_Centric_Rep__c))
            {
                //If ownership of the account hasn't been updated, force it's update using zip assignments
                System.debug('CreateBankReferralCrossover rfrl.SourceLead__r.LeadSource='+rfrl.SourceLead__r.LeadSource+' rfrl.Referral_Contact__r.Referral_Account__r.Bank_Centric_Rep__c='+rfrl.Referral_Contact__r.Referral_Account__r.Bank_Centric_Rep__c+' accountByOppId.get(opp.Id).OwnerId='+ checkAccount.OwnerId);
                System.debug('checkAccount.OwnerId='+checkAccount.OwnerId+' UserInfo.getUserId='+UserInfo.getUserId());
                
                checkAccount = [SELECT Id, Name, OwnerId, NumberOfEmployees, Use_Zip_Assignment_Rules__c FROM Account WHERE Id = :checkAccount.Id];
                
                System.debug('saveOpp the account being entered='+checkAccount);
                ZipCheckOwner.SKIP_TRIGGERS=false;
                System.debug('SKIP_TRIGGERS='+ZipCheckOwner.SKIP_TRIGGERS);
                checkAccount.Use_Zip_Assignment_Rules__c = true;
                
                List<Account> DMLAccountList = new List<Account>();
                DMLAccountList.add(checkAccount);
                DMLHelper.performDML2(DMLAccountList, DmlHelper.DML_UPDATE, 'CreateBankReferralCrossover', 'startChange', 'Updating ownership of Account', true);
                didUpdate=true;
                
                checkAccount = [SELECT Id, Name, OwnerId, NumberOfEmployees, Use_Zip_Assignment_Rules__c FROM Account WHERE Id = :checkAccount.Id];
                
                
            } //if((rfrl.SourceLead__r.LeadSource == LABEL.LeadSource_ReferralBank && rfrl.Referral_Contact__r.Referral_Account__r.Bank_Centric_Rep__c == null) || (rfrl.SourceLead__r.LeadSource == LABEL.LeadSource_ReferralBank && checkAccount != null && checkAccount.OwnerId != rfrl.Referral_Contact__r.Referral_Account__r.Bank_Centric_Rep__c))
            //If the new Account owner is not equal to the original Lead owner, create a Crossover.
            if(checkAccount.OwnerId != rfrl.SourceLead__r.OwnerId || Test.isRunningTest())
            {        
                System.debug('updatedAccount='+checkAccount);
                createCrossoverRequest(checkAccount, leadType);
            } // if(checkAccount.OwnerId != rfrl.SourceLead__r.OwnerId || Test.isRunningTest())
        } //if(rfrls.size() > 0)
        
        
        else
        {
            return;
        }
        
        /*
else
{

Opportunity[] opps = oppMap.values();
Map<Id, Id> acctIds = new Map<Id, Id>();
for(Opportunity opp : opps)
{
acctIds.put(opp.Id, opp.AccountId);
}

Account[] acct = [SELECT Id, Name, OwnerId, Use_Zip_Assignment_Rules__c, Products__c FROM Account WHERE Id IN :acctIds.values()];
Account checkAccount = acct[0];
System.debug('acct='+acct);

checkAccount.Use_Zip_Assignment_Rules__c = true;
if(checkAccount.Products__c==null)
{
checkAccount.Products__c='Payroll';
}
if(checkAccount.Products__c.contains('Payroll'))
{
leadType='Payroll';
}
else
{
leadType='401k';
}
update checkAccount;

createCrossoverRequest(checkAccount, leadType);
}
*/
        
    }
    
    public void createCrossoverRequest(Account acct, String ldType)
    {
        CrossoverRequestController crt = new CrossoverRequestController(acct, ldType);
    }
    
    
}