force-app/main/default/objects/Account/fields/Referral__c.field-meta.xml
<CustomField>
    <fullName>Referral__c</fullName>
    <label>Referral Source Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Firm</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Dealer</fullName>
            </value>
            <value>
                <fullName>Broker Dealer Branch</fullName>
            </value>
            <value>
                <fullName>Business Consultant</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Full Service Agency</fullName>
            </value>
            <value>
                <fullName>Health Insurance Broker</fullName>
            </value>
            <value>
                <fullName>Insurance Broker</fullName>
            </value>
            <value>
                <fullName>Insurance Carrier</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>MSP Partner</fullName>
            </value>
            <value>
                <fullName>National Account</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paychex Co</fullName>
            </value>
            <value>
                <fullName>Payroll Company</fullName>
            </value>
            <value>
                <fullName>PEO Broker</fullName>
            </value>
            <value>
                <fullName>Private Equity Firm</fullName>
            </value>
            <value>
                <fullName>Property and Casualty Broker</fullName>
            </value>
            <value>
                <fullName>Strategic Account</fullName>
            </value>
            <value>
                <fullName>Strategic Accountant Firm</fullName>
            </value>
            <value>
                <fullName>Trusted Advisor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>PBS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pay</fullName>
            </value>
            <value>
                <fullName>PAS</fullName>
            </value>
            <value>
                <fullName>H&amp;B</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral__c.field-meta.xml
<CustomField>
    <fullName>Referral__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this a referral?</description>
    <label>Referral</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/PEO_Opportunity_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>PEO_Opportunity_Record_Type</fullName>
    <active>true</active>
    <businessProcess>PEO Sales Process</businessProcess>
    <description>Sales reps use this record type to track a Flex PEO prospect through the sales process.</description>
    <label>PEO Opportunity Record Type</label>
</RecordType>

force-app/main/default/objects/RecordType__c/RecordType__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Additional Information for record types</description>
    <label>RecordType</label>
</CustomObject>

force-app/main/default/objects/RecordType__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the object this record type is associated with</inlineHelpText>
    <label>Object Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecordType__c/fields/RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The full name of the record type in case it&apos;s longer than the size of the name field.</inlineHelpText>
    <label>RecordType Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <description>An object to store Referral information</description>
    <label>Referral</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Referral_Partner__c.field-meta.xml
<CustomField>
    <fullName>Referral_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The type of referral partner.</inlineHelpText>
    <label>Referral Partner</label>
    <referenceTo>Referral_Partner__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Selling_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Selling_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Opportunity for the Selling Rep.</inlineHelpText>
    <label>Selling Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Referrals-Selling</relationshipLabel>
    <relationshipName>Selling_Opps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Partner__c/Referral_Partner__c.object-meta.xml
<CustomObject>
    <description>The partners that can be referred to.</description>
    <label>Referral Partner</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Referral Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Partner__c/fields/CreateRefOpp__c.field-meta.xml
<CustomField>
    <fullName>CreateRefOpp__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Do we need to create an Opportunity for the Referring rep?</inlineHelpText>
    <label>Create Referring Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Referral_Partner__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Is this an active referral partner?</inlineHelpText>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Referral_Partner__c/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <inlineHelpText>The type of partner - internal vs external</inlineHelpText>
    <label>Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amplifinity</fullName>
            </value>
            <value>
                <fullName>External Referral</fullName>
            </value>
            <value>
                <fullName>Inbound Partner Referral</fullName>
            </value>
            <value>
                <fullName>Integrated Selling</fullName>
            </value>
            <value>
                <fullName>Internal Referral</fullName>
            </value>
            <value>
                <fullName>NSS Referral</fullName>
            </value>
            <value>
                <fullName>Oasis</fullName>
            </value>
            <value>
                <fullName>PEO Referral</fullName>
            </value>
            <value>
                <fullName>SOAR Referral</fullName>
            </value>
            <value>
                <fullName>MMS SDR</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>NSS Referral Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral_Partner__c/fields/Ref_To_Type__c.field-meta.xml
<CustomField>
    <fullName>Ref_To_Type__c</fullName>
    <inlineHelpText>The field type that will display in the Ref To column on the Referral Page</inlineHelpText>
    <label>Ref To Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contact</fullName>
                <default>true</default>
                <label>Contact</label>
            </value>
            <value>
                <fullName>Referral Contact</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral_Partner__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <inlineHelpText>The Sales Org for this Referral Partner - used for Zip Assignment lookup.</inlineHelpText>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BenAdmin</fullName>
            </value>
            <value>
                <fullName>BusDev</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>ESR</fullName>
            </value>
            <value>
                <fullName>EW</fullName>
            </value>
            <value>
                <fullName>HNBF</fullName>
            </value>
            <value>
                <fullName>HROI</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>Icon</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>PAS</fullName>
            </value>
            <value>
                <fullName>PAY</fullName>
            </value>
            <value>
                <fullName>PC</fullName>
            </value>
            <value>
                <fullName>PEO</fullName>
            </value>
            <value>
                <fullName>TAA</fullName>
            </value>
            <value>
                <fullName>HRS WHOLESALER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral_Partner__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <inlineHelpText>The order the records will be displayed.</inlineHelpText>
    <label>Sort Order</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org-Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>BenAdmin</fullName>
            </value>
            <value>
                <fullName>Benetrac</fullName>
            </value>
            <value>
                <fullName>BusDev</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Relations</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Center</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise Service Center</fullName>
            </value>
            <value>
                <fullName>ESR</fullName>
            </value>
            <value>
                <fullName>EW</fullName>
            </value>
            <value>
                <fullName>Field Operations Core</fullName>
            </value>
            <value>
                <fullName>HNBF</fullName>
            </value>
            <value>
                <fullName>HROI</fullName>
            </value>
            <value>
                <fullName>HR Online</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>HRS 401K-S125</fullName>
            </value>
            <value>
                <fullName>HRS Premier</fullName>
            </value>
            <value>
                <fullName>Icon</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Merchant Services</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MMS Hub</fullName>
            </value>
            <value>
                <fullName>MPSC</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>PAS</fullName>
            </value>
            <value>
                <fullName>PAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntegratedSellingControllerTest.cls
/* 
 * Test methods for the IntegratedSellingControllerTest.
 *
 * History
 * -------
 * 09/27/2018 Lynn Michels        Created.
 *
 */
@isTest
private class IntegratedSellingControllerTest {
	
	@testSetup
   static void setupData() {
   	//create referral partners for integrated selling
   	List<Referral_Partner__c> refPartners = new List<Referral_Partner__c>();
    refPartners.add(new Referral_Partner__c(Name='MMS',Partner_Type__c=ReferralController.REF_INTSELL,Sort_Order__c=20,Ref_To_Type__c='User',CreateRefOpp__c=false, IsActive__c=true));
    refPartners.add(new Referral_Partner__c(Name='PAS',Partner_Type__c=ReferralController.REF_INTSELL,Sort_Order__c=20,Ref_To_Type__c='User',CreateRefOpp__c=false, IsActive__c=true));
    refPartners.add(new Referral_Partner__c(Name='PAY',Partner_Type__c=ReferralController.REF_INTSELL,Sort_Order__c=20,Ref_To_Type__c='User',CreateRefOpp__c=false, IsActive__c=true));
   	insert refPartners;
   	
    //set up RecordType custom setting
    RecordType__c[] recordTypes = new RecordType__c[]{}; 
	//PEO
	recordTypes.add(new RecordType__c(Name=Label.PEO_Opportunity_Record_Type,ObjectName__c=ObjectHelper.OBJECT_OPPTY,RecordTypeName__c=Label.PEO_Opportunity_Record_Type, Sales_Org__c=UserHelper.SO_PEO_ASO));
    //MMS
    recordTypes.add(new RecordType__c(Name=Label.MMS_Opportunity_Record_Type,ObjectName__c=ObjectHelper.OBJECT_OPPTY,RecordTypeName__c=Label.MMS_Opportunity_Record_Type, Sales_Org__c=UserHelper.SO_MMS));
    //CORE
    recordTypes.add(new RecordType__c(Name=Label.PAY_Opportunity_Record_Type,ObjectName__c=ObjectHelper.OBJECT_OPPTY,RecordTypeName__c=Label.PAY_Opportunity_Record_Type, Sales_Org__c=UserHelper.SO_CORE));
    insert recordTypes;

   } // setupData 
    
    static testMethod void getAcctOppsTestWithExistingReferrals() {
    	CreateTestData.createSingleAandTwoCts();
    	List<Account> accountList= [SELECT Id FROM Account];
    system.debug('LM accountList '+accountList);
    	List<Contact> contactList = [SELECT Id FROM Contact];
    system.debug('LM cotactList '+contactList); 
    	//create Core opp and attach it to a referral
    	CreateTestData.createTestCoreOptys(accountList[0].id, contactList[0].id);
    	List<Opportunity> coreOppList = [SELECT Id, OwnerId, AccountId FROM Opportunity WHERE RecordType.Name = 'Core Opportunity Record Type'];
   		Referral__c referral = new Referral__c(Name='TestReferral-Core', Selling_Opportunity__c = coreOppList[0].id);
    	insert referral;
    	
    	//create an mms opp
    	CreateTestData.createTestMMSSoldOptys(accountList[0].id, contactList[0].id);
    	
    	List<Opportunity> opps = IntegratedSellingController.getAcctOpps(accountList[0].id);
    	system.assertEquals(2, opps.size());
    	
  		//process the opportunities and ensure the data is created properly
    	IntegratedSellingController.processOpportunities(opps);
    	//verify one referral join is created and there are 2 referrals
    	
    	List<Referral__c> referralList = [SELECT Id, Selling_Opportunity__c, Account__c, OwnerId, User__c, Status__c FROM Referral__c];
    	system.assertEquals(2, referralList.size());
    	
    	List<Referral__c> referralMMS = [SELECT Id, Referral_Partner__r.Name FROM Referral__c WHERE Referral_Partner__r.Name = 'MMS'];
    	List<Referral__c> referralPAY = [SELECT Id, Referral_Partner__r.Name FROM Referral__c WHERE Referral_Partner__r.Name = 'PAY'];
    	
    	List<ReferralJoin__c> referralJoin = [SELECT Id, PAS_Referral__c,MMS_Referral__c, Core_Referral__c FROM ReferralJoin__c];
    	system.assertEquals(1, referralJoin.size());
    	system.assertEquals(null, referralJoin[0].PAS_Referral__c);
    	system.assertEquals(referralMMS[0].id,  referralJoin[0].MMS_Referral__c);
    	system.assertEquals(referralPAY[0].id,  referralJoin[0].Core_Referral__c);
    		
    }// getAcctOppsTest
    
    static testMethod void getOppsTestNoExistingReferrals() {
    	CreateTestData.createSingleAandTwoCts();
    	List<Account> accountList= [SELECT Id FROM Account];
    system.debug('LM accountList '+accountList);
    	List<Contact> contactList = [SELECT Id FROM Contact];
    system.debug('LM cotactList '+contactList); 
    	CreateTestData.createTestCoreOptys(accountList[0].id, contactList[0].id);
    	CreateTestData.createTestPEOOptys(accountList[0].id, contactList[0].id);
    	List<Opportunity> oppList = [SELECT Id FROM Opportunity];
    system.debug('LM oppList '+oppList); 
    	List<Opportunity> opps = IntegratedSellingController.getOpps(oppList[0].id);
    	system.assertEquals(2, opps.size());
    	
    	IntegratedSellingController.processOpportunities(opps);
    	List<ReferralJoin__c> referralJoin = [SELECT Id FROM ReferralJoin__c];
    	List<Referral__c> referralList = [SELECT Id, Selling_Opportunity__c, Account__c, OwnerId, User__c, Status__c, Referral_Partner__c FROM Referral__c];
    	system.assertEquals(2, referralList.size());
    	system.assertEquals(1, referralJoin.size());
    	
    }// getOppsTest
}