force-app/main/default/objects/Account/fields/Referral__c.field-meta.xml
<CustomField>
    <fullName>Referral__c</fullName>
    <label>Referral Source Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Firm</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Dealer</fullName>
            </value>
            <value>
                <fullName>Broker Dealer Branch</fullName>
            </value>
            <value>
                <fullName>Business Consultant</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Full Service Agency</fullName>
            </value>
            <value>
                <fullName>Health Insurance Broker</fullName>
            </value>
            <value>
                <fullName>Insurance Broker</fullName>
            </value>
            <value>
                <fullName>Insurance Carrier</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>MSP Partner</fullName>
            </value>
            <value>
                <fullName>National Account</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paychex Co</fullName>
            </value>
            <value>
                <fullName>Payroll Company</fullName>
            </value>
            <value>
                <fullName>PEO Broker</fullName>
            </value>
            <value>
                <fullName>Private Equity Firm</fullName>
            </value>
            <value>
                <fullName>Property and Casualty Broker</fullName>
            </value>
            <value>
                <fullName>Strategic Account</fullName>
            </value>
            <value>
                <fullName>Strategic Accountant Firm</fullName>
            </value>
            <value>
                <fullName>Trusted Advisor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Referral_ID__c.field-meta.xml
<CustomField>
    <fullName>Referral_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Referral ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bank_Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Bank_Lead_ID__c</fullName>
    <description>Used to track opportunities referred by Bankers and are tracked in LTS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Lead ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CheckIfCloned__c.field-meta.xml
<CustomField>
    <fullName>CheckIfCloned__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if this is a cloned opportunity</inlineHelpText>
    <label>Check If Cloned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <description>The Id of the current Opportunity, or if this is a cloned record, the Id of the Opportunity this is cloned from.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Id of the current Opportunity, or if this is a cloned record, the Id of the Opportunity this is cloned from.</inlineHelpText>
    <label>Opportunity Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral__c.field-meta.xml
<CustomField>
    <fullName>Referral__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this a referral?</description>
    <label>Referral</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral_ID__c.field-meta.xml
<CustomField>
    <fullName>Referral_ID__c</fullName>
    <description>This field was created for the Influitive Integration. Unfortunately the api name needs to be named exactly like this, as it is passed into an outbound message and they&apos;ve indicated the field needed to be named in this way.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Influitive Referral ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ReferralLookup__c.field-meta.xml
<CustomField>
    <fullName>ReferralLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral Lookup</label>
    <referenceTo>Referral__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PartnerReferral__c/PartnerReferral__c.object-meta.xml
<CustomObject>
    <description>Referrals that are coming from a partner (ex bank, cpa, et al)</description>
    <label>Partner Referral</label>
    <nameField>
        <displayFormat>L{00000000}</displayFormat>
        <label>Referral Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PartnerReferral__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Referrals (Account)</relationshipLabel>
    <relationshipName>Partner_Referral_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PartnerReferral__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Partner Referral (Contact)</relationshipLabel>
    <relationshipName>Partner_Referral_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PartnerReferral__c/fields/Referral__c.field-meta.xml
<CustomField>
    <fullName>Referral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The referral record that was generated as part of this partner referral.</inlineHelpText>
    <label>Referral</label>
    <referenceTo>Referral__c</referenceTo>
    <relationshipLabel>Partner Referrals</relationshipLabel>
    <relationshipName>PartnerReferrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <description>An object to store Referral information</description>
    <label>Referral</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Paychex employee this referral is for.</inlineHelpText>
    <label>Refer To Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You must select a Paychex employee as a Contact.</errorMessage>
        <filterItems>
            <field>Contact.HR_Person_Id__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>startsWith</operation>
            <value>Paychex Inc SA</value>
        </filterItems>
        <infoMessage>A Paychex Employee must be selected as a Contact</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referrals (Contact)</relationshipLabel>
    <relationshipName>Internal_Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/PartnerReferral__c.field-meta.xml
<CustomField>
    <fullName>PartnerReferral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup back to the Partner Referral object.</description>
    <label>Partner Referral</label>
    <referenceTo>PartnerReferral__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Referral_Id__c.field-meta.xml
<CustomField>
    <fullName>Referral_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Unique id for the referral.</inlineHelpText>
    <label>Referral Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Selling_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Selling_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Opportunity for the Selling Rep.</inlineHelpText>
    <label>Selling Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Referrals-Selling</relationshipLabel>
    <relationshipName>Selling_Opps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/SourceContact__c.field-meta.xml
<CustomField>
    <fullName>SourceContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Prospect-Client Contact record that is the contact for this referral.</inlineHelpText>
    <label>Source Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Contact should be linked to the Prospect-Client</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referrals (Source Contact)</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TriggerSetup__c/TriggerSetup__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Is a particular trigger setup for use in the Trigger Methods class?</description>
    <label>Trigger Setup</label>
</CustomObject>

force-app/main/default/objects/TriggerSetupClasses__c/TriggerSetupClasses__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The classes that are executed as part of each trigger execution</description>
    <label>Trigger Setup Classes</label>
</CustomObject>

force-app/main/default/classes/OpptyChkCloneTest.cls
/* 
 * Test methods for OpptyChkClone
 *
 * History
 * -------
   06/16/2017 Dan Carmen   Created
   
 *
 */
@isTest
private class OpptyChkCloneTest {

   static testMethod void testClonedOpps() {
      // setup triggers
      TriggerSetupClasses__c[] setupClasses = new TriggerSetupClasses__c[]{};
      TriggerSetup__c trigSetup1 = TriggerMethodsTest.createCustomSetting(null, 'OpptyBefore', true, false, new String[]{'OpptyChkClone'},setupClasses);
      TriggerSetup__c trigSetup2 = TriggerMethodsTest.createCustomSetting(null, 'OpptyAfter', false, true, new String[]{'OpptyChkClone'},setupClasses);
      insert setupClasses;
      
      Account acct1 = new Account(Name='Test Acct1');
      Account acct2 = new Account(Name='Test Acct2');
      Account acct3 = new Account(Name='Test Acct3');
      Account[] accts = new Account[]{acct1,acct2,acct3};
      insert accts;
      Contact ctct1 = new Contact(AccountId=acct1.Id, LastName='Last1');
      Contact ctct2 = new Contact(AccountId=acct2.Id, LastName='Last1');
      Contact ctct3 = new Contact(AccountId=acct3.Id, LastName='Last1');
      Contact[] ctcts = new Contact[]{ctct1,ctct2,ctct3};
      insert ctcts;
      
      Opportunity opp1 = new Opportunity(Name='Opp1', AccountId=acct1.Id, StageName='Pending', CloseDate=Date.today());
      insert opp1;
      
      OpportunityContactRole ocr1 = new OpportunityContactRole(ContactId=ctct1.Id, OpportunityId=opp1.Id, IsPrimary=true);
      insert ocr1;
      
      PartnerReferral__c partRef = new PartnerReferral__c(Contact__c=ctct1.Id, Account__c=acct1.Id);
      insert partRef;
      partRef = [Select Id, Name, Contact__c, Account__c from PartnerReferral__c where Id=:partRef.Id];
      
      Referral__c ref1 = new Referral__c(Name='Test Ref', Referral_Id__c=partRef.Name, Account__c=acct1.Id, SourceContact__c=ctct1.Id
                                       ,PartnerReferral__c=partRef.Id, Selling_Opportunity__c=opp1.Id);
      insert ref1;
                
      opp1.ReferralLookup__c = ref1.Id;
      opp1.Bank_Lead_ID__c = ref1.Referral_Id__c;
      update opp1;
      
      // create cloned opps
      Test.startTest();
      Opportunity opp2 = new Opportunity(Name='Opp2', AccountId=acct2.Id, StageName='Pending', CloseDate=Date.today(), OpportunityId__c=opp1.Id);
      Opportunity opp3 = new Opportunity(Name='Opp2', AccountId=acct3.Id, StageName='Pending', CloseDate=Date.today(), OpportunityId__c=opp1.Id);
      Opportunity[] opps = new Opportunity[]{opp2,opp3};
      insert opps;
      
      Test.stopTest();
      System.assertEquals(3,[select count() from Referral__c]);
      
      Referral__c ref2 = [Select Id, Name, Referral_Id__c, Account__c, SourceContact__c, PartnerReferral__c, Selling_Opportunity__c from Referral__c where Selling_Opportunity__c=:opp2.Id];
      System.assertEquals(ref1.Referral_Id__c, ref2.Referral_Id__c);
      System.assertEquals(acct2.Id, ref2.Account__c);
      System.assertEquals(partRef.Id, ref2.PartnerReferral__c);
      System.assertEquals(null, ref2.SourceContact__c);
      
      Referral__c ref3 = [Select Id, Name, Referral_Id__c, Account__c, SourceContact__c, PartnerReferral__c, Selling_Opportunity__c from Referral__c where Selling_Opportunity__c=:opp3.Id];
      System.assertEquals(ref1.Referral_Id__c, ref3.Referral_Id__c);
      System.assertEquals(acct3.Id, ref3.Account__c);
      System.assertEquals(partRef.Id, ref3.PartnerReferral__c);
      System.assertEquals(null, ref3.SourceContact__c);
      
      delete ref3;
      
      OpportunityContactRole ocr3 = new OpportunityContactRole(ContactId=ctct3.Id, OpportunityId=opp3.Id, IsPrimary=true);
      insert ocr3;

      opp3.CheckIfCloned__c = true;
      update opp3;
      
      ref3 = [Select Id, Name, Referral_Id__c, Account__c, SourceContact__c, PartnerReferral__c, Selling_Opportunity__c from Referral__c where Selling_Opportunity__c=:opp3.Id];
      System.assertEquals(ref1.Referral_Id__c, ref3.Referral_Id__c);
      System.assertEquals(acct3.Id, ref3.Account__c);
      System.assertEquals(partRef.Id, ref3.PartnerReferral__c);
      System.assertEquals(ctct3.Id, ref3.SourceContact__c);
      
      opp3 = [Select Id, Name, CheckIfCloned__c from Opportunity where Id=:opp3.Id];
      System.assertEquals(false, opp3.CheckIfCloned__c);
      
      
   } // testClonedOpps
   
} // class OpptyChkCloneTest