force-app/main/default/objects/Account/fields/Referral_Type__c.field-meta.xml
<CustomField>
    <fullName>Referral_Type__c</fullName>
    <label>Referral Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Firm</fullName>
            </value>
            <value>
                <fullName>Bank - Tier 1</fullName>
            </value>
            <value>
                <fullName>Bank - Tier 2</fullName>
            </value>
            <value>
                <fullName>52 Bank Tier 1</fullName>
            </value>
            <value>
                <fullName>52 Bank Tier 2</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>100 Broker</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Strategic Account</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/AICPA_Enrolled__c.field-meta.xml
<CustomField>
    <fullName>AICPA_Enrolled__c</fullName>
    <label>AICPA Enrolled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/AICPA_Enrolled_Date__c.field-meta.xml
<CustomField>
    <fullName>AICPA_Enrolled_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date enrolled in AICPA, initially set via a data load from WAR, will be automatically set as the date AICPA enrolled is checked</inlineHelpText>
    <label>AICPA Enrolled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AICPA_Original_Type__c.field-meta.xml
<CustomField>
    <fullName>AICPA_Original_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AICPA Original Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AKC_Registered__c.field-meta.xml
<CustomField>
    <fullName>AKC_Registered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AKC Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Business_Owner__c.field-meta.xml
<CustomField>
    <fullName>Business_Owner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used as part of e-client load.  Indicates if contact is an owner or primary decision maker.</description>
    <inlineHelpText>Used for Sales purposes.  Indicates if contact is an owner or primary decision maker.</inlineHelpText>
    <label>Business Owner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Types__c.field-meta.xml
<CustomField>
    <fullName>Contact_Types__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The different types of roles this contact performs.</inlineHelpText>
    <label>Contact Types</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_AKC_Registered__c.field-meta.xml
<CustomField>
    <fullName>Date_AKC_Registered__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date AKC Registered</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PayrollContact__c.field-meta.xml
<CustomField>
    <fullName>PayrollContact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this a Payroll Contact? This is set based on values coming from the Contact Types field.</description>
    <label>Payroll Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Referral_Type__c.field-meta.xml
<CustomField>
    <fullName>Referral_Type__c</fullName>
    <label>Referral Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100 Broker</fullName>
            </value>
            <value>
                <fullName>10 CPA Referring 3-4/Year</fullName>
            </value>
            <value>
                <fullName>11 CPA2BIZ Call</fullName>
            </value>
            <value>
                <fullName>12 CPA Call</fullName>
            </value>
            <value>
                <fullName>19 CPA2BIZ Referral</fullName>
            </value>
            <value>
                <fullName>30 CPA Referring &lt;3/Year</fullName>
            </value>
            <value>
                <fullName>50 CPA Non-referring</fullName>
            </value>
            <value>
                <fullName>52 Bank Call</fullName>
            </value>
            <value>
                <fullName>5 CPA Referring &gt;4/Year</fullName>
            </value>
            <value>
                <fullName>60 Financial Advisor</fullName>
            </value>
            <value>
                <fullName>70 IIA Contracted</fullName>
            </value>
            <value>
                <fullName>70 IIA General</fullName>
            </value>
            <value>
                <fullName>76 Money Manager</fullName>
            </value>
            <value>
                <fullName>77 IIA Contracted</fullName>
            </value>
            <value>
                <fullName>80 Remote Program</fullName>
            </value>
            <value>
                <fullName>90 Employee</fullName>
            </value>
            <value>
                <fullName>Strategic Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TAA_Reference_Date__c.field-meta.xml
<CustomField>
    <fullName>TAA_Reference_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>To mark when a client has agreed to be a reference</inlineHelpText>
    <label>TAA Reference Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Willing_to_Be_a_Reference_TAA__c.field-meta.xml
<CustomField>
    <fullName>Willing_to_Be_a_Reference_TAA__c</fullName>
    <description>To note whether a client agreed to be a reference or not.</description>
    <inlineHelpText>Please indicate if the client has agreed to be a reference for time and attendance.</inlineHelpText>
    <label>Willing to Be a Reference - TAA</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>PST</fullName>
            </value>
            <value>
                <fullName>TLO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactCheckTypeTest.cls
/* 
 * Test methods for the ContactCheckType class
 *
 * History
 * -------
   01/28/2016 Dan Carmen      Created
   12/13/2017 Dan Carmen      Changed the Payroll Contact criteria
   07/18/2019 Dan Carmen      Add criteria for Business Owner

 */
@isTest
private class ContactCheckTypeTest {

   static testMethod void testCheckType() {
      Account acct = new Account(Name='Enterprise');
      insert acct;
      
      Contact ctct1 = new Contact(AccountId=acct.Id,LastName='Kirk');
      Contact ctct2 = new Contact(AccountId=acct.Id,LastName='Spock', Contact_Types__c='Live Long and Prosper');
      Contact ctct3 = new Contact(AccountId=acct.Id,LastName='McCoy', Contact_Types__c='Medical Payroll');
      Contact ctct4 = new Contact(AccountId=acct.Id,LastName='Sulu', Contact_Types__c='Payroll');
      Contact[] ctcts = new Contact[]{ctct1,ctct2,ctct3,ctct4};
      insert ctcts;
      
      Map<Id, Contact> ctctMap = new Map<Id,Contact>([Select id, Name, PayrollContact__c, Contact_Types__c from Contact where Id in :ctcts]);
      System.assertEquals(false,ctctMap.get(ctct1.Id).PayrollContact__c);
      System.assertEquals(false,ctctMap.get(ctct2.Id).PayrollContact__c);
      System.assertEquals(true,ctctMap.get(ctct3.Id).PayrollContact__c);
      System.assertEquals(true,ctctMap.get(ctct4.Id).PayrollContact__c);
      
      ctctMap.get(ctct3.Id).Contact_Types__c='Medical;Payroll';
      ctctMap.get(ctct4.Id).Contact_Types__c='Navigation Payroll';
      // create new array since they were re-selected
      update ctctMap.values();
      
      ctctMap = new Map<Id,Contact>([Select id, Name, PayrollContact__c, Contact_Types__c from Contact where Id in :ctctMap.keySet()]);
      System.assertEquals(false,ctctMap.get(ctct1.Id).PayrollContact__c);
      System.assertEquals(false,ctctMap.get(ctct2.Id).PayrollContact__c);
      System.assertEquals(true,ctctMap.get(ctct3.Id).PayrollContact__c);
      System.assertEquals(true,ctctMap.get(ctct4.Id).PayrollContact__c);

   } // static testMethod
   
   static testMethod void testOtherAttributes() {
      Account acct = new Account(Name='Test Account');
      insert acct;
      
      Contact ctct = new Contact(LastName='Contact', AccountId=acct.Id, Referral_Type__c='Test Type');
      ctct.Title = 'Business Owner';
      ctct.Willing_to_Be_a_Reference_TAA__c = 'Yes';
      ctct.AICPA_Enrolled__c = 'Y';
      ctct.AKC_Registered__c = true;
      
      insert ctct;
      
      ctct = [Select Id, LastName, Title, Business_Owner__c
                    ,Willing_to_Be_a_Reference_TAA__c, TAA_Reference_Date__c
                    ,AICPA_Enrolled__c, AICPA_Enrolled_Date__c, AICPA_Original_Type__c
                    ,AKC_Registered__c, Date_AKC_Registered__c
                From Contact
               Where Id=:ctct.Id];
      System.assertEquals('Business Owner', ctct.Title);
      System.assertEquals(true, ctct.Business_Owner__c);
      System.assertEquals('Yes', ctct.Willing_to_Be_a_Reference_TAA__c);
      System.assertEquals(Date.today(), ctct.TAA_Reference_Date__c);
      System.assertEquals('Y', ctct.AICPA_Enrolled__c);
      System.assertEquals(Date.today(), ctct.AICPA_Enrolled_Date__c);
      System.assertEquals('Test Type', ctct.AICPA_Original_Type__c);
      System.assertEquals(true, ctct.AKC_Registered__c);
      System.assertEquals(Date.today(), ctct.Date_AKC_Registered__c);
   } // testOtherAttributes
   
} // class ContactCheckTypeTest