force-app/main/default/objects/Account/fields/SalesParent__c.field-meta.xml
<CustomField>
    <fullName>SalesParent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Manually updated by Sales, Added for Case #19672066</description>
    <inlineHelpText>Used to identify the primary location or location of the decision maker and used for multi-ID Scenarios.</inlineHelpText>
    <label>Sales Parent</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND (2 OR 7) AND 3 AND 4) OR (1 AND (2 OR 7) AND 5 AND 6) OR (1 AND (2 OR 7) AND 8 AND 9)</booleanFilter>
        <errorMessage>Sales Parent can not be a child of another account AND Sales Parent must have a  corresponding record type to the current account.</errorMessage>
        <filterItems>
            <field>Account.isChild__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Child_Count__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Core Account Record Type,MMS Account Record Type</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Core Account Record Type,MMS Account Record Type</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Core Referral Source Record Type, HRS Referral Source Record Type, Paychex Internal Referral Account Record Type, Referral Account Record Type, Sales Channel Referral Account Record Type, Sales Partner Referral Account Record Type</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Core Referral Source Record Type, HRS Referral Source Record Type, Paychex Internal Referral Account Record Type, Referral Account Record Type, Sales Channel Referral Account Record Type, Sales Partner Referral Account Record Type</value>
        </filterItems>
        <filterItems>
            <field>$Source.Child_Count__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Prospect</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Prospect</value>
        </filterItems>
        <infoMessage>Sales Parent can not be a child of another account AND Sales Parent must have a  corresponding record type to the current account.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Child Accounts</relationshipLabel>
    <relationshipName>Sales_Parent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/PEO_Onboarding_Checklist__c.object-meta.xml
<CustomObject>
    <label>PEO Underwriting Checklist</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PEO Underwriting Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PEO Underwriting Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Parent_PEO_Checklist__c.field-meta.xml
<CustomField>
    <fullName>Parent_PEO_Checklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent PEO Checklist</label>
    <referenceTo>PEO_Onboarding_Checklist__c</referenceTo>
    <relationshipLabel>Child PEO Underwriting Checklists</relationshipLabel>
    <relationshipName>PEO_Underwriting_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Prospect_Client__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup to the related account.</description>
    <label>Prospect-Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>PEO_Onboarding_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Medical_Questionnaire__c/PEO_Onboarding_Medical_Questionnaire__c.object-meta.xml
<CustomObject>
    <label>PEO Underwriting Medical Questionnaire</label>
    <nameField>
        <displayFormat>of-{0000}</displayFormat>
        <label>PEO Underwriting Medical Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PEO Underwriting Medical Questionnaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PEO_Onboarding_Medical_Questionnaire__c/fields/Current_PEO_Carrier_if_applicable__c.field-meta.xml
<CustomField>
    <fullName>Current_PEO_Carrier_if_applicable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Current PEO Carrier(if applicable)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Medical_Questionnaire__c/fields/PEO_Onboarding_Checklist__c.field-meta.xml
<CustomField>
    <fullName>PEO_Onboarding_Checklist__c</fullName>
    <label>PEO Underwriting Checklist</label>
    <referenceTo>PEO_Onboarding_Checklist__c</referenceTo>
    <relationshipLabel>PEO Underwriting Medical Questionnaires</relationshipLabel>
    <relationshipName>PEO_Onboarding_Medical_Questionnaires</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Medical_Questionnaire__c/fields/Renewal_date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Renewal date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Medical_Questionnaire__c/fields/Use_Parent_Questionnaire_Answers__c.field-meta.xml
<CustomField>
    <fullName>Use_Parent_Questionnaire_Answers__c</fullName>
    <description>Used to determine whether questions need to be filled out for the child questionnaire or not.</description>
    <label>Use Parent Questionnaire Answers</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Carrier</fullName>
            </value>
            <value>
                <fullName>Same as Parent</fullName>
            </value>
            <value>
                <fullName>Different from Parent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TriggerSetupClasses__c/TriggerSetupClasses__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The classes that are executed as part of each trigger execution</description>
    <label>Trigger Setup Classes</label>
</CustomObject>

force-app/main/default/classes/PEOUWMedQuestionBeforeTest.cls
@IsTest
public class PEOUWMedQuestionBeforeTest {
    
    @testSetup
    public static void setup(){
        
        TriggerSetupClasses__c[] classes = new TriggerSetupClasses__c[]{};
            TriggerMethodsTest.createTriggerSetting('PEOOnboardingMedicalQuestionnaire', true, false, false, false, new String[]{'PEOUWMedQuestionBefore'}, classes, TriggerMethods.INTERFACE_C);
        insert classes;
        
        RecordTypeHelperTest.setupRecordType();
        Id acctRTMMS = RecordTypeHelper.getRecordType(RecordTypeHelper.MMS_ACCOUNT,ObjectHelper.OBJECT_ACCOUNT).getRecordTypeId();
        
        Account acc = new Account();
        acc.Name = 'Peo test';
        acc.RecordTypeId = acctRTMMS;
        insert acc;
        
        Account childAcc1 = new Account();
        childAcc1.Name = 'Peo test 2';
        childAcc1.SalesParent__c = acc.Id;
        childAcc1.RecordTypeId = acctRTMMS;
        insert childAcc1;       
        
        Contact c = new Contact(AccountId=acc.id,
                                FirstName = 'Test1',
                                LastName = 'Contact',
                                Email='testing@testing.com');
        Contact c2 = new Contact(AccountId=childAcc1.id,
                                 FirstName = 'Test2',
                                 LastName = 'Contact',
                                 Email='testing2@testing2.com');
        List<Contact> ctctList = new List<Contact>();
        ctctList.add(c);
        ctctList.add(c2);
        insert ctctList;
        
        PEO_Onboarding_Checklist__c peo = new PEO_Onboarding_Checklist__c();
        peo.Prospect_Client__c=acc.id;
        peo.Name='testing Peo';
        insert peo;
        
        PEO_Onboarding_Checklist__c peo2 = new PEO_Onboarding_Checklist__c(Parent_PEO_Checklist__c=peo.Id);
        peo2.Prospect_Client__c=acc.id;
        peo2.Name='testing Peo2';
        insert peo2;
        
        List<PEO_Onboarding_Medical_Questionnaire__c> medQuestionnaires = new List<PEO_Onboarding_Medical_Questionnaire__c>();
        PEO_Onboarding_Medical_Questionnaire__c parentQuestionnaire = new PEO_Onboarding_Medical_Questionnaire__c(PEO_Onboarding_Checklist__c=peo.Id, Renewal_date__c=System.today(), Current_PEO_Carrier_if_applicable__c='Test Carrier');
        PEO_Onboarding_Medical_Questionnaire__c childQuestionnaire = new PEO_Onboarding_Medical_Questionnaire__c(PEO_Onboarding_Checklist__c=peo2.Id);
        medQuestionnaires.add(parentQuestionnaire);
        medQuestionnaires.add(childQuestionnaire);
        insert medQuestionnaires;
    }
    
    public static testMethod void testSetParentData(){
        
        PEO_Onboarding_Checklist__c parentChecklist = [SELECT Id, Name FROM PEO_Onboarding_Checklist__c WHERE Name = 'testing Peo'];
        PEO_Onboarding_Checklist__c childChecklist = [SELECT Id, Name FROM PEO_Onboarding_Checklist__c WHERE Name = 'testing Peo2'];
        
        PEO_Onboarding_Medical_Questionnaire__c parentMQ = [SELECT Id, Name, Renewal_date__c, Current_PEO_Carrier_if_applicable__c FROM PEO_Onboarding_Medical_Questionnaire__c WHERE PEO_Onboarding_Checklist__c = :parentChecklist.Id];
        PEO_Onboarding_Medical_Questionnaire__c childMQ = [SELECT Id, Name, Renewal_date__c, Current_PEO_Carrier_if_applicable__c, Use_Parent_Questionnaire_Answers__c FROM PEO_Onboarding_Medical_Questionnaire__c WHERE PEO_Onboarding_Checklist__c = :childChecklist.Id];
        
        childMQ.Use_Parent_Questionnaire_Answers__c = 'Same as Parent';
        update childMQ;
        
        childMQ = [SELECT Id, Name, Renewal_date__c, Current_PEO_Carrier_if_applicable__c, Use_Parent_Questionnaire_Answers__c FROM PEO_Onboarding_Medical_Questionnaire__c WHERE Id = :childMQ.Id];
        
        System.assertEquals('Same as Parent', childMQ.Use_Parent_Questionnaire_Answers__c);
        //System.assertEquals(parentMQ.Renewal_date__c, childMQ.Renewal_date__c);
        //System.assertEquals(parentMQ.Current_PEO_Carrier_if_applicable__c, childMQ.Current_PEO_Carrier_if_applicable__c);
        
    }
}