force-app/main/default/objects/CustomCompactLayoutItem__mdt/CustomCompactLayoutItem__mdt.object-meta.xml
<CustomObject>
    <label>Custom Compact Layout Item</label>
    <pluralLabel>Custom Compact Layout Items</pluralLabel>
</CustomObject>

force-app/main/default/objects/CustomCompactLayoutItem__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomCompactLayoutItem__mdt/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <label>Developer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomCompactLayoutItem__mdt/fields/LookupIdField__c.field-meta.xml
<CustomField>
    <fullName>LookupIdField__c</fullName>
    <label>Lookup Id Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomCompactLayoutItem__mdt/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact</fullName>
                <default>true</default>
                <label>Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomCompactLayoutItem__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomCompactLayoutItem__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactBannerPopoverAuraService.cls
public with sharing class ContactBannerPopoverAuraService {
	@AuraEnabled
	public static List<CustomCompactLayoutItem__mdt> getCompactLayoutFields() {
		List<CustomCompactLayoutItem__mdt> compactLayoutFields = [
			SELECT Label, DeveloperName__c, Order__c, Type__c, LookupIdField__c
			FROM CustomCompactLayoutItem__mdt
			WHERE Active__c = true
			AND ObjectName__c = 'Contact'
			ORDER BY Order__c ASC
		];

		return compactLayoutFields;
	}
}