force-app/main/default/objects/Apex_Batch_Control__c/Apex_Batch_Control__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These are settings that can be used to implement some control over apex batch jobs.</description>
    <label>Apex Batch Control</label>
</CustomObject>

force-app/main/default/objects/Apex_Batch_Control__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Should the job run?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apex_Batch_Control__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <inlineHelpText>This is used by the UpdateZipOwnershipController to allow the batches to be manually launched.</inlineHelpText>
    <label>Batch Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Org_Unit__c/Org_Unit__c.object-meta.xml
<CustomObject>
    <label>Org Unit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Org Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Org_Unit__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Sales Org for this Org Unit</inlineHelpText>
    <label>Sales Org</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/Zip_Assignment__c.object-meta.xml
<CustomObject>
    <description>The Zip code assignments for the sales reps.</description>
    <label>Zip Assignment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Assignment__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The District Org Unit this zip assignment is attached to.</inlineHelpText>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Zip Assignment can only be linked to an Org Unit of type District.</errorMessage>
        <filterItems>
            <field>Org_Unit__c.Org_Type__c</field>
            <operation>equals</operation>
            <value>District</value>
        </filterItems>
        <infoMessage>Only Districts can be linked to a Zip Assignment</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Org_Unit__c</referenceTo>
    <relationshipLabel>Zip Assignments</relationshipLabel>
    <relationshipName>Zip_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/fields/DistrictNbr__c.field-meta.xml
<CustomField>
    <fullName>DistrictNbr__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The District Number for the zip code</inlineHelpText>
    <label>District Nbr</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/fields/ZipTerritory__c.field-meta.xml
<CustomField>
    <fullName>ZipTerritory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The territory this zip code is assigned to.</inlineHelpText>
    <label>Territory</label>
    <referenceTo>ZipTerritory__c</referenceTo>
    <relationshipLabel>Zip Assignments</relationshipLabel>
    <relationshipName>Zip_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZipImport__c/ZipImport__c.object-meta.xml
<CustomObject>
    <description>Object used to import zip codes</description>
    <label>Zip Import</label>
    <nameField>
        <displayFormat>Id-{00000}</displayFormat>
        <label>Import Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zip Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipImportDetail__c/ZipImportDetail__c.object-meta.xml
<CustomObject>
    <label>Zip Import Detail</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Import Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipImportDetail__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>Org_Unit__c</referenceTo>
    <relationshipLabel>Zip Import Details</relationshipLabel>
    <relationshipName>ZipImportDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZipImportDetail__c/fields/DistrictKey__c.field-meta.xml
<CustomField>
    <fullName>DistrictKey__c</fullName>
    <formula>Sales_Org__c +&quot; District &quot;+ DistrictNbr__c +&quot;, &quot;+ ZipSegmentName__c</formula>
    <label>District Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipImportDetail__c/fields/DistrictNbr__c.field-meta.xml
<CustomField>
    <fullName>DistrictNbr__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The number of the district</inlineHelpText>
    <label>District Nbr</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipImportDetail__c/fields/ImportFieldsOkay__c.field-meta.xml
<CustomField>
    <fullName>ImportFieldsOkay__c</fullName>
    <formula>AND( NOT(ISBLANK( DistrictNbr__c))
    ,NOT(ISBLANK( Sales_Org__c ))
    ,NOT(ISBLANK( Name ))
    ,NOT(ISBLANK( ZipSegmentName__c ))
    ,NOT(ISBLANK( ZipTerritoryName__c ))
   )</formula>
    <inlineHelpText>Was the required information passed in?</inlineHelpText>
    <label>Import Fields Okay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZipImportDetail__c/fields/IsSuccess__c.field-meta.xml
<CustomField>
    <fullName>IsSuccess__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Was this import successful?</inlineHelpText>
    <label>Is Success?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZipImportDetail__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipImportDetail__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This is set to true once the record is evaluated</inlineHelpText>
    <label>Processed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZipImportDetail__c/fields/Zip_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Zip_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip Assignment</label>
    <referenceTo>Zip_Assignment__c</referenceTo>
    <relationshipLabel>Zip Import Details</relationshipLabel>
    <relationshipName>ZipImportDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZipImportDetail__c/fields/ZipImport__c.field-meta.xml
<CustomField>
    <fullName>ZipImport__c</fullName>
    <label>Zip Import</label>
    <referenceTo>ZipImport__c</referenceTo>
    <relationshipLabel>Zip Import Details</relationshipLabel>
    <relationshipName>ZipImportDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZipImportDetail__c/fields/ZipSegmentName__c.field-meta.xml
<CustomField>
    <fullName>ZipSegmentName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip Segment Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipImportDetail__c/fields/ZipTerritory__c.field-meta.xml
<CustomField>
    <fullName>ZipTerritory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip Territory</label>
    <referenceTo>ZipTerritory__c</referenceTo>
    <relationshipLabel>Zip Import Details</relationshipLabel>
    <relationshipName>ZipImportDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZipImportDetail__c/fields/ZipTerritoryName__c.field-meta.xml
<CustomField>
    <fullName>ZipTerritoryName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of the territory</inlineHelpText>
    <label>Zip Territory Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipImportDetail__c/fields/ZipTerritoryOld__c.field-meta.xml
<CustomField>
    <fullName>ZipTerritoryOld__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The previous zip territory (before the move).</inlineHelpText>
    <label>Zip Territory Old</label>
    <referenceTo>ZipTerritory__c</referenceTo>
    <relationshipLabel>Zip Import Details-Old</relationshipLabel>
    <relationshipName>ZipImportDetails_Old</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZipTerritory__c/ZipTerritory__c.object-meta.xml
<CustomObject>
    <description>The Zip Code Territories by District</description>
    <label>Zip Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Territories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipTerritory__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <inlineHelpText>The district for this territory</inlineHelpText>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>A territory must be attached to a District</errorMessage>
        <filterItems>
            <field>Org_Unit__c.Org_Type__c</field>
            <operation>equals</operation>
            <value>District</value>
        </filterItems>
        <infoMessage>District</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Org_Unit__c</referenceTo>
    <relationshipLabel>Zip Territories</relationshipLabel>
    <relationshipName>Zip_Territories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZipTerritory__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>District__r.Sales_Org__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZipInsertBatch.cls
/* 
 * Batch process to import zip code update information
 *
 * History
 * -------
   03/13/2015 Dan Carmen   Created
   09/05/2023 Dan Carmen   Add launchBatch method
   02/09/2024 Dan Carmen   Extra check for creating a change record

 */
global without sharing class ZipInsertBatch implements Database.Batchable<SObject>, Database.Stateful , Schedulable {
    
   public static final String CLASSNAME='ZipInsertBatch';

   // The number of distinct zip insert records processed. */
   global Integer numberZipInserts = 0;
   
   global Integer numberNotSuccess = 0;

   /** Keep track of totals by district number and sales org/segment name */
   global Map<String,Integer> changeByDistrictMap = new Map<String,Integer>();
   
   global String batchMsg = '';
   
   global Set<Id> zipImportIdSet = new Set<Id>();

   global JobHelper jh = new JobHelper(CLASSNAME);

   // The maximum number of records to retrieve at once. 
   //public static Integer BATCH_SIZE=1000;
   
   // Query the batches to be processed.
   global Database.QueryLocator start(Database.BatchableContext BC){
      // save the record - show that the job started
      jh.setStarted();
      // for normal running
      return Database.getQueryLocator([SELECT Id
                                             ,Name
                                             ,District__c
                                             ,District__r.Id
                                             ,DistrictKey__c
                                             ,DistrictNbr__c
                                             ,ImportFieldsOkay__c
                                             ,IsSuccess__c
                                             ,Notes__c
                                             ,Processed__c
                                             ,Sales_Org__c
                                             ,Zip_Assignment__c
                                             ,Zip_Assignment__r.Id
                                             ,ZipImport__c
                                             ,ZipSegmentName__c
                                             ,ZipTerritory__c
                                             ,ZipTerritory__r.Id
                                             ,ZipTerritoryName__c
                                             ,ZipTerritoryOld__c
                                             ,ZipTerritoryOld__r.Id
                                         FROM ZipImportDetail__c
                                        WHERE Processed__c = false
                                        ORDER BY Name]);
   } // start

   // In order to schedule a batch run
   global void execute(SchedulableContext sc) {
      launchBatch();
   } // execute

   global void execute(Database.BatchableContext BC, List<SObject> scope) {
      List<ZipImportDetail__c> zips = (List<ZipImportDetail__c>)scope;
      System.debug('ZipBatch number of zips='+zips.size());
      numberZipInserts += zips.size();
      
      processZips(zips);
      
      ErrorLog.checkSave();
   } // execute
   
   private void processZips(List<ZipImportDetail__c> zips) {
   	Boolean okayToContinue = ZipInsertMethods.checkDistrict(zips);
   	if (okayToContinue) {
   	   List<Zip_Assignment__c> updateZas = new List<Zip_Assignment__c>();
   	   List<ZipImportDetail__c> checkZipDetailInsert = new List<ZipImportDetail__c>();
   	   List<Zip_Assignment__c> insertZas = new List<Zip_Assignment__c>();
         okayToContinue = ZipInsertMethods.findZipAssignments(zips, updateZas, checkZipDetailInsert, insertZas);
         if (okayToContinue) {
         	if (!updateZas.isEmpty()) {
               ZipAssignment.SKIP_TRIGGER=false;
               DmlHelper.performDML2(updateZas, DmlHelper.DML_UPDATE, 'ZipInsertBatch', 'processZips', 'Update Zip Assigns', false); 
         	} // if (!updateZas.isEmpty
         	
            if (!insertZas.isEmpty()) {
               ZipAssignment.SKIP_TRIGGER=false;
               DmlHelper.performDML2(insertZas, DmlHelper.DML_INSERT, 'ZipInsertBatch', 'processZips', 'Insert Zip Assigns', false); 
               
            } // if (!insertZas.isEmpty()
            
            if (!checkZipDetailInsert.isEmpty()) {
               for (ZipImportDetail__c zipDetail : checkZipDetailInsert) {
                  if (zipDetail.Zip_Assignment__r != null) {
                     zipDetail.Zip_Assignment__c = zipDetail.Zip_Assignment__r.Id;
                     zipDetail.Zip_Assignment__r = null;
                  }
               } // for (ZipImportDetail
            } // if (!checkZipDetailInsert.isEmpty()
            
         } // if (okayToContinue
   	} // if (okayToContinue
      
      addToTotal(zips);
      
      DmlHelper.performDML2(zips, DmlHelper.DML_UPDATE, 'ZipInsertBatch', 'processZips', 'Update ZipImportDetail__c', false); 
   } // processZips
   
   private void addToTotal(List<ZipImportDetail__c> zips) {
   	for (ZipImportDetail__c zipDetail : zips) {
   		zipImportIdSet.add(zipDetail.ZipImport__c);

         if (zipDetail.ZipTerritory__r != null) {
            zipDetail.ZipTerritory__c = zipDetail.ZipTerritory__r.Id;
            zipDetail.ZipTerritory__r = null;
         }

         if (zipDetail.ZipTerritory__c != null) {
            Integer nbrChanges = changeByDistrictMap.get(zipDetail.DistrictKey__c);
            if (nbrChanges == null) {
               nbrChanges = 1;
            } else {
               nbrChanges++;
            }
            changeByDistrictMap.put(zipDetail.DistrictKey__c,nbrChanges);
         } else {
            // if no territory, not successful
            numberNotSuccess++;
         }
   	} // for (ZipImportDetail__c
   } // addToTotal
   
   
   global void finish(Database.BatchableContext BC){
      ErrorLog.checkSave();
      
      // Get the ID of the AsyncApexJob representing this batch job
      String message = '\nTotal Changes Processed: '+numberZipInserts;
      message += '\nNumber Success: '+(numberZipInserts-numberNotSuccess);
      message += '\nNumber Failed: '+numberNotSuccess;
      
      /*
      message += ' \n\n Total Accounts updated='+totalChanges.Accounts_Updated__c;
      message += ' \n Total Contacts updated='+totalChanges.Contacts_Updated__c;
      message += ' \n Total Leads updated='+totalChanges.Leads_Updated__c;
      message += ' \n Total Referral Accounts updated='+totalChanges.Referral_Accounts_Updated__c;
      message += ' \n Total Referral Contacts updated='+totalChanges.Referral_Contacts_Updated__c+'\n';
      */

      for (String districtInfo : changeByDistrictMap.keySet()) {
         Integer nbrChanges = changeByDistrictMap.get(districtInfo);
            message += ' \n For '+districtInfo+', Nbr Changes: '+nbrChanges;
      } // for (String districtInfo

      message += '\n'+batchMsg;
      
      jh.completeJob(bc, 'Zip File Insert', message);

      ZipInsertMethods.processCompleteZipImports(zipImportIdSet);
   } // finish
    
   public static void launchBatch() {
      Apex_Batch_Control__c abc = Apex_Batch_Control__c.getInstance(CLASSNAME);
      if (abc != null && abc.Active__c) {
         //Integer batchSize = (abc.BatchSize__c != null ? Integer.valueOf(abc.BatchSize__c) : 500);
         //Database.executeBatch(new ZipInsertBatch(), batchSize);
         JobHelper.launchBatchWithSchedule(new ZipInsertBatch(), CLASSNAME, Datetime.now(), 1);
      }

   } // launchBatch

} // class ZipInsertBatch