force-app/main/default/objects/Apex_Batch_Control__c/Apex_Batch_Control__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These are settings that can be used to implement some control over apex batch jobs.</description>
    <label>Apex Batch Control</label>
</CustomObject>

force-app/main/default/objects/Apex_Batch_Control__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <inlineHelpText>This is used by the UpdateZipOwnershipController to allow the batches to be manually launched.</inlineHelpText>
    <label>Batch Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter district number as a 3 digit number with leading zero</inlineHelpText>
    <label>District</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/HR_Person_Id__c.field-meta.xml
<CustomField>
    <fullName>HR_Person_Id__c</fullName>
    <description>The Person Id from HR</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Person Id from HR</inlineHelpText>
    <label>HR Person Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org-Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>BenAdmin</fullName>
            </value>
            <value>
                <fullName>Benetrac</fullName>
            </value>
            <value>
                <fullName>BusDev</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Relations</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Center</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise Service Center</fullName>
            </value>
            <value>
                <fullName>ESR</fullName>
            </value>
            <value>
                <fullName>EW</fullName>
            </value>
            <value>
                <fullName>Field Operations Core</fullName>
            </value>
            <value>
                <fullName>HNBF</fullName>
            </value>
            <value>
                <fullName>HROI</fullName>
            </value>
            <value>
                <fullName>HR Online</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>HRS 401K-S125</fullName>
            </value>
            <value>
                <fullName>HRS Premier</fullName>
            </value>
            <value>
                <fullName>Icon</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Merchant Services</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MMS Hub</fullName>
            </value>
            <value>
                <fullName>MPSC</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/Zip_Assignment__c.object-meta.xml
<CustomObject>
    <description>The Zip code assignments for the sales reps.</description>
    <label>Zip Assignment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Assignment__c/fields/CreateChangeRecord__c.field-meta.xml
<CustomField>
    <fullName>CreateChangeRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to force the creation of a change record.</description>
    <label>Create Change Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The District Org Unit this zip assignment is attached to.</inlineHelpText>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Zip Assignment can only be linked to an Org Unit of type District.</errorMessage>
        <filterItems>
            <field>Org_Unit__c.Org_Type__c</field>
            <operation>equals</operation>
            <value>District</value>
        </filterItems>
        <infoMessage>Only Districts can be linked to a Zip Assignment</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Org_Unit__c</referenceTo>
    <relationshipLabel>Zip Assignments</relationshipLabel>
    <relationshipName>Zip_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/fields/HR_Person_Id__c.field-meta.xml
<CustomField>
    <fullName>HR_Person_Id__c</fullName>
    <description>The unique identifier of the sales rep from the HR system</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The unique identifier of the sales rep from the HR system</inlineHelpText>
    <label>HR Person Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/fields/NeedsUpdate__c.field-meta.xml
<CustomField>
    <fullName>NeedsUpdate__c</fullName>
    <formula>AND( (ZipTerritory__c != null)
     ,OR( (User__c !=  ZipTerritory__r.TerritoryRep__c )
       ,( District__c !=  ZipTerritory__r.District__c )
       ,( ZipTerritory__r.TerritoryRep__c != null &amp;&amp; HR_Person_Id__c !=  ZipTerritory__r.TerritoryRep__r.HR_Person_Id__c )
       ,( ZipTerritory__r.TerritoryRep__c != null &amp;&amp; ZipTerritory__r.TerritoryRep__r.IsActive = false)
  ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If the zip assignment differs from the zip territory in a few key aspects we&apos;ll mark it as needing to be updated.</inlineHelpText>
    <label>Needs Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/fields/Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Rep_Name__c</fullName>
    <description>The name of the Sales Rep</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the Sales Rep</inlineHelpText>
    <label>Rep Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <description>The Sales Office Number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Sales Office Number</inlineHelpText>
    <label>Sales Office*</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the User record.</description>
    <inlineHelpText>Lookup to the User record.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Zip_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/fields/Zip_Code_Information__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip Code Information</label>
    <referenceTo>Zip_Code_Information__c</referenceTo>
    <relationshipLabel>Zip Assignments</relationshipLabel>
    <relationshipName>Zip_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zip_Assignment__c/fields/ZipTerritory__c.field-meta.xml
<CustomField>
    <fullName>ZipTerritory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The territory this zip code is assigned to.</inlineHelpText>
    <label>Territory</label>
    <referenceTo>ZipTerritory__c</referenceTo>
    <relationshipLabel>Zip Assignments</relationshipLabel>
    <relationshipName>Zip_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zip_Segment__c/Zip_Segment__c.object-meta.xml
<CustomObject>
    <description>The Zip Code segmentation information.</description>
    <label>Zip Segment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Segment__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sales Org</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipTerritory__c/ZipTerritory__c.object-meta.xml
<CustomObject>
    <description>The Zip Code Territories by District</description>
    <label>Zip Territory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Territories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipTerritory__c/fields/CheckZipUser__c.field-meta.xml
<CustomField>
    <fullName>CheckZipUser__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this to evaluate the zip codes attached to the territory - to make sure the user matches the territory.</inlineHelpText>
    <label>Check Zip User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZipTerritory__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <inlineHelpText>The district for this territory</inlineHelpText>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>A territory must be attached to a District</errorMessage>
        <filterItems>
            <field>Org_Unit__c.Org_Type__c</field>
            <operation>equals</operation>
            <value>District</value>
        </filterItems>
        <infoMessage>District</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Org_Unit__c</referenceTo>
    <relationshipLabel>Zip Territories</relationshipLabel>
    <relationshipName>Zip_Territories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ZipTerritory__c/fields/HR_Person_Id__c.field-meta.xml
<CustomField>
    <fullName>HR_Person_Id__c</fullName>
    <formula>TerritoryRep__r.HR_Person_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HR Person Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipTerritory__c/fields/Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Rep_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Rep Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipTerritory__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <formula>District__r.Sales_Org__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Org</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipTerritory__c/fields/Territory_Nbr__c.field-meta.xml
<CustomField>
    <fullName>Territory_Nbr__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The number of the territory</inlineHelpText>
    <label>Territory Nbr</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipTerritory__c/fields/TerritoryContact__c.field-meta.xml
<CustomField>
    <fullName>TerritoryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If a non-Salesforce user is the contact for this territory, link them to the territory here.</inlineHelpText>
    <label>Territory Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must select a contact linked to the Paychex Inc SA prospect-client record.</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>equals</operation>
            <value>Paychex Inc SA</value>
        </filterItems>
        <filterItems>
            <field>Contact.HR_Person_Id__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <infoMessage>Contact must be linked to the Paychex Inc SA prospect-client record.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Zip Territories</relationshipLabel>
    <relationshipName>Zip_Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ZipTerritory__c/fields/TerritoryRep__c.field-meta.xml
<CustomField>
    <fullName>TerritoryRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The territory rep</inlineHelpText>
    <label>Territory Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Zip_Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ZipTerritoryQueueable.cls
/* 
   Update the zip assignments attached to a territory
     
   History
   -------
   05/25/2021 Dan Carmen   Created
   02/08/2024 Dan Carmen   Try to force the change record creation

 */
public class ZipTerritoryQueueable implements Queueable {
    
   public static final String CLASSNAME='ZipTerritoryQueueable';
    
   public Set<Id> territoryIdSet;
    
   public ZipTerritoryQueueable(Set<Id> p_territoryIdSet) {
      territoryIdSet = p_territoryIdSet;
   } // ZipTerritoryQueueable
    
   public void execute(QueueableContext context) {
      processRecs();
   } // execute

   public void processRecs() {
      JobHelper jh = new JobHelper(CLASSNAME);
      Apex_Batch_Control__c abc = getBatchControl();
      // what's the maximum number of records we want to process before re-running?
      Integer recLimit = (abc != null && abc.BatchSize__c != null ? Integer.valueOf(abc.BatchSize__c) : 1000);
       
      System.debug('processRecs territoryIdSet='+territoryIdSet.size()+' recLimit='+recLimit);

      Integer zipRetrieved = 0;
       
      Map<Id,ZipTerritory__c> territoryMap = ZipTerritoryQueueable.getTerritoryMap(territoryIdSet);
      
      for (Zip_Assignment__c[] zipAssigns : [Select Id, Name
                                                   ,CreateChangeRecord__c
                                                   ,District__c
                                                   ,HR_Person_Id__c
                                                   ,Rep_Name__c
                                                   ,Sales_Office__c
                                                   ,Sales_Org__c
                                                   ,User__c
                                                   ,Zip_Code_Information__c
                                                   ,ZipTerritory__c
                                               From Zip_Assignment__c
                                              Where ZipTerritory__c in :territoryMap.keySet()
                                                and NeedsUpdate__c = true
                                                limit :recLimit
                                             ]) {
         zipRetrieved += zipAssigns.size();
         System.debug('processRecs zipRetrieved='+zipRetrieved);
         Zip_Assignment__c[] updateZipAssignments = new Zip_Assignment__c[]{};
         for (Zip_Assignment__c za : zipAssigns) {
            ZipTerritory__c territory = territoryMap.get(za.ZipTerritory__c);
            if (territory != null) {
                if (checkZaUpdate(territory, za)) {
                  updateZipAssignments.add(za);
                }
            } else {
                // if we didn't retrieve a territory, remove it from the set so we don't try to process it again.
                System.debug('processRecs territoryId not found: '+za.ZipTerritory__c);
                territoryIdSet.remove(za.ZipTerritory__c);
            } // if (territory != null
            
         } // for (Zip_Assignment__c za
         // make sure the triggers fire
         ZipAssignment.SKIP_TRIGGER=false;
         DmlHelper.performDML2(updateZipAssignments, DmlHelper.DML_UPDATE, CLASSNAME, 'processRecs', 'Update Zip Assignments', false);
      } // for (Zip_Assignment__c[] zipAssigns
      
      ErrorLog.checkSave();
      jh.tracker.Nbr_Batches__c = zipRetrieved;
      jh.completeJob(CLASSNAME, 'Number of Territories='+territoryMap.size()+' zipRetrieved='+zipRetrieved+' recLimit='+recLimit);
       
      System.debug('processRecs end of method zipRetrieved='+zipRetrieved);
      // if we've hit the limit then that means there are probably still more to process
      if (zipRetrieved >= recLimit) {
         launchQueueable(territoryIdSet, System.isQueueable());
      }
   } // processRecs
    
   // get all of the territories with rep information.
   public static Map<Id,ZipTerritory__c> getTerritoryMap(Set<Id> p_territoryIdSet) {
      // only select the territories with an active rep.
      Map<Id,ZipTerritory__c> territoryMap = new Map<Id,ZipTerritory__c>([Select Id, Name, CheckZipUser__c, District__c
                                                                                ,Rep_Name__c, Sales_Org__c
                                                                                ,TerritoryContact__c, Territory_Nbr__c
                                                                                ,TerritoryRep__c
                                                                                ,TerritoryRep__r.Id, TerritoryRep__r.Name
                                                                                ,TerritoryRep__r.HR_Person_Id__c
                                                                                ,TerritoryRep__r.SalesOfficeNumber__c
                                                                                ,Zip_Segment__c
                                                                            from ZipTerritory__c
                                                                           Where Id in :p_territoryIdSet
                                                                             and TerritoryOkay__c=true]);
      return territoryMap;
   } // getTerritoryMap
    
   public static Boolean checkZaUpdate(ZipTerritory__c territory, Zip_Assignment__c za) {
      Boolean updated = false;
      if (za.Rep_Name__c != territory.Rep_Name__c) {
         za.Rep_Name__c = territory.Rep_Name__c;
         updated = true;
      }
      if (za.User__c != territory.TerritoryRep__c) {
         za.User__c = territory.TerritoryRep__c;
         za.CreateChangeRecord__c = true;
         updated = true;
      }
      if (territory.TerritoryRep__c != null) {
         if (territory.TerritoryRep__r != null && (za.HR_Person_Id__c != territory.TerritoryRep__r.HR_Person_Id__c 
                                                   || za.Sales_Office__c != territory.TerritoryRep__r.SalesOfficeNumber__c)
            ) {
            za.HR_Person_Id__c = territory.TerritoryRep__r.HR_Person_Id__c;
            za.Sales_Office__c = territory.TerritoryRep__r.SalesOfficeNumber__c;
            updated = true;
         }
      } else {
         za.HR_Person_Id__c = null;
         za.Sales_Office__c = null;
         updated = true;
      } // if (territory.TerritoryRep__c
               
      if (za.District__c != territory.District__c) {
         za.District__c = territory.District__c;
         updated = true;
      }
      return updated;
   } // checkZaUpdate
    
   public static void launchQueueable(Set<Id> p_territoryIdSet, Boolean forceRelaunch){
      if (!p_territoryIdSet.isEmpty()) {
         Apex_Batch_Control__c abc = getBatchControl();
         System.debug('checkLaunchQueuable p_territoryIdSet='+p_territoryIdSet.size()+' abc='+abc);
         // we won't using this command during a test
         Boolean abcIsActive = (abc != null && abc.Active__c);
         ZipTerritoryQueueable ztq = new ZipTerritoryQueueable(p_territoryIdSet);
         Boolean allowFuture = Utilities.allowFuture();
         System.debug('checkLaunchQueuable abcIsActive='+abcIsActive+' forceRelaunch='+forceRelaunch+' allowFuture='+allowFuture);
         if (abcIsActive && (forceRelaunch || allowFuture)) {
            System.enqueueJob(ztq);
         } else {
            // run it inline
            System.debug('checkLaunchQueuable launching inline');
            ztq.processRecs();
         }
      } // if (!p_territoryIdSet.isEmpty
    } // launchQueueable

   public static Apex_Batch_Control__c getBatchControl() {
      Apex_Batch_Control__c abc = Apex_Batch_Control__c.getInstance(CLASSNAME);
      return abc;
   } // getBatchControl

} // class ZipTerritoryQueueable