force-app/main/default/objects/Apex_Batch_Control__c/Apex_Batch_Control__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These are settings that can be used to implement some control over apex batch jobs.</description>
    <label>Apex Batch Control</label>
</CustomObject>

force-app/main/default/objects/Apex_Batch_Control__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <inlineHelpText>This is used by the UpdateZipOwnershipController to allow the batches to be manually launched.</inlineHelpText>
    <label>Batch Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_Batch_Control__c/fields/ProcessNotes__c.field-meta.xml
<CustomField>
    <fullName>ProcessNotes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Notes on processing</inlineHelpText>
    <label>Process Notes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Tracker__c/Job_Tracker__c.object-meta.xml
<CustomObject>
    <description>Track the status and output for Apex batch jobs.</description>
    <label>Job Tracker</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Tracker Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Tracker__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The output for this apex job.</inlineHelpText>
    <label>Notes</label>
    <length>15000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/PurgeControl__c.object-meta.xml
<CustomObject>
    <description>Control the purge of data from different objects within Salesforce</description>
    <label>Purge Control</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Purge Control Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purge Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurgeControl__c/fields/AdditionalPurgeCriteria__c.field-meta.xml
<CustomField>
    <fullName>AdditionalPurgeCriteria__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Is there any additional criteria beyond the number of days?</inlineHelpText>
    <label>Additional Purge Criteria</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/AlwaysEmail__c.field-meta.xml
<CustomField>
    <fullName>AlwaysEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>For the process check, do we always email these results?</inlineHelpText>
    <label>Always Email?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/Archive__c.field-meta.xml
<CustomField>
    <fullName>Archive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Archive?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/ArchiveFrequency__c.field-meta.xml
<CustomField>
    <fullName>ArchiveFrequency__c</fullName>
    <label>ArchiveFrequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <inlineHelpText>The number of records to process at a time</inlineHelpText>
    <label>Batch Size</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/BusinessHoursOnly__c.field-meta.xml
<CustomField>
    <fullName>BusinessHoursOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Does this only run during business hours (used for process checker)?</inlineHelpText>
    <label>Business Hours Only?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/CheckApexClass__c.field-meta.xml
<CustomField>
    <fullName>CheckApexClass__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>During the ProcessChecker, are we going to run a separate Apex class instead of inline logic?</inlineHelpText>
    <label>Check Apex Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/CheckRecycleBin__c.field-meta.xml
<CustomField>
    <fullName>CheckRecycleBin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Checked, will add &apos;ALL ROWS&apos; to the end of the SOQL statement to search the recycle bin. Useful for looking for recently deleted records.</description>
    <inlineHelpText>If Checked, will add &apos;ALL ROWS&apos; to the end of the SOQL statement to search the recycle bin. Useful for looking for recently deleted records.</inlineHelpText>
    <label>Check Recycle Bin?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/DateFieldToCheck__c.field-meta.xml
<CustomField>
    <fullName>DateFieldToCheck__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the date field to check.</inlineHelpText>
    <label>Date Field To Check</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/DaysToRun__c.field-meta.xml
<CustomField>
    <fullName>DaysToRun__c</fullName>
    <inlineHelpText>Which days of the week do we want this process to run?</inlineHelpText>
    <label>Days To Run</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/EmailBody__c.field-meta.xml
<CustomField>
    <fullName>EmailBody__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>If there&apos;s anything extra to add to the email body for this notification</inlineHelpText>
    <label>Email Body</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/EmailNotification__c.field-meta.xml
<CustomField>
    <fullName>EmailNotification__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>A comma separated list of people we should notify if we don&apos;t meet the criteria of the process check</inlineHelpText>
    <label>Email Notification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/EmailSubject__c.field-meta.xml
<CustomField>
    <fullName>EmailSubject__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The subject of the email sent by the process checker</inlineHelpText>
    <label>Email Subject</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this purge job active?</inlineHelpText>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/LatestQuery__c.field-meta.xml
<CustomField>
    <fullName>LatestQuery__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The latest query performed for data</inlineHelpText>
    <label>Latest Query</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/MoreRecords__c.field-meta.xml
<CustomField>
    <fullName>MoreRecords__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Are there more records to purge?</inlineHelpText>
    <label>More Records?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/NbrDaysToKeep__c.field-meta.xml
<CustomField>
    <fullName>NbrDaysToKeep__c</fullName>
    <inlineHelpText>The number of days of data to keep. Anything older will be purged.</inlineHelpText>
    <label>Nbr Days To Keep</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/NbrMinutesToQuery__c.field-meta.xml
<CustomField>
    <fullName>NbrMinutesToQuery__c</fullName>
    <inlineHelpText>For the Process Check, how many minutes back in time are we querying for?</inlineHelpText>
    <label>Nbr Minutes To Query</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/Next_Archive_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Archive_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Next Archive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/NextRunDays__c.field-meta.xml
<CustomField>
    <fullName>NextRunDays__c</fullName>
    <inlineHelpText>The number of days until the next run. Can be used in conjunction with Time of Day To Run or Next Run Interval (minutes).</inlineHelpText>
    <label>Next Run Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/NextRunInterval__c.field-meta.xml
<CustomField>
    <fullName>NextRunInterval__c</fullName>
    <inlineHelpText>Once this run completes, how many minutes until the next time this runs?</inlineHelpText>
    <label>Next Run Interval (minutes)</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/NextRunTime__c.field-meta.xml
<CustomField>
    <fullName>NextRunTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>When is the next time this process will run?</inlineHelpText>
    <label>Next Run Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/ObjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPIName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Object API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/PermanentlyDelete__c.field-meta.xml
<CustomField>
    <fullName>PermanentlyDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Do we want to permanently delete these records (remove them from the recycle bin)?</inlineHelpText>
    <label>Permanently Delete *DO NOT USE*</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/ProcessCheckMaxRecs__c.field-meta.xml
<CustomField>
    <fullName>ProcessCheckMaxRecs__c</fullName>
    <inlineHelpText>For the Process Check, the maximum number of records we should be finding.</inlineHelpText>
    <label>Process Check Max Recs</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/ProcessCheckMinRecs__c.field-meta.xml
<CustomField>
    <fullName>ProcessCheckMinRecs__c</fullName>
    <inlineHelpText>For the Process Check the minimum number of records we should be finding</inlineHelpText>
    <label>Process Check Min Recs</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/ProcessNotes__c.field-meta.xml
<CustomField>
    <fullName>ProcessNotes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Process Notes</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>Process Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purge Only</fullName>
            </value>
            <value>
                <fullName>Purge and Archive</fullName>
            </value>
            <value>
                <fullName>Data Check Only</fullName>
            </value>
            <value>
                <fullName>Empty Recycle Bin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/RelaunchBatch__c.field-meta.xml
<CustomField>
    <fullName>RelaunchBatch__c</fullName>
    <formula>AND(IsActive__c = true
, OR(ISPICKVAL(ProcessType__c,&apos;Purge Only&apos;),ISPICKVAL(ProcessType__c,&apos;Purge and Archive&apos;))
,OR (ISBLANK(LatestRunDate__c)
,LatestRunDate__c &lt; TODAY()
,MoreRecords__c = true))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Do we relaunch the batch process?</inlineHelpText>
    <label>Relaunch Batch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/TimeOfDayToRun__c.field-meta.xml
<CustomField>
    <fullName>TimeOfDayToRun__c</fullName>
    <inlineHelpText>Instead of providing a run interval, if we want this to run at the same time every day, provide that time here.</inlineHelpText>
    <label>Time Of Day To Run</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/PurgeControl__c/fields/TotalNbrRecordsPurged__c.field-meta.xml
<CustomField>
    <fullName>TotalNbrRecordsPurged__c</fullName>
    <inlineHelpText>Number of records purged</inlineHelpText>
    <label>Total Nbr Records Purged</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProcessChecker.cls
/* 
 * A batch job to run checks on objects to see if they're being used.
 * 
        Database.executeBatch(new ProcessChecker(), 1);

  replace PartnerReferralMonitor, BatchJobChecker

 *
 * History
 * -------
   01/14/2019 Dan Carmen        Created
   09/04/2020 Dan Carmen        Update code so it works properly.
   01/22/2021 Dan Carmen        Add option to permanently delete 
   04/22/2021 Dan Carmen        Change launchBatch method
   08/10/2022 Justin Stouffer   Add option to check recycle bin
 */
global with sharing class ProcessChecker implements Database.Batchable<SObject>, Database.Stateful , Schedulable {

   global static final String CLASSNAME='ProcessChecker';
   // which process types does this process run for?
   global static String[] PROCESS_TYPES = new String[]{'Data Check Only'};
   
   // The total number of purge records found.
   global Integer numberPurges = 0;
   // The total number processes that we found that were outside of the acceptable range.
   global Integer numberOutsideRange = 0;
   /** The time the process started. */
   global DateTime startTime;
   
   // messages that occur during the process. 
   global String processNotes = '';
   
   global JobHelper jh = new JobHelper(CLASSNAME);
   
   global ProcessChecker() {
      startTime = DateTime.now();
   } // UserUpdateFromContact
   
   global String[] processMsgs = new String[]{};

   global String msgExtra = '';
    
   global Database.QueryLocator start(Database.BatchableContext BC){
       
      String instanceName = Utilities.checkForProduction();
      if (String.isNotBlank(instanceName)) {
         msgExtra = 'This was running in the '+instanceName+' instance. \n\n';
      }

      // save the record - show that the job started
      jh.setStarted();
      return getDataLocator(PROCESS_TYPES);
   } // start

   global static Database.QueryLocator getDataLocator(String[] processTypes){
       
      return Database.getQueryLocator([SELECT id, Name
                                             ,AdditionalPurgeCriteria__c
                                             ,AlwaysEmail__c
                                             //,Archive__c
                                             //,ArchiveFrequency__c
                                             ,BatchSize__c
                                             ,BusinessHoursOnly__c
                                             ,CheckApexClass__c
                                             ,CheckRecycleBin__c
                                             ,DateFieldToCheck__c
                                             ,DaysToRun__c
                                             ,EmailBody__c
                                             ,EmailNotification__c
                                             ,EmailSubject__c
                                             ,IsActive__c
                                             ,LatestQuery__c
                                             ,MoreRecords__c
                                             ,NbrDaysToKeep__c
                                             ,NbrMinutesToQuery__c
                                             //,Next_Archive_Date__c
                                             ,NextRunDays__c
                                             ,NextRunInterval__c
                                             ,NextRunTime__c
                                             ,Notes__c
                                             ,ObjectAPIName__c
                                             ,PermanentlyDelete__c
                                             ,ProcessCheckMinRecs__c
                                             ,ProcessCheckMaxRecs__c
                                             ,ProcessNotes__c
                                             ,ProcessType__c
                                             ,RelaunchBatch__c 
                                             ,TimeOfDayToRun__c
                                             ,TotalNbrRecordsPurged__c
                                             // only pull the latest tracker record to see if we reuse based on purge date 
                                             ,(Select Id
                                                     ,EndDate__c
                                                     ,NbrFailed__c
                                                     ,NbrFound__c
                                                     ,NbrIterations__c
                                                     ,NbrRecsPurged__c
                                                     ,OutsideRange__c
                                                     ,PurgeDate__c
                                                     ,SecondsProcessed__c
                                                     ,StartDate__c
                                                 From PurgeControlTrackers__r
                                                order by CreatedDate desc limit 1 )
                                         FROM PurgeControl__c 
                                        WHERE IsActive__c = true
                                          AND ProcessType__c in :processTypes
                                          AND (NextRunTime__c=null OR NextRunTime__c <= :Datetime.now())
                                       order by NextRunTime__c ASC]);
   } // getDataLocator

   // get a single record to process that can be run anytime. Get the oldest record that meets the criteria
   global static PurgeControl__c getAnyTimeRecord(String[] processTypes){
       
      PurgeControl__c[] pcs = [SELECT id, Name
                                             ,AdditionalPurgeCriteria__c
                                             ,AlwaysEmail__c
                                             //,Archive__c
                                             //,ArchiveFrequency__c
                                             ,BatchSize__c
                                             ,BusinessHoursOnly__c
                                             ,CheckApexClass__c
                                             ,CheckRecycleBin__c
                                             ,DateFieldToCheck__c
                                             ,DaysToRun__c
                                             ,EmailBody__c
                                             ,EmailNotification__c
                                             ,EmailSubject__c
                                             ,IsActive__c
                                             ,LatestQuery__c
                                             ,MoreRecords__c
                                             ,NbrDaysToKeep__c
                                             ,NbrMinutesToQuery__c
                                             //,Next_Archive_Date__c
                                             ,NextRunDays__c
                                             ,NextRunInterval__c
                                             ,NextRunTime__c
                                             ,Notes__c
                                             ,ObjectAPIName__c
                                             ,PermanentlyDelete__c
                                             ,ProcessCheckMinRecs__c
                                             ,ProcessCheckMaxRecs__c
                                             ,ProcessNotes__c
                                             ,ProcessType__c
                                             ,RelaunchBatch__c
                                             ,TimeOfDayToRun__c
                                             ,TotalNbrRecordsPurged__c
                                             // only pull the latest tracker record to see if we reuse based on purge date 
                                             ,(Select Id
                                                     ,EndDate__c
                                                     ,NbrFailed__c
                                                     ,NbrFound__c
                                                     ,NbrIterations__c
                                                     ,NbrRecsPurged__c
                                                     ,OutsideRange__c
                                                     ,PurgeDate__c
                                                     ,SecondsProcessed__c
                                                     ,StartDate__c
                                                 From PurgeControlTrackers__r
                                                order by CreatedDate desc limit 1 )
                                         FROM PurgeControl__c 
                                        WHERE IsActive__c = true
                                          AND ProcessType__c in :processTypes
                                          AND AllowRunAnytime__c = true
                                       ORDER BY LastModifiedDate Asc ];
      return (pcs.size() > 0 ? pcs[0] : null);
   } // getAnyTimeRecord

   // In order to schedule a batch run
   global void execute(SchedulableContext sc) {
      launchBatch();
   } // execute

   // Execute a batch.
   global void execute(Database.BatchableContext BC, List<SObject> scope){
      List<PurgeControl__c> purges = (List<PurgeControl__c>)scope;
      numberPurges += purges.size();
      PurgeControlTracker__c[] insertTrackers = new PurgeControlTracker__c[]{};
      PurgeControlTracker__c[] updateTrackers = new PurgeControlTracker__c[]{};
      Messaging.SingleEmailMessage[] emails = new Messaging.SingleEmailMessage[]{};
      
      for (PurgeControl__c pc : purges) {
         PurgeControlTracker__c pcd = getTracker(pc, Date.today(), insertTrackers, updateTrackers);
         if (String.isNotBlank(pc.CheckApexClass__c)) {
            try {
               Type t = Type.forName(pc.CheckApexClass__c);
               BatchControlInterface batchInstance = (BatchControlInterface)t.newInstance();
               Boolean success = batchInstance.handleProcessCheck(pc, pcd,emails, processMsgs);
               numberOutsideRange = numberOutsideRange + (!success ? 1 : 0);
            } catch  (Exception e) {
               pc.IsActive__c = false;
               String exMessage = pc.Name+' Exception instantiating class '+pc.CheckApexClass__c+': '+e.getMessage()+'; '+e.getStackTraceString();
               StringHelper.addToProcessNotes(pc, exMessage);
               processMsgs.add(exMessage);
               numberOutsideRange++;
            }
         } else {
            handleProcessCheck(pc,pcd, emails);
         }
         setNextRunTime(pc);
      } // for (PurgeControl__c pc
      
      System.debug('execute purges='+purges.size()+' insertTrackers='+insertTrackers.size()+' updateTrackers='+updateTrackers.size());
      DmlHelper.performDML(purges, DmlHelper.DML_UPDATE, 'PurgeBatch', 'execute', 'update the purge records', true);
      DmlHelper.performDML(insertTrackers, DmlHelper.DML_INSERT, 'PurgeBatch', 'execute', 'inserting purge trackers', true);
      DmlHelper.performDML(updateTrackers, DmlHelper.DML_UPDATE, 'PurgeBatch', 'execute', 'updating purge trackers', true);
      if (!emails.isEmpty()) {
         Messaging.sendEmail(emails);
      }

   } // execute

  // The maximum number of records to retrieve at once. 
   public static Integer MAX_BATCH=1000;

   global void handleProcessCheck(PurgeControl__c pc, PurgeControlTracker__c pcd, Messaging.SingleEmailMessage[] emails) {
      System.debug('handleProcessCheck pc='+pc.Name);
      // verify Purge Control has criteria
      if ((String.isBlank(pc.DateFieldToCheck__c) || (pc.NbrDaysToKeep__c == null && pc.NbrMinutesToQuery__c == null)) && (String.isBlank(pc.AdditionalPurgeCriteria__c))) {
         pc.IsActive__c = false;
         numberOutsideRange++;
         StringHelper.addToProcessNotes(pc, 'Check criteria could not be found!');
         processMsgs.add(pc.Name+': Check criteria could not be found!');
         System.debug('handleProcessCheck check criteria could not be found');
         return;
      } // if ((String.isBlank(pc.DateFieldToCheck__c
      
      // need number of records to check for - if more than x records or less than x records? 
      // email body?
      

      // so we can calculate how many seconds this is running
      Datetime processStart = DateTime.now();
      Integer batchSize = MAX_BATCH;
      if (pc.BatchSize__c != null && pc.BatchSize__c > 0) {
         batchSize = Integer.valueOf(pc.BatchSize__c);
      }
       
      String procInfo = 'Count for '+pc.Name+', object '+pc.ObjectAPIName__c+', ';
      // build the query
      String query = 'Select count() from '+pc.ObjectAPIName__c;   // change this from PurgeBatch
      Date checkDate = Date.today(); // we will be running this every day to check the status - keep track here
      Datetime checkDateTime = Datetime.now();
      
      String[] addlCriteria = new String[]{};
      if (String.isNotBlank(pc.DateFieldToCheck__c) && pc.NbrMinutesToQuery__c != null) {
         checkDateTime = Datetime.now().addMinutes(-(Integer)pc.NbrMinutesToQuery__c);
         procInfo += 'checkDateTime='+checkDateTime.format('M/d/yyyy hh:mm')+' ';
         addlCriteria.add(pc.DateFieldToCheck__c+'>= :checkDateTime ');
      }
      // to check for records found in the last N days
      if (String.isNotBlank(pc.DateFieldToCheck__c) && pc.NbrDaysToKeep__c != null) {
         checkDate = Date.today().addDays(-(Integer)pc.NbrDaysToKeep__c);
         procInfo += 'checkDate='+checkDate+' ';
         addlCriteria.add(pc.DateFieldToCheck__c+'>= :checkDate ');
      }
      if (String.isNotBlank(pc.AdditionalPurgeCriteria__c)) {
         addlCriteria.add(pc.AdditionalPurgeCriteria__c);
      }
      if (!addlCriteria.isEmpty()) {
         query += (' where '+String.join(addlCriteria,' and '));
      }
      query += ' limit :batchSize ';
      if (pc.CheckRecycleBin__c){
         query += ' ALL ROWS ';     
      }

      pc.LatestQuery__c = query;
      
      try {
         Integer foundNow = Database.countQuery(query);
         System.debug('handleProcessCheck foundNow='+foundNow);
         pcd.NbrFound__c += foundNow;
         pcd.NbrIterations__c++;
         
         
         String emailBody = null;
         procInfo += 'Number of records found: '+foundNow+'. ';
         Boolean outsideRange = false;
         if (pc.ProcessCheckMaxRecs__c != null && foundNow > pc.ProcessCheckMaxRecs__c) {
            outsideRange = true;
            procInfo += 'Maximum expected is '+pc.ProcessCheckMaxRecs__c+'! ****';
         } else if (pc.ProcessCheckMinRecs__c != null && foundNow < pc.ProcessCheckMinRecs__c) {
            outsideRange = true;
            procInfo += 'We are expecting at least '+pc.ProcessCheckMinRecs__c+' record(s)! **** ';
         }
         if (outsideRange) {
            numberOutsideRange++;
            pcd.OutsideRange__c = true;
         }
         if (outsideRange || pc.AlwaysEmail__c) {
            procInfo += '\n\n'+query;
            buildEmail(pc, procInfo, emails);
         }
         
         String checkNotes = (pc.Name+' foundNow='+foundNow+' procInfo='+procInfo);
         processMsgs.add(checkNotes);
         //processNotes += ('\n    '+checkNotes);

         StringHelper.addToProcessNotes(pc, checkNotes);
      } catch (Exception e) {
         pc.IsActive__c=false;
         StringHelper.addToProcessNotes(pc, 'Error in query: '+query+'. Ex='+e.getMessage()+'; '+e.getStackTraceString());
         System.debug(pc.Name+' handleProcessCheck notes='+pc.Notes__c);
         processMsgs.add('Exception occurred with '+pc.Name+'! query: '+query+'. Ex='+e.getMessage());
      }
      pcd.EndDate__c=DateTime.now();
      Integer numSeconds = Integer.valueOf((pcd.EndDate__c.getTime() - processStart.getTime())/1000);
      pcd.SecondsProcessed__c += numSeconds;
   } // handleProcessCheck
    
   global static void setNextRunTime(PurgeControl__c pc) {
      pc.NextRunTime__c = null;
      if (pc.TimeOfDayToRun__c != null) {
         Integer nbrDays = (pc.NextRunDays__c != null && pc.NextRunDays__c > 0 ? Integer.valueOf(pc.NextRunDays__c) : 1);
         pc.NextRunTime__c = DateTime.newInstance(Date.today().addDays(nbrDays), pc.TimeOfDayToRun__c);
      } else if (pc.NextRunInterval__c != null) {
         Integer nbrMinutes = Integer.valueOf(pc.NextRunInterval__c);
         if (!pc.BusinessHoursOnly__c) {
            pc.NextRunTime__c = Datetime.now().addMinutes(nbrMinutes);
            if (pc.NextRunDays__c != null && pc.NextRunDays__c > 0) {
               pc.NextRunTime__c.addDays(Integer.valueOf(pc.NextRunDays__c));
            }
         } else {
            BusinessHours[] hours = [Select Id, Name, TimeZoneSidKey from BusinessHours where IsActive=true and Name = 'Sales Support' limit 1];
            if (!hours.isEmpty()) {
                pc.NextRunTime__c = BusinessHours.add(hours[0].id , Datetime.now(), (nbrMinutes * 60000));
            } else {
                StringHelper.addToProcessNotes(pc,'\n **** Could NOT find the Sales Support Business Hours');
            }
         }
      }
      // if days of the week are specified, make sure the scheduled next run time is on one of those days
      if (pc.NextRunTime__c != null && String.isNotBlank(pc.DaysToRun__c) && pc.DaysToRun__c != 'All') {
         Set<String> daysSet = new Set<String>(pc.DaysToRun__c.split(';'));
         String nextDay = pc.NextRunTime__c.format('EEEE');
         Integer dayCounter = 0;
         while (!daysSet.contains(nextDay) && dayCounter < 7) {
            pc.NextRunTime__c = pc.NextRunTime__c.addDays(1);
            nextDay = pc.NextRunTime__c.format('EEEE');
            dayCounter++;
         } // while
      }
        
   } // setNextRunTime
    
   public static PurgeControlTracker__c getTracker(PurgeControl__c pc, Date purgeDate, PurgeControlTracker__c[] insertTrackers, PurgeControlTracker__c[] updateTrackers) {
      PurgeControlTracker__c pcd = null;
      if (pc.PurgeControlTrackers__r != null && !pc.PurgeControlTrackers__r.isEmpty()) {
         // only check the latest one (only one should be returned)
         if (pc.PurgeControlTrackers__r[0].PurgeDate__c == purgeDate) {
            pcd = pc.PurgeControlTrackers__r[0];
            updateTrackers.add(pcd);
         }
      }
      if (pcd == null) {
         // if one doesn't already exist for the date create a new one.
         pcd = new PurgeControlTracker__c(PurgeControl__c=pc.Id, NbrRecsPurged__c=0, NbrIterations__c=0
                                         ,NbrFound__c=0, NbrFailed__c=0
                                         ,StartDate__c=Datetime.now()
                                         ,PurgeDate__c=purgeDate, SecondsProcessed__c=0);
         insertTrackers.add(pcd);
      }
      return pcd;
   } // getTracker
   
   // send an email for a specific process
   global void buildEmail(PurgeControl__c pc, String emailBody, Messaging.SingleEmailMessage[] emails) {
      if (String.isNotBlank(pc.EmailNotification__c )) {
         Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
         mail.setTargetObjectId(UserInfo.getUserId());
         mail.setSaveAsActivity(false);
         String[] addressList = pc.EmailNotification__c.split(',');
         if (!addressList.isEmpty()) {
            mail.setCcAddresses(addressList);
         }
         String subject = (String.isNotBlank(pc.EmailSubject__c) ? pc.EmailSubject__c : '**'+pc.Name+' falls outside of its expected range!');
         mail.setSubject(subject);
         String body = msgExtra+(emailBody+ '\n'+ (String.isNotBlank(pc.EmailBody__c) ? pc.EmailBody__c : 'Please take appropriate action.'));
         mail.setPlainTextBody(body);
         emails.add(mail);
      }
   } // buildEmail
   
   global void finish(Database.BatchableContext bc){
      // did this job already run today?
      Integer jobRuns = [select count() from Job_Tracker__c where Job_Name__c=:CLASSNAME and CreatedDate=today];
      
      String message = '\nTotal ProcessChecks Processed: '+numberPurges+' '; 
      message += '\nNumber of checks that fell outside acceptable range: '+numberOutsideRange+' \n'; 
      
      String msgSummary = '\n'+String.join(processMsgs,'\n\n');
      message += msgSummary;
      System.debug('finish processNotes='+processNotes);
      message += '\n\n'+processNotes;
      
      jh.completeJob(bc, 'Purge Batch', message);
      
      Apex_Batch_Control__c abc = Apex_Batch_Control__c.getInstance(CLASSNAME);
       
      // update Apex Batch Control with the latest 
      System.debug('finish has numberOutsideRange='+numberOutsideRange+' jobRuns='+jobRuns+' abc='+abc);
      // send an email for the entire job. Only send if the first run of the day or results are falling outside of range.
      if ((numberOutsideRange > 0 || jobRuns == 0) && abc != null && abc.AdditionalEmails__c != null) {
         String subject = 'COE Process Tracker' + (numberOutsideRange > 0 ? ': HAS RESULTS OUTSIDE OF ACCEPTED RANGE' : '');
         Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
         mail.setSaveAsActivity(false);

         mail.setTargetObjectId(UserInfo.getUserId());
         mail.setSubject(subject);
         mail.setPlainTextBody (msgExtra+message);

         if (String.isNotBlank(abc.AdditionalEmails__c)) {
            mail.setCcAddresses(abc.AdditionalEmails__c.split(','));
         }

         Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
      } // if (String.isNotBlank
      
      // only run once for a test
      if (!Test.isRunningTest()) {
         launchBatch();
      }
   } // finish
   
   public static DateTime getNextRunTime(String[] processTypes) {
      PurgeControl__c[] pcs = [SELECT Id, BusinessHoursOnly__c,IsActive__c
                                     ,NextRunTime__c
                                 FROM PurgeControl__c 
                                WHERE IsActive__c = true
                                  AND ProcessType__c in :processTypes
                                  AND NextRunTime__c !=null
                                order by NextRunTime__c asc];
      Datetime nextRunTime = (!pcs.isEmpty() ? pcs[0].NextRunTime__c : null);
      System.debug('getNextRunTime pcs='+pcs.size()+' nextRunTime='+nextRunTime);
      return nextRunTime;
   }

   public static void launchBatch() {
      DateTime nextRunTime = getNextRunTime(PROCESS_TYPES);
      if (nextRunTime != null) {
         JobHelper.launchBatchWithSchedule(new ProcessChecker(), CLASSNAME, nextRunTime, 1);
      }
   } // launchBatch

} // class ProcessChecker