force-app/main/default/objects/Reference_Do_Not_Contact__c/Reference_Do_Not_Contact__c.object-meta.xml
<CustomObject>
    <label>Reference Do Not Contact Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Reference Do Not Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reference Do Not Contact Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_Do_Not_Contact__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Email</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Do_Not_Contact__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Requestor</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Do_Not_Contact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Case 26171567</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waiting on Documentation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UnsubscribeEmailController.cls
public with sharing class UnsubscribeEmailController {
 
    @AuraEnabled
    public static Boolean updateRecord(String emailString) {
        System.debug('Entered Apex'+emailString);
        Boolean flag = false;
        if(emailString!=null){
            Reference_Do_Not_Contact__c refDNC = new Reference_Do_Not_Contact__c();
            refDNC.Contact_Email__c = emailString;
            refDNC.Status__c = 'New';
            refDNC.Requestor__c = 'UnsubscribeEmail';
            insert refDNC;
            System.debug('created rec'+refDNC);
            flag= true;
        } 
        return flag;
	}
}