force-app/main/default/objects/Product_Pricebook_Map__c/Product_Pricebook_Map__c.object-meta.xml
<CustomObject>
    <label>Product-Pricebook Map</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product-Pricebook Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Pricebook_Map__c/fields/Pricebook_Id__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Id__c</fullName>
    <description>The Salesforce ID of the pricebook.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Salesforce ID of the pricebook.</inlineHelpText>
    <label>Pricebook Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Pricebook_Map__c/fields/Pricebook_Name__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Name__c</fullName>
    <description>The name of the pricebook</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the pricebook</inlineHelpText>
    <label>Pricebook Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductPricebookMap.cls
/* 
 * Methods for the Product_Pricebook_Map__c object.
 *
 * History
 * -------
 * 06/16/2011 Dan Carmen   Created
   10/26/2018 Dan Carmen   Increment API to version 44

 */
public with sharing class ProductPricebookMap {

   public static void getPricebookId(Product_Pricebook_Map__c[] records) {
      // get the pricebook names
      Map<String,String> pricebookNameMap = new Map<String,String>();
      for (Product_Pricebook_Map__c ppm : records) {
         pricebookNameMap.put(ppm.Pricebook_Name__c,ppm.Pricebook_Name__c);
      } // for (Product_Pricebook_Map__c
      
      // select the pricebooks
      Pricebook2[] pricebooks = [Select Id, Name
                                   from Pricebook2
                                 where Name IN :pricebookNameMap.values()];
      
      // set the pricebook ids 
      for (Product_Pricebook_Map__c ppm : records) {
         ppm.Pricebook_Id__c = null;
         for (Pricebook2 pb : pricebooks) {
            if (ppm.Pricebook_Name__c == pb.Name) {
               ppm.Pricebook_Id__c = pb.Id;
               break;
            }
         } // for (Pricebook2
      } // for (Product_Pricebook_Map__c
   } // getPricebookId
   
} // class ProductPricebookMap