force-app/main/default/objects/Lead/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Mthd_Lead_Rcvd__c.field-meta.xml
<CustomField>
    <fullName>Mthd_Lead_Rcvd__c</fullName>
    <label>Mthd Lead Rcvd</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Rep Effort</fullName>
            </value>
            <value>
                <fullName>CPA Call</fullName>
            </value>
            <value>
                <fullName>On The Spot Explore Paychex Referral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The referral source for this lead</description>
    <label>Referral Contact</label>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/Referral_Account__c.object-meta.xml
<CustomObject>
    <description>Referral Source Company Information</description>
    <label>Referral Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Referral Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Contact__c/Referral_Contact__c.object-meta.xml
<CustomObject>
    <label>Referral Contact</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Contact__c/fields/Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Contact_ID__c</fullName>
    <description>This number is initially populated by the ID from WAR. Going forward this number is auto generated from the contact</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Contact ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Account__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Referral Contacts</relationshipLabel>
    <relationshipName>Referral_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Is this referral contact record setup for online access?</inlineHelpText>
    <label>Online Access</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/UsernameDate__c.field-meta.xml
<CustomField>
    <fullName>UsernameDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date that the username was set from Online</inlineHelpText>
    <label>Username Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LeadOnlineSetupTest.cls
/* Test methods for the LeadOnlineSetup class.
   
  History
  -------
  03/11/2016 Dan Carmen   Created
  
 */
@isTest
private class LeadOnlineSetupTest {

   static testMethod void testLeads() {
      ReferralObjectsSync.SKIP_SYNC=false;
      Referral_Account__c refAcct = new Referral_Account__c(Name='Test Acct');
      insert refAcct;
      
      Referral_Contact__c refCtct1 = new Referral_Contact__c(Name='Test Ctct1', Referral_Account__c=refAcct.Id);
      Referral_Contact__c refCtct2 = new Referral_Contact__c(Name='Test Ctct1', Referral_Account__c=refAcct.Id);
      Referral_Contact__c[] refCtcts = new Referral_Contact__c[]{refCtct1,refCtct2};
      insert refCtcts;
      
      refCtct1 = [Select Id, Name, Contact_Id__c, User_Name__c, UsernameDate__c from Referral_Contact__c where Id=:refCtct1.Id];
      refCtct2 = [Select Id, Name, Contact_Id__c, User_Name__c, UsernameDate__c from Referral_Contact__c where Id=:refCtct2.Id];
      
      System.debug('testLeads refCtct1='+refCtct1);
      System.assertEquals(true, refCtct1.Contact_Id__c != null);
      System.assertEquals(null,refCtct1.User_Name__c);
      System.assertEquals(null,refCtct1.UsernameDate__c);
      
      System.assertEquals(true, refCtct2.Contact_Id__c != null);
      System.assertEquals(null,refCtct2.User_Name__c);
      System.assertEquals(null,refCtct2.UsernameDate__c);
      
      Lead ld1 = new Lead(Company='Test1', FirstName='username1', LastName=refCtct1.Contact_Id__c, PostalCode='12345', Status=LeadOnlineSetup.STATUS_OPEN, Mthd_Lead_Rcvd__c=LeadOnlineSetup.CHECK_METHOD);
      Lead ld2 = new Lead(Company='Test2', FirstName='username2', LastName=refCtct2.Contact_Id__c, PostalCode='12345', Status=LeadOnlineSetup.STATUS_OPEN, Mthd_Lead_Rcvd__c=LeadOnlineSetup.CHECK_METHOD);
      Lead ld3 = new Lead(Company='Test3', FirstName='username3', LastName='BadId', PostalCode='12345', Status=LeadOnlineSetup.STATUS_OPEN, Mthd_Lead_Rcvd__c=LeadOnlineSetup.CHECK_METHOD);
      Lead[] lds = new Lead[]{ld1,ld2,ld3};
      insert lds;
      
      ld1 = [Select Id, FirstName, Status, Comment__c from Lead where Id=:ld1.Id];
      System.assertEquals(LeadOnlineSetup.STATUS_CLOSE, ld1.Status);
      
      ld2 = [Select Id, FirstName, Status, Comment__c from Lead where Id=:ld2.Id];
      System.assertEquals(LeadOnlineSetup.STATUS_CLOSE, ld2.Status);

      ld3 = [Select Id, FirstName, Status, Comment__c from Lead where Id=:ld3.Id];
      System.assertEquals(LeadOnlineSetup.STATUS_ERROR, ld3.Status);
      System.assertEquals(LeadOnlineSetup.ERROR_MSG,ld3.Comment__c);
      
      refCtct1 = [Select Id, Name, Contact_Id__c, User_Name__c, UsernameDate__c from Referral_Contact__c where Id=:refCtct1.Id];
      refCtct2 = [Select Id, Name, Contact_Id__c, User_Name__c, UsernameDate__c from Referral_Contact__c where Id=:refCtct2.Id];

      System.assertEquals(ld1.FirstName,refCtct1.User_Name__c);
      System.assertEquals(Date.today(),refCtct1.UsernameDate__c);

      System.assertEquals(ld2.FirstName,refCtct2.User_Name__c);
      System.assertEquals(Date.today(),refCtct2.UsernameDate__c);

   } // testLeads
} // class LeadOnlineSetupTest