force-app/main/default/objects/Sequence__c/Sequence__c.object-meta.xml
<CustomObject>
    <label>Sequence</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sequence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sequence__c/fields/Default_Start_Days__c.field-meta.xml
<CustomField>
    <fullName>Default_Start_Days__c</fullName>
    <description>The number of days to default the sequence start date after the first run date.</description>
    <inlineHelpText>The number of days to default the sequence start date after the first run date.</inlineHelpText>
    <label>Default Start Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sequence__c/fields/Nbr_Emps_High__c.field-meta.xml
<CustomField>
    <fullName>Nbr_Emps_High__c</fullName>
    <label>Nbr Emps High</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sequence__c/fields/Nbr_Emps_Low__c.field-meta.xml
<CustomField>
    <fullName>Nbr_Emps_Low__c</fullName>
    <label>Nbr Emps Low</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sequence__c/fields/RecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RecordType Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sequence__c/fields/RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RecordType Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sequence__c/fields/Start_Week__c.field-meta.xml
<CustomField>
    <fullName>Start_Week__c</fullName>
    <description>The week after the Sequence Start Date that the sequence started. If -1, sequence starts before the Sequence Start Date. Week 1 starts on the Sequence Start Date.</description>
    <inlineHelpText>The week after the Sequence Start Date that the sequence started. If -1, sequence starts before the Sequence Start Date. Week 1 starts on the Sequence Start Date.</inlineHelpText>
    <label>Start Week</label>
    <summarizedField>Sequence_Detail__c.Week_Start__c</summarizedField>
    <summaryForeignKey>Sequence_Detail__c.Sequence__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sequence__c/fields/Valid_Group__c.field-meta.xml
<CustomField>
    <fullName>Valid_Group__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Valid Group</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sequence_Detail__c/Sequence_Detail__c.object-meta.xml
<CustomObject>
    <label>Sequence Detail</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequence Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sequence_Detail__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <referenceTo>Sequence__c</referenceTo>
    <relationshipLabel>Sequence Details</relationshipLabel>
    <relationshipName>Sequence_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sequence_Detail__c/fields/Sequence_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Stage__c</fullName>
    <label>Sequence Stage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payroll Rep</fullName>
            </value>
            <value>
                <fullName>Workers Compensation</fullName>
            </value>
            <value>
                <fullName>401(k) Services</fullName>
            </value>
            <value>
                <fullName>Health &amp; Benefits</fullName>
            </value>
            <value>
                <fullName>HR Solutions</fullName>
            </value>
            <value>
                <fullName>NSS</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sequence_Detail__c/fields/Week_End__c.field-meta.xml
<CustomField>
    <fullName>Week_End__c</fullName>
    <description>The week number after the Sequence Start Date this stage ends.</description>
    <inlineHelpText>The week number after the Sequence Start Date this stage ends.</inlineHelpText>
    <label>Week End</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sequence_Detail__c/fields/Week_Start__c.field-meta.xml
<CustomField>
    <fullName>Week_Start__c</fullName>
    <description>The week number after the Sequence Start Date this stage starts.</description>
    <inlineHelpText>The week number after the Sequence Start Date this stage starts.</inlineHelpText>
    <label>Week Start</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter district number as a 3 digit number with leading zero</inlineHelpText>
    <label>District</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org-Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>BenAdmin</fullName>
            </value>
            <value>
                <fullName>Benetrac</fullName>
            </value>
            <value>
                <fullName>BusDev</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Relations</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Center</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise Service Center</fullName>
            </value>
            <value>
                <fullName>ESR</fullName>
            </value>
            <value>
                <fullName>EW</fullName>
            </value>
            <value>
                <fullName>Field Operations Core</fullName>
            </value>
            <value>
                <fullName>HNBF</fullName>
            </value>
            <value>
                <fullName>HROI</fullName>
            </value>
            <value>
                <fullName>HR Online</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>HRS 401K-S125</fullName>
            </value>
            <value>
                <fullName>HRS Premier</fullName>
            </value>
            <value>
                <fullName>Icon</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Merchant Services</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MMS Hub</fullName>
            </value>
            <value>
                <fullName>MPSC</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SequenceTest.cls
/* 
   Tests for the Sequence and SequenceDetail triggers.
   
  History
  -------
   02/01/2012 Dan Carmen   Created
   02/11/2014 Dan Carmen   Commented out code
   
 */
@isTest
public class SequenceTest {

   /*
   public static User coreUser;
   public static User mmsUser;
   
   public static void setupTestUsers() {
      AccountCheckSequence.group1DistSet.clear();
      AccountCheckSequence.group2DistSet.clear();

      // get a user in one of the districts
      coreUser = [Select Id, Name, Sales_Org__c, District__c from User where IsActive=true and Sales_Org__c = :UserHelper.SO_CORE and District__c like '0%' limit 1];
      mmsUser = [Select Id, Name, Sales_Org__c, District__c from User where IsActive=true and Sales_Org__c = :UserHelper.SO_MMS and District__c like '4%' limit 1];
      AccountCheckSequence.group1DistSet.add(coreUser.District__c);
      AccountCheckSequence.group2DistSet.add(mmsUser.District__c);
   } // setupTestUsers
   
   /** Setup test sequence data. Set anything already there to inactive
    */
    /*
   public static Sequence__c[] setupTestData() {
      // query for any existing data
      Sequence__c[] existingSeqs = [Select Id, IsActive__c from Sequence__c where IsActive__c=true];
      // if data, inactivate the records
      if (!existingSeqs.isEmpty()) {
         for (Sequence__c seq : existingSeqs) {
            seq.IsActive__c = false;
         }
         update existingSeqs;
      } // if (!existingSeqs

      // tests for the trigger
      // try with bad record type name
      Sequence__c seq0 = new Sequence__c(Name='TestMethod seq1',IsActive__c=true,Default_Start_Days__c=0, Nbr_Emps_Low__c=0, Nbr_Emps_High__c=10, RecordTypeName__c='This is a bad record type name');
      Database.SaveResult result = Database.insert(seq0,false);            
      // verify that failed
      System.assertEquals(false,result.isSuccess());
      
      // create new Sequences
      Sequence__c seq1 = new Sequence__c(Name='TestMethod seq1',IsActive__c=true,Default_Start_Days__c=0, Nbr_Emps_Low__c=0, Nbr_Emps_High__c=10, RecordTypeName__c=RecordTypeHelper.CORE_ACCOUNT, Valid_Group__c='Group1;');
      Sequence__c seq2 = new Sequence__c(Name='TestMethod seq1',IsActive__c=true,Default_Start_Days__c=0, Nbr_Emps_Low__c=11, Nbr_Emps_High__c=9999, RecordTypeName__c=RecordTypeHelper.CORE_ACCOUNT, Valid_Group__c='Group1;');
      Sequence__c seq3 = new Sequence__c(Name='TestMethod seq1',IsActive__c=true,Default_Start_Days__c=14, Nbr_Emps_Low__c=0, Nbr_Emps_High__c=9999, RecordTypeName__c=RecordTypeHelper.MMS_ACCOUNT, Valid_Group__c='Group2;');
      Sequence__c[] seqs = new Sequence__c[]{seq1,seq2,seq3};
      Database.SaveResult[] results = Database.insert(seqs,false);
      // verify all were successful
      for (Database.SaveResult sr : results) {
         System.assertEquals(true,sr.isSuccess());
      }
      
      // create details for all
      Sequence_Detail__c[] details = new Sequence_Detail__c[]{};
      createDetails(seq1,details,false);
      createDetails(seq2,details,false);
      createDetails(seq3,details,true);
      insert details;
      
      Sequence__c[] sequences = getSequences();
      Sequence__c[] retVals = new Sequence__c[]{};
      retVals.add(getSeq(seq1.Id,sequences));
      retVals.add(getSeq(seq2.Id,sequences));
      retVals.add(getSeq(seq3.Id,sequences));
      return retVals;
   } // setupTestData

   public static Sequence__c[] getSequences() {
      Sequence__c[] seqs = [Select Id
                                ,Name
                                ,Default_Start_Days__c
                                ,IsActive__c
                                ,Nbr_Emps_Low__c
                                ,Nbr_Emps_High__c
                                ,RecordTypeId__c
                                ,RecordTypeName__c
                                ,Start_Week__c
                                ,Valid_Group__c
                                ,(Select Id
                                        ,Sequence_Stage__c
                                        ,Week_Start__c
                                        ,Week_End__c
                                    From Sequence_Details__r
                                   order by Week_Start__c)
                            From Sequence__c];
      return seqs;
   } // getSequences
   

   private static Sequence__c getSeq(Id seqId, Sequence__c[] sequences) {
      Sequence__c foundVal = null;
      for (Sequence__c seq : sequences) {
         if (seq.Id == seqId) {
            foundVal = seq;
            break;
         }
      } // for
      return foundVal;
   } // getSeq
   
   private static void createDetails(Sequence__c seq,  Sequence_Detail__c[] details, Boolean useNegOne) {
      if (useNegOne) {
         details.add(new Sequence_Detail__c(Name='Neg One',Sequence__c=seq.Id, Sequence_Stage__c='Stage 0', Week_Start__c=-1, Week_End__c=0));
      }
      details.add(new Sequence_Detail__c(Name='Stage One',Sequence__c=seq.Id, Sequence_Stage__c='Stage 1', Week_Start__c=1, Week_End__c=2));
      details.add(new Sequence_Detail__c(Name='None',Sequence__c=seq.Id, Sequence_Stage__c=null, Week_Start__c=3, Week_End__c=3));
      details.add(new Sequence_Detail__c(Name='All',Sequence__c=seq.Id, Sequence_Stage__c='Stage 3', Week_Start__c=4, Week_End__c=null));
      
   } // createDetails
   

   static testMethod void testTriggers() {
        setupTestData();
   } // 
   
   */
} // class SequenceTest