force-app/main/default/objects/Opportunity/fields/Payroll_Unit__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DSA checks this for all opportunities that count as a unit</description>
    <label>Payroll Unit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <description>One time fee charged to new Account</description>
    <label>Setup Fee</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Payroll_Unit__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Unit__c</fullName>
    <label>Payroll Unit</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of this product record.</description>
    <inlineHelpText>The status of this product record.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Create - Received</fullName>
            </value>
            <value>
                <fullName>Create - Qualified</fullName>
            </value>
            <value>
                <fullName>Plan</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Pending - Submitted to VSS</fullName>
            </value>
            <value>
                <fullName>Sold - Submitted to FSS</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Sold - Submitted</fullName>
            </value>
            <value>
                <fullName>Sold - Started</fullName>
            </value>
            <value>
                <fullName>Sold - Commissioned</fullName>
            </value>
            <value>
                <fullName>Not Sold</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Referred Not Sold</fullName>
            </value>
            <value>
                <fullName>Referred Sold</fullName>
            </value>
            <value>
                <fullName>Referred Submitted</fullName>
            </value>
            <value>
                <fullName>Referred Started</fullName>
            </value>
            <value>
                <fullName>Referred Commissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SubmittedRevenueCloneControllerTest.cls
@isTest
private class SubmittedRevenueCloneControllerTest {
    
    @isTest static void testConstructor() {
        Opportunity opp = new Opportunity(Name='Test opp', StageName = 'Sold - Submitted', CloseDate=Date.today());
        insert opp;
        
        Test.setCurrentPageReference(new PageReference('Page.SubmittedRevenueClone')); 
        System.currentPageReference().getParameters().put('id', opp.Id);
        
        Test.startTest();
        SubmittedRevenueCloneController controller = new SubmittedRevenueCloneController();
        Test.stopTest();
        
        System.assertEquals(controller.products != null, true);
    }
    
    @isTest static void submittedRevenueCloneTest() {
        Opportunity opp = new Opportunity(Name='Test opp', StageName = 'Sold - Submitted', CloseDate=Date.today(), Payroll_Unit__c = true);
        insert opp;
        
        String[] prodNames = new String[]{'OpptyLineItemTest','Direct Deposit', 'Submitted Revenue Adjustment'};
        PricebookEntry[] entries = ProductMethodsTest.getEntries(prodNames,'OpptyLineItemTest',null);
        PricebookEntry entry = entries.get(0);
        PricebookEntry entry2 = entries.get(1);
        PricebookEntry entry3 = entries.get(2);
     
        OpportunityLineItem oli = new OpportunityLineItem(OpportunityId=opp.Id, PricebookEntryId=entry.Id, Status__c='Pending', ServiceDate=Date.today()
                                                          ,Quantity=1, TotalPrice=1000, Setup_Fee__c=100, Payroll_Unit__c=2.5);
        OpportunityLineItem oli2 = new OpportunityLineItem(OpportunityId=opp.Id, PricebookEntryId=entry2.Id, Status__c='Pending', ServiceDate=Date.today()
                                                          ,Quantity=1, TotalPrice=1000, Setup_Fee__c=100, Payroll_Unit__c=2.5);
        OpportunityLineItem oli3 = new OpportunityLineItem(OpportunityId=opp.Id, PricebookEntryId=entry3.Id, Status__c='Pending', ServiceDate=Date.today()
                                                          ,Quantity=1, TotalPrice=1000, Setup_Fee__c=100, Payroll_Unit__c=2.5);
        
        List<OpportunityLineItem> olis = new List<OpportunityLineItem>{oli, oli2, oli3};
        insert olis;

        Test.setCurrentPageReference(new PageReference('Page.SubmittedRevenueClone')); 
        System.currentPageReference().getParameters().put('id', opp.Id);
        System.currentPageReference().getParameters().put('strCloseDateName', string.valueOf(Date.today()+1));
        
        Test.startTest();
        SubmittedRevenueCloneController controller = new SubmittedRevenueCloneController();
      
        //This will generate another oppty clone
        for(Integer i = 0; i < 1; i++) {
            controller.wrapOppLineItems.get(i).hasRevOnSubmit = true;
            controller.wrapOppLineItems.get(i).selected = true;
        }
  
        controller.processSelected();
        controller.previewOpportunityClones();
        controller.cancel();
        controller.previewOpportunityClones();
        controller.cloneOpportunity();
        Test.stopTest();
        
        List<Opportunity> numOppties = [Select Id, StageName from Opportunity where Name = 'Test Opp'];
        System.assertEquals(String.valueOf(numOppties.size()), '3');
        System.assertEquals(numOppties.get(0).StageName, 'Sold - Submitted');
        System.assertEquals(numOppties.get(1).StageName, 'Sold - Submitted');
        
	}
    
}