force-app/main/default/objects/Reference_401k_S125__c/Reference_401k_S125__c.object-meta.xml
<CustomObject>
    <description>Used by operations teams to track the status of a new plans</description>
    <label>Reference 401k/S125</label>
    <nameField>
        <displayFormat>Reference 401k/S125-{000000}</displayFormat>
        <label>Reference_401k_S125</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference_401k_S125</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_401k_S125__c/fields/Anti_Cutback_Review_Complete__c.field-meta.xml
<CustomField>
    <fullName>Anti_Cutback_Review_Complete__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Anti-Cutback Review Complete</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_401k_S125__c/fields/Census__c.field-meta.xml
<CustomField>
    <fullName>Census__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Added for: 401k/S125
Manually Entered or Fed in: Manually
Brief Description of what this will represent: It will indicate whether the onboarding representative completed a 401k/S125 census review. In other words, whether they looked over all employee data and confirmed it is complete and accurate.</description>
    <label>Census</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reference_401k_S125__c/fields/PEP__c.field-meta.xml
<CustomField>
    <fullName>PEP__c</fullName>
    <label>PEP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3(38) Mesirow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_401k_S125__c/fields/Prior_RK_Contacted_for_PEP_Risk_Assess__c.field-meta.xml
<CustomField>
    <fullName>Prior_RK_Contacted_for_PEP_Risk_Assess__c</fullName>
    <description>Prior RK Contacted for PEP Risk Assessment</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Prior RK Contacted for PEP Risk Assessment</inlineHelpText>
    <label>Prior RK Contacted for PEP Risk Assess</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_401k_S125__c/fields/Risk_Assessment_Complete__c.field-meta.xml
<CustomField>
    <fullName>Risk_Assessment_Complete__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Risk Assessment Complete</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_PEP_Due_Diligence__c/Reference_PEP_Due_Diligence__c.object-meta.xml
<CustomObject>
    <description>A reference object in order for the team to monitor their work load.</description>
    <label>Reference PEP Due Diligence</label>
    <nameField>
        <displayFormat>Ref PEP-{000000}</displayFormat>
        <label>Reference PEP Due Diligence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference_PEP_Due_Diligence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_PEP_Due_Diligence__c/fields/Adoption_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Adoption_Agreement__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Adoption Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_PEP_Due_Diligence__c/fields/Anti_Cutback_Result__c.field-meta.xml
<CustomField>
    <fullName>Anti_Cutback_Result__c</fullName>
    <label>Anti-Cutback Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Research Needed</fullName>
            </value>
            <value>
                <fullName>Client changed mind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_PEP_Due_Diligence__c/fields/Anti_Cutback_Review_Complete__c.field-meta.xml
<CustomField>
    <fullName>Anti_Cutback_Review_Complete__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Anti-Cutback Review Complete</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_PEP_Due_Diligence__c/fields/Authorization_Letter__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Letter__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Authorization Letter</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_PEP_Due_Diligence__c/fields/Basic_Plan_Document__c.field-meta.xml
<CustomField>
    <fullName>Basic_Plan_Document__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Basic Plan Document</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_PEP_Due_Diligence__c/fields/Census__c.field-meta.xml
<CustomField>
    <fullName>Census__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Census</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_PEP_Due_Diligence__c/fields/Participant_Summary__c.field-meta.xml
<CustomField>
    <fullName>Participant_Summary__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Participant Summary</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_PEP_Due_Diligence__c/fields/Reference_401k_S125__c.field-meta.xml
<CustomField>
    <fullName>Reference_401k_S125__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference 401k/S125</label>
    <referenceTo>Reference_401k_S125__c</referenceTo>
    <relationshipLabel>Reference_PEP_Due_Diligence</relationshipLabel>
    <relationshipName>Reference_PEP_Due_Diligence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_PEP_Due_Diligence__c/fields/Risk_Assessment_Complete__c.field-meta.xml
<CustomField>
    <fullName>Risk_Assessment_Complete__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Risk Assessment Complete</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_PEP_Due_Diligence__c/fields/Risk_Assessment_Result__c.field-meta.xml
<CustomField>
    <fullName>Risk_Assessment_Result__c</fullName>
    <label>Risk Assessment Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Corrective Action Pending</fullName>
            </value>
            <value>
                <fullName>Documents Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_PEP_Due_Diligence__c/fields/Submission_Docs_Received_in_Good_Order__c.field-meta.xml
<CustomField>
    <fullName>Submission_Docs_Received_in_Good_Order__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Submission Docs Received in Good Order</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_PEP_Due_Diligence__c/fields/Summary_Plan_Description__c.field-meta.xml
<CustomField>
    <fullName>Summary_Plan_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Summary Plan Description</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_PEP_Due_Diligence__c/fields/X1st_Communication_Sent_to_Prior_RK__c.field-meta.xml
<CustomField>
    <fullName>X1st_Communication_Sent_to_Prior_RK__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>1st Communication Sent to Prior RK</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RefPEPDueDiligenceMethodsTest.cls
/* 
	Unit tests for Reference PEP Due Diligence.
	Req: https://wiki.paychex.com/display/CP/APR0116626+-+New+Object+in+SFDC+for+PEP+Due+Diligence+Team

   
	History
	-------
	04/09/2021 Manmeet Vaseer   Created

 */
@isTest
public class RefPEPDueDiligenceMethodsTest {
    
    /*
     * Populate Submission_Docs_Received_in_Good_Order__c date only when all other
     * dates are populated on Reference_PEP_Due_Diligence__c.
     * 
     * Uses RefPEPDueDiligenceTrigger.
     */
    static testMethod void testSubmissionDocsReceivedInGoodOrderPopulated()
    {
        Reference_PEP_Due_Diligence__c newPepRec = new Reference_PEP_Due_Diligence__c(Adoption_Agreement__c=System.today(),
					Summary_Plan_Description__c=System.today(), Basic_Plan_Document__c=System.today(), Census__c=System.today(),
                    Participant_Summary__c=System.today(), Authorization_Letter__c=System.today());
        insert newPepRec;
        
        Map<Id, Reference_PEP_Due_Diligence__c> refPepMap = new Map<Id, Reference_PEP_Due_Diligence__c>([SELECT Id, Submission_Docs_Received_in_Good_Order__c FROM Reference_PEP_Due_Diligence__c]);
        newPepRec = refPepMap.get(newPepRec.Id);
        
        System.assertNotEquals(null, newPepRec, 'PEP Due Diligence record should not be null.');
        System.assertNotEquals(null, newPepRec.Submission_Docs_Received_in_Good_Order__c, 'Submission_Docs_Received_in_Good_Order__c should not be null.');
    }

    /*
     * Do not populate Submission_Docs_Received_in_Good_Order__c date if any/all of the
     * dates are not populated on Reference_PEP_Due_Diligence__c.
     * 
     * Uses RefPEPDueDiligenceTrigger.
     */
    static testMethod void testSubmissionDocsReceivedInGoodOrderNotPopulated()
    {
        Reference_PEP_Due_Diligence__c newPepRec = new Reference_PEP_Due_Diligence__c(Adoption_Agreement__c=System.today(),
					Summary_Plan_Description__c=System.today(), Basic_Plan_Document__c=System.today(), Census__c=null,
                    Participant_Summary__c=System.today(), Authorization_Letter__c=System.today());
        insert newPepRec;
        
        Map<Id, Reference_PEP_Due_Diligence__c> refPepMap = new Map<Id, Reference_PEP_Due_Diligence__c>([SELECT Id, Submission_Docs_Received_in_Good_Order__c FROM Reference_PEP_Due_Diligence__c]);
        newPepRec = refPepMap.get(newPepRec.Id);
        
        System.assertNotEquals(null, newPepRec, 'PEP Due Diligence record should not be null.');
        System.assertEquals(null, newPepRec.Submission_Docs_Received_in_Good_Order__c, 'Submission_Docs_Received_in_Good_Order__c should be null.');
    }
    
   /*
     * Populate Reference_401k_S125__c Anti_Cutback_Review_Complete__c and Risk_Assessment_Complete__c date only when 
     * Anti_Cutback_Result__c/Risk_Assessment_Result__c value is 'Pass' on Reference_PEP_Due_Diligence__c.
     * 
     * The RefPEPDueDiligenceTrigger trigger should automatically set Reference_401k_S125__c Anti_Cutback_Review_Complete__c and Risk_Assessment_Complete__c dates.
     */
    static testMethod void testAntiCutbackRiskAssessmentPopulated()
    {
        Reference_401k_S125__c newRef401kS125 = new Reference_401k_S125__c();
        insert newRef401kS125;

        Reference_PEP_Due_Diligence__c newPepRec = new Reference_PEP_Due_Diligence__c(Anti_Cutback_Review_Complete__c=System.today(),
					Risk_Assessment_Complete__c=System.today(), Anti_Cutback_Result__c='Pass', Risk_Assessment_Result__c='Pass',
                    Reference_401k_S125__c=newRef401kS125.Id, X1st_Communication_Sent_to_Prior_RK__c=System.today());
        insert newPepRec;
        
        List<Reference_PEP_Due_Diligence__c> newPepRecs = new List<Reference_PEP_Due_Diligence__c>();
        newPepRecs.add(newPepRec);
        
      //  RefPEPDueDiligenceMethods.handleBefore(newPepRecs, null);
      //  RefPEPDueDiligenceMethods.handleAfter(newPepRecs, null);
        
        Map<Id, Reference_401k_S125__c> ref401kMap = new Map<Id, Reference_401k_S125__c>([SELECT Id, Name, Anti_Cutback_Review_Complete__c, Risk_Assessment_Complete__c, Prior_RK_Contacted_for_PEP_Risk_Assess__c FROM Reference_401k_S125__c]);
        newRef401kS125 = ref401kMap.get(newRef401kS125.Id);
        System.assertNotEquals(null, newRef401kS125.Anti_Cutback_Review_Complete__c, 'Ref401kS125 Anti_Cutback_Review_Complete__c should not be null.');
        System.assertNotEquals(null, newRef401kS125.Risk_Assessment_Complete__c, 'Ref401kS125 Risk_Assessment_Complete__c should not be null.');
        System.assertNotEquals(null, newRef401kS125.Prior_RK_Contacted_for_PEP_Risk_Assess__c, 'Ref401kS125 Prior_RK_Contacted_for_PEP_Risk_Assess__c should not be null.');
    }

   /*
     * Do not populate Reference_401k_S125__c Anti_Cutback_Review_Complete__c and Risk_Assessment_Complete__c date only when 
     * Anti_Cutback_Result__c/Risk_Assessment_Result__c value is not 'Pass' on Reference_PEP_Due_Diligence__c.
     * 
     * The RefPEPDueDiligenceTrigger trigger should automatically set Reference_401k_S125__c Anti_Cutback_Review_Complete__c and Risk_Assessment_Complete__c dates.
     */
    static testMethod void testAntiCutbackRiskAssessmentNotPopulated()
    {
        Reference_401k_S125__c newRef401kS125 = new Reference_401k_S125__c();
        insert newRef401kS125;

        Reference_PEP_Due_Diligence__c newPepRec = new Reference_PEP_Due_Diligence__c(Anti_Cutback_Review_Complete__c=System.today(),
					Risk_Assessment_Complete__c=System.today(), Anti_Cutback_Result__c=null, Risk_Assessment_Result__c=null,
                    Reference_401k_S125__c=newRef401kS125.Id, X1st_Communication_Sent_to_Prior_RK__c=null);
        insert newPepRec;
        
        List<Reference_PEP_Due_Diligence__c> newPepRecs = new List<Reference_PEP_Due_Diligence__c>();
        newPepRecs.add(newPepRec);
        
       // RefPEPDueDiligenceMethods.handleBefore(newPepRecs, null);
       // RefPEPDueDiligenceMethods.handleAfter(newPepRecs, null);
        
        Map<Id, Reference_401k_S125__c> ref401kMap = new Map<Id, Reference_401k_S125__c>([SELECT Id, Name, Anti_Cutback_Review_Complete__c, Risk_Assessment_Complete__c, Prior_RK_Contacted_for_PEP_Risk_Assess__c FROM Reference_401k_S125__c]);
        newRef401kS125 = ref401kMap.get(newRef401kS125.Id);
        System.assertEquals(null, newRef401kS125.Anti_Cutback_Review_Complete__c, 'Ref401kS125 Anti_Cutback_Review_Complete__c should be null.');
        System.assertEquals(null, newRef401kS125.Risk_Assessment_Complete__c, 'Ref401kS125 Risk_Assessment_Complete__c should be null.');
        System.assertEquals(null, newRef401kS125.Prior_RK_Contacted_for_PEP_Risk_Assess__c, 'Ref401kS125 Prior_RK_Contacted_for_PEP_Risk_Assess__c should be null.');
    }
    
    /*
     * Test a valid scenario where Ref 401k/S125 object record is 'Service Onboarding 401k Conversions' record type.
     * And, PEP field of Ref 401k/S125 object record is populated with some value.
     * 
     * The Reference401After trigger should automatically create a new PEP Due Diligence object record and attach it to the Ref 401k/S125 object record.
     */
    static testMethod void testCreateNewForConversionsRecType() {
        Schema.RecordTypeInfo refOnb401kConvrt = RecordTypeHelper.getRecordType('Service Onboarding 401k Conversions', 'Reference_401k_S125__c');
        Schema.RecordTypeInfo refOnb401kLMNCrt = RecordTypeHelper.getRecordType('Service Onboarding 401k Large Market New Case', 'Reference_401k_S125__c');
       
        List<Reference_401k_S125__c> refList = new List<Reference_401k_S125__c>();
        
        Reference_401k_S125__c newRef401kS125 = new Reference_401k_S125__c(RecordTypeId=refOnb401kConvrt.getRecordTypeId(), PEP__c='3(38) Mesirow');
        refList.add(newRef401kS125);
        
        newRef401kS125 = new Reference_401k_S125__c(RecordTypeId=refOnb401kLMNCrt.getRecordTypeId(), PEP__c='3(38) Mesirow');
        refList.add(newRef401kS125);
        
        insert refList;
        RefPEPDueDiligenceMethods.createNewPEPRecs(refList);
        
        List<Reference_PEP_Due_Diligence__c> pepRecCreated = [SELECT Reference_401k_S125__c FROM Reference_PEP_Due_Diligence__c];
        System.assertEquals(1, pepRecCreated.size(), 'Exactly one PEP Due Diligence object record should have been created');
        System.assertEquals(refList[0].Id, pepRecCreated[0].Reference_401k_S125__c, 'New PEP Due Diligence object record is not attached to correct Ref 401k/S125 object record.');        
    }
    
    
}