force-app/main/default/objects/Contact/fields/Consent_to_Text__c.field-meta.xml
<CustomField>
    <fullName>Consent_to_Text__c</fullName>
    <defaultValue>false</defaultValue>
    <description>case #26177053 - set to True if prospect-client agrees to receive text messages</description>
    <label>Consent to Text</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Consent_to_Text__c.field-meta.xml
<CustomField>
    <fullName>Consent_to_Text__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consent to Text</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Send_to_H_B_Implementation__c.field-meta.xml
<CustomField>
    <fullName>Send_to_H_B_Implementation__c</fullName>
    <label>Send to H&amp;B Implementation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/HNBF_Opportunity_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>HNBF_Opportunity_Record_Type</fullName>
    <active>true</active>
    <businessProcess>HNBF Sales Process</businessProcess>
    <description>HRS HNBF Opportunity Record Type</description>
    <label>HNBF Opportunity Record Type</label>
</RecordType>

force-app/main/default/objects/User/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter district number as a 3 digit number with leading zero</inlineHelpText>
    <label>District</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Yes_No.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <description>Used for Yes/No Picklists</description>
    <masterLabel>Yes/No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/opptyContactRoleHandlerTest.cls
/* Test Methods for the opptyContactRoleHandler class
   
  History
  -------
  03/18/2013 Lalan Kumar     Created

*/

@isTest
public class opptyContactRoleHandlerTest {
    
    static testMethod void updateOppPhoneandConsentToTextTest(){
        
        User u1 = [Select Id, Name from User where (District__c='012' or District__c='031' or District__c='033') and IsActive=true limit 1];
        Account acct = new Account(Name='Test Send to HB Acct');
        insert acct;
        Contact ctct = new Contact(FirstName='Test', LastName='Contact', AccountId=acct.Id,Consent_to_Text__c = true, MobilePhone = '1234567890');
        insert ctct;
        id hnbfOpptyRecTypeId = RecordTypeHelper.getRecordType(Label.HNBF_Opportunity_Record_Type,'Opportunity').getRecordTypeId();
        Opportunity oppty1 = new Opportunity(Name='Test Oppty1', RecordTypeId=hnbfOpptyRecTypeId,AccountId=acct.Id
                                             ,StageName=Label.OppStage_Qualified
                                             ,Send_to_H_B_Implementation__c='Yes'
                                             ,CloseDate=Date.today().addDays(30)
                                             ,OwnerId=u1.id);
        insert oppty1;
        Test.enableChangeDataCapture();
        OpportunityContactRole ocr1 = new OpportunityContactRole(ContactId=ctct.Id, OpportunityId=oppty1.Id, IsPrimary=true);
        insert ocr1;
        Test.getEventBus().deliver(); 
    }
    
        

}