force-app/main/default/objects/Contact/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Franchise National Account referral account.</inlineHelpText>
    <label>Referral National Account</label>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>not really used anywhere, as of 4/19/2013 is blank for all production records</description>
    <label>Referral Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Contact__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>R00N50000001WySDEA0</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>PBS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pay</fullName>
            </value>
            <value>
                <fullName>PAS</fullName>
            </value>
            <value>
                <fullName>H&amp;B</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Referral Account of the Referral Contact at the time of the Opportunity. This is so we know at a company level the referrals made, even if the contact changes companies.</description>
    <inlineHelpText>The Referral Account of the Referral Contact at the time of the Opportunity.</inlineHelpText>
    <label>Referral Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Account__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field should only be completed if the Lead Source is an external partner (CPA, Bank, FA, etc.)</inlineHelpText>
    <label>Referral Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Contact__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Referral Contacts with End Dates will only appear if you click the Show All Results link below.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>OppRCs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/Referral_Account__c.object-meta.xml
<CustomObject>
    <description>Referral Source Company Information</description>
    <label>Referral Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Referral Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Contact__c/Referral_Contact__c.object-meta.xml
<CustomObject>
    <label>Referral Contact</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Contact__c/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Account__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Referral Contacts</relationshipLabel>
    <relationshipName>Referral_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <description>Paychex Sales Division</description>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PAY</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>PBS</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>NSS</fullName>
            </value>
            <value>
                <fullName>BENETRAC</fullName>
            </value>
            <value>
                <fullName>DSR</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GENERIC</fullName>
            </value>
            <value>
                <fullName>HNB</fullName>
            </value>
            <value>
                <fullName>HNBF</fullName>
            </value>
            <value>
                <fullName>PAI</fullName>
            </value>
            <value>
                <fullName>PAI GENERI</fullName>
            </value>
            <value>
                <fullName>PAO</fullName>
            </value>
            <value>
                <fullName>PAS</fullName>
            </value>
            <value>
                <fullName>Stromberg</fullName>
            </value>
            <value>
                <fullName>TCS</fullName>
            </value>
            <value>
                <fullName>TIB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org-Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>BenAdmin</fullName>
            </value>
            <value>
                <fullName>Benetrac</fullName>
            </value>
            <value>
                <fullName>BusDev</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Relations</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Center</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise Service Center</fullName>
            </value>
            <value>
                <fullName>ESR</fullName>
            </value>
            <value>
                <fullName>EW</fullName>
            </value>
            <value>
                <fullName>Field Operations Core</fullName>
            </value>
            <value>
                <fullName>HNBF</fullName>
            </value>
            <value>
                <fullName>HROI</fullName>
            </value>
            <value>
                <fullName>HR Online</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>HRS 401K-S125</fullName>
            </value>
            <value>
                <fullName>HRS Premier</fullName>
            </value>
            <value>
                <fullName>Icon</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Merchant Services</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MMS Hub</fullName>
            </value>
            <value>
                <fullName>MPSC</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>PAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityDATest.cls
/*
 * History
 * --------
   03/18/2022 Dan Carmen        Increment API version

*/ 
@IsTest
private class OpportunityDATest {
    @testSetup
    public static void setupData() {
        ObjectBannerAuraServiceTest.setupData();
    }
    
    @IsTest
    static void getOpenOpportunitiesByContact() {
        Contact ctct = ObjectBannerAuraServiceTest.getTestCtct();
        List<Opportunity> returnOpportunities = new OpportunityDA().getOpenOpportunitiesByContactId(ctct.Id);
        System.assertEquals(1,returnOpportunities.size());
    } // getOpenOpportunitiesByContact

    @IsTest
    static void getOpenOpportunitiesByAccountId() {
        Account acct = ObjectBannerAuraServiceTest.getTestAcct();
        List<Opportunity> returnOpportunities = new OpportunityDA().getOpenOpportunitiesByAccountId(acct.Id);
        System.assertEquals(1,returnOpportunities.size());
        
    } // getOpenOpportunitiesByAccountId

    @IsTest
    static void getOpenOpportunitiesByReferralAccountId() {
        Referral_Account__c refAcct = ObjectBannerAuraServiceTest.getTestRefAcct();
        List<Opportunity> returnOpportunities = new OpportunityDA().getOpenOpportunitiesByReferralAccountId(refAcct.Id);
        System.assertEquals(1,returnOpportunities.size());
        
    } // getOpenOpportunitiesByReferralAccountId

    @IsTest
    static void getOpenOpportunitiesByReferralContactId() {
        Referral_Contact__c refCtct = ObjectBannerAuraServiceTest.getTestRefCtct();
        List<Opportunity> returnOpportunities = new OpportunityDA().getOpenOpportunitiesByReferralContactId(refCtct.Id);
        System.assertEquals(1,returnOpportunities.size());

    } // getOpenOpportunitiesByReferralContactId

    @IsTest
    static void getOpportunityById() {
        Opportunity opp = ObjectBannerAuraServiceTest.getTestOpp();
        List<Opportunity> returnOpportunities = new OpportunityDA().getOpportunityById(opp.Id);
        System.assertEquals(1,returnOpportunities.size());
        System.assertEquals(opp.Id, returnOpportunities[0].Id);
    } // getOpportunityById

    @isTest
    static void testCommunityUser(){
        Account acct = new Account(Name='test');
        insert acct;
        Contact ctct = new Contact(FirstName='test',LastName='test',AccountId=acct.Id,email='test@test.test');    
        insert ctct;
        Profile prof = [SELECT Id FROM Profile where name='Customer Community Login User Clone'];
        User u = new User(
        	UserName = 'testOppDACommUser@test.testtesttest',
            FirstName = ctct.FirstName,
            LastName = ctct.LastName,
            Alias = 'tDAest',
            email = ctct.Email,
            ContactId = ctct.Id,
            ProfileId = prof.Id,
            EmailEncodingKey = 'UTF-8',
            CommunityNickname = 'tesDAt',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            Sales_Org__c = 'PAS');
        insert u;
        Opportunity opp = new Opportunity(AccountId=acct.Id,CloseDate=date.today(),StageName='Pending',Name='test');
        insert opp;
        OpportunityDA da= new OpportunityDA();
        Opportunity oppRet = da.getOpportunityInfo(opp.Id);
        system.assert(oppRet!=null);
        User uRet = da.getPortalUsersByOpportunityId(acct.Id);
        system.assert(uRet!=null);
        
    } // testCommunityUser

} // class OpportunityDATest