force-app/main/default/objects/Contact/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Franchise National Account referral account.</inlineHelpText>
    <label>Referral National Account</label>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>not really used anywhere, as of 4/19/2013 is blank for all production records</description>
    <label>Referral Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Contact__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>R00N50000001WySDEA0</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/Referral_Account__c.object-meta.xml
<CustomObject>
    <description>Referral Source Company Information</description>
    <label>Referral Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Referral Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Account__c/fields/CPA_Program_Status__c.field-meta.xml
<CustomField>
    <fullName>CPA_Program_Status__c</fullName>
    <label>CPA Program Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>No Longer In Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral_Account__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/Referral_Contact__c.object-meta.xml
<CustomObject>
    <label>Referral Contact</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Referred</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Referral_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/CPA_Program_status__c.field-meta.xml
<CustomField>
    <fullName>CPA_Program_status__c</fullName>
    <label>CPA Program status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Unenrolled/no longer in Program</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Referral Contact Email</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Account__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Referral Contacts</relationshipLabel>
    <relationshipName>Referral_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Community_User_First_Login__c.field-meta.xml
<CustomField>
    <fullName>Community_User_First_Login__c</fullName>
    <description>Created as a part of US38( When community user logins for the first time)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Community User First Login</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User/fields/Requested_Invite_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Invite_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Requested Invite Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CPAEmailServiceHandler.cls
/*
 * 01/13/2023  Josh Cartwright Created - used to write back to the referral contact during CPA enrollment in Accountant Program Portal 
 * 
 * */
global class CPAEmailServiceHandler implements Messaging.InboundEmailHandler {
/**
 * When an email is submitted, an email will kick off the process for a particular record id.
 */
   global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
      // Create an InboundEmailResult object for returning the result of the  Apex Email Service
      Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
       system.debug('JC email.plainTextBody' + email.plainTextBody);
      id userId = email.plainTextBody.left(18);
       
       User[] users = [Select Id, Name, FirstName, LastName
                        ,UserRoleId
                        ,ContactId
                        ,email
                        ,Community_User_First_Login__c
                        ,IsActive
                        ,Requested_Invite_Date__c
                        From User
                        Where Id =: userId];
        
        System.debug('doPost users='+users.size());
        Map<Id, User> userMap = new Map<Id, User>();
        for(User userObj : users) {
            if(String.isNotBlank(userObj.ContactId)) {
                userMap.put(userObj.ContactId, userObj);
            }
        }
        System.debug('updateCPAProgStatus userMap:'+userMap);
        if(!userMap.isEmpty()) {
            List<Referral_Contact__c> refContListForUpdate = new List<Referral_Contact__c>();
            for(Referral_Contact__c refCont : [SELECT Id, Name, Contact__c, email__c, CPA_Program_status__c, Referral_Account__c FROM Referral_Contact__c WHERE Contact__c IN :userMap.keySet()]) {
                System.debug('updateCPAProgStatus refCont:'+refCont);
                System.debug('updateCPAProgStatus refCont CPA_Program_status__c:'+refCont.CPA_Program_status__c);
                
                if(userMap.containsKey(refCont.Contact__c)) {
                    User userObj = userMap.get(refCont.Contact__c);
                    if(userObj.email != refCont.Email__c ){
                        refCont.email__c = userObj.Email; 
                    }
                    if(userObj.Community_User_First_Login__c != null && userObj.IsActive && refCont.CPA_Program_status__c !=null && refCont.CPA_Program_status__c == 'Invited') {
                        refCont.CPA_Program_status__c = 'Enrolled';
                        refContListForUpdate.add(refCont);
                    }
                    else if(userObj.IsActive == false) {
                        refCont.CPA_Program_status__c = 'Unenrolled/no longer in Program'; 
                        refContListForUpdate.add(refCont);
                    }
                    else if(userObj.Requested_Invite_Date__c != null && userObj.Community_User_First_Login__c == null) {
                        refCont.CPA_Program_status__c = 'Invited';
                        refContListForUpdate.add(refCont);
                    }
                    else if(userObj.Requested_Invite_Date__c == null) {
                        refCont.CPA_Program_status__c = null;
                        refContListForUpdate.add(refCont);
                    }
                    else {
                        refCont.CPA_Program_status__c = null;
                        refContListForUpdate.add(refCont);
                    }
                    System.debug('refContListForUpdate:'+refContListForUpdate);
                }
            }
            if(!refContListForUpdate.isEmpty()) {
                Database.update(refContListForUpdate,false);
            }
        }
      return result;
   } // handleInboundEmail
   
} // class CPAEmailServiceHandler