force-app/main/default/objects/Contact/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Franchise National Account referral account.</inlineHelpText>
    <label>Referral National Account</label>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>not really used anywhere, as of 4/19/2013 is blank for all production records</description>
    <label>Referral Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Contact__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>R00N50000001WySDEA0</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/Referral_Account__c.object-meta.xml
<CustomObject>
    <description>Referral Source Company Information</description>
    <label>Referral Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Referral Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Account__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/fields/Referral_Source_Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Referral_Source_Business_Type__c</fullName>
    <description>Please notify Dan C before adding/changing values in this picklist. This is used in the WAR integration and if the mapping isn&apos;t correct the records won&apos;t sync.</description>
    <label>Referral Source Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting Firm</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Broker Dealer</fullName>
            </value>
            <value>
                <fullName>Broker Dealer Branch</fullName>
            </value>
            <value>
                <fullName>Business Consultant</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Full Service Agency</fullName>
            </value>
            <value>
                <fullName>Health Insurance Broker</fullName>
            </value>
            <value>
                <fullName>Insurance Broker</fullName>
            </value>
            <value>
                <fullName>Insurance Carrier</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>MSP Partner</fullName>
            </value>
            <value>
                <fullName>National Account</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paychex Co</fullName>
            </value>
            <value>
                <fullName>Payroll Company</fullName>
            </value>
            <value>
                <fullName>PEO Broker</fullName>
            </value>
            <value>
                <fullName>Private Equity Firm</fullName>
            </value>
            <value>
                <fullName>P&amp;C Broker</fullName>
                <label>Property and Casualty Broker</label>
            </value>
            <value>
                <fullName>Strategic Account</fullName>
            </value>
            <value>
                <fullName>Strategic Accountant Firm</fullName>
            </value>
            <value>
                <fullName>Trusted Advisor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral_Account__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State/Province</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/fields/Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>Street_Address_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Street Address 1</label>
    <length>132</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/Referral_Contact__c.object-meta.xml
<CustomObject>
    <label>Referral Contact</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Contact__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>Referral_Account__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Pulled from the Referral Account</inlineHelpText>
    <label>Referral Account City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Referral Contact Phone</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Account__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Referral Contacts</relationshipLabel>
    <relationshipName>Referral_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Contact__c/fields/Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>Street_Address_1__c</fullName>
    <formula>Referral_Account__r.Street_Address_1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Pulled from the Referral Account</inlineHelpText>
    <label>Referral Account Street Address 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeletedItems.cls
/*
 *    Retrieves the user's deleted events, prospect/clients, referral accounts, contacts, referral contacts
 
    07/06/2020  Jacob Hinds         Added without sharing per PMD
 *
 */

@RestResource(urlMapping='/deletedItems/*')
global without sharing class DeletedItems
{
    @HttpGet
    global static Item getDeletedItems()
    {
        Item it = new Item();
        DateTime modifiedDate = null;
    
        try
        {
            String modifiedDate_str = '';
            if (RestContext.request != null)
            {
                modifiedDate_str = RestContext.request.params.get('date');
                modifiedDate = getModifiedDate(modifiedDate_str);
            }
        }
        catch(Exception e)
        {
            //if there is an error, return empty 
            it.errors.add(new Error('param', e.getMessage()));
            return it;
        }
        
        return getItems(modifiedDate);
    }
    
    global static DateTime getModifiedDate(String modifiedDate)
    {
        if (!String.isBlank(modifiedDate))
        {
            //convert the UTC date to something parseable by the valueOf() method
            modifiedDate = modifiedDate.replaceAll('T', ' ').substringBefore('.');
        }
        else
        {
            return null;
        }
        
        return DateTime.valueOfGmt(modifiedDate);
    }
    
    global static Item getItems(DateTime modifiedDate)
    {
        Item it = new Item();
    
        try
        {
            for (Event e : [SELECT Id, LastModifiedDate FROM Event WHERE IsDeleted = true AND LastModifiedDate >=: modifiedDate AND OwnerId =: UserInfo.getUserId() ALL ROWS])
            {
                it.results.add(new Result('Event', e.Id, e.LastModifiedDate));
            }
        }
        catch (Exception e)
        {
            it.errors.add(new Error('Event', e.getMessage()));
        }

        try
        {
            for (Account e : [SELECT Id, LastModifiedDate FROM Account WHERE IsDeleted = true AND LastModifiedDate >=: modifiedDate AND OwnerId =: UserInfo.getUserId() ALL ROWS])
            {
                it.results.add(new Result('Account', e.Id, e.LastModifiedDate));
            }
        }
        catch (Exception e)
        {
            it.errors.add(new Error('Account', e.getMessage()));
        }
        
        try
        {
            for (Referral_Account__c e : [SELECT Id, LastModifiedDate FROM Referral_Account__c WHERE IsDeleted = true AND LastModifiedDate >=: modifiedDate AND OwnerId =: UserInfo.getUserId() ALL ROWS])
            {
                it.results.add(new Result('Referral_Account__c', e.Id, e.LastModifiedDate));
            }
        }
        catch (Exception e)
        {
            it.errors.add(new Error('Referral_Account__c', e.getMessage()));
        }
        
        try
        {
            for (Contact e : [SELECT Id, LastModifiedDate FROM Contact WHERE IsDeleted = true AND LastModifiedDate >=: modifiedDate AND OwnerId =: UserInfo.getUserId() ALL ROWS])
            {
                it.results.add(new Result('Contact', e.Id, e.LastModifiedDate));
            }
        }
        catch (Exception e)
        {
            it.errors.add(new Error('Contact', e.getMessage()));
        }
        
        try
        {
            for (Referral_Contact__c e : [SELECT Id, LastModifiedDate FROM Referral_Contact__c WHERE IsDeleted = true AND LastModifiedDate >=: modifiedDate AND OwnerId =: UserInfo.getUserId() ALL ROWS])
            {
                it.results.add(new Result('Referral_Contact__c', e.Id, e.LastModifiedDate));
            }
        }
        catch (Exception e)
        {
            it.errors.add(new Error('Referral_Contact__c', e.getMessage()));
        }
        
        return it;
    }
    
    global class Item
    {
        List<Result> results = new List<Result>();
        List<Error> errors = new List<Error>();
    }
    
    global class Result
    {
        String objectType = '';
        String id = '';
        DateTime modifiedDate = null;
        
        global Result(String objectType, String id, DateTime modifiedDate)
        {
            this.objectType = objectType;
            this.id = id;
            this.modifiedDate = modifiedDate;
        }
    }
    
    global class Error
    {
        String objectType = '';
        String message = '';
        
        global Error(String objectType, String message)
        {
            this.objectType = objectType;
            this.message = message;
        }
    }
    
    @isTest
    global static void test_invokePOJO()
    {
        Error e = new Error('', '');
    }
    
    @isTest
    global static void test_noDate()
    {
        Account a = new Account(Name = 'Name');
        insert a;
        delete a;
        
        Test.startTest();
        Item it = getDeletedItems();
        Test.stopTest();
        
        System.assertEquals(1, it.results.size());
        System.assertEquals(a.Id, it.results[0].id);
        System.assertEquals(0, it.errors.size());
    }
    
    @isTest
    global static void test_getModifiedDate()
    {
        DateTime result1 = getModifiedDate('');
        System.assertEquals(null, result1);
        
        DateTime result2 = getModifiedDate('2013-05-27T18:36:40.000Z');
        System.assertEquals(DateTime.newInstanceGmt(2013,5,27,18,36,40), result2);
    }
    
    @isTest
    global static void test_AccountNoDate()
    {
        Account a = new Account(Name = 'Name');
        insert a;
        delete a;
        
        DateTime dt = null;
        
        Test.startTest();
        Item it = getItems(dt);
        Test.stopTest();
        
        System.assertEquals(1, it.results.size());
        System.assertEquals(a.Id, it.results[0].id);
        System.assertEquals(0, it.errors.size());
    }
    
    @isTest
    global static void test_deletedEvent()
    {
        Account a = new Account(Name = 'Name');
        insert a;
        
        Event e = new Event(WhatId = a.Id, StartDateTime = DateTime.now(), EndDateTime = DateTime.now().addHours(2));
        insert e;
        
        DateTime dt = DateTime.now().addMinutes(-1);
        
        Item it1 = getItems(dt);
        System.assertEquals(0, it1.results.size());
        System.assertEquals(0, it1.errors.size());
        
        delete e;
        Event[] events = [SELECT Id, LastModifiedDate FROM Event WHERE Id =: e.Id ALL ROWS];
        
        Item it2 = getItems(dt);
        System.assertEquals(0, it2.errors.size());
        System.assertEquals(1, it2.results.size());
        System.assertEquals('Event', it2.results[0].objectType);
        System.assertEquals(events[0].Id, it2.results[0].id);
        System.assertEquals(events[0].LastModifiedDate, it2.results[0].modifiedDate);
    }
    
    @isTest
    global static void test_deletedAccount()
    {
        Account a = new Account(Name = 'Name');
        insert a;
        
        DateTime dt = DateTime.now().addMinutes(-1);
        
        Item it1 = getItems(dt);
        System.assertEquals(0, it1.results.size());
        System.assertEquals(0, it1.errors.size());
        
        delete a;
        Account[] accts = [SELECT Id, LastModifiedDate FROM Account WHERE Id =: a.Id ALL ROWS];
        
        Item it2 = getItems(dt);
        System.assertEquals(0, it2.errors.size());
        System.assertEquals(1, it2.results.size());
        System.assertEquals('Account', it2.results[0].objectType);
        System.assertEquals(accts[0].Id, it2.results[0].id);
        System.assertEquals(accts[0].LastModifiedDate, it2.results[0].modifiedDate);
    }
        
    @isTest
    global static void test_deletedContact()
    {
        Account a = new Account(Name = 'Name');
        insert a;
        
        Contact c = new Contact(LastName = 'LastName', AccountId = a.Id);
        insert c;
        
        DateTime dt = DateTime.now().addMinutes(-1);
        
        Item it1 = getItems(dt);
        System.assertEquals(0, it1.errors.size());
        System.assertEquals(0, it1.results.size());
        
        delete c;
        Contact[] contacts = [SELECT Id, LastModifiedDate FROM Contact WHERE Id =: c.Id ALL ROWS];
        
        Item it2 = getItems(dt);
        System.assertEquals(0, it2.errors.size());
        System.assertEquals(1, it2.results.size());
        System.assertEquals('Contact', it2.results[0].objectType);
        System.assertEquals(contacts[0].Id, it2.results[0].id);
        System.assertEquals(contacts[0].LastModifiedDate, it2.results[0].modifiedDate);
    }
    
    @isTest
    global static void test_deletedReferralAccount()
    {
        Referral_Account__c a = new Referral_Account__c(Name = 'Name', Referral_Source_Business_Type__c = 'Broker', Street_Address_1__c = '123 Main St', City__c = 'city', State_Province__c = 'il', Zip_Postal_Code__c = '60606');
        insert a;
        
        DateTime dt = DateTime.now();
        
        Item it1 = getItems(dt);
        System.assertEquals(0, it1.results.size());
        System.assertEquals(0, it1.errors.size());
        
        delete a;
        Referral_Account__c[] accts = [SELECT Id, LastModifiedDate FROM Referral_Account__c WHERE Id =: a.Id ALL ROWS];
        
        Item it2 = getItems(dt);
        System.assertEquals(0, it2.errors.size());
        System.assertEquals(1, it2.results.size());
        System.assertEquals('Referral_Account__c', it2.results[0].objectType);
        System.assertEquals(accts[0].Id, it2.results[0].id);
        System.assertEquals(accts[0].LastModifiedDate, it2.results[0].modifiedDate);
    }
    
    @isTest
    global static void test_deletedReferralContact()
    {
        Referral_Account__c a = new Referral_Account__c(Name = 'Name', Referral_Source_Business_Type__c = 'Broker', Street_Address_1__c = '123 Main St', City__c = 'city', State_Province__c = 'il', Zip_Postal_Code__c = '60606');
        insert a;
        
        Referral_Contact__c c = new Referral_Contact__c(Name = 'LastName', Referral_Account__c = a.Id, Phone__c = '1233454567');
        insert c;
        
        DateTime dt = DateTime.now().addMinutes(-1);
        
        Item it1 = getItems(dt);
        System.assertEquals(0, it1.errors.size());
        System.assertEquals(0, it1.results.size());
        
        delete c;
        Referral_Contact__c[] contacts = [SELECT Id, LastModifiedDate FROM Referral_Contact__c WHERE Id =: c.Id ALL ROWS];
        
        Item it2 = getItems(dt);
        System.assertEquals(0, it2.errors.size());
        System.assertEquals(1, it2.results.size());
        System.assertEquals('Referral_Contact__c', it2.results[0].objectType);
        System.assertEquals(contacts[0].Id, it2.results[0].id);
        System.assertEquals(contacts[0].LastModifiedDate, it2.results[0].modifiedDate);
    }
    
    @isTest
    global static void test_multiple()
    {
        Account a = new Account(Name = 'Name');
        insert a;
        
        Contact c = new Contact(LastName = 'LastName', AccountId = a.Id);
        insert c;
        
        DateTime dt = DateTime.now().addMinutes(-1);
        
        Item it1 = getItems(dt);
        System.assertEquals(0, it1.errors.size());
        System.assertEquals(0, it1.results.size());
        
        delete c;
        delete a;
        
        Item it2 = getItems(dt);
        System.assertEquals(0, it2.errors.size());
        System.assertEquals(2, it2.results.size());
    }
}