force-app/main/default/objects/Contact/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Franchise National Account referral account.</inlineHelpText>
    <label>Referral National Account</label>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>not really used anywhere, as of 4/19/2013 is blank for all production records</description>
    <label>Referral Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Contact__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>R00N50000001WySDEA0</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Referral Account of the Referral Contact at the time of the Opportunity. This is so we know at a company level the referrals made, even if the contact changes companies.</description>
    <inlineHelpText>The Referral Account of the Referral Contact at the time of the Opportunity.</inlineHelpText>
    <label>Referral Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Account__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referral_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field should only be completed if the Lead Source is an external partner (CPA, Bank, FA, etc.)</inlineHelpText>
    <label>Referral Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Contact__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Referral Contacts with End Dates will only appear if you click the Show All Results link below.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Contact__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>OppRCs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Account__c/Referral_Account__c.object-meta.xml
<CustomObject>
    <description>Referral Source Company Information</description>
    <label>Referral Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Referral Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Accounts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Contact__c/Referral_Contact__c.object-meta.xml
<CustomObject>
    <label>Referral Contact</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Contact__c/fields/Referral_Account__c.field-meta.xml
<CustomField>
    <fullName>Referral_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referral Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referral_Account__c.End_Date__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>Search results exclude records with an end date.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referral_Account__c</referenceTo>
    <relationshipLabel>Referral Contacts</relationshipLabel>
    <relationshipName>Referral_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ActivityDATest.cls
/* 

  History
  -------
  03/22/2022 Dan Carmen          Cleaned up code

 */
@IsTest
private class ActivityDATest {
    @testSetup
    public static void setupData() {
        ObjectBannerAuraServiceTest.setupData();
        UserHelperTest.setupSalesOrgSetting();
    } // setupData
    
    @IsTest
    static void testGetOpenActivities() {
       Contact ctct = ObjectBannerAuraServiceTest.getTestCtct();
       ActivityDA.ActivityCombined[] expectedActivities = ActivityDA.getOpenActivities(ctct.Id);
       System.assertEquals(true, expectedActivities.size() > 0);
 
       Account acct = ObjectBannerAuraServiceTest.getTestAcct();
       expectedActivities = ActivityDA.getOpenActivities(acct.Id);
       System.assertEquals(true, expectedActivities.size() > 0);
        
       Referral_Account__c refAcct = ObjectBannerAuraServiceTest.getTestRefAcct();
       expectedActivities = ActivityDA.getOpenActivities(refAcct.Id);
       System.assertEquals(true, expectedActivities.size() > 0);

       Referral_Contact__c refCtct = ObjectBannerAuraServiceTest.getTestRefCtct();
       expectedActivities = ActivityDA.getOpenActivities(refCtct.Id);
       System.assertEquals(true, expectedActivities.size() > 0);

       Opportunity opp = ObjectBannerAuraServiceTest.getTestOpp();
       expectedActivities = ActivityDA.getOpenActivities(opp.Id);
       System.assertEquals(true, expectedActivities.size() > 0);

    } // testGetOpenActivities

    @IsTest
    static void testInitialPresentations() {
        Opportunity opp = ObjectBannerAuraServiceTest.getTestOpp();
        
        List<Event> returnEvents = new ActivityDA().getInitialPresentationEventsByOpportunityId(opp.Id);
        System.assertEquals(returnEvents.size(), 1);
        System.assertEquals(returnEvents[0].Type, 'Presentation - Initial');
    } // getInitialPresenetationEventsByOpportunityId_GivenOpportunityId_ReturnsAllInitialPresentationEvents

    @IsTest
    static void testContactRoles() {
        Opportunity opp = ObjectBannerAuraServiceTest.getTestOpp();
        List<OpportunityContactRole> returnContactRoles = new ActivityDA().getContactRolesByOpportunityId(opp.Id);
        System.debug('return contact roles: ' + returnContactRoles);

        System.assertEquals(returnContactRoles.size(), 1);
    } // getContactRolesByOpportunityId_GivenOpportunityId_ReturnsAllContactRoles

    static testMethod void testActivityCombined() {
       Task tsk = new Task(Subject='Test', ActivityDate=Date.today());
       ActivityDA.ActivityCombined act = new ActivityDA.ActivityCombined(tsk);
       System.assertEquals(null,act.recId);
       System.assertEquals(Date.today(), act.activityDate);
       System.assertEquals('Task',act.type);
       System.assertEquals('Test',act.subject);
       System.assertEquals(null,act.whoId);
       System.assertEquals(null,act.whatId);
       //String whoName = act.whoName;
       //String whatName = act.whatName;
       System.assertEquals(null,act.whoLink);
       System.assertEquals(null,act.whatLink);
        
    }
} // class ActivityDATest