force-app/main/default/objects/PEO_Onboarding_Checklist__c/PEO_Onboarding_Checklist__c.object-meta.xml
<CustomObject>
    <label>PEO Underwriting Checklist</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PEO Underwriting Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PEO Underwriting Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Industry_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Industry_Record_Types__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Industry Record Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Peo_IndSpecific_formStatus__c.field-meta.xml
<CustomField>
    <fullName>Peo_IndSpecific_formStatus__c</fullName>
    <label>ISQ Form Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/Prospect_Client__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup to the related account.</description>
    <label>Prospect-Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>PEO_Onboarding_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TriggerSetupClasses__c/TriggerSetupClasses__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The classes that are executed as part of each trigger execution</description>
    <label>Trigger Setup Classes</label>
</CustomObject>

force-app/main/default/objects/WC_Questionnaire_Industry_Specific__c/WC_Questionnaire_Industry_Specific__c.object-meta.xml
<CustomObject>
    <description>this to hold industry specific questions</description>
    <label>WC Questionnaire Industry Specific</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>WC Questionnaire industry Specific Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WC Questionnaire Industry Specific</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WC_Questionnaire_Industry_Specific__c/fields/Peo_IndSpecific_formStatus__c.field-meta.xml
<CustomField>
    <fullName>Peo_IndSpecific_formStatus__c</fullName>
    <label>Peo_IndSpecific_formStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Questionnaire_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WC_Questionnaire_Industry_Specific__c/fields/PEO_Underwriting_Checklist__c.field-meta.xml
<CustomField>
    <fullName>PEO_Underwriting_Checklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PEO Underwriting Checklist</label>
    <referenceTo>PEO_Onboarding_Checklist__c</referenceTo>
    <relationshipLabel>WC Questionnaire Industry Specific</relationshipLabel>
    <relationshipName>WC_Questionnaire_Industry_Specific</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Questionnaire_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <masterLabel>Questionnaire_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WCQuestionnaireIndustrySpecificAfterTest.cls
/* After Trigger Test class for WC Questionnaire Industry Specific object
*
*   HISTORY
*  ---------
*   08/12/2021  Matt Fritschi     Created
    02/10/2022  Jake Hinds        Status to checklist

*/

@IsTest
public class WCQuestionnaireIndustrySpecificAfterTest {

    @testSetup
    public static void setup(){
        
        TriggerSetupClasses__c[] classes = new TriggerSetupClasses__c[]{};
        TriggerMethodsTest.createTriggerSetting('WCQuestionnaireIndustrySpecific', false, true, false, true, new String[]{'WCQuestionnaireIndustrySpecificAfter'}, classes, TriggerMethods.INTERFACE_C);
        insert classes;
        
        RecordTypeHelperTest.setupRecordType();
        Id acctRTMMS = RecordTypeHelper.getRecordType(RecordTypeHelper.MMS_ACCOUNT,ObjectHelper.OBJECT_ACCOUNT).getRecordTypeId();
        
        Account acc = new Account();
        acc.Name = 'Peo test';
        acc.RecordTypeId = acctRTMMS;
        insert acc; 
        
        Contact c = new Contact(AccountId=acc.id,
                               FirstName = 'Test1',
                               LastName = 'Contact',
                               Email='testing@testing.com');
        List<Contact> ctctList = new List<Contact>();
        ctctList.add(c);
        insert ctctList;
        
        PEO_Onboarding_Checklist__c peo = new PEO_Onboarding_Checklist__c();
        peo.Prospect_Client__c=acc.id;
        peo.Name='testing Peo';
        insert peo;
        
    }
    
    public static testMethod void setFieldsOnChildren(){
        
        PEO_Onboarding_Checklist__c parentChecklist = [SELECT Id, Name, Industry_Record_Types__c FROM PEO_Onboarding_Checklist__c WHERE Name = 'testing Peo'];
        
        RecordType recType = [SELECT Id, Name from RecordType WHERE sObjectType='WC_Questionnaire_Industry_Specific__c' AND Name != null LIMIT 1];
        
        WC_Questionnaire_Industry_Specific__c indSpecific = new WC_Questionnaire_Industry_Specific__c(PEO_Underwriting_Checklist__c = parentChecklist.Id, RecordTypeId = recType.Id);
        insert indSpecific;
            
        parentChecklist = [SELECT Id, Name, Industry_Record_Types__c FROM PEO_Onboarding_Checklist__c WHERE Id = :parentChecklist.Id];
        System.assertEquals('!.!' + recType.Name + '!.!', parentChecklist.Industry_Record_Types__c);
        
        RecordType recType2 = [SELECT Id, Name from RecordType WHERE sObjectType='WC_Questionnaire_Industry_Specific__c' AND Name != null AND Name != :recType.Name LIMIT 1];
        
        WC_Questionnaire_Industry_Specific__c indSpecific2 = new WC_Questionnaire_Industry_Specific__c(PEO_Underwriting_Checklist__c = parentChecklist.Id, RecordTypeId = recType2.Id);
        insert indSpecific2;
        
        parentChecklist = [SELECT Id, Name, Industry_Record_Types__c FROM PEO_Onboarding_Checklist__c WHERE Id = :parentChecklist.Id];
        System.assertEquals('!.!' + recType.Name + '!.!' + recType2.Name + '!.!', parentChecklist.Industry_Record_Types__c);
    }
    public static testMethod void testChecklistComplete(){
        
        Account acct1 = new Account(Name='test1');
        Account acct2 = new Account(Name='test2');
        insert new Account[]{acct1,acct2};
            
        PEO_Onboarding_Checklist__c checklist1 = new PEO_Onboarding_Checklist__c(Name='testCheck1',Prospect_Client__c = acct1.Id,Industry_Record_Types__c='!.!Test!.!');
        PEO_Onboarding_Checklist__c checklist2 = new PEO_Onboarding_Checklist__c(Name='testCheck2',Prospect_Client__c = acct2.Id,Industry_Record_Types__c='!.!Test!.!');
        insert new PEO_Onboarding_Checklist__c[]{checklist1,checklist2};
            
        WC_Questionnaire_Industry_Specific__c ind1Chk1 = new WC_Questionnaire_Industry_Specific__c(Name='ind1Chk1',PEO_Underwriting_Checklist__c=checklist1.Id);
        WC_Questionnaire_Industry_Specific__c ind2Chk1 = new WC_Questionnaire_Industry_Specific__c(Name='ind2Chk1',PEO_Underwriting_Checklist__c=checklist1.Id);
        WC_Questionnaire_Industry_Specific__c ind1Chk2 = new WC_Questionnaire_Industry_Specific__c(Name='ind2Chk1',PEO_Underwriting_Checklist__c=checklist2.Id);
        insert new WC_Questionnaire_Industry_Specific__c[]{ind1Chk1,ind2Chk1,ind1Chk2};
        
        test.startTest();
        ind1Chk1.Peo_IndSpecific_formStatus__c = 'Complete';
        ind1Chk2.Peo_IndSpecific_formStatus__c = 'Complete';
        update new WC_Questionnaire_Industry_Specific__c[]{ind1Chk1,ind1Chk2};
        
        PEO_Onboarding_Checklist__c uChecklist1 = [SELECT Id,Peo_IndSpecific_formStatus__c FROM PEO_Onboarding_Checklist__c WHERE Id =:checklist1.Id LIMIT 1];
        system.assertEquals(null,uChecklist1.Peo_IndSpecific_formStatus__c);
        PEO_Onboarding_Checklist__c uChecklist2 = [SELECT Id,Peo_IndSpecific_formStatus__c FROM PEO_Onboarding_Checklist__c WHERE Id =:checklist2.Id LIMIT 1];
        system.assertEquals('Complete',uChecklist2.Peo_IndSpecific_formStatus__c);
        
        delete ind1Chk2;
        uChecklist2 = [SELECT Id,Peo_IndSpecific_formStatus__c FROM PEO_Onboarding_Checklist__c WHERE Id =:checklist2.Id LIMIT 1];
        system.assertEquals(null,uChecklist2.Peo_IndSpecific_formStatus__c);
        test.stopTest();
    }
}