force-app/main/default/objects/PEO_Onboarding_Checklist__c/PEO_Onboarding_Checklist__c.object-meta.xml
<CustomObject>
    <label>PEO Underwriting Checklist</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PEO Underwriting Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PEO Underwriting Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PEO_Onboarding_Checklist__c/fields/state_with_most_employees__c.field-meta.xml
<CustomField>
    <fullName>state_with_most_employees__c</fullName>
    <description>In which states do you have the most employees?</description>
    <inlineHelpText>This field holds the state codes</inlineHelpText>
    <label>Which State has the most WSEs?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PEO_Onboarding_Medical_Questionnaire__c/PEO_Onboarding_Medical_Questionnaire__c.object-meta.xml
<CustomObject>
    <label>PEO Underwriting Medical Questionnaire</label>
    <nameField>
        <displayFormat>of-{0000}</displayFormat>
        <label>PEO Underwriting Medical Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PEO Underwriting Medical Questionnaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PEO_Onboarding_Medical_Questionnaire__c/fields/PEO_Onboarding_Checklist__c.field-meta.xml
<CustomField>
    <fullName>PEO_Onboarding_Checklist__c</fullName>
    <label>PEO Underwriting Checklist</label>
    <referenceTo>PEO_Onboarding_Checklist__c</referenceTo>
    <relationshipLabel>PEO Underwriting Medical Questionnaires</relationshipLabel>
    <relationshipName>PEO_Onboarding_Medical_Questionnaires</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CommunityAccountEditFormController.cls
/* 
* Controller for the PEO Edge CommunityAccountEditForm component
*
* History
* -------
* 08/19/2021    Ahmed Elawad   Created
*/

public without sharing class CommunityAccountEditFormController {
    
    // Saves the PEO Checklist record
    @AuraEnabled  
    public static Boolean savePeoOnboardingChecklist(PEO_Onboarding_Checklist__c peoOnbChecklist, String formName){ 
        return CommunityMethods.savePeoOnboardingChecklist(peoOnbChecklist, formName, 'CommunityAccountEditFormController');
    }
    
    // Save the medical questionnaire record
    @AuraEnabled
    public static Boolean saveMedicalQuestionnaire(PEO_Onboarding_Medical_Questionnaire__c rec, String formName) {
        return CommunityMethods.saveMedicalQuestionnaire(rec, formName, 'CommunityAccountEditFormController');
    }
    
    // save miltuple PEO_Onboarding_Medical_Questionnaire__c records.
    @AuraEnabled
    public static Boolean saveMedicalQuestionnaires(List<PEO_Onboarding_Medical_Questionnaire__c> recs, String formName) {
        return CommunityMethods.saveMedicalQuestionnaires(recs, formName, 'CommunityAccountEditFormController');
    }
    
    // Get the PEO onboarding checklist for the passed in Account ID
    @AuraEnabled
    public static PEO_Onboarding_Checklist__c getPEOOnboardingChecklist(Id accountId,PEO_Onboarding_Checklist__c oldChecklist, String formName) {
        return CommunityMethods.getPEOOnboardingChecklist(accountId, oldChecklist, formName, 'CommunityAccountEditFormController');
    }
    
    // Get the Medical Questionnaire for the passed in PEO Underwriting Checklist ID
    @AuraEnabled
    public static PEO_Onboarding_Medical_Questionnaire__c getMedicalQuestionnaire(Id peoUnderwritingChecklistId, String formName) {
        return CommunityMethods.getMedicalQuestionnaireForm(peoUnderwritingChecklistId, formName, 'CommunityAccountEditFormController');
    }
    
    // Save the account record
    // Update the CS location data if the updated account is a child in a multi ID
    // Returns the account that was updated without re-querying
     @AuraEnabled  
    public static Account saveThisAccount(Account acct, String formName){ 
        System.debug('Updating acct...');
        // handle the type conversion for the recieved acct record
        Integer numofEmps = acct.NumberOfEmployees;
        acct.NumberOfEmployees = numofEmps;
        try {
            update acct;
            String[] fldList = new String[]{};
                Schema.FieldSet oppFldSet = Schema.SObjectType.Account.fieldSets.PEO_Edge_Form_Fields;
            for (Schema.FieldSetMember fsm : oppFldSet.getFields()) {
                String fldName = fsm.getFieldPath();
                fldList.add(fldName);
            }
            String queryString = 'SELECT '
                + String.join(fldList,',') 
                +' FROM Account WHERE Id = \''+ acct.Id + '\' LIMIT 1';
            return Database.query(queryString);
        } catch(Exception e) {
            communityMethods.logCommunityError(e, 'saveThisAccount', 'CommunityAccountEditFormController',formName, new List<Account>{acct});
            return null;
        }
    }
    
    // retrieves the picklist values from the state_with_most_employees__c field on the PEO_Onboarding_Checklist__c OBJ
    // Returns the list as a map: {NY: New York, etc...}
    @AuraEnabled
    public static Map<String, String> getSelectOptions(String formName) {
        try {
            Map<String, String> options = new Map<String, String>();
            Schema.sObjectType objType = PEO_Onboarding_Checklist__c.getSObjectType();
            Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
            map < String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
            List<Schema.PicklistEntry> pList = fieldMap.get('state_with_most_employees__c').getDescribe().getPickListValues();
            for (Schema.PicklistEntry p: pList) {
                options.put(p.getValue(), p.getLabel());
            }
            return options;
        } catch(Exception e) {
            communityMethods.logCommunityError(e, 'getOptions', 'CommunityAccountEditFormController', formName, null);
        }
        return null;
    }
    
    @AuraEnabled
    public static Boolean checkIfBenchmarkValuesExist(Account account, PEO_Onboarding_Checklist__c checklist) {
        return communityMethods.checkIfBenchmarkValuesExist(account, checklist);
    }
    
    @AuraEnabled
    public static Map<String, Decimal> retrieveBenchmarkValues(PEO_Onboarding_Checklist__c checklist) {
        return communityMethods.retrieveBenchmarkValues(checklist);
    }
    
    @AuraEnabled
    public static Boolean checkBLSPermissions(Id userId, String benchMarkPermission){
        return communityMethods.checkBLSPermissions(userId, benchMarkPermission);
    }
    
}