force-app/main/default/objects/Organization_Structure__c/Organization_Structure__c.object-meta.xml
<CustomObject>
    <description>Organizational information such as Sales Office, Zone and Area for the Paychex Sales Orgs</description>
    <label>Organization Structure</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>District Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Structure__c/fields/Role_Area__c.field-meta.xml
<CustomField>
    <fullName>Role_Area__c</fullName>
    <description>The name of the Role at the Area level</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the Role at the Area level</inlineHelpText>
    <label>Role - Area</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/Role_District__c.field-meta.xml
<CustomField>
    <fullName>Role_District__c</fullName>
    <description>The name of the Role for the district.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the Role for the district.</inlineHelpText>
    <label>Role - District</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/Role_Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Role_Sales_Office__c</fullName>
    <description>The name of the Role for the sales office.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the Role for the sales office.</inlineHelpText>
    <label>Role - Sales Office</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/Role_Zone__c.field-meta.xml
<CustomField>
    <fullName>Role_Zone__c</fullName>
    <description>The name of the Role at the zone level</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the Role at the zone level</inlineHelpText>
    <label>Role - Zone</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/RoleId_Area__c.field-meta.xml
<CustomField>
    <fullName>RoleId_Area__c</fullName>
    <description>The Id of the Role at the Area level</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Id of the Role at the Area level</inlineHelpText>
    <label>RoleId - Area</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/RoleId_District__c.field-meta.xml
<CustomField>
    <fullName>RoleId_District__c</fullName>
    <description>The Id of the Role for the district.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Id of the Role for the district.</inlineHelpText>
    <label>RoleId - District</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/RoleId_Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>RoleId_Sales_Office__c</fullName>
    <description>The Id of the Role for the sales office.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Id of the Role for the sales office.</inlineHelpText>
    <label>RoleId - Sales Office</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/RoleId_Zone__c.field-meta.xml
<CustomField>
    <fullName>RoleId_Zone__c</fullName>
    <description>The Id of the Role at the Zone level</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Id of the Role at the Zone level</inlineHelpText>
    <label>RoleId - Zone</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrgStrcRole.cls
/* 
 * Set the Role Name and Id on the Organization Structure object
 *
 * History
 * -------
 * 09/14/2011 Dan Carmen   Created
   03/05/2012 Dan Carmen   Added logic to populate zone and area role information
   07/17/2012 Dan Carmen   Added change to order of profile check
   02/15/2013 Dan Carmen   Logic to populate the Cost Center field from the Sales Office Number if not populated
   08/01/2014 Dan Carmen   Commented out the role code because it's no longer needed.
   04/30/2020 Dan Carmen   Add code back in to maintain roles if needed.
 
 */
public with sharing class OrgStrcRole {

   public static void processStrcs(Organization_Structure__c[] strcs, Map<Id,Organization_Structure__c> oldMap) {

      Set<String> roleNameSet = new Set<String>();
      
      for (Organization_Structure__c strc : strcs) {
         // clear out the id fields
         strc.RoleId_District__c = null;
         strc.RoleId_Sales_Office__c = null;
         strc.RoleId_Zone__c = null;
         strc.RoleId_Area__c = null;
          
         if (String.isNotBlank(strc.Role_Sales_Office__c)) {
             roleNameSet.add(strc.Role_Sales_Office__c);
         }
         if (String.isNotBlank(strc.Role_District__c)) {
             roleNameSet.add(strc.Role_District__c);
         }
         if (String.isNotBlank(strc.Role_Zone__c)) {
             roleNameSet.add(strc.Role_Zone__c);
         }
         if (String.isNotBlank(strc.Role_Area__c)) {
             roleNameSet.add(strc.Role_Area__c);
         }
      } // for (Organization_Structure__c strc
       
      if (!roleNameSet.isEmpty()) {
         UserRole[] roles = [Select Id, Name from UserRole where Name in :roleNameSet];
         Map<String,UserRole> roleMap = new Map<String,UserRole>();
         for (UserRole role : roles) {
             roleMap.put(role.Name, role);
         }
         for (Organization_Structure__c strc : strcs) {
            if (String.isNotBlank(strc.Role_Sales_Office__c)) {
               UserRole role = roleMap.get(strc.Role_Sales_Office__c);
               if (role != null) {
                  strc.RoleId_Sales_Office__c = role.Id;
               }
            }
            if (String.isNotBlank(strc.Role_District__c)) {
               UserRole role = roleMap.get(strc.Role_District__c);
               if (role != null) {
                  strc.RoleId_District__c = role.Id;
               }
            }
            if (String.isNotBlank(strc.Role_Zone__c)) {
               UserRole role = roleMap.get(strc.Role_Zone__c);
               if (role != null) {
                  strc.RoleId_Zone__c = role.Id;
               }
            }
            if (String.isNotBlank(strc.Role_Area__c)) {
               UserRole role = roleMap.get(strc.Role_Area__c);
               if (role != null) {
                  strc.RoleId_Area__c = role.Id;
               }
            }
         }
      } // if (!roleNameSet.isEmpty
       
   } // processStrcs
         
} // class OrgStrcRole