force-app/main/default/objects/Reference_PEO__c/Reference_PEO__c.object-meta.xml
<CustomObject>
    <label>Reference PEO</label>
    <nameField>
        <displayFormat>PEO-{000000}</displayFormat>
        <label>Reference PEO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference PEOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_PEO_Discrepancy__c/Reference_PEO_Discrepancy__c.object-meta.xml
<CustomObject>
    <description>This will house discrepancies for the following groups : 
PEO New Business</description>
    <label>Reference PEO Discrepancy</label>
    <nameField>
        <displayFormat>Disc-{00000000}</displayFormat>
        <label>Discrepancy ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference PEO Discrepancies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_PEO_Discrepancy__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Additional Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Reference_PEO_Discrepancy__c/fields/Discrepancy_Area__c.field-meta.xml
<CustomField>
    <fullName>Discrepancy_Area__c</fullName>
    <label>Discrepancy Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Contractual</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>Payroll Issues</fullName>
            </value>
            <value>
                <fullName>Medical Underwriting</fullName>
            </value>
            <value>
                <fullName>Workers Comp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_PEO_Discrepancy__c/fields/Discrepancy_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Discrepancy_Sub_Type__c</fullName>
    <label>Discrepancy Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Discrepancy_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>&quot;Assigns Employee Numbers&quot; Marked &quot;No&quot;</fullName>
            </value>
            <value>
                <fullName>(Marital Status) &amp; (Exemptions) listed in addition to &quot;Exempt&quot; will default to S-0 unless new W4 received</fullName>
            </value>
            <value>
                <fullName>1st check date outside of submission guidelines</fullName>
            </value>
            <value>
                <fullName>401(k)</fullName>
            </value>
            <value>
                <fullName>401k Section not completed</fullName>
            </value>
            <value>
                <fullName>Account and/or Routing Numbers are cut off</fullName>
            </value>
            <value>
                <fullName>Accountholder&apos;s signature-cannot set up w/o signature or bank letter stating ee is on the acct.</fullName>
            </value>
            <value>
                <fullName>ACH Account</fullName>
            </value>
            <value>
                <fullName>Address Illegible</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Admin fee 0</fullName>
            </value>
            <value>
                <fullName>Admin fee doesn&apos;t match other common/controlled groups/parent</fullName>
            </value>
            <value>
                <fullName>Aflac</fullName>
            </value>
            <value>
                <fullName>Annual salary needed for requested Life Ins. enrollment</fullName>
            </value>
            <value>
                <fullName>Approval Expired- New MFF Needed</fullName>
            </value>
            <value>
                <fullName>Approval over 90 days</fullName>
            </value>
            <value>
                <fullName>Band Change Needed</fullName>
            </value>
            <value>
                <fullName>Bank Account/Routing number error</fullName>
            </value>
            <value>
                <fullName>Bank letter for Savings account</fullName>
            </value>
            <value>
                <fullName>BCP</fullName>
            </value>
            <value>
                <fullName>Benefit Class</fullName>
            </value>
            <value>
                <fullName>Benefits Insurance Class Code</fullName>
            </value>
            <value>
                <fullName>Benefit Worksheets missing</fullName>
            </value>
            <value>
                <fullName>Benefit Worksheets missing/incomplete</fullName>
            </value>
            <value>
                <fullName>Benefit Worksheets not signed</fullName>
            </value>
            <value>
                <fullName>Billing schedule indicates to bill setup fees but check received</fullName>
            </value>
            <value>
                <fullName>Branch Client Number</fullName>
            </value>
            <value>
                <fullName>Branch Client Number/Payroll Specialist Name</fullName>
            </value>
            <value>
                <fullName>Business structure not checked</fullName>
            </value>
            <value>
                <fullName>Cannot do flat $ amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_PEO_Discrepancy__c/fields/Discrepancy_Type__c.field-meta.xml
<CustomField>
    <fullName>Discrepancy_Type__c</fullName>
    <label>Discrepancy Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Discrepancy_Area__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>401(k)</fullName>
            </value>
            <value>
                <fullName>All Employee Paperwork Not Submitted with Deal</fullName>
            </value>
            <value>
                <fullName>Ancillary Products</fullName>
            </value>
            <value>
                <fullName>Back-up Docs</fullName>
            </value>
            <value>
                <fullName>Benefits Enrollment</fullName>
            </value>
            <value>
                <fullName>Benefits Worksheets</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Billing Schedule</fullName>
            </value>
            <value>
                <fullName>Billing Schedule Incorrect</fullName>
            </value>
            <value>
                <fullName>COI Missing/Incorrect/Incomplete</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Compliance Page</fullName>
            </value>
            <value>
                <fullName>CSA/PEO081</fullName>
                <label>CSA</label>
            </value>
            <value>
                <fullName>Deductions</fullName>
            </value>
            <value>
                <fullName>Direct Deposit</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>EE Information</fullName>
            </value>
            <value>
                <fullName>EE Paperwork</fullName>
            </value>
            <value>
                <fullName>Final Enrollment</fullName>
            </value>
            <value>
                <fullName>Final Underwriting</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Form 8973</fullName>
            </value>
            <value>
                <fullName>Fulfillment Center</fullName>
            </value>
            <value>
                <fullName>Health and Benefits</fullName>
            </value>
            <value>
                <fullName>Initial Quote</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Missing ESR Import Spreadsheet</fullName>
            </value>
            <value>
                <fullName>Missing PEO0365</fullName>
            </value>
            <value>
                <fullName>Missing Prior Wages</fullName>
            </value>
            <value>
                <fullName>Missing WC approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_PEO_Discrepancy__c/fields/HoldPayrollWillNotRun__c.field-meta.xml
<CustomField>
    <fullName>HoldPayrollWillNotRun__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payroll Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reference_PEO_Discrepancy__c/fields/NonHoldPayrollWillRun__c.field-meta.xml
<CustomField>
    <fullName>NonHoldPayrollWillRun__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non-Hold: Action Req - Payroll Will Run</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reference_PEO_Discrepancy__c/fields/Reference_PEO__c.field-meta.xml
<CustomField>
    <fullName>Reference_PEO__c</fullName>
    <label>Reference PEO</label>
    <referenceTo>Reference_PEO__c</referenceTo>
    <relationshipLabel>Reference PEO Discrepancies</relationshipLabel>
    <relationshipName>PEO_Discrepancies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org-Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>BenAdmin</fullName>
            </value>
            <value>
                <fullName>Benetrac</fullName>
            </value>
            <value>
                <fullName>BusDev</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Corporate Relations</fullName>
            </value>
            <value>
                <fullName>Dedicated Service Center</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise Service Center</fullName>
            </value>
            <value>
                <fullName>ESR</fullName>
            </value>
            <value>
                <fullName>EW</fullName>
            </value>
            <value>
                <fullName>Field Operations Core</fullName>
            </value>
            <value>
                <fullName>HNBF</fullName>
            </value>
            <value>
                <fullName>HROI</fullName>
            </value>
            <value>
                <fullName>HR Online</fullName>
            </value>
            <value>
                <fullName>HRS</fullName>
            </value>
            <value>
                <fullName>HRS 401K-S125</fullName>
            </value>
            <value>
                <fullName>HRS Premier</fullName>
            </value>
            <value>
                <fullName>Icon</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Merchant Services</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MMS Hub</fullName>
            </value>
            <value>
                <fullName>MPSC</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RefPEOSummaryViewControllerTest.cls
/**
 * 07/07/2016 Lynn Michels		created
 * 05/04/2017 Carrie Marciano	Added SB to end of profile names
 */
@isTest
private class RefPEOSummaryViewControllerTest {

	//make sure the correct field set displays for a user not Sales or HRG
    static testMethod void testAnyUser() {
	    Reference_PEO__c rp = new Reference_PEO__c();
	    insert rp;
	    Test.SetCurrentPageReference(Page.ReferencePEODiscrepancy);
	    ApexPages.Standardcontroller sc1 = New ApexPages.StandardController(rp);
	    System.CurrentPageReference().getParameters().put('id',rp.Id);
	    RefPEOSummaryViewController refSummaryController = new RefPEOSummaryViewController(sc1);
	      
	    system.assert(rp.id != null);
	    refSummaryController.fieldList();
	    refSummaryController.getFieldSetFields();
	    system.assertEquals('HRG_Summary_Set', refSummaryController.fieldSet);
    } 
    
    //make sure the correct fields display for HRG user
     static testMethod void testHRGUser() {
     	Profile p = [SELECT Id FROM Profile WHERE Name='HRS Sales Manager - SB'];
      	User u = new User(Alias = 'hrguser', Email='hrguser@testorg.com',
				      	EmailEncodingKey='UTF-8', LastName='Hrg', LanguageLocaleKey='en_US',
				      	LocaleSidKey='en_US', ProfileId = p.Id,Sales_Org__c='HRS',
				      	TimeZoneSidKey='America/Los_Angeles', UserName='hrguser@testorg.com');
     	Reference_PEO__c rp = new Reference_PEO__c();
      	insert rp;
     	System.runAs(u){
    		
      		Test.SetCurrentPageReference(Page.RefPEOSummaryView);
      		ApexPages.Standardcontroller sc1 = New ApexPages.StandardController(rp);
      		System.CurrentPageReference().getParameters().put('id',rp.Id);
      		RefPEOSummaryViewController refSummaryController = new RefPEOSummaryViewController(sc1);
       		system.assert(rp.id != null);
       		refSummaryController.getFieldSetFields();
      	 	system.assertEquals('Sales_Summary_Set', refSummaryController.fieldSet);
     	}//end runAs
    } //end testHRGUser
    
    //make sure correct fields display for Sales user
    static testMethod void testSalesUser() {
     	Profile p = [SELECT Id FROM Profile WHERE Name='2008-09 HRS Premier Support Rep'];
      	User u = new User(Alias = 'salesa', Email='salesabc@testorg.com',
				      	EmailEncodingKey='UTF-8', LastName='salesabc', LanguageLocaleKey='en_US',
				      	LocaleSidKey='en_US', ProfileId = p.Id, EmployeeNumber = '12345', Sales_Org__c='HRS Premier',
				      	TimeZoneSidKey='America/Los_Angeles', UserName='salesabc@testorg.com');
		Reference_PEO__c rp = new Reference_PEO__c();
      	insert rp;
      				      	
     	System.runAs(u){
    		
      		Test.SetCurrentPageReference(Page.RefPEOSummaryView);
      		ApexPages.Standardcontroller sc1 = New ApexPages.StandardController(rp);
      		System.CurrentPageReference().getParameters().put('id',rp.Id);
      		RefPEOSummaryViewController refSummaryController = new RefPEOSummaryViewController(sc1);
       		system.assert(rp != null);
       		refSummaryController.getFieldSetFields();
      	 	system.assertEquals('HRG_Summary_Set', refSummaryController.fieldSet);
     	}//end runAs
    } //end testSalesUser
    
    //ensure the discrepencies are being found
    static testMethod void testWithDiscrepencies() {
     	Profile p = [SELECT Id FROM Profile WHERE Name='2008-09 HRS Premier Support Rep'];
      	User u = new User(Alias = 'salesd', Email='salesdef@testorg.com',
				      	EmailEncodingKey='UTF-8', LastName='salesdef', LanguageLocaleKey='en_US',
				      	LocaleSidKey='en_US', ProfileId = p.Id, EmployeeNumber = '67891', Sales_Org__c='HRS Premier',
				      	TimeZoneSidKey='America/Los_Angeles', UserName='salesdef@testorg.com');
		Reference_PEO__c rp = new Reference_PEO__c();
      	insert rp;		      	
	
	      Reference_PEO_Discrepancy__c disc1 = new Reference_PEO_Discrepancy__c();
	      disc1.Reference_PEO__c = rp.Id;
	      disc1.Discrepancy_Area__c = 'Test1';
	      disc1.Discrepancy_Type__c = 'Test Type 1';
	      disc1.Discrepancy_Sub_Type__c = 'Test Sub Type 1';
	      disc1.HoldPayrollWillNotRun__c = true;
	      disc1.NonHoldPayrollWillRun__c = true;
	      disc1.Additional_Information__c = 'This is additional information';
	      insert disc1;
	
	      Reference_PEO_Discrepancy__c disc2 = new Reference_PEO_Discrepancy__c();
	      disc2.Reference_PEO__c = rp.Id;
	      disc2.Discrepancy_Area__c = 'Test2';
	      disc2.Discrepancy_Type__c = 'Test Type 2';
	      disc2.Discrepancy_Sub_Type__c = 'Test Sub Type 2';
	      disc2.HoldPayrollWillNotRun__c = false;
	      disc2.NonHoldPayrollWillRun__c = false;
	      disc2.Additional_Information__c = 'This is more additional information';
	      insert disc2;
      
     	System.runAs(u){
      		Test.SetCurrentPageReference(Page.RefPEOSummaryView);
      		ApexPages.Standardcontroller sc1 = New ApexPages.StandardController(rp);
      		System.CurrentPageReference().getParameters().put('id',rp.Id);
      		RefPEOSummaryViewController refSummaryController = new RefPEOSummaryViewController(sc1);
       		system.assert(rp.id != null);
       		       system.debug('peo' + rp.id);
       		       system.assertEquals(rp.id, refSummaryController.refPEO.id);
       		
       		refSummaryController.getFieldSetFields();
      	 	system.assertEquals('HRG_Summary_Set', refSummaryController.fieldSet);
      	 	
      	 	List<Reference_PEO_Discrepancy__c> discrepList =  new List<Reference_PEO_Discrepancy__c>();
      	 	discrepList = refSummaryController.getPeoDiscrepancies();
      	 	system.assertEquals(2, discrepList.size()); 	
     	}//end runAs
    } //end testWithDiscrepencies
 
}