force-app/main/default/objects/Reference_PEO__c/Reference_PEO__c.object-meta.xml
<CustomObject>
    <label>Reference PEO</label>
    <nameField>
        <displayFormat>PEO-{000000}</displayFormat>
        <label>Reference PEO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference PEOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_PEO_Onboarding_Candidates__c/Reference_PEO_Onboarding_Candidates__c.object-meta.xml
<CustomObject>
    <label>Reference PEO Push</label>
    <nameField>
        <displayFormat>PEO-Push {000000}</displayFormat>
        <label>Reference PEO Push ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference PEO Push</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_PEO_Onboarding_Candidates__c/fields/Complete__c.field-meta.xml
<CustomField>
    <fullName>Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Complete?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reference_PEO_Onboarding_Candidates__c/fields/Employee_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Employee First Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_PEO_Onboarding_Candidates__c/fields/Employee_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Employee Last Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_PEO_Onboarding_Candidates__c/fields/Last4SSN__c.field-meta.xml
<CustomField>
    <fullName>Last4SSN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last4SSN</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_PEO_Onboarding_Candidates__c/fields/Reference_PEO_ID__c.field-meta.xml
<CustomField>
    <fullName>Reference_PEO_ID__c</fullName>
    <label>Reference PEO</label>
    <referenceTo>Reference_PEO__c</referenceTo>
    <relationshipName>Reference_PEO_Onboarding_Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RefPeoPaperEmpControllerTest.cls
/* The test methods for the RefPeoPaperEmpController.
 *
 * History
 * -------
 * 02/14/2017 Jermaine Stukes   Created
 *
 */
@isTest
public class RefPeoPaperEmpControllerTest {
    
    //Test addition of Paper Employee
    static testMethod void test_addPaperEmployee()
    {
        //Create Reference PEO
        Reference_PEO__c testPEO =  new Reference_PEO__c();
        insert testPEO;
        //Update Page Reference
        Test.SetCurrentPageReference(Page.ReferencePEODiscrepancy);
        ApexPages.Standardcontroller sc1 = New ApexPages.StandardController(testPEO);
        System.CurrentPageReference().getParameters().put('id',testPEO.Id);
        //Add Paper Employee
        Reference_PEO_Onboarding_Candidates__c OC = new Reference_PEO_Onboarding_Candidates__c();
        OC.Reference_PEO_ID__c = testPEO.Id;
        OC.Complete__c = true;
        OC.Employee_First_Name__c = 'Test';
        OC.Employee_Last_Name__c = 'Paper Candidate';
        OC.Last4SSN__c = '2222';
        
        RefPeoPaperEmpController testReference = new RefPeoPaperEmpController();
        testReference.OnboardingCandidate = OC;
        testReference.submitUpdates();
        OC.Complete__c = false;
        
        testReference.updateSave();

        //Verify Paper Employee added
        System.assertEquals(true, testReference.candidatesEntered);
        System.assertEquals(1, testReference.refOnCandidates.size());
    }
    
    //Test Removal of Paper Employee
    static testMethod void test_RemoveCandidate()
    {
        //Create Reference PEO
        Reference_PEO__c testPEO =  new Reference_PEO__c();
        insert testPEO;
        //Update Page Reference
        Test.SetCurrentPageReference(Page.ReferencePEODiscrepancy);
        ApexPages.Standardcontroller sc1 = New ApexPages.StandardController(testPEO);
        System.CurrentPageReference().getParameters().put('id',testPEO.Id);
        //Add Paper Employee
        RefPeoPaperEmpController testReference = new RefPeoPaperEmpController();
        //testReference.cancel();
        List<Reference_PEO_Onboarding_Candidates__c> ocList = new List<Reference_PEO_Onboarding_Candidates__c>();
        Reference_PEO_Onboarding_Candidates__c OC = new Reference_PEO_Onboarding_Candidates__c();
        OC.Reference_PEO_ID__c = testPEO.Id;
        OC.Complete__c = true;
        OC.Employee_First_Name__c = 'Test';
        OC.Employee_Last_Name__c = 'Paper Candidate';
        OC.Last4SSN__c = '1111';
        ocList.add(OC);
        Reference_PEO_Onboarding_Candidates__c OC2 = new Reference_PEO_Onboarding_Candidates__c();
        OC2.Reference_PEO_ID__c = testPEO.Id;
        OC2.Complete__c = true;
        OC2.Employee_First_Name__c = 'Test2';
        OC2.Employee_Last_Name__c = 'Paper Candidate';
        OC2.Last4SSN__c = '2222';
        ocList.add(OC2);
        Reference_PEO_Onboarding_Candidates__c OC3 = new Reference_PEO_Onboarding_Candidates__c();
        OC3.Reference_PEO_ID__c = testPEO.Id;
        OC3.Complete__c = true;
        OC3.Employee_First_Name__c = 'Test3';
        OC3.Employee_Last_Name__c = 'Paper Candidate';
        OC3.Last4SSN__c = '3333';
        ocList.add(OC3);
        insert ocList;
        testReference.refOnCandidates = ocList;
        testReference.removeEmp();
        //Verify Candidate is removed
        System.assertEquals(2, testReference.refOnCandidates.size());
    }
    
    //Test disabled buttons and additional Code Coverage 
    static testMethod void test_DisabledButtons()
    {
        //Create Reference PEO
        Reference_PEO__c testPEO =  new Reference_PEO__c();
        List<Reference_PEO_Onboarding_Candidates__c> ocList = new List<Reference_PEO_Onboarding_Candidates__c>();
        insert testPEO;
        //Update Page Reference
        Test.SetCurrentPageReference(Page.ReferencePEODiscrepancy);
        ApexPages.Standardcontroller sc1 = New ApexPages.StandardController(testPEO);
        System.CurrentPageReference().getParameters().put('id',testPEO.Id);
        RefPEODiscrepancyController rpdc = new RefPEODiscrepancyController(sc1);
        //Add Paper Employee
        RefPeoPaperEmpController testReference = new RefPeoPaperEmpController();
        
        
        Reference_PEO_Onboarding_Candidates__c OC = new Reference_PEO_Onboarding_Candidates__c();
        OC.Reference_PEO_ID__c = testPEO.Id;
        OC.Complete__c = true;
        OC.Employee_First_Name__c = 'first';
        OC.Employee_Last_Name__c = 'last';
        OC.Last4SSN__c = '2222';
        testReference.OnboardingCandidate = OC;
        testReference.Validate();
        //Verify Button not disabled
        System.assertEquals(false, testReference.disableButtons);
        //Misc code coverage
        testReference.cancel();
        testReference.quickSave();
        testReference.Updated();
        System.assertEquals(true, testReference.candidateUpdated);
        
    }
    

        
}