force-app/main/default/objects/PicklistDetail__c/PicklistDetail__c.object-meta.xml
<CustomObject>
    <description>A list of the picklist values by record types</description>
    <label>Picklist Detail</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Object-RT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PicklistDetail__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Was there an error processing this record?</inlineHelpText>
    <label>Error?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PicklistDetail__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The API name of the field.</inlineHelpText>
    <label>Field Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PicklistDetail__c/fields/NbrPicklistValues__c.field-meta.xml
<CustomField>
    <fullName>NbrPicklistValues__c</fullName>
    <inlineHelpText>How many picklist values were found for this combination?</inlineHelpText>
    <label>Nbr Picklist Values</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PicklistDetail__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The API name of the object</inlineHelpText>
    <label>Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PicklistDetail__c/fields/PicklistData__c.field-meta.xml
<CustomField>
    <fullName>PicklistData__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>List of all the picklist value for this field/record type combination</inlineHelpText>
    <label>Picklist Data</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PicklistDetail__c/fields/ProcessNotes__c.field-meta.xml
<CustomField>
    <fullName>ProcessNotes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Process Notes</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PicklistDetail__c/fields/RecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Id of the record type</inlineHelpText>
    <label>RecordTypeId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PicklistDetail__c/fields/RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the record type</inlineHelpText>
    <label>RecordType Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PicklistDetail__c/fields/ValuesLastUpdated__c.field-meta.xml
<CustomField>
    <fullName>ValuesLastUpdated__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The timestamp of when the values were last updated from the metadata.</inlineHelpText>
    <label>Values Last Updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/PicklistDetailWrapper.cls
/* 
 * Methods to help with PicklistDetail__c data. 
 *
 * History
 * -------
   07/17/2018 Dan Carmen         Add additional fields to the queries

 */
public with sharing class PicklistDetailWrapper {
    
    public Map<String,PicklistDetail__c> detailByFldMap = new Map<String,PicklistDetail__c>();
    public String[] fieldNames = new String[]{};
    public String objectName;
    public String recordTypeName;
    public RecordType rt = null;

    public PicklistDetailWrapper(PicklistDetail__c pkDetail) {
        objectName = pkDetail.ObjectName__c;
        recordTypeName = pkDetail.RecordTypeName__c;
        detailByFldMap.put(pkDetail.FieldName__c,pkDetail);
        fieldNames.add(pkDetail.FieldName__c);
    } // PicklistDetailWrapper


    public String getKey() {
        return objectName + recordTypeName;
    }

    public void addDetail(PicklistDetail__c pkDetail) {
        detailByFldMap.put(pkDetail.FieldName__c,pkDetail);
        fieldNames.add(pkDetail.FieldName__c);
    } // addDetail
    
    public void setRecordType(RecordType p_rt) {
        rt = p_rt;
        // make sure the record type id is set on the object.
        for (PicklistDetail__c pkDetail : detailByFldMap.values()) {
            pkDetail.RecordTypeId__c = rt.Id;
        }
    } // setRecordType
    
    public void setError(Boolean isError, String notesToAdd) {
        for (PicklistDetail__c pkDetail : detailByFldMap.values()) {
            pkDetail.Error__c = isError;
            addToProcessNotes(pkDetail, notesToAdd);
            if (isError) {
                pkDetail.NbrPicklistValues__c = 0;
                pkDetail.PicklistData__c = null;
                pkDetail.RecordTypeId__c = null;
                pkDetail.ValuesLastUpdated__c = Datetime.now();
            }
        }
    } // setError

    public void addToAllProcessNotes(String notesToAdd) {
        for (PicklistDetail__c pkDetail : detailByFldMap.values()) {
            addToProcessNotes(pkDetail, notesToAdd);
        }
    } // addToProcessNotes
      

    private static void addToProcessNotes(PicklistDetail__c pkDetail, String notesToAdd) {
        if (String.isNotBlank(notesToAdd)) {
            StringHelper.addNotesToField(pkDetail, 'ProcessNotes__c', PicklistDetailCalloutHelper.PROCESS_NOTES_SIZE, notesToAdd, true);
        }
   } // addToProcessTracker
} // class PicklistDetailWrapper