force-app/main/default/objects/AreaCode__c/AreaCode__c.object-meta.xml
<CustomObject>
    <label>Area Code</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Area Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Area Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AreaCode__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The state this area code is in. If it is in more than one state, the most state with the most zip codes will be listed first.</inlineHelpText>
    <label>State</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AreaCode__c/fields/TimeZoneAbbrev__c.field-meta.xml
<CustomField>
    <fullName>TimeZoneAbbrev__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The abbreviation for the time zone</inlineHelpText>
    <label>Time Zone Abbrev</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AreaCode__c/fields/TimeZoneName__c.field-meta.xml
<CustomField>
    <fullName>TimeZoneName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Time Zone this area code is part of. If part of more than one time zone, the one with the most zip codes will be listed.</inlineHelpText>
    <label>Time Zone Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AreaCodeLink__c/AreaCodeLink__c.object-meta.xml
<CustomObject>
    <description>Link between the Zip Code Information and Area Code objects</description>
    <label>Area Code Link</label>
    <nameField>
        <displayFormat>Link-{000000}</displayFormat>
        <label>Link Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Area Code Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AreaCodeLink__c/fields/AreaCode__c.field-meta.xml
<CustomField>
    <fullName>AreaCode__c</fullName>
    <label>Area Code</label>
    <referenceTo>AreaCode__c</referenceTo>
    <relationshipLabel>Area Code Links</relationshipLabel>
    <relationshipName>AreaCodeLinks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AreaCodeLink__c/fields/Zip_Code_Information__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Information__c</fullName>
    <label>Zip Code Information</label>
    <referenceTo>Zip_Code_Information__c</referenceTo>
    <relationshipLabel>Area Code Links</relationshipLabel>
    <relationshipName>AreaCodeLinks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>Account.Legal_State__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <displayFormat>State-{00000}</displayFormat>
        <label>State Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zip_Code_Information__c/Zip_Code_Information__c.object-meta.xml
<CustomObject>
    <description>City/State information on Zip codes as provided by Zip-Codes.com</description>
    <label>Zip Code Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code_Information__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>2 letter state name abbreviation.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>2 letter state name abbreviation.</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zip_Code_Information__c/fields/TimeZoneAbbrev__c.field-meta.xml
<CustomField>
    <fullName>TimeZoneAbbrev__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Abbreviation of the time zone.</inlineHelpText>
    <label>Time Zone Abbrev</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AreaCodeMethods.cls
/* 
 * Methods for working with area codes. 
   Tests are in the ZipCodeInformationTest class.
 *
 * History
 * -------
 * 09/17/2013 Dan Carmen   Created
   03/30/2015 Dan Carmen   Trigger modification
 *
 */
public with sharing class AreaCodeMethods {

   public static void findTimeZones(Set<Id> areaCodeIdSet) {
   	
      // select the area codes
      Map<Id,AreaCode__c> areaCodeMap = new Map<Id,AreaCode__c>([Select Id, Name, State__c, TimeZoneName__c, TimeZoneAbbrev__c from AreaCode__c where Id in :areaCodeIdSet]);
      System.debug('findTimeZones areaCodeMap size='+areaCodeMap.size());
       
   	AggregateResult[] timeZoneResults = [SELECT count(Id) nbrZips, Zip_Code_Information__r.TimeZoneName__c timeZoneName, Zip_Code_Information__r.TimeZoneAbbrev__c timeZoneAbbrev, AreaCode__c 
   	                                      FROM AreaCodeLink__c
   	                                     Where AreaCode__c in :areaCodeIdSet
   	                                     group by Zip_Code_Information__r.TimeZoneName__c, Zip_Code_Information__r.TimeZoneAbbrev__c, AreaCode__c
   	                                     order by AreaCode__c, count(id) desc];

      // keep track on the records that were changed
      Map<Id,AreaCode__c> changedAreaCodeMap = new Map<Id,AreaCode__c>();
      
      // only take the first one for an area code   	                                     
      Id prevAreaCodeId = null;
      for (AggregateResult ar : timeZoneResults) {
         Id thisAreaCodeId = (Id)ar.get('AreaCode__c');
         // only take the first one
         if (thisAreaCodeId != prevAreaCodeId) {
            prevAreaCodeId = thisAreaCodeId;
            AreaCode__c ac = areaCodeMap.get(thisAreaCodeId);
            if (ac != null) {
               String timeZoneName = (String)ar.get('timeZoneName');
               String timeZoneAbbrev = (String)ar.get('timeZoneAbbrev');
               System.debug('findTimeZones timeZoneName='+timeZoneName+' timeZoneAbbrev='+timeZoneAbbrev);
               
               if (ac.TimeZoneName__c != timeZoneName || ac.TimeZoneAbbrev__c != timeZoneAbbrev) {
                  ac.TimeZoneName__c = timeZoneName;
                  ac.TimeZoneAbbrev__c = timeZoneAbbrev;
                  changedAreaCodeMap.put(ac.Id, ac);
               }
            } // if (ac != null 
         } // if
      } // for (AggregateResult ar

      AggregateResult[] stateResults = [SELECT count(Id) nbrZips, Zip_Code_Information__r.State__c state, AreaCode__c 
                                            FROM AreaCodeLink__c
                                           Where AreaCode__c in :areaCodeIdSet
                                           group by Zip_Code_Information__r.State__c, AreaCode__c
                                           order by AreaCode__c, count(id) desc];

      // compile the state(s) first, then compare to the area code record (in case there are multiple states)
      Map<Id,String> stateMapById = new Map<Id,String>();
      for (AggregateResult ar : stateResults) {
         Id thisAreaCodeId = (Id)ar.get('AreaCode__c');
         String stateValue = stateMapById.get(thisAreaCodeId);
         if (String.isNotBlank(stateValue)) {
            stateValue += ';'; 
         } else {
         	stateValue = '';
         }
         stateValue += (String)ar.get('state');
         System.debug('findTimeZones thisAreaCodeId='+thisAreaCodeId+' stateValue='+stateValue);
         stateMapById.put(thisAreaCodeId,stateValue);
      } // for (AggregateResult ar

      // compare the old values with the new.
      for (AreaCode__c ac : areaCodeMap.values()) {
      	String stateValue = stateMapById.get(ac.Id);
         System.debug('findTimeZones ac.Id='+ac.Id+' ac.State__c='+ac.State__c+' stateValue='+stateValue);
      	if (ac.State__c != stateValue) {
      	   ac.State__c = stateValue;
            changedAreaCodeMap.put(ac.Id, ac);
      	}
      } // for (AreaCode__c
      
      System.debug('findTimeZones number of changed changedAreaCodeMap='+changedAreaCodeMap.size());
      // update the changes
      if (!changedAreaCodeMap.isEmpty()) {
         update changedAreaCodeMap.values();
      }
   } // findTimeZones
} // class AreaCodeMethods