force-app/main/default/objects/Reference_Core_Payroll__c/Reference_Core_Payroll__c.object-meta.xml
<CustomObject>
    <description>Object used to store additional information for on-boarding Core Payroll.</description>
    <label>Reference Core Payroll</label>
    <nameField>
        <displayFormat>CORE-{000000000}</displayFormat>
        <label>Reference Core Payroll Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Core Payroll</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_Core_Payroll__c/fields/Payroll_Run_Date__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Run_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payroll Run Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_Core_Payroll__c/fields/X1st_Payroll_Run_Week__c.field-meta.xml
<CustomField>
    <fullName>X1st_Payroll_Run_Week__c</fullName>
    <description>The week of the month the first payroll is set to run</description>
    <inlineHelpText>The week of the month the first payroll is set to run</inlineHelpText>
    <label>1st Payroll Run Week</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RefCorePayFiscalWeek.cls
/** Called from Before Trigger for Reference Core Payroll object. Updates the 1st Payroll Run Week
 *
 * History
 * -------
 *  08/17/2016 Jacob Hinds      Created
 *
 */
public with sharing class RefCorePayFiscalWeek {
    public class MonthWrapper {
      public Period month;
      public Period[] weeks;
   }
    public static void calculateFiscalWeek(List<Reference_Core_Payroll__c> refs){
        //[SELECT FiscalYearSettings.Name FROM Period WHERE Type = 'Year' AND StartDate <= TODAY AND EndDate >= TODAY].FiscalYearSettings.Name
        List<Reference_Core_Payroll__c> updateRefs = new List<Reference_Core_Payroll__c>();
        String fyName = [SELECT FiscalYearSettings.Name FROM Period WHERE Type = 'Year' AND StartDate <= TODAY AND EndDate >= TODAY].FiscalYearSettings.Name;
        if(fyName != null){
            Period[] months = [SELECT FiscalYearSettings.Name,PeriodLabel,Number,StartDate,EndDate FROM Period WHERE Type = 'Month' AND FiscalYearSettings.Name = :fyName]; 
            if(months != null){
                for(Reference_Core_Payroll__c ref:refs){
                    for(Period month:months){
                        if(ref.Payroll_Run_Date__c >= month.StartDate && ref.Payroll_Run_Date__c <= month.EndDate){
                            Integer difference = month.StartDate.daysBetween(ref.Payroll_Run_Date__c);
                            Double unRounded = difference/7;
                            //ref.X1st_Payroll_Run_Week_Auto__c = (Integer)math.floor(unRounded)+1;
                            ref.X1st_Payroll_Run_Week__c = String.valueOf(Integer.valueOf(math.floor(unRounded)+1));
                        }
                    }
                }
            }
        }
        
    }
}